### ISSUE TITLE
Webhook admission panic during validate cluster obj

### ISSUE THREAD

**Issue by R-omk** [rook/rook#10222]
**Is this a bug report or feature request?**
* Bug Report

```
2022-05-06 14:40:38.011047 I | rook-ceph-webhook: validate update cephcluster "rook-ceph"                                                                                                                      │
│ 2022-05-06 14:40:38.011172 I | http: panic serving 10.233.104.1:40590: runtime error: index out of range [1] with length 1                                                                                     │
│ goroutine 5561 [running]:                                                                                                                                                                                      │
│ net/http.(*conn).serve.func1()                                                                                                                                                                                 │
│     /opt/hostedtoolcache/go/1.17.9/x64/src/net/http/server.go:1802 +0xb9                                                                                                                                       │
│ panic({0x1df5440, 0xc00090ab40})                                                                                                                                                                               │
│     /opt/hostedtoolcache/go/1.17.9/x64/src/runtime/panic.go:1047 +0x266                                                                                                                                        │
│ github.com/rook/rook/pkg/apis/ceph.rook.io/v1.validateUpdatedCephCluster(0xc00117cd80, 0xc00117d200)                                                                                                           │
│     /home/runner/work/rook/rook/pkg/apis/ceph.rook.io/v1/cluster.go:85 +0x46a                                                                                                                                  │
│ github.com/rook/rook/pkg/apis/ceph.rook.io/v1.(*CephCluster).ValidateUpdate(0xc00117cd80, {0x22d87c8, 0xc00117d200})                                                                                           │
│     /home/runner/work/rook/rook/pkg/apis/ceph.rook.io/v1/cluster.go:64 +0xab                                                                                                                                   │
│ sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*validatingHandler).Handle(_, {_, _}, {{{0xc0014018c0, 0x24}, {{0xc00109b250, 0xc}, {0xc00109b25c, 0x2}, {0xc00109b260, ...}}, ...}})                    │
│     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/webhook/admission/validator.go:93 +0x7a9                                                                                                │
│ sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle(_, {_, _}, {{{0xc0014018c0, 0x24}, {{0xc00109b250, 0xc}, {0xc00109b25c, 0x2}, {0xc00109b260, ...}}, ...}})                              │
│     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/webhook/admission/webhook.go:146 +0xa2                                                                                                  │
│ sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc000ca3f00, {0x7f0ac2c3b778, 0xc0003523c0}, 0xc001363400)                                                                          │
│     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/webhook/admission/http.go:99 +0xef6                                                                                                     │
│ github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1({0x7f0ac2c3b778, 0xc0003523c0}, 0xc0003523c0)                                                                          │
│     /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.11.1/prometheus/promhttp/instrument_server.go:40 +0xd4                                                                                      │
│ net/http.HandlerFunc.ServeHTTP(0x22ea528, {0x7f0ac2c3b778, 0xc0003523c0}, 0xc000857a60)                                                                                                                        │
│     /opt/hostedtoolcache/go/1.17.9/x64/src/net/http/server.go:2047 +0x2f                                                                                                                                       │
│ github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x22ea528, 0xc000792460}, 0xc001363400)                                                                                │
│     /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.11.1/prometheus/promhttp/instrument_server.go:117 +0xa8                                                                                     │
│ net/http.HandlerFunc.ServeHTTP(0x1, {0x22ea528, 0xc000792460}, 0x3387800)                                                                                                                                      │
│     /opt/hostedtoolcache/go/1.17.9/x64/src/net/http/server.go:2047 +0x2f                                                                                                                                       │
│ github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x22ea528, 0xc000792460}, 0xc001363400)                                                                               │
│     /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.11.1/prometheus/promhttp/instrument_server.go:84 +0xbf                                                                                      │
│ net/http.HandlerFunc.ServeHTTP(0xc0956ab9808b3cbe, {0x22ea528, 0xc000792460}, 0xc000792460)                                                                                                                    │
│     /opt/hostedtoolcache/go/1.17.9/x64/src/net/http/server.go:2047 +0x2f                                                                                                                                       │
│ net/http.(*ServeMux).ServeHTTP(0xc001c175eb, {0x22ea528, 0xc000792460}, 0xc001363400)                                                                                                                          │
│     /opt/hostedtoolcache/go/1.17.9/x64/src/net/http/server.go:2425 +0x149                                                                                                                                      │
│ net/http.serverHandler.ServeHTTP({0x22dc648}, {0x22ea528, 0xc000792460}, 0xc001363400)                                                                                                                         │
│     /opt/hostedtoolcache/go/1.17.9/x64/src/net/http/server.go:2879 +0x43b                                                                                                                                      │
│ net/http.(*conn).serve(0xc00182e0a0, {0x22f7168, 0xc001bccd20})                                                                                                                                                │
│     /opt/hostedtoolcache/go/1.17.9/x64/src/net/http/server.go:1930 +0xb08                                                                                                                                      │
│ created by net/http.(*Server).Serve                                                                                                                                                                            │
│     /opt/hostedtoolcache/go/1.17.9/x64/src/net/http/server.go:3034 +0x4e8                                                                                                                                      │
│ 2022-05-06 14:40:41.470800 I | rook-ceph-webhook: validate update cephcluster "rook-ceph"        


```

**Environment**:

* Rook version: v1.9.2
* Kubernetes version: v1.22.8
* Storage backend status: HEALTH_OK

**Comment by R-omk** [comment]
This happens if you try to add a new one `StorageClassDeviceSet` to an existing cluster.
It need to compare elements by name and not by index

**Comment by R-omk** [comment]
https://github.com/rook/rook/blame/v1.9.2/pkg/apis/ceph.rook.io/v1/cluster.go#L84-L85

**Comment by travisn** [comment]
Thanks for the report, until we get this fixed note that you can disable the admission controller with [this setting](https://github.com/rook/rook/blob/release-1.9/deploy/examples/operator.yaml#L562).
