### ISSUE TITLE
OSD prepare is not working with pvc

### ISSUE THREAD

**Issue by df-cgdm** [rook/rook#10377]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
OSD pods are not created

**Expected behavior:**

**How to reproduce it (minimal and precise):**
I create a new cluster using pvc 

[**File(s)](url) to submit**:
* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
[cluster.yaml.txt](https://github.com/rook/rook/files/8825049/cluster.yaml.txt)

* Operator's logs, if necessary
[rook-ceph-osd-prepare-huawei-data-1rqlpl-qmsjb.txt](https://github.com/rook/rook/files/8825070/rook-ceph-osd-prepare-huawei-data-1rqlpl-qmsjb.txt)

**Comment by travisn** [comment]
The attached osd prepare log shows the device was skipped:
```
2022-06-02 14:56:29.200343 I | cephosd: skipping device "/mnt/huawei-data-1rqlpl" because it contains a filesystem "ceph_bluestore"
```

This is a clean device that has never been used before?

**Comment by df-cgdm** [comment]
Yes it a fresh one. It's the first time we're trying to deploy ceph on our flash array.

**Comment by df-cgdm** [comment]
To be sure I've retry to create a cluster.  Here are the log files of the operator and the two prepare job:
[](url
[rook-ceph-operator-5fbc764f69-7jnrf.log](https://github.com/rook/rook/files/8830332/rook-ceph-operator-5fbc764f69-7jnrf.log)
[rook-ceph-os
[rook-ceph-osd-prepare-huawei-data-12s4dl-52vtd.log](https://github.com/rook/rook/files/8830335/rook-ceph-osd-prepare-huawei-data-12s4dl-52vtd.log)
d-prepare-huawei-data-0rhrfp-kxbml.log](https://github.com/rook/rook/files/8830333/rook-ceph-osd-prepare-huawei-data-0rhrfp-kxbml.log)
)

in the operator log we can see an error just after the creation of two pvc:
```
2022-06-03 06:58:20.052578 I | op-osd: start running osds in namespace "rook-ceph"
2022-06-03 06:58:20.052588 I | op-osd: wait timeout for healthy OSDs during upgrade or restart is "10m0s"
2022-06-03 06:58:20.057748 I | op-osd: start provisioning the OSDs on PVCs, if needed
2022-06-03 06:58:20.061363 I | op-osd: creating 2 new PVCs for device set "huawei"
2022-06-03 06:58:20.068862 I | op-osd: successfully provisioned PVC "huawei-data-0rhrfp"
2022-06-03 06:58:20.152100 I | op-osd: successfully provisioned PVC "huawei-data-12s4dl"
2022-06-03 06:58:20.158488 I | op-osd: OSD will have its main bluestore block on "huawei-data-0rhrfp"
2022-06-03 06:58:20.374283 I | op-osd: started OSD provisioning job for PVC "huawei-data-0rhrfp"
2022-06-03 06:58:20.374293 I | op-osd: OSD will have its main bluestore block on "huawei-data-12s4dl"
2022-06-03 06:58:20.865024 I | op-osd: started OSD provisioning job for PVC "huawei-data-12s4dl"
2022-06-03 06:58:20.865036 I | op-osd: start provisioning the OSDs on nodes, if needed
2022-06-03 06:58:20.865039 I | op-osd: no nodes are defined for configuring OSDs on raw devices
2022-06-03 06:58:20.961892 I | op-osd: OSD orchestration status for PVC huawei-data-0rhrfp is "starting"
2022-06-03 06:58:20.961903 I | op-osd: OSD orchestration status for PVC huawei-data-12s4dl is "starting"
2022-06-03 06:58:48.433172 I | op-osd: OSD orchestration status for node huawei-data-12s4dl is "orchestrating"
2022-06-03 06:58:48.673875 I | op-osd: OSD orchestration status for node huawei-data-0rhrfp is "orchestrating"
2022-06-03 06:58:48.922541 I | op-osd: OSD orchestration status for PVC huawei-data-12s4dl is "orchestrating"
2022-06-03 06:58:49.171259 I | op-osd: OSD orchestration status for PVC huawei-data-0rhrfp is "orchestrating"
2022-06-03 06:58:57.538578 I | op-osd: OSD orchestration status for PVC huawei-data-0rhrfp is "failed"
2022-06-03 06:58:57.538611 E | op-osd: failed to provision OSD(s) on PVC huawei-data-0rhrfp. &{OSDs:[] Status:failed PvcBackedOSD:true Message:failed to configure devices: failed to initialize devices on PVC: failed to run ceph-volume. Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new 946117e6-630e-4b65-82a7-0e6645574677
Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-0
Running command: /usr/bin/chown -h ceph:ceph /dev/mapper/mpathaf
Running command: /usr/bin/chown -R ceph:ceph /dev/dm-10
Running command: /usr/bin/ln -s /dev/mapper/mpathaf /var/lib/ceph/osd/ceph-0/block
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/osd/ceph-0/activate.monmap
 stderr: got monmap epoch 3
Running command: /usr/bin/ceph-authtool /var/lib/ceph/osd/ceph-0/keyring --create-keyring --name osd.0 --add-key AQAusZliOZWTFxAAXI+MwfgEYy73tZKJlZh7Jw==
 stdout: creating /var/lib/ceph/osd/ceph-0/keyring
added entity osd.0 auth(key=AQAusZliOZWTFxAAXI+MwfgEYy73tZKJlZh7Jw==)
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/keyring
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0/
Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 0 --monmap /var/lib/ceph/osd/ceph-0/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-0/ --osd-uuid 946117e6-630e-4b65-82a7-0e6645574677 --setuser ceph --setgroup ceph
 stderr: 2022-06-03T06:58:55.663+0000 7f4a09c97200 -1 bluestore(/var/lib/ceph/osd/ceph-0/) _read_fsid unparsable uuid
--> Was unable to complete a new OSD, will rollback changes
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.0 --yes-i-really-mean-it
 stderr: purged osd.0
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 169, in main
    self.safe_prepare(self.args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 91, in safe_prepare
    self.prepare()
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 134, in prepare
    tmpfs,
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 68, in prepare_bluestore
    db=db
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/prepare.py", line 481, in osd_mkfs_bluestore
    raise RuntimeError('Command failed with exit code %s: %s' % (returncode, ' '.join(command)))
RuntimeError: Command failed with exit code 250: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 0 --monmap /var/lib/ceph/osd/ceph-0/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-0/ --osd-uuid 946117e6-630e-4b65-82a7-0e6645574677 --setuser ceph --setgroup ceph. debug logs below:
```

**Comment by travisn** [comment]
It seems the main error is: 
```
bluestore(/var/lib/ceph/osd/ceph-0/) _read_fsid unparsable uuid
```

Then the osd creation attempts to roll back, but doesn't do it cleanly and leaves the ceph bluestore info on the disk, and any attempt after that will skip the disk because it appears in use already.

Are these PVCs status, or provisioned dynamically? Can you test [wiping them clean](https://rook.github.io/docs/rook/v1.9/Storage-Configuration/ceph-teardown/#zapping-devices) before the rook cluster creates the OSDs?

**Comment by df-cgdm** [comment]
So here is what I've done. 
1/ Create a new cluster, get the same error.
2/ stop the operator
3/ load the 2 pvc in a container to wipe the pvc using blkdiscard 
4/  restart the operator

The result is similar

Here are the logs
- step 1 operator logs
[rook-ceph-operator-67f7d5c9b6-kdr8m.log](https://github.com/rook/rook/files/8837190/rook-ceph-operator-67f7d5c9b6-kdr8m.log)
- step4 operator logs and osd prepare logs
[rook-ceph-operator-7cd98cf656-nlc2k.log](https://github.com/rook/rook/files/8837192/rook-ceph-operator-7cd98cf656-nlc2k.log)
[rook-ceph-osd-prepare-huawei-data-09877g-gw7j9.log](https://github.com/rook/rook/files/8837193/rook-ceph-osd-prepare-huawei-data-09877g-gw7j9.log)
[rook-ceph-osd-prepare-huawei-data-1r775t-ljxm7.log](https://github.com/rook/rook/files/8837194/rook-ceph-osd-prepare-huawei-data-1r775t-ljxm7.log)

**Comment by travisn** [comment]
In this environment, it seems that the osd is just failing to initialize. 
@df-cgdm If you are configuring an encrypted cluster, it could be related to #10375.

@guits Any ideas what causes error 250 from ceph-volume?

From the operator log:
```
[2022-06-04 06:47:48,176][ceph_volume.process][INFO  ] stderr 2022-06-04T06:47:48.170+0000 7f3f9efc9200 -1 [0;31m ** ERROR: error creating empty object store in /var/lib/ceph/osd/ceph-1/: (5) Input/output error[0m
[2022-06-04 06:47:48,176][ceph_volume.devices.raw.prepare][ERROR ] raw prepare was unable to complete
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 91, in safe_prepare
    self.prepare()
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 134, in prepare
    tmpfs,
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 68, in prepare_bluestore
    db=db
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/prepare.py", line 481, in osd_mkfs_bluestore
    raise RuntimeError('Command failed with exit code %!s(MISSING): %!s(MISSING)' %!((MISSING)returncode, ' '.join(command)))
RuntimeError: Command failed with exit code 250: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid a2be68d7-d0d0-452e-be8e-31120a45c68f --setuser ceph --setgroup ceph
[2022-06-04 06:47:48,177][ceph_volume.devices.raw.prepare][INFO  ] will rollback OSD ID creation
[2022-06-04 06:47:48,177][ceph_volume.process][INFO  ] Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.1 --yes-i-really-mean-it
[2022-06-04 06:47:48,653][ceph_volume.process][INFO  ] stderr purged osd.1
[2022-06-04 06:47:48,663][ceph_volume][ERROR ] exception caught by decorator
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 169, in main
    self.safe_prepare(self.args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 91, in safe_prepare
    self.prepare()
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 134, in prepare
    tmpfs,
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 68, in prepare_bluestore
    db=db
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/prepare.py", line 481, in osd_mkfs_bluestore
    raise RuntimeError('Command failed with exit code %!s(MISSING): %!s(MISSING)' %!((MISSING)returncode, ' '.join(command)))
RuntimeError: Command failed with exit code 250: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid a2be68d7-d0d0-452e-be8e-31120a45c68f --setuser ceph --setgroup ceph
: exit status 1}
```

The osd prepare logs don't look useful since the osd init is attempting to config for the second time and then just failing with 
```
skipping device "/mnt/huawei-data-1r775t" because it contains a filesystem "ceph_bluestore"
```

**Comment by guits** [comment]
> @guits Any ideas what causes error 250 from ceph-volume?


@travisn the rc 250 is returned by `ceph-osd`, not `ceph-volume`

that being said, there could be multiple reasons for `ceph-osd` to return 250: can't acquire lock on device, bluestore issue, ...

could it be related to https://tracker.ceph.com/issues/54019 ?

**Comment by travisn** [comment]
@guits Thanks for the pointer!
@df-cgdm According to that linked ceph tracker, can you create the OSDs if you add the following setting to the [ceph.conf overrides](https://rook.github.io/docs/rook/v1.9/Storage-Configuration/Advanced/ceph-configuration/#custom-cephconf-settings)?
```
bluefs_buffered_io = false 
```

**Comment by df-cgdm** [comment]
I had the same result

But I'm not sure to have well configured. I've created the following config map before creating the cluster CRD. Is it correct?
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    bluefs_buffered_io = false
```

Here are the logs:
[rook-ceph-operator-6864b469c9-xqgnv.log](https://github.com/rook/rook/files/8850910/rook-ceph-operator-6864b469c9-xqgnv.log)
[rook-ceph-osd-prepare-huawei-data-1bj9dl-7rt2s.log](https://github.com/rook/rook/files/8850911/rook-ceph-osd-prepare-huawei-data-1bj9dl-7rt2s.log)
[rook-ceph-osd-prepare-huawei-data-052vtf-77rm9.log](https://github.com/rook/rook/files/8850912/rook-ceph-osd-prepare-huawei-data-052vtf-77rm9.log)

**Comment by guits** [comment]
I'm asking out of ignorance (I'm not sure whether it makes a difference), but shouldn't it be in the `[osd]` section?

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [osd]
    bluefs_buffered_io = false
```

**Comment by df-cgdm** [comment]
I've tried but it doesn't change the result

**Comment by travisn** [comment]
@df-cgdm The syntax looks correct. If you created the configmap before creating the CephCluster CR (cluster.yaml), it would be picked up. So it seems likely there is some other issue in the environment, but unfortunately not sure what.

**Comment by guits** [comment]
> Here are the logs: 
[rook-ceph-operator-6864b469c9-xqgnv.log](https://github.com/rook/rook/files/8850910/rook-ceph-operator-6864b469c9-xqgnv.log) 
[rook-ceph-osd-prepare-huawei-data-1bj9dl-7rt2s.log](https://github.com/rook/rook/files/8850911/rook-ceph-osd-prepare-huawei-data-1bj9dl-7rt2s.log) 
[rook-ceph-osd-prepare-huawei-data-052vtf-77rm9.log](https://github.com/rook/rook/files/8850912/rook-ceph-osd-prepare-huawei-data-052vtf-77rm9.log)

@travisn these are logs from rook and ceph-volume only, shouldn't we have the log from the daemon `ceph-osd` itself somewhere?
Not sure whether `ceph-osd` prints something on stdout/stderr in that case but ceph-volume doesn't capture them anyway, see [1]

[1] https://github.com/ceph/ceph/blob/master/src/ceph-volume/ceph_volume/util/prepare.py#L471-L481)

**Comment by travisn** [comment]
@guits Since the osd prepare failed, the osd daemon is not started, so I don't expect there would be logs in that case from the osd daemons.

**Comment by guits** [comment]
@travisn what is failing here is a `ceph-osd` command, so I was thinking it might print its error to a log file.
```
Command failed with exit code 250: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid a2be68d7-d0d0-452e-be8e-31120a45c68f --setuser ceph --setgroup ceph
```

**Comment by travisn** [comment]
The `ceph-osd --mkfs` command runs in the osd prepare pod, so there may be more details in that log, but looks like the job is failing and being restarted (and resulting in a different error) before we can capture the original log. 
@df-cgdm Could you try capturing the osd prepare log immediately upon first failure? You might only have a few seconds window to capture it though.

**Comment by df-cgdm** [comment]
@travisn it was tricky but I've managed to capture the first osd prepare log.
Here it is:
[rook-ceph-osd-prepare-huawei-data-1pxmqd-7958g.log](https://github.com/rook/rook/files/8869276/rook-ceph-osd-prepare-huawei-data-1pxmqd-7958g.log)

**Comment by leseb** [comment]
The `is not a valid LUKS device` is a bit misleading but it simply indicates that the device is not encrypted. So it's not a failure.

**Comment by guits** [comment]
> @guits Does anything else from this log stand out? 

No. Indeed, unfortunately, I don't see anything that can help here.
Just like that, it's hard to help.

Not sure if you can rerun the command `/usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid d1def179-da8d-48b1-bd46-7127bdcdf249 --setuser ceph --setgroup ceph` 'manually', maybe with more verbosity?
Otherwise, I would probably ask 'bluestore experts', maybe they could have pointers.
