### ISSUE TITLE
Encrypted OSD activation fails in v16.2.9

### ISSUE THREAD

**Issue by heilerich** [rook/rook#10375]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After an upgrade from ceph `v16.2.7` to `v16.2.9` OSDs pods start crash looping due to a failing activation init container. After a rollback to 16.2.7 everything works fine again.

**Expected behavior:**
Rook 1.9.4 claims to support all Ceph Pacific versions v16.2.0 and higher

**How to reproduce it (minimal and precise):**
Change `.spec.cephVersion.image` to `quay.io/ceph/ceph:v16.2.9` in a existing Ceph cluster.

**File(s) to submit**:
<details>
<summary>Cluster CR (before upgrade)</summary>

```yaml
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.7
  monitoring:
    enabled: true
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    modules:
      - name: pg_autoscaler
        enabled: true
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 60
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      encryptedDevice: "true"
    nodes:
    - ...
```
</details>

<details>
<summary>OSD activation init container log (after upgrade)</summary>

```
+ OSD_ID=0
+ OSD_UUID=beb4a899-a318-49ff-a9aa-2e933e49a948
+ OSD_STORE_FLAG=--bluestore
+ OSD_DATA_DIR=/var/lib/ceph/osd/ceph-0
+ CV_MODE=lvm
+ DEVICE=/dev/ceph-bcd778c7-43f9-4474-97b2-72352958d86e/osd-block-beb4a899-a318-49ff-a9aa-2e933e49a948
+ ceph -n client.admin auth get-or-create osd.0 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring
[osd.0]
	key = AQBxxPpgozOtFBAASau6FiqoNLQ6TY0JG9ToQg==
+ [[ lvm == \l\v\m ]]
++ mktemp -d
+ TMP_DIR=/tmp/tmp.JMxnO4ivWp
+ ceph-volume lvm activate --no-systemd --bluestore 0 beb4a899-a318-49ff-a9aa-2e933e49a948
Running command: /usr/bin/ceph --cluster ceph --name client.osd-lockbox.beb4a899-a318-49ff-a9aa-2e933e49a948 --keyring /var/lib/ceph/osd/ceph-0/lockbox.keyring config-key get dm-crypt/osd/beb4a899-a318-49ff-a9aa-2e933e49a948/luks
Traceback (most recent call last):
  File "/usr/lib64/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'global'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/configuration.py", line 80, in is_valid
    self.get('global', 'fsid')
  File "/usr/lib64/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib64/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'global'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/main.py", line 46, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 377, in main
    self.activate(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 301, in activate
    activate_bluestore(lvs, args.no_systemd)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 176, in activate_bluestore
    encryption_utils.luks_open(dmcrypt_secret, osd_block_lv.lv_path, osd_block_lv.lv_uuid)
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/encryption.py", line 97, in luks_open
    get_key_size_from_conf(),
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/encryption.py", line 21, in get_key_size_from_conf
    default='512')
  File "/usr/lib/python3.6/site-packages/ceph_volume/configuration.py", line 95, in get_safe
    self.is_valid()
  File "/usr/lib/python3.6/site-packages/ceph_volume/configuration.py", line 82, in is_valid
    raise exceptions.ConfigurationKeyError('global', 'fsid')
ceph_volume.exceptions.ConfigurationKeyError: Unable to find expected configuration key: "fsid" from section "global"
```
</details>

**Environment**:
* OS (e.g. from /etc/os-release): Flatcar Container Linux by Kinvolk 3139.2.1 (Oklo)
* Kernel (e.g. `uname -a`): 5.15.37-flatcar
* Cloud provider or hardware configuration: bare-metal
* Rook version (use `rook version` inside of a Rook Pod): v1.9.4
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.7 (dd0603118f56ab514f133c8d2e3adfc983942503) pacific (stable)
* Kubernetes version (use `kubectl version`): v1.22.8
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Vanilla
* Storage backend status : HEALTH_OK

**Comment by travisn** [comment]
In my testing of v16.2.9, I also observed the following tests with Rook v1.9.4:
1. When configuring a v16.2.7 cluster **with encryption**, then upgrading to v16.2.9, the OSDs immediately hit the error reported in this issue
2. When configuring a v16.2.7 cluster **without encryption**, then upgrading to v16.2.9, the OSDs were upgraded properly 
3. When configuring a new v16.2.9 cluster **with encryption** (no upgrade), the OSDs also failed.

The encryption is enabled in the repro with:
```
  storage:
    config:
      encryptedDevice: "true"
```

@leseb could you take a look?

**Comment by travisn** [comment]
Updated the title since it affects all encrypted v16.2.9 clusters, whether new or upgraded.

**Comment by travisn** [comment]
#10333 seems to be the fix for this issue
