### ISSUE TITLE
osd's are not starting when metadata device is specified

### ISSUE THREAD

**Issue by MerouaneBen** [rook/rook#10747]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When I start the cluster, all the `rook-ceph-osd-prepare-*` start failing and eventually no OSD's  are provisioned.

**Expected behavior:**
Cluster should start without issues when specifying `metadataDevice`
**How to reproduce it (minimal and precise):**

start cluster and define  `metadataDevice`
**File(s) to submit**:

* Cluster CR (custom resource), below is my `values-override.yaml` file
```
cephClusterSpec:
  dashboard:
    enabled: true
    port: 8443
    ssl: true
    urlPrefix: /
  mgr:
    count: 2
  mon:
    count: 3
  storage:
    config:
      metadataDevice: "sde"
    nodes:
    - devices:
      - config:
          deviceClass: hdd
        name: /dev/ceph-hdd1/ceph-hdd1-lv
      - config:
          deviceClass: hdd
        name: /dev/ceph-hdd2/ceph-hdd2-lv
      name: worker1
    - devices:
      - config:
          deviceClass: hdd
        name: /dev/ceph-hdd1/ceph-hdd1-lv
      - config:
          deviceClass: hdd
        name: /dev/ceph-hdd2/ceph-hdd2-lv
      name: worker2
    - devices:
      - config:
          deviceClass: hdd
        name: /dev/ceph-hdd1/ceph-hdd1-lv
      - config:
          deviceClass: hdd
        name: /dev/ceph-hdd2/ceph-hdd2-lv
      name: worker3
    - devices:
      - config:
          deviceClass: hdd
        name: /dev/ceph-hdd1/ceph-hdd1-lv
      - config:
          deviceClass: hdd
        name: /dev/ceph-hdd2/ceph-hdd2-lv
      name: worker4
cephObjectStores:
- name: ceph-objectstore
  spec:
    dataPool:
      erasureCoded:
        codingChunks: 2
        dataChunks: 4
      failureDomain: osd
    gateway:
      instances: 2
      port: 80
      priorityClassName: system-cluster-critical
      resources:
        limits:
          cpu: 2000m
          memory: 6Gi
        requests:
          cpu: 1000m
          memory: 2Gi
    healthCheck:
      bucket:
        interval: 60s
    metadataPool:
      failureDomain: host
      replicated:
        size: 3
    preservePoolsOnDelete: true
  storageClass:
    enabled: true
    name: ceph-bucket-delete
    parameters:
      region: us-east-1
    reclaimPolicy: Delete
public_address: somelink.com
toolbox:
  enabled: true
version: 1.9.8
```
* Operator's logs:
```
2022-08-20 20:37:39.030327 I | clusterdisruption-controller: all "host" failure domains: []. osd is down in failure domain: "". active node drains: false. pg health: "cluster is not fully clean. PGs: [{StateName:unknown Count:80}]"
2022-08-20 20:37:39.034732 I | clusterdisruption-controller: reconciling osd pdb reconciler as the allowed disruptions in default pdb is 0
2022-08-20 20:37:39.196335 I | op-osd: waiting... 0 of 4 OSD prepare jobs have finished processing and 0 of 0 OSDs have been updated
2022-08-20 20:37:48.517698 I | clusterdisruption-controller: all "host" failure domains: []. osd is down in failure domain: "". active node drains: false. pg health: "cluster is not fully clean. PGs: [{StateName:unknown Count:80}]"
2022-08-20 20:37:48.522079 I | clusterdisruption-controller: reconciling osd pdb reconciler as the allowed disruptions in default pdb is 0
2022-08-20 20:37:52.996124 I | exec: timeout waiting for process radosgw-admin to return. Sending interrupt signal to the process
2022-08-20 20:37:52.997574 I | ceph-object-controller: created object store "ceph-objectstore" in namespace "rook-ceph"
2022-08-20 20:38:07.998275 I | exec: timeout waiting for process radosgw-admin to return. Sending interrupt signal to the process
2022-08-20 20:38:08.005940 E | ceph-object-controller: failed to reconcile CephObjectStore "rook-ceph/ceph-objectstore". failed to create object store deployments: failed to start rgw health checker for CephObjectStore "rook-ceph/ceph-objectstore", will re-reconcile: failed to create bucket checker for CephObjectStore "rook-ceph/ceph-objectstore": failed to create or retrieve rgw admin ops user: failed to create object user "rgw-admin-ops-user". error code 1 for object store "ceph-objectstore": failed to create s3 user. . : signal: interrupt
2022-08-20 20:38:09.538365 I | clusterdisruption-controller: all "host" failure domains: []. osd is down in failure domain: "". active node drains: false. pg health: "cluster is not fully clean. PGs: [{StateName:unknown Count:80}]"
2022-08-20 20:38:09.543611 I | clusterdisruption-controller: reconciling osd pdb reconciler as the allowed disruptions in default pdb is 0
2022-08-20 20:38:19.030265 I | clusterdisruption-controller: all "host" failure domains: []. osd is down in failure domain: "". active node drains: false. pg health: "cluster is not fully clean. PGs: [{StateName:unknown Count:80}]"
2022-08-20 20:38:19.034713 I | clusterdisruption-controller: reconciling osd pdb reconciler as the allowed disruptions in default pdb is 0
2022-08-20 20:38:39.196717 I | op-osd: waiting... 0 of 4 OSD prepare jobs have finished processing and 0 of 0 OSDs have been updated
2022-08-20 20:38:40.030720 I | clusterdisruption-controller: all "host" failure domains: []. osd is down in failure domain: "". active node drains: false. pg health: "cluster is not fully clean. PGs: [{StateName:unknown Count:80}]"
2022-08-20 20:38:40.035317 I | clusterdisruption-controller: reconciling osd pdb reconciler as the allowed disruptions in default pdb is 0
2022-08-20 20:38:49.737426 I | clusterdisruption-controller: all "host" failure domains: []. osd is down in failure domain: "". active node drains: false. pg health: "cluster is not fully clean. PGs: [{StateName:unknown Count:80}]"
2022-08-20 20:38:49.742179 I | clusterdisruption-controller: reconciling osd pdb reconciler as the allowed disruptions in default pdb is 0
2022-08-20 20:39:10.611896 I | clusterdisruption-controller: all "host" failure domains: []. osd is down in failure domain: "". active node drains: false. pg health: "cluster is not fully clean. PGs: [{StateName:unknown Count:80}]"
2022-08-20 20:39:10.616381 I | clusterdisruption-controller: reconciling osd pdb reconciler as the allowed disruptions in default pdb is 0
2022-08-20 20:39:20.243748 I | clusterdisruption-controller: all "host" failure domains: []. osd is down in failure domain: "". active node drains: false. pg health: "cluster is not fully clean. PGs: [{StateName:unknown Count:80}]"
2022-08-20 20:39:20.298902 I | clusterdisruption-controller: reconciling osd pdb reconciler as the allowed disruptions in default pdb is 0
2022-08-20 20:39:29.932820 I | ceph-spec: parsing mon endpoints: b=10.43.162.102:6789,c=10.43.36.108:6789,a=10.43.228.68:6789
2022-08-20 20:39:29.932853 I | ceph-spec: detecting the ceph image version for image registry.gitlab.com/exfo/products/asa/sensai/core/secondaryimages/ceph/ceph:v16.2.10...
2022-08-20 20:39:30.957798 I | ceph-spec: detected ceph image version: "16.2.10-0 pacific"
2022-08-20 20:39:32.506890 I | ceph-object-controller: reconciling object store deployments
2022-08-20 20:39:32.517939 I | ceph-object-controller: ceph object store gateway service running at 10.43.35.181
2022-08-20 20:39:32.517958 I | ceph-object-controller: reconciling object store pools
2022-08-20 20:39:34.539025 I | cephclient: application "rook-ceph-rgw" is already set on pool "ceph-objectstore.rgw.control"
2022-08-20 20:39:34.539049 I | cephclient: reconciling replicated pool ceph-objectstore.rgw.control succeeded
2022-08-20 20:39:35.600555 I | cephclient: setting pool property "pg_num_min" to "8" on pool "ceph-objectstore.rgw.control"
2022-08-20 20:39:38.502582 I | cephclient: application "rook-ceph-rgw" is already set on pool "ceph-objectstore.rgw.meta"
2022-08-20 20:39:38.502612 I | cephclient: reconciling replicated pool ceph-objectstore.rgw.meta succeeded
2022-08-20 20:39:39.196718 I | op-osd: waiting... 0 of 4 OSD prepare jobs have finished processing and 0 of 0 OSDs have been updated
2022-08-20 20:39:39.518968 I | cephclient: setting pool property "pg_num_min" to "8" on pool "ceph-objectstore.rgw.meta"
2022-08-20 20:39:41.214910 I | clusterdisruption-controller: all "host" failure domains: []. osd is down in failure domain: "". active node drains: false. pg health: "cluster is not fully clean. PGs: [{StateName:unknown Count:80}]"
```
* Crashing pod(s) logs in my case all `rook-ceph-osd-prepare-*` pods
```
2022-08-20 20:17:06.893346 I | cephclient: getting or creating ceph auth key "client.bootstrap-osd"
2022-08-20 20:17:06.893360 D | exec: Running command: ceph auth get-or-create-key client.bootstrap-osd mon allow profile bootstrap-osd --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json
2022-08-20 20:17:07.523745 D | cephosd: will use raw mode since cluster version is at least pacific
2022-08-20 20:17:07.523765 D | cephosd: won't use raw mode since there is a metadata device "sde"
2022-08-20 20:17:07.523772 D | exec: Running command: nsenter --mount=/rootfs/proc/1/ns/mnt -- /usr/sbin/lvm --help
2022-08-20 20:17:07.530805 I | cephosd: successfully called nsenter
2022-08-20 20:17:07.530832 I | cephosd: binary "/usr/sbin/lvm" found on the host, proceeding with osd preparation
2022-08-20 20:17:07.531540 I | cephosd: Successfully updated lvm config file "/etc/lvm/lvm.conf"
2022-08-20 20:17:07.531649 I | cephosd: skipping metadata device sde config since it will be configured with a data device
2022-08-20 20:17:07.531661 I | cephosd: configuring new LVM device dm-0
2022-08-20 20:17:07.531669 I | cephosd: sde found in the desired metadata devices
2022-08-20 20:17:07.531680 I | cephosd: using sde as metadataDevice for device /dev/mapper/ceph--hdd2-ceph--hdd2--lv and let ceph-volume lvm batch decide how to create volumes
2022-08-20 20:17:07.531687 I | cephosd: configuring new LVM device dm-1
2022-08-20 20:17:07.531707 I | cephosd: sde found in the desired metadata devices
2022-08-20 20:17:07.531710 I | cephosd: using sde as metadataDevice for device /dev/mapper/ceph--hdd1-ceph--hdd1--lv and let ceph-volume lvm batch decide how to create volumes
2022-08-20 20:17:07.531724 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --osds-per-device 1 --crush-device-class hdd /dev/mapper/ceph--hdd2-ceph--hdd2--lv /dev/mapper/ceph--hdd1-ceph--hdd1--lv --db-devices /dev/sde --report
2022-08-20 20:17:08.425815 D | exec: --> passed data devices: 0 physical, 2 LVM
2022-08-20 20:17:08.425838 D | exec: --> relative data size: 1.0
2022-08-20 20:17:08.426615 D | exec: Traceback (most recent call last):
2022-08-20 20:17:08.426625 D | exec:   File "/usr/sbin/ceph-volume", line 11, in <module>
2022-08-20 20:17:08.426628 D | exec:     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
2022-08-20 20:17:08.426631 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
2022-08-20 20:17:08.426634 D | exec:     self.main(self.argv)
2022-08-20 20:17:08.426636 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
2022-08-20 20:17:08.426639 D | exec:     return f(*a, **kw)
2022-08-20 20:17:08.426641 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
2022-08-20 20:17:08.426644 D | exec:     terminal.dispatch(self.mapper, subcommand_args)
2022-08-20 20:17:08.426647 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2022-08-20 20:17:08.426649 D | exec:     instance.main()
2022-08-20 20:17:08.426652 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/main.py", line 46, in main
2022-08-20 20:17:08.426654 D | exec:     terminal.dispatch(self.mapper, self.argv)
2022-08-20 20:17:08.426657 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2022-08-20 20:17:08.426660 D | exec:     instance.main()
2022-08-20 20:17:08.426662 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
2022-08-20 20:17:08.426664 D | exec:     return func(*a, **kw)
2022-08-20 20:17:08.426667 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 425, in main
2022-08-20 20:17:08.426669 D | exec:     plan = self.get_plan(self.args)
2022-08-20 20:17:08.426672 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 463, in get_plan
2022-08-20 20:17:08.426675 D | exec:     args.wal_devices)
2022-08-20 20:17:08.426677 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 483, in get_deployment_layout
2022-08-20 20:17:08.426680 D | exec:     plan.extend(get_lvm_osds(lvm_devs, args))
2022-08-20 20:17:08.426682 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 93, in get_lvm_osds
2022-08-20 20:17:08.426685 D | exec:     disk.Size(b=int(lv.lvs[0].lv_size)),
2022-08-20 20:17:08.426687 D | exec: IndexError: list index out of range
2022-08-20 20:17:08.452029 C | rookcmd: failed to configure devices: failed to initialize osd: failed ceph-volume report: exit status 1
```

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
* Kernel (e.g. `uname -a`):
`Linux worker2 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): `v1.9.8`
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3+k3s1", GitCommit:"990ba0e88c90f8ed8b50e0ccd375937b841b176e", GitTreeState:"clean", BuildDate:"2022-07-19T01:10:03Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.24) exceeds the supported minor version skew of +/-1
``` 
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): k3s cluster `v1.24.3+k3s1`
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by satoru-takeuchi** [comment]
Specifying metadatadevice is not allowed for OSD on LV but its validation was not implemented by mistake. I'll fix it later.
