### ISSUE TITLE
Dashboard services return 500, if Ganesha NFS enabled

### ISSUE THREAD

**Issue by mecseid** [rook/rook#10995]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
I got an HTTP 500 error when the dasboard wants to call `/api/service`

**Expected behavior:**
Get HTTP 200 OK response with the expected (running services) result.

**How to reproduce it (minimal and precise):**
* Create a `CephNFS` custom resource
* Open dashboard
* Go to Cluster --> Services

**File(s) to submit**:
* CephNFS CR
```yaml
apiVersion: ceph.rook.io/v1
kind: CephNFS
metadata:
  name: nfs
  namespace: rook-ceph
spec:
  server:
    active: 1
    logLevel: NIV_INFO
    resources:
      limits:
        cpu: "1"
        memory: "256Mi"
```

**Logs to submit**:

* mgr logs
```
debug 2022-09-15T08:52:26.263+0000 7fdb50f66700  0 [rook ERROR orchestrator._interface] 'pool'
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 125, in wrapper
    return OrchResult(f(*args, **kwargs))
  File "/usr/share/ceph/mgr/rook/module.py", line 354, in describe_service
    if nfs['spec']['rados']['pool'] != NFS_POOL_NAME:
KeyError: 'pool'
debug 2022-09-15T08:52:26.264+0000 7fdb50f66700  0 [dashboard ERROR exception] Internal Server Error
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 47, in dashboard_exception_handler
    return handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/_base_controller.py", line 258, in inner
    ret = func(*args, **kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/_rest_controller.py", line 191, in wrapper
    return func(*vpath, **params)
  File "/usr/share/ceph/mgr/dashboard/controllers/orchestrator.py", line 33, in _inner
    return method(self, *args, **kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/service.py", line 35, in list
    return [service.to_dict() for service in orch.services.list(service_name=service_name)]
  File "/usr/share/ceph/mgr/dashboard/services/orchestrator.py", line 38, in inner
    raise_if_exception(completion)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 228, in raise_if_exception
    raise e
KeyError: 'pool'
debug 2022-09-15T08:52:26.266+0000 7fdb50f66700  0 [dashboard ERROR request] [10.142.211.105:52864] [GET] [500] [0.824s] [admin] [513.0B] /api/service
debug 2022-09-15T08:52:26.266+0000 7fdb50f66700  0 [dashboard ERROR request] [b'{"status": "500 Internal Server Error", "detail": "The server encountered an unexpected condition which prevented it from fulfilling the request.", "request_id": "2260ba9a-038d-4cba-aa39-b80a44c2c9a9"}
```

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod): v1.10.1
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 17.2.3 (dff484dfc9e19a9819f375586300b3b79d80034d) quincy (stable)
* Kubernetes version (use `kubectl version`): v1.24.4

**Comment by parth-gr** [comment]
I think you need to also create the pool CR `.nfs`, https://github.com/rook/rook/blob/eaee34872b5ba19cfea1864caf088f998d42b0a0/deploy/examples/nfs.yaml#L95

Something similar we do for [nfs-test](https://github.com/rook/rook/blob/eaee34872b5ba19cfea1864caf088f998d42b0a0/deploy/examples/nfs-test.yaml#L16)
For a single node.

**Comment by mecseid** [comment]
I followed this description: https://rook.io/docs/rook/v1.10/Storage-Configuration/NFS/nfs/
This one says that I have to create `.nfs` only if I want to change anything in the configuration: https://rook.io/docs/rook/v1.10/Storage-Configuration/NFS/nfs-advanced/#changing-configuration-of-the-nfs-pool

And actually looks like the operator created the `.nfs` pool:
```
$ ceph osd lspools | grep .nfs
5 .nfs
```

**Comment by travisn** [comment]
Ceph will create the `.nfs` pool automatically if there is no pool CR defined for it, so you're correct no need to create it explicity.

@jmolmo Ideas on this dashboard issue?

**Comment by jmolmo** [comment]
I think this can be solved with [46321](https://github.com/ceph/ceph/pull/46321):

Note: I do not know why this is still not merged, it was solved long time ago. I will contact with the orch team directly to see if we can merge this asap.

**Comment by jmolmo** [comment]
Merged. I have asked also to back port this issue to Quincy asap.

**Comment by mecseid** [comment]
I updated the operator to v1.10.2, and ceph to v17.2.4-20220930, deleted the `cephnfses.ceph.rook.io`, the `.nfs` pool, and disabled the `nfs` mgr module.

Afther that I recreated the `cephnfses.ceph.rook.io`, and reenabled the `nfs` mgr module.
I went to the NFS page in the dasboard, but got the following error:
```
Remote method threw exception: Traceback (most recent call last): File "/usr/share/ceph/mgr/nfs/module.py", line 154, in cluster_ls return available_clusters(self) File "/usr/share/ceph/mgr/nfs/utils.py", line 39, in available_clusters orchestrator.raise_if_exception(completion) File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 228, in raise_if_exception raise e KeyError: 'pool'
```

Operator log:
```
2022-10-02 10:32:14.361981 I | ceph-spec: adding finalizer "cephnfs.ceph.rook.io" on "nfs"
2022-10-02 10:32:14.422717 E | ceph-nfs-controller: failed to set nfs "nfs" status to "". failed to update object "rook-ceph/nfs" status: Operation cannot be fulfilled on cephnfses.ceph.rook.io "nfs": the object has been modified; please apply your changes to the latest version and try again
2022-10-02 10:32:14.462142 I | ceph-spec: parsing mon endpoints: d=10.142.84.213:6789,e=10.142.116.81:6789,f=10.142.89.71:6789
2022-10-02 10:32:14.462325 I | ceph-spec: detecting the ceph image version for image quay.io/ceph/ceph:v17.2.4-20220930...
2022-10-02 10:32:18.980699 I | ceph-spec: detected ceph image version: "17.2.4-0 quincy"
2022-10-02 10:32:19.775085 I | ceph-nfs-controller: configuring pool ".nfs" for nfs
2022-10-02 10:32:21.959012 I | ceph-nfs-controller: set pool ".nfs" for the application nfs
2022-10-02 10:32:21.993869 I | ceph-nfs-controller: updating ceph nfs "nfs"
2022-10-02 10:32:22.220380 I | ceph-nfs-controller: ensuring kerberos configuration is removed from rados namespace rados://.nfs/nfs/
2022-10-02 10:32:22.221057 I | ceph-nfs-controller: locking rados object "rados://.nfs/nfs/conf-nfs.nfs"
2022-10-02 10:32:22.433168 I | ceph-nfs-controller: successfully locked rados object "rados://.nfs/nfs/conf-nfs.nfs"
2022-10-02 10:32:22.605879 I | ceph-nfs-controller: unlocking rados object "rados://.nfs/nfs/conf-nfs.nfs"
2022-10-02 10:32:23.086187 I | ceph-nfs-controller: successfully unlocked rados object "rados://.nfs/nfs/conf-nfs.nfs"
2022-10-02 10:32:23.251722 I | cephclient: getting or creating ceph auth key "client.nfs-ganesha.nfs.a"
2022-10-02 10:32:24.846738 I | ceph-nfs-controller: ceph nfs deployment "rook-ceph-nfs-nfs-a" started
2022-10-02 10:32:24.885455 I | ceph-nfs-controller: ceph nfs service running at 10.142.102.120:2049
2022-10-02 10:32:24.885495 I | ceph-nfs-controller: adding ganesha "a" to grace db
```

MGR log:
```
debug 2022-10-02T11:17:05.572+0000 7efd9a969700  0 [rook INFO rook.rook_cluster] Full fetch of <bound method CustomObjectsApi.list_namespaced_custom_object of <kubernetes.client.api.custom_objects_api.CustomObjectsApi object at 0x7efdc02079e8>>. result: 1
debug 2022-10-02T11:17:05.817+0000 7efd9a969700  0 [rook INFO rook.rook_cluster] Full fetch of <bound method CoreV1Api.list_namespaced_pod of <kubernetes.client.api.core_v1_api.CoreV1Api object at 0x7efdd24d02b0>>. result: 13
debug 2022-10-02T11:17:05.854+0000 7efd9a969700  0 [rook ERROR orchestrator._interface] 'pool'
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 125, in wrapper
    return OrchResult(f(*args, **kwargs))
  File "/usr/share/ceph/mgr/rook/module.py", line 354, in describe_service
    if nfs['spec']['rados']['pool'] != NFS_POOL_NAME:
KeyError: 'pool'
debug 2022-10-02T11:17:05.861+0000 7efd9a969700 -1 Remote method threw exception: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/nfs/module.py", line 154, in cluster_ls
    return available_clusters(self)
  File "/usr/share/ceph/mgr/nfs/utils.py", line 39, in available_clusters
    orchestrator.raise_if_exception(completion)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 228, in raise_if_exception
    raise e
KeyError: 'pool'

debug 2022-10-02T11:17:05.865+0000 7efd9a969700  0 [dashboard ERROR controllers.nfs] Remote method threw exception: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/nfs/module.py", line 154, in cluster_ls
    return available_clusters(self)
  File "/usr/share/ceph/mgr/nfs/utils.py", line 39, in available_clusters
    orchestrator.raise_if_exception(completion)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 228, in raise_if_exception
    raise e
KeyError: 'pool'
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/controllers/nfs.py", line 271, in status
    mgr.remote('nfs', 'cluster_ls')
  File "/usr/share/ceph/mgr/mgr_module.py", line 2170, in remote
    args, kwargs)
RuntimeError: Remote method threw exception: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/nfs/module.py", line 154, in cluster_ls
    return available_clusters(self)
  File "/usr/share/ceph/mgr/nfs/utils.py", line 39, in available_clusters
    orchestrator.raise_if_exception(completion)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 228, in raise_if_exception
    raise e
KeyError: 'pool'
```

**Comment by jmolmo** [comment]
Fix available in quay.io/ceph/daemon-base:latest-quincy-devel .
