### ISSUE TITLE
Rook orchestrator reading from wrong namespace 

### ISSUE THREAD

**Issue by Gentoli** [rook/rook#11386]
**Is this a bug report or feature request?**

* Bug Report

Not sure if Rook Orchestrator issues are handled here.

**Deviation from expected behavior:**
Some dashboards do not load. Rook orchestrator fetching CephNFS/CephFS CR from wrong namespace.

**Expected behavior:**
Dashboards do load. 

Seems it can be fix by using the correct namespace variable ([example](https://github.com/Gentoli/ceph/commit/9c137b7f8be33e3a35564257cd54d65ceb4d28d0)), although there are other hardcoded CR name.

**How to reproduce it (minimal and precise):**

- create a cluster in non `rook-ceph` namespace
- enabled rook orchestrator 
- create CephNFS
- go to NFS dashboard

**File(s) to submit**:

N/A

**Logs to submit**
NFS:
``` python
debug 2022-12-06T03:56:39.722+0000 7f7bae8e0700  0 [rook ERROR orchestrator._interface] (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '87b51331-3262-4374-bdef-b5645d48e052', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '28374a6d-236b-4e03-a764-388189ef6555', 'X-Kubernetes-Pf-Prioritylevel-Uid': '72f430bf-7eb3-49a2-8725-a36c539ac7d7', 'Date': 'Tue, 06 Dec 2022 03:56:39 GMT', 'Content-Length': '363'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"cephnfses.ceph.rook.io is forbidden: User \"system:serviceaccount:openshift-storage:rook-ceph-mgr\" cannot list resource \"cephnfses\" in API group \"ceph.rook.io\" in the namespace \"rook-ceph\"","reason":"Forbidden","details":{"group":"ceph.rook.io","kind":"cephnfses"},"code":403}

Traceback (most recent call last):
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 125, in wrapper
    return OrchResult(f(*args, **kwargs))
  File "/usr/share/ceph/mgr/rook/module.py", line 351, in describe_service
    all_nfs = self.rook_cluster.get_resource("cephnfses")
  File "/usr/share/ceph/mgr/rook/rook_cluster.py", line 1079, in get_resource
    return custom_objects.items
  File "/usr/share/ceph/mgr/rook/rook_cluster.py", line 260, in items
    resource_version = self._fetch()
  File "/usr/share/ceph/mgr/rook/rook_cluster.py", line 319, in _fetch
    response = self.api_func(**self.kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api/custom_objects_api.py", line 1489, in list_namespaced_custom_object
    (data) = self.list_namespaced_custom_object_with_http_info(group, version, namespace, plural, **kwargs)  # noqa: E501
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api/custom_objects_api.py", line 1609, in list_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 345, in call_api
    _preload_content, _request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 176, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 366, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 241, in GET
    query_params=query_params)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '87b51331-3262-4374-bdef-b5645d48e052', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '28374a6d-236b-4e03-a764-388189ef6555', 'X-Kubernetes-Pf-Prioritylevel-Uid': '72f430bf-7eb3-49a2-8725-a36c539ac7d7', 'Date': 'Tue, 06 Dec 2022 03:56:39 GMT', 'Content-Length': '363'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"cephnfses.ceph.rook.io is forbidden: User \"system:serviceaccount:openshift-storage:rook-ceph-mgr\" cannot list resource \"cephnfses\" in API group \"ceph.rook.io\" in the namespace \"rook-ceph\"","reason":"Forbidden","details":{"group":"ceph.rook.io","kind":"cephnfses"},"code":403}


debug 2022-12-06T03:56:39.724+0000 7f7bae8e0700 -1 Remote method threw exception: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/nfs/module.py", line 154, in cluster_ls
    return available_clusters(self)
  File "/usr/share/ceph/mgr/nfs/utils.py", line 39, in available_clusters
    orchestrator.raise_if_exception(completion)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 228, in raise_if_exception
    raise e
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '87b51331-3262-4374-bdef-b5645d48e052', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '28374a6d-236b-4e03-a764-388189ef6555', 'X-Kubernetes-Pf-Prioritylevel-Uid': '72f430bf-7eb3-49a2-8725-a36c539ac7d7', 'Date': 'Tue, 06 Dec 2022 03:56:39 GMT', 'Content-Length': '363'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"cephnfses.ceph.rook.io is forbidden: User \"system:serviceaccount:openshift-storage:rook-ceph-mgr\" cannot list resource \"cephnfses\" in API group \"ceph.rook.io\" in the namespace \"rook-ceph\"","reason":"Forbidden","details":{"group":"ceph.rook.io","kind":"cephnfses"},"code":403}

```

CephFS:

```
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"cephfilesystems.ceph.rook.io is forbidden: User \"system:serviceaccount:openshift-storage:rook-ceph-mgr\" cannot list resource \"cephfilesystems\" in API group \"ceph.rook.io\" in the namespace \"rook-ceph\"","reason":"Forbidden","details":{"group":"ceph.rook.io","kind":"cephfilesystems"},"code":403}
```

**Cluster Status to submit**:
N/A

**Environment**:
* OS (e.g. from /etc/os-release): OKD FCOS
* Kernel (e.g. `uname -a`): `Linux rook-ceph-tools-6584b468fd-l6222 6.0.10-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Nov 26 16:53:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Supermicro X10
* Rook version (use `rook version` inside of a Rook Pod): 
* Storage backend version (e.g. for ceph do `ceph -v`):  `quay.io/ceph/ceph:v17.2.5`
* Kubernetes version (use `kubectl version`): `v1.24.0-2568+56584349e9412b-dirty`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): `HEALTH_WARN 4 pool(s) have no replicas configured; 38 mgr modules have recently crashed`

**Comment by travisn** [comment]
Did you already open a PR in the [Ceph repo](https://github.com/ceph/ceph) with your example fix? Agreed the namespace should not be hard-coded to `rook-ceph`.

**Comment by Gentoli** [comment]
@travisn 
No I haven't, I think they want a tracker ticket for PRs, unless it's ok to not have it.

**Comment by travisn** [comment]
Sounds good to open a tracker.

**Comment by Gentoli** [comment]
https://tracker.ceph.com/login
> Your account was created and is now pending administrator approval.

I think I will leave these to you.. There is also the k8s object names and labels changes and I don't have a setup to test the changes.

**Comment by jmolmo** [comment]
Upstream tracker issue: https://tracker.ceph.com/issues/58210

**Comment by jmolmo** [comment]
Fix: https://github.com/ceph/ceph/pull/49432

**Comment by jmolmo** [comment]
@Gentoli  Thank you very much for your contribution (it was also needed another small replacement) . I have tested and it seems that everything is working now in the orchestrator part (at least the problems directly related with the use of a different namespace from the default one).

Please review https://github.com/ceph/ceph/pull/49432

**Comment by jmolmo** [comment]
solved in https://github.com/ceph/ceph/pull/49432
