### ISSUE TITLE
Can't visitor ceph dashboard use http

### ISSUE THREAD

**Issue by mc956759** [rook/rook#11465]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After login dashboard successfully, the /ui-api/motd and /api/osd/settings return 401

**Expected behavior:**
Visitor ceph dashboard successfully, by http.

**How to reproduce it (minimal and precise):**

· modify cluster.yaml "dashboard ssl: false"
· start a NodePort service by use "kubectl apply -f dashboard-external-http.yaml"
· visitor http://external_ip:node_port，login interface can display.
· login by admin and passwd, return 401, and the passwd is correct.
· check the logs, found that " Login successful: admin" and "[GET] [401] [0.004s] [136.0B] [ae0fed5d-4b01-4016-9dfb-de52a7d486f3] /ui-api/motd"

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:
```
debug 2022-12-21T03:39:18.077+0000 7fc0e8fff700  0 [dashboard INFO controllers.auth] Login successful: admin
debug 2022-12-21T03:39:18.085+0000 7fc0e8fff700  0 [dashboard INFO request] [::ffff:10.244.0.0:35981] [POST] [201] [0.252s] [455.0B] [9e01d3f2-0144-41d8-961f-ee916c81be8f] /api/auth
debug 2022-12-21T03:39:18.133+0000 7fc0e6ffb700  0 [dashboard WARNING request] [::ffff:10.244.0.0:35981] [GET] [401] [0.004s] [136.0B] [ae0fed5d-4b01-4016-9dfb-de52a7d486f3] /ui-api/motd
debug 2022-12-21T03:39:18.149+0000 7fc0e7ffd700  0 [dashboard WARNING request] [::ffff:10.244.0.0:35981] [GET] [401] [0.003s] [134.0B] [4d552e22-d12d-4dbe-b4fa-d6ac3412774c] /api/health/minimal
debug 2022-12-21T03:39:18.161+0000 7fc0e7ffd700  0 [dashboard WARNING request] [::ffff:10.244.0.0:38460] [GET] [401] [0.010s] [135.0B] [1cbeb0e3-5470-4070-b94f-ea9e97d73253] /api/osd/settings
debug 2022-12-21T03:39:18.165+0000 7fc0e7ffd700  0 [dashboard WARNING request] [::ffff:10.244.0.0:43290] [GET] [401] [0.004s] [135.0B] [88dcbc55-bafc-4461-8957-711aae968b71] /api/settings/alertmanager-api-host
debug 2022-12-21T03:39:18.165+0000 7fc0e5ff9700  0 [dashboard WARNING request] [::ffff:10.244.0.0:30233] [GET] [401] [0.007s] [135.0B] [4beb1352-76bf-4cf5-8779-578a99bb4fa7] /api/mgr/module/telemetry
debug 2022-12-21T03:39:18.165+0000 7fc0e77fc700  0 [dashboard WARNING request] [::ffff:10.244.0.0:56857] [GET] [401] [0.011s] [136.0B] [c4fb5471-5112-4b77-8f24-8c0e3f73d4ba] /ui-api/standard_settings
debug 2022-12-21T03:39:18.169+0000 7fc0e4ff7700  0 [dashboard WARNING request] [::ffff:10.244.0.0:38460] [GET] [401] [0.003s] [135.0B] [f3e38884-7c94-42ee-8b58-4804b0e2b411] /api/settings/prometheus-api-host
debug 2022-12-21T03:39:18.185+0000 7fc0e87fe700  0 [dashboard INFO request] [::ffff:10.244.0.0:56857] [GET] [200] [0.004s] [29.0B] [4ebaf8ab-cc05-4083-a544-e4b17049be5e] /ui-api/langs
debug 2022-12-21T03:39:18.185+0000 7fc0e9800700  0 [dashboard WARNING request] [::ffff:10.244.0.0:38460] [GET] [401] [0.007s] [135.0B] [a0a17eca-e76c-40b6-8c10-e68599db5fdb] /api/prometheus/notifications
debug 2022-12-21T03:39:18.201+0000 7fc0e57f8700  0 [dashboard ERROR frontend.error] (http://10.8.69.97:30149/#/login): Http failure response for http://10.8.69.97:30149/api/health/minimal: 401 Unauthorized
 None

debug 2022-12-21T03:39:18.201+0000 7fc0e6ffb700  0 [dashboard INFO request] [::ffff:10.244.0.0:32027] [POST] [200] [0.005s] [74.0B] [5574f5ed-72ea-4711-aff9-c227b141f1fe] /api/auth/check
debug 2022-12-21T03:39:18.201+0000 7fc0e57f8700  0 [dashboard INFO request] [::ffff:10.244.0.0:39762] [POST] [200] [0.003s] [24.0B] [ebf669ec-003c-4110-afb7-6e3243776799] /ui-api/logging/js-error
debug 2022-12-21T03:39:18.217+0000 7fc0e7ffd700  0 [dashboard INFO request] [::ffff:10.244.0.0:39762] [GET] [200] [0.003s] [29.0B] [4f0f3e59-f9b6-4378-8961-524b47696ed1] /ui-api/langs
```

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary
there are some traceback info in log:
```
debug 2022-12-21T03:38:45.956+0000 7fc0e9800700  0 [dashboard ERROR exception] Internal Server Error
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 47, in dashboard_exception_handler
    return handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/home.py", line 135, in __call__
    return serve_file(full_path)
  File "/usr/lib/python3.6/site-packages/cherrypy/lib/static.py", line 77, in serve_file
    cptools.validate_since()
  File "/usr/lib/python3.6/site-packages/cherrypy/lib/cptools.py", line 116, in validate_since
    raise cherrypy.HTTPRedirect([], 304)
cherrypy._cperror.HTTPRedirect: ([], 304)
debug 2022-12-21T03:38:45.956+0000 7fc0e9800700  0 [dashboard INFO request] [::ffff:10.244.0.0:29960] [GET] [304] [0.004s] [0.0B] [c38701b0-55fb-4e96-87c8-45cdba2e8fbd] /forkawesome-webfont.7c20758e3e7c7dff7c8d.woff2
debug 2022-12-21T03:38:45.992+0000 7fc0e87fe700  0 [dashboard ERROR exception] Internal Server Error
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 47, in dashboard_exception_handler
    return handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/home.py", line 135, in __call__
    return serve_file(full_path)
  File "/usr/lib/python3.6/site-packages/cherrypy/lib/static.py", line 77, in serve_file
    cptools.validate_since()
  File "/usr/lib/python3.6/site-packages/cherrypy/lib/cptools.py", line 116, in validate_since
    raise cherrypy.HTTPRedirect([], 304)
cherrypy._cperror.HTTPRedirect: ([], 304)
```

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): 20.04.4 LTS (Focal Fossa)
* Kernel (e.g. `uname -a`):5.4.0-135-generic
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):v1.10.7
* Storage backend version (e.g. for ceph do `ceph -v`):v16.2.10 and v17.2.5 both have this problem
* Kubernetes version (use `kubectl version`):v1.26.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by parth-gr** [comment]
Were you still able to login by https:// ??

**Comment by mc956759** [comment]
> Were you still able to login by https:// ??

No, https:// also return errors.

**Comment by jmolmo** [comment]
@mc956759 : 
I guess that probably the dashboard was working previously using https.
Can you check if it works after executing a "ceph mgr fail"  command ( use ceph toolbox or krew plugin)

If it does not work we will need to review the dashboard config.

Please obtain and provide the following information:

```
From your kubernetes cluster:

kubectl get cephcluster rook-ceph -n rook-ceph -o yaml | grep -A 5 "dashboard:"
kubectl get services -n rook-ceph
kubectl describe po --selector="app=rook-ceph-mgr" -n rook-ceph | grep -B 4 "Node:"


From the host where you try to access the Ceph dashboard, access the Dashboard service (use the same url you write in your web browser):
# curl -vvv https://192.168.122.56:30871
Note: copy the url to be used below


From the the Ceph toolbox to execute the following commands:
ceph -s
ceph health detail
ceph orch status
ceph mgr module ls


Force the error to raise again and obtain a clean mgr log to pass it


Using ceph toolbox:
- Trigger a ceph manage failover:
# ceph mgr fail

-Obtain the id of the active mgr:
bash-4.4$ ceph -s | grep mgr:
    mgr: b(active, since 19h), standbys: a

-From your browser, try to connect again with the ceph dashboard

-From your kubernetes cluster obtain the logs of the mgr (use the id instance of the active manager, in this example it is "b")
# kubectl logs -l="ceph_daemon_type=mgr, instance=b" -n rook-ceph  --tail=5000 > manager.log

Include as part of the bug information the obtained "manager.log" file.
```
