### ISSUE TITLE
rook-config-override is not updated while monitor placement changes

### ISSUE THREAD

**Issue by gaord** [rook/rook#11547]
Hi,
it is on rook 1.10 + ceph 17.2.5

manager pod run with empty ceph.conf as in /etc/ceph/ceph.conf. as a result, some ceph cli ends up with exception in cluster log as below:
[ERR]
Failed to create /rgwexport export for nfs4rgw Traceback (most recent call last): File "/usr/share/ceph/mgr/nfs/export.py", line 399, in create_export return self.create_rgw_export(**kwargs) File "/usr/share/ceph/mgr/nfs/export.py", line 701, in create_rgw_export self._create_export_user(export) File "/usr/share/ceph/mgr/nfs/export.py", line 278, in _create_export_user f'Failed to fetch key for bucket {export.path} owner {rgwfsal.user_id}' nfs.exception.NFSException: Failed to fetch key for bucket testbk owner demouser
1/16/23 1:00:42 AM
[ERR]
Command '['radosgw-admin', '-k', '/etc/ceph/keyring-store/keyring', '-n', 'mgr.b', 'user', 'info', '--uid', 'demouser']' timed out after 10 seconds

rook operator has the following error:
[root@demo-master-01 ~]# kubectl logs rook-ceph-operator-78bd445776-gwd8n -n rook-ceph|grep rook-config-override
2023-01-11 01:58:55.362058 W | op-mon: failed to set Rook and/or user-defined Ceph config options before starting mons; will retry after starting mons. failed to apply default Ceph configurations: failed to set one or more Ceph configs: failed to set ceph config in the centralized mon configuration database; you may need to use the rook-config-override ConfigMap. output: Cluster connection aborted: exit status 1: failed to set ceph config in the centralized mon configuration database; you may need to use the rook-config-override ConfigMap. output: Cluster connection aborted: exit status 1: failed to set ceph config in the centralized mon configuration database; you may need to use the rook-config-override ConfigMap. output: Cluster connection aborted: exit status 1
2023-01-11 02:20:10.313163 W | op-mon: failed to set Rook and/or user-defined Ceph config options before starting mons; will retry after starting mons. failed to apply default Ceph configurations: failed to set one or more Ceph configs: failed to set ceph config in the centralized mon configuration database; you may need to use the rook-config-override ConfigMap. output: Cluster connection aborted: exit status 1: failed to set ceph config in the centralized mon configuration database; you may need to use the rook-config-override ConfigMap. output: Cluster connection aborted: exit status 1: failed to set ceph config in the centralized mon configuration database; you may need to use the rook-config-override ConfigMap. output: Cluster connection aborted: exit status 1

expected:
operator can update cm rook-config-override to reflect running monitors, so that manager pod can pick up correct ceph.conf for ceph cli to be functioning normally.

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
The `rook-config-override` by design does not contain the latest mons. The mons are passed as env vars to the Ceph daemons so they can pick up on the latest mons when they start. 

This issue shows the error from the nfs module. @BlaineEXE could you take a look?

The errors from the operator log seem unrelated. The operator will be able to handle updates to the mons since it regenerates its own ceph.conf internally for operator commands.

**Comment by gaord** [comment]
Rados uses dns to get monitor ip address by default. The problem is gone by updating  stale records in dns. Close this. Thanks for  help.  @travisn 
https://docs.ceph.com/en/quincy/rados/configuration/mon-lookup-dns
