### ISSUE TITLE
ceph orch device ls fails with rook as orchestrator

### ISSUE THREAD

**Issue by mnlipp** [rook/rook#11644]
* Bug Report

I've set up a three node cluster with quincy.

**Deviation from expected behavior:**

In the toolbox running `ceph orch device ls` results in

```
Error EINVAL: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 1755, in _handle_command
    return self.handle_command(inbuf, cmd)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 171, in handle_command
    return dispatch[cmd['prefix']].call(self, cmd, inbuf)
  File "/usr/share/ceph/mgr/mgr_module.py", line 462, in call
    return self.func(mgr, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 107, in <lambda>
    wrapper_copy = lambda *l_args, **l_kwargs: wrapper(*l_args, **l_kwargs)  # noqa: E731
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 96, in wrapper
    return func(*args, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator/module.py", line 484, in _list_devices
    inv_hosts = raise_if_exception(completion)
  File "/usr/share/ceph/mgr/orchestrator/_interface.py", line 228, in raise_if_exception
    raise e
Exception: No storage class exists matching name provided in ceph config at mgr/rook/storage_class
```

**Expected behavior:**

Show device list.

**How to reproduce it (minimal and precise):**

Setup a cluster as described in the documentation.

I suspect that the problem is related to having host storage only. Despite that, the configured storage class is `local`:

```
bash-4.4$ ceph config get mgr mgr/rook/storage_class
local
```

As no storageClass is configured in the cluster cr (host storage only), this might lead to the problem.

**Comment by mnlipp** [comment]
Ceph problem, https://tracker.ceph.com/issues/58686
