### ISSUE TITLE
How to replace an OSD with db

### ISSUE THREAD

**Issue by CrossainQi** [rook/rook#12112]
Hi everyone, i have a 3 nodes cluster and i am trying to replace an OSD with db but got serveral errors. 

**Is this a bug report or feature request?**
* Bug Report

**How to reproduce it (minimal and precise):**

1. deploy the cluster and deploy serveral resources on the cluster.
2. take a look at the node01, vda is corresponding to osd.0
`[root@csrmirror03v rook-ceph]# lsblk
NAME                                                                                                  MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda                                                                                                     8:0    0  100G  0 disk
├─sda1                                                                                                  8:1    0    1M  0 part
└─sda2                                                                                                  8:2    0  100G  0 part /
sdb                                                                                                     8:16   0  100G  0 disk
└─ceph--f8da3743--99dc--48d4--8c01--c7da4be5599d-osd--db--4eaaa977--d087--4201--bdba--d4910605fa3c    252:1    0   10G  0 lvm
vda                                                                                                   253:0    0  200G  0 disk
└─ceph--aa22a7ae--92de--4a31--a3e3--202e218a7395-osd--block--996da5b7--50a5--4cb9--8c74--eec440b497a2 252:0    0  200G  0 lvm`
3. kubectl -n rook-ceph scale deployment rook-ceph-operator --replicas=0
4. (toolbox)ceph osd out osd.0
5. kubectl -n rook-ceph scale deployment rook-ceph-osd-0 --replicas=0
6. toolbox)ceph osd down osd.0
7. (toolbox)ceph osd purge 0
8. detach vda and attach another disk(vdb)
9. modify cr definition yaml and apply
10. kubectl -n rook-ceph scale deployment rook-ceph-operator --replicas=1
11. take a look at the pods 
`> k get pods -n rook-ceph
NAME                                               READY   STATUS                  RESTARTS        AGE
csi-cephfsplugin-b8zgz                             2/2     Running                 0               66m
csi-cephfsplugin-mtkc8                             2/2     Running                 0               66m
csi-cephfsplugin-provisioner-bf9664d96-gbzn6       5/5     Running                 0               66m
csi-cephfsplugin-provisioner-bf9664d96-mcm9w       5/5     Running                 0               66m
csi-cephfsplugin-qn2n6                             2/2     Running                 0               66m
csi-rbdplugin-67nw5                                2/2     Running                 0               66m
csi-rbdplugin-cbp4f                                2/2     Running                 0               66m
csi-rbdplugin-provisioner-7cd7ff4d77-2n9zt         5/5     Running                 0               66m
csi-rbdplugin-provisioner-7cd7ff4d77-rjkz8         5/5     Running                 0               66m
csi-rbdplugin-tsh95                                2/2     Running                 0               66m
rook-ceph-crashcollector-node01-6f87d9b6d8-xh5b5   1/1     Running                 0               61m
rook-ceph-crashcollector-node02-64f4447bf-sx2w2    1/1     Running                 0               63m
rook-ceph-mgr-a-5fd48c7c4-s4zf7                    2/2     Running                 0               65m
rook-ceph-mon-a-55bf48796f-ptzbr                   2/2     Running                 0               65m
rook-ceph-operator-545597b95d-mgm95                1/1     Running                 0               55m
rook-ceph-osd-0-74d94d69c4-hvdh6                   0/2     Init:CrashLoopBackOff   15 (73s ago)    53m
rook-ceph-osd-1-788d747956-f6bbp                   2/2     Running                 0               63m
rook-ceph-osd-prepare-node01--1-jtwb7              0/1     CrashLoopBackOff        5 (2m29s ago)   5m21s
rook-ceph-osd-prepare-node02--1-7t7gn              0/1     Completed               0               5m21s
rook-ceph-rgw-ceph-objectstore-a-f78c9bdf6-68npl   2/2     Running                 0               61m
rook-ceph-tools-698659c97f-6whcg                   1/1     Running                 0               66m`

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
before:
`
...
storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false

    config:
    #  metadataDevice: "sdb" # specify a non-rotational storage so ceph-volume will use it as block db device of bluestore.
      databaseSizeMB: "20480" # uncomment if the disks are smaller than 100 GB
    #  journalSizeMB: "20480"  # uncomment if the disks are 20 GB or smaller
  label.
    nodes:
      - name: "node01"
        devices: # specific devices to use for storage can be specified for each node
          - name: "vda"
        config:
          metadataDevice: "sdb"
      - name: "node02"
        devices:
          - name: "vdc"
...  
`
after:
`
...
storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false

    config:
    #  metadataDevice: "sdb" # specify a non-rotational storage so ceph-volume will use it as block db device of bluestore.
      databaseSizeMB: "20480" # uncomment if the disks are smaller than 100 GB
    #  journalSizeMB: "20480"  # uncomment if the disks are 20 GB or smaller
  label.
    nodes:
      - name: "node01"
        devices: # specific devices to use for storage can be specified for each node
          - name: "vdb"
        config:
          metadataDevice: "sdb"
      - name: "node02"
        devices:
          - name: "vdc"
...  
`
**Logs to submit**:

* Operator's logs, if necessary
`2023-04-19 09:22:27.395781 I | op-k8sutil: Found previous job rook-ceph-osd-prepare-node01. Status={Conditions:[] StartTime:2023-04-19 09:17:00 +0000 UTC CompletionTime:<nil> Active:1 Succeeded:0 Failed:0 CompletedIndexes: UncountedTerminatedPods:nil Ready:<nil>}
2023-04-19 09:22:27.395832 I | op-osd: started OSD provisioning job for node "node01"
2023-04-19 09:22:27.596550 I | op-k8sutil: Removing previous job rook-ceph-osd-prepare-node02 to start a new one
2023-04-19 09:22:27.697035 I | op-k8sutil: batch job rook-ceph-osd-prepare-node02 still exists
2023-04-19 09:22:30.706673 I | op-k8sutil: batch job rook-ceph-osd-prepare-node02 deleted
2023-04-19 09:22:30.796563 I | op-osd: started OSD provisioning job for node "node02"
2023-04-19 09:22:30.803350 I | op-osd: OSD orchestration status for node node01 is "starting"
2023-04-19 09:22:30.803431 I | op-osd: OSD orchestration status for node node02 is "starting"
2023-04-19 09:22:31.895640 I | clusterdisruption-controller: osd "rook-ceph-osd-0" is down but no node drain is detected
2023-04-19 09:22:33.796002 I | op-mgr: successful modules: dashboard
2023-04-19 09:22:34.802644 I | op-mgr: successful modules: prometheus
2023-04-19 09:22:36.599075 W | cephclient: the cluster has fewer than 3 osds. not performing upgrade check. running in best-effort
2023-04-19 09:22:36.599153 I | op-osd: skipping osd checks for ok-to-stop
2023-04-19 09:22:36.696506 I | op-osd: updating OSD 0 on node "node01"
2023-04-19 09:22:36.997139 I | op-osd: OSD orchestration status for node node02 is "orchestrating"
2023-04-19 09:22:36.997525 I | op-osd: OSD orchestration status for node node02 is "completed"
2023-04-19 09:22:38.201661 I | clusterdisruption-controller: osd is down in the failure domain "node01", but pgs are active+clean. Requeuing in case pg status is not updated yet...
2023-04-19 09:22:38.202537 I | clusterdisruption-controller: osd "rook-ceph-osd-0" is down but no node drain is detected
2023-04-19 09:22:39.095897 E | ceph-spec: failed to update cluster condition to {Type:Ready Status:True Reason:ClusterCreated Message:Cluster created successfully LastHeartbeatTime:2023-04-19 09:22:39.011250532 +0000 UTC m=+3344.092036221 LastTransitionTime:2023-04-19 08:18:33 +0000 UTC}. failed to update object "rook-ceph/rook-ceph" status: Operation cannot be fulfilled on cephclusters.ceph.rook.io "rook-ceph": the object has been modified; please apply your changes to the latest version and try again
2023-04-19 09:22:40.598275 W | cephclient: the cluster has fewer than 3 osds. not performing upgrade check. running in best-effort
2023-04-19 09:22:40.598339 I | op-osd: skipping osd checks for ok-to-stop
2023-04-19 09:22:40.609531 I | op-osd: updating OSD 1 on node "node02"
2023-04-19 09:22:41.315996 I | clusterdisruption-controller: osd is down in the failure domain "node01", but pgs are active+clean. Requeuing in case pg status is not updated yet...
2023-04-19 09:22:41.625064 I | op-osd: OSD orchestration status for node node01 is "orchestrating"
2023-04-19 09:22:42.999611 I | op-osd: OSD orchestration status for node node01 is "failed"
2023-04-19 09:22:42.999658 E | op-osd: failed to provision OSD(s) on node node01. &{OSDs:[] Status:failed PvcBackedOSD:false Message:failed to configure devices: failed to initialize osd: metadata device sdb is not found}
2023-04-19 09:22:43.034642 E | ceph-cluster-controller: failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph osds: 1 failures encountered while running osds on nodes in namespace "rook-ceph".
failed to provision OSD(s) on node node01. &{OSDs:[] Status:failed PvcBackedOSD:false Message:failed to configure devices: failed to initialize osd: metadata device sdb is not found}
2023-04-19 09:22:53.203547 I | clusterdisruption-controller: osd "rook-ceph-osd-0" is down but no node drain is detected
2023-04-19 09:22:54.830004 I | clusterdisruption-controller: osd is down in the failure domain "node01", but pgs are active+clean. Requeuing in case pg status is not updated yet...
2023-04-19 09:22:56.317847 I | clusterdisruption-controller: osd "rook-ceph-osd-0" is down but no node drain is detected
2023-04-19 09:22:57.843877 I | clusterdisruption-controller: osd is down in the failure domain "node01", but pgs are active+clean. Requeuing in case pg status is not updated yet...
2023-04-19 09:23:09.832211 I | clusterdisruption-controller: osd "rook-ceph-osd-0" is down but no node drain is detected
2023-04-19 09:23:11.512276 I | clusterdisruption-controller: osd is down in the failure domain "node01", but pgs are active+clean. Requeuing in case pg status is not updated yet...
2023-04-19 09:23:12.846086 I | clusterdisruption-controller: osd "rook-ceph-osd-0" is down but no node drain is detected
2023-04-19 09:23:14.402978 I | clusterdisruption-controller: osd is down in the failure domain "node01", but pgs are active+clean. Requeuing in case pg status is not updated yet...`
* Crashing pod(s) logs, if necessary
osd-0 logs:
`> k logs -f -n rook-ceph rook-ceph-osd-0-74d94d69c4-hvdh6 activate
+ OSD_ID=0
+ CEPH_FSID=51046e26-f1e8-4ecf-bbda-979f6bfa6a5d
+ OSD_UUID=fc26116e-dec0-4109-b792-e1e947ced2d1
+ OSD_STORE_FLAG=--bluestore
+ OSD_DATA_DIR=/var/lib/ceph/osd/ceph-0
+ CV_MODE=lvm
+ DEVICE=/dev/ceph-8f03dc71-80c3-40c7-ad66-fb609ccc892a/osd-block-fc26116e-dec0-4109-b792-e1e947ced2d1
+ cp --no-preserve=mode /etc/temp-ceph/ceph.conf /etc/ceph/ceph.conf
+ python3 -c '
import configparser

config = configparser.ConfigParser()
config.read('\''/etc/ceph/ceph.conf'\'')

if not config.has_section('\''global'\''):
    config['\''global'\''] = {}

if not config.has_option('\''global'\'','\''fsid'\''):
    config['\''global'\'']['\''fsid'\''] = '\''51046e26-f1e8-4ecf-bbda-979f6bfa6a5d'\''

with open('\''/etc/ceph/ceph.conf'\'', '\''w'\'') as configfile:
    config.write(configfile)
'
+ ceph -n client.admin auth get-or-create osd.0 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring
[osd.0]
	key = AQBRpj9kRQjiNhAA2LsaHgIwOeEYU2ofnQccxQ==
+ [[ lvm == \l\v\m ]]
++ mktemp -d
+ TMP_DIR=/tmp/tmp.00vcBhR5R7
+ ceph-volume lvm activate --no-systemd --bluestore 0 fc26116e-dec0-4109-b792-e1e947ced2d1
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 41, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 153, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/main.py", line 46, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 380, in main
    self.activate(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 299, in activate
    activate_bluestore(lvs, args.no_systemd, getattr(args, 'no_tmpfs', False))
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 149, in activate_bluestore
    raise RuntimeError('could not find a bluestore OSD to activate')
RuntimeError: could not find a bluestore OSD to activate`
 osd-prepare:
`2023-04-19 08:50:50.688300 D | exec: Running command: lsblk /dev/vdc --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME,MOUNTPOINT,FSTYPE
2023-04-19 08:50:50.694535 D | sys: lsblk output: "SIZE=\"214748364800\" ROTA=\"1\" RO=\"0\" TYPE=\"disk\" PKNAME=\"\" NAME=\"/dev/vdc\" KNAME=\"/dev/vdc\" MOUNTPOINT=\"\" FSTYPE=\"\""
2023-04-19 08:50:50.694592 D | exec: Running command: sgdisk --print /dev/vdc
2023-04-19 08:50:50.700524 D | exec: Running command: udevadm info --query=property /dev/vdc
2023-04-19 08:50:50.707246 D | sys: udevadm info output: "DEVLINKS=/dev/disk/by-path/virtio-pci-0000:00:05.0 /dev/disk/by-id/virtio-6bba4a6c-c6b4-4577-b /dev/disk/by-path/pci-0000:00:05.0\nDEVNAME=/dev/vdc\nDEVPATH=/devices/pci0000:00/0000:00:05.0/virtio2/block/vdc\nDEVTYPE=disk\nID_PATH=pci-0000:00:05.0\nID_PATH_TAG=pci-0000_00_05_0\nID_SERIAL=6bba4a6c-c6b4-4577-b\nMAJOR=253\nMINOR=32\nSUBSYSTEM=block\nTAGS=:systemd:\nUSEC_INITIALIZED=1642288355"
2023-04-19 08:50:50.707294 D | exec: Running command: lsblk --noheadings --path --list --output NAME /dev/vdc
2023-04-19 08:50:50.709944 D | inventory: discovered disks are:
2023-04-19 08:50:50.710101 D | inventory: &{Name:sda1 Parent:sda HasChildren:false DevLinks:/dev/disk/by-uuid/bb9f682c-5636-4684-aca6-b1ce5c576fb2 /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0-part1 /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_2a39b4b9-070a-416e-9-part1 Size:107373116928 UUID: Serial:0QEMU_QEMU_HARDDISK_2a39b4b9-070a-416e-9 Type:part Rotational:true Readonly:false Partitions:[] Filesystem:ext4 Mountpoint:rootfs Vendor:QEMU Model:QEMU_HARDDISK WWN: WWNVendorExtension: Empty:false CephVolumeData: RealPath:/dev/sda1 KernelName:sda1 Encrypted:false}
2023-04-19 08:50:50.710124 D | inventory: &{Name:dm-1 Parent: HasChildren:false DevLinks:/dev/disk/by-id/dm-uuid-LVM-3ETQ7EG2x3ev8zO1w7oDdaOSOyv4WsIbt6XQnOXo1uh3WD7M7sXh3ZHgzZXjiJmE /dev/disk/by-id/dm-name-ceph--1f6901ad--8237--4c62--9461--c2837964e21f-osd--db--357ba145--63ac--4c83--8dc6--62dccc8f6bae Size:21474836480 UUID: Serial: Type:lvm Rotational:true Readonly:false Partitions:[] Filesystem: Mountpoint: Vendor: Model: WWN: WWNVendorExtension: Empty:false CephVolumeData: RealPath:/dev/mapper/ceph--1f6901ad--8237--4c62--9461--c2837964e21f-osd--db--357ba145--63ac--4c83--8dc6--62dccc8f6bae KernelName:dm-1 Encrypted:false}
2023-04-19 08:50:50.710148 D | inventory: &{Name:vdc Parent: HasChildren:false DevLinks:/dev/disk/by-path/virtio-pci-0000:00:05.0 /dev/disk/by-id/virtio-6bba4a6c-c6b4-4577-b /dev/disk/by-path/pci-0000:00:05.0 Size:214748364800 UUID:214da919-685b-423b-81de-35d9fc1476a1 Serial:6bba4a6c-c6b4-4577-b Type:disk Rotational:true Readonly:false Partitions:[] Filesystem: Mountpoint: Vendor: Model: WWN: WWNVendorExtension: Empty:false CephVolumeData: RealPath:/dev/vdc KernelName:vdc Encrypted:false}
2023-04-19 08:50:50.710154 I | cephosd: creating and starting the osds
2023-04-19 08:50:50.710176 D | cephosd: desiredDevices are [{Name:vdc OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: InitialWeight: IsFilter:false IsDevicePathFilter:false}]
2023-04-19 08:50:50.710189 D | cephosd: context.Devices are:
2023-04-19 08:50:50.710203 D | cephosd: &{Name:sda1 Parent:sda HasChildren:false DevLinks:/dev/disk/by-uuid/bb9f682c-5636-4684-aca6-b1ce5c576fb2 /dev/disk/by-path/pci-0000:00:04.0-scsi-0:0:0:0-part1 /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_2a39b4b9-070a-416e-9-part1 Size:107373116928 UUID: Serial:0QEMU_QEMU_HARDDISK_2a39b4b9-070a-416e-9 Type:part Rotational:true Readonly:false Partitions:[] Filesystem:ext4 Mountpoint:rootfs Vendor:QEMU Model:QEMU_HARDDISK WWN: WWNVendorExtension: Empty:false CephVolumeData: RealPath:/dev/sda1 KernelName:sda1 Encrypted:false}
2023-04-19 08:50:50.710216 D | cephosd: &{Name:dm-1 Parent: HasChildren:false DevLinks:/dev/disk/by-id/dm-uuid-LVM-3ETQ7EG2x3ev8zO1w7oDdaOSOyv4WsIbt6XQnOXo1uh3WD7M7sXh3ZHgzZXjiJmE /dev/disk/by-id/dm-name-ceph--1f6901ad--8237--4c62--9461--c2837964e21f-osd--db--357ba145--63ac--4c83--8dc6--62dccc8f6bae Size:21474836480 UUID: Serial: Type:lvm Rotational:true Readonly:false Partitions:[] Filesystem: Mountpoint: Vendor: Model: WWN: WWNVendorExtension: Empty:false CephVolumeData: RealPath:/dev/mapper/ceph--1f6901ad--8237--4c62--9461--c2837964e21f-osd--db--357ba145--63ac--4c83--8dc6--62dccc8f6bae KernelName:dm-1 Encrypted:false}
2023-04-19 08:50:50.710228 D | cephosd: &{Name:vdc Parent: HasChildren:false DevLinks:/dev/disk/by-path/virtio-pci-0000:00:05.0 /dev/disk/by-id/virtio-6bba4a6c-c6b4-4577-b /dev/disk/by-path/pci-0000:00:05.0 Size:214748364800 UUID:214da919-685b-423b-81de-35d9fc1476a1 Serial:6bba4a6c-c6b4-4577-b Type:disk Rotational:true Readonly:false Partitions:[] Filesystem: Mountpoint: Vendor: Model: WWN: WWNVendorExtension: Empty:false CephVolumeData: RealPath:/dev/vdc KernelName:vdc Encrypted:false}
2023-04-19 08:50:50.710237 I | cephosd: skipping device "sda1" with mountpoint "rootfs"
2023-04-19 08:50:50.710244 I | cephosd: old lsblk can't detect bluestore signature, so try to detect here
2023-04-19 08:50:50.711075 I | cephosd: skipping device "dm-1", detected an existing OSD. UUID=fc26116e-dec0-4109-b792-e1e947ced2d1
2023-04-19 08:50:50.711103 I | cephosd: old lsblk can't detect bluestore signature, so try to detect here
2023-04-19 08:50:50.711155 D | exec: Running command: lsblk /dev/vdc --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME,MOUNTPOINT,FSTYPE
2023-04-19 08:50:50.718667 D | sys: lsblk output: "SIZE=\"214748364800\" ROTA=\"1\" RO=\"0\" TYPE=\"disk\" PKNAME=\"\" NAME=\"/dev/vdc\" KNAME=\"/dev/vdc\" MOUNTPOINT=\"\" FSTYPE=\"\""
2023-04-19 08:50:50.718702 D | exec: Running command: ceph-volume inventory --format json /dev/vdc
2023-04-19 08:50:51.326978 I | cephosd: device "vdc" is available.
2023-04-19 08:50:51.327009 I | cephosd: "vdc" found in the desired devices
2023-04-19 08:50:51.327019 I | cephosd: device "vdc" is selected by the device filter/name "vdc"
2023-04-19 08:50:51.339464 I | cephosd: configuring osd devices: {"Entries":{"vdc":{"Data":-1,"Metadata":null,"Config":{"Name":"vdc","OSDsPerDevice":1,"MetadataDevice":"","DatabaseSizeMB":0,"DeviceClass":"hdd","InitialWeight":"","IsFilter":false,"IsDevicePathFilter":false},"PersistentDevicePaths":["/dev/disk/by-path/virtio-pci-0000:00:05.0","/dev/disk/by-id/virtio-6bba4a6c-c6b4-4577-b","/dev/disk/by-path/pci-0000:00:05.0"],"DeviceInfo":{"name":"vdc","parent":"","hasChildren":false,"devLinks":"/dev/disk/by-path/virtio-pci-0000:00:05.0 /dev/disk/by-id/virtio-6bba4a6c-c6b4-4577-b /dev/disk/by-path/pci-0000:00:05.0","size":214748364800,"uuid":"214da919-685b-423b-81de-35d9fc1476a1","serial":"6bba4a6c-c6b4-4577-b","type":"disk","rotational":true,"readOnly":false,"Partitions":null,"filesystem":"","mountpoint":"","vendor":"","model":"","wwn":"","wwnVendorExtension":"","empty":false,"real-path":"/dev/vdc","kernel-name":"vdc"}}}}
2023-04-19 08:50:51.339564 I | cephclient: getting or creating ceph auth key "client.bootstrap-osd"
2023-04-19 08:50:51.339587 D | exec: Running command: ceph auth get-or-create-key client.bootstrap-osd mon allow profile bootstrap-osd --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json
2023-04-19 08:50:52.010784 D | cephosd: won't use raw mode since there is a metadata device "sdb"
2023-04-19 08:50:52.010851 D | exec: Running command: nsenter --mount=/rootfs/proc/1/ns/mnt -- /usr/sbin/lvm --help
2023-04-19 08:50:52.023547 I | cephosd: successfully called nsenter
2023-04-19 08:50:52.023582 I | cephosd: binary "/usr/sbin/lvm" found on the host, proceeding with osd preparation
2023-04-19 08:50:52.025207 I | cephosd: Successfully updated lvm config file "/etc/lvm/lvm.conf"
2023-04-19 08:50:52.025402 I | cephosd: configuring new LVM device vdc
2023-04-19 08:50:52.046802 C | rookcmd: failed to configure devices: failed to initialize osd: metadata device sdb is not found`

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by travisn** [comment]
```
2023-04-19 08:50:52.046802 C | rookcmd: failed to configure devices: failed to initialize osd: metadata device sdb is not found
```
Are there any log messages earlier in the osd prepare log that would show that sdb exists or not? Rook is saying the disk isn't found. If you run lsblk on the host, you see it, right?
