### ISSUE TITLE
OSD containers turns to CrashLoopBackOff after reboot

### ISSUE THREAD

**Issue by C4a15Wh** [rook/rook#12708]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**
I reboot the node which the OSDs in, and upgrade the old kernel(4.19) with the new kernel(6.10)
I'm sure that the kubelet、dockerd and containerd worked well, and the PCIe SSD Device has been detected.
However, the OSDs Pods didn't work well as usual, it turns to "CrashLoopBackOff" and show me the log: 
<View it at logs area>
I don't know what it happens, please tell me how to resolve the problem, thx!!!!

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

Operator Pods: 
```
kubectl logs rook-ceph-operator-76fcc58ff4-xnqxf -n rook-ceph
2023-08-12 17:21:54.404683 I | op-flags: failed to set flag "logtostderr". no such flag -logtostderr
2023-08-12 17:21:54.404983 I | rookcmd: starting Rook v1.7.11 with arguments '/usr/local/bin/rook ceph operator'
2023-08-12 17:21:54.405004 I | rookcmd: flag values: --csi-cephfs-plugin-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin.yaml, --csi-cephfs-provisioner-dep-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin-provisioner-dep.yaml, --csi-rbd-plugin-template-path=/etc/ceph-csi/rbd/csi-rbdplugin.yaml, --csi-rbd-provisioner-dep-template-path=/etc/ceph-csi/rbd/csi-rbdplugin-provisioner-dep.yaml, --enable-machine-disruption-budget=false, --help=false, --kubeconfig=, --log-level=INFO, --operator-image=, --service-account=
2023-08-12 17:21:54.405009 I | cephcmd: starting Rook-Ceph operator
2023-08-12 17:21:54.538688 I | cephcmd: base ceph version inside the rook operator image is "ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable)"
2023-08-12 17:21:54.545143 I | op-k8sutil: ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS="15" (configmap)
2023-08-12 17:21:54.547959 I | op-k8sutil: ROOK_ENABLE_DISCOVERY_DAEMON="false" (configmap)
2023-08-12 17:21:54.551014 I | operator: looking for secret "rook-ceph-admission-controller"
2023-08-12 17:21:54.553741 I | operator: secret "rook-ceph-admission-controller" not found. proceeding without the admission controller
2023-08-12 17:21:54.556991 I | op-k8sutil: ROOK_ENABLE_FLEX_DRIVER="false" (configmap)
2023-08-12 17:21:54.557002 I | operator: watching all namespaces for ceph cluster CRs
2023-08-12 17:21:54.557121 I | operator: setting up the controller-runtime manager
2023-08-12 17:21:54.559597 I | ceph-cluster-controller: ConfigMap "rook-ceph-operator-config" changes detected. Updating configurations
2023-08-12 17:21:54.564018 I | op-k8sutil: ROOK_LOG_LEVEL="INFO" (configmap)
2023-08-12 17:21:55.166142 I | ceph-cluster-controller: successfully started
2023-08-12 17:21:55.166230 I | ceph-cluster-controller: enabling hotplug orchestration
2023-08-12 17:21:55.166252 I | ceph-crashcollector-controller: successfully started
2023-08-12 17:21:55.166319 I | ceph-block-pool-controller: successfully started
2023-08-12 17:21:55.166383 I | ceph-object-store-user-controller: successfully started
2023-08-12 17:21:55.166451 I | ceph-object-realm-controller: successfully started
2023-08-12 17:21:55.166503 I | ceph-object-zonegroup-controller: successfully started
2023-08-12 17:21:55.166553 I | ceph-object-zone-controller: successfully started
2023-08-12 17:21:55.166699 I | ceph-object-controller: successfully started
2023-08-12 17:21:55.166804 I | ceph-file-controller: successfully started
2023-08-12 17:21:55.166875 I | ceph-nfs-controller: successfully started
2023-08-12 17:21:55.166959 I | ceph-rbd-mirror-controller: successfully started
2023-08-12 17:21:55.167033 I | ceph-client-controller: successfully started
2023-08-12 17:21:55.167092 I | ceph-filesystem-mirror-controller: successfully started
2023-08-12 17:21:55.168117 I | operator: starting the controller-runtime manager
2023-08-12 17:21:55.272259 I | clusterdisruption-controller: create event from ceph cluster CR
2023-08-12 17:21:55.372890 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2023-08-12 17:21:55.376022 I | op-k8sutil: ROOK_ENABLE_FLEX_DRIVER="false" (configmap)
2023-08-12 17:21:55.377805 I | clusterdisruption-controller: deleted all legacy blocking PDBs for osds
2023-08-12 17:21:55.383363 I | clusterdisruption-controller: deleted all legacy node drain canary pods
2023-08-12 17:21:55.401731 I | ceph-csi: successfully created csi config map "rook-ceph-csi-config"
2023-08-12 17:21:55.408924 I | op-k8sutil: ROOK_CSI_ENABLE_RBD="true" (configmap)
2023-08-12 17:21:55.411106 I | op-mon: parsing mon endpoints: b=192.168.1.10:6789,d=192.168.1.8:6789,c=192.168.1.9:6789
2023-08-12 17:21:55.423901 I | ceph-cluster-controller: enabling ceph mon monitoring goroutine for cluster "rook-ceph"
2023-08-12 17:21:55.423931 I | op-osd: ceph osd status in namespace "rook-ceph" check interval "1m0s"
2023-08-12 17:21:55.423937 I | ceph-cluster-controller: enabling ceph osd monitoring goroutine for cluster "rook-ceph"
2023-08-12 17:21:55.423953 I | ceph-cluster-controller: ceph status check interval is 1m0s
2023-08-12 17:21:55.423962 I | ceph-cluster-controller: enabling ceph status monitoring goroutine for cluster "rook-ceph"
2023-08-12 17:21:55.527567 I | ceph-cluster-controller: skipping ceph status since operator is still initializing
2023-08-12 17:21:55.610487 I | op-k8sutil: ROOK_CSI_ENABLE_CEPHFS="true" (configmap)
2023-08-12 17:21:55.809777 I | op-k8sutil: ROOK_OBC_WATCH_OPERATOR_NAMESPACE="true" (configmap)
2023-08-12 17:21:55.809807 I | op-bucket-prov: ceph bucket provisioner launched watching for provisioner "rook-ceph.ceph.rook.io/bucket"
I0812 17:21:55.811877       7 manager.go:118] objectbucket.io/provisioner-manager "msg"="starting provisioner"  "name"="rook-ceph.ceph.rook.io/bucket"
2023-08-12 17:21:56.010240 I | op-k8sutil: ROOK_CSI_ALLOW_UNSUPPORTED_VERSION="false" (configmap)
2023-08-12 17:21:56.237952 I | ceph-cluster-controller: detecting the ceph image version for image registry.cn-beijing.aliyuncs.com/yunionio/ceph:v14.2.22...
2023-08-12 17:21:56.410825 I | op-k8sutil: ROOK_CSI_ENABLE_GRPC_METRICS="false" (configmap)
2023-08-12 17:21:56.810234 I | op-k8sutil: CSI_ENABLE_HOST_NETWORK="true" (default)
2023-08-12 17:21:57.210444 I | op-k8sutil: ROOK_CSI_CEPH_IMAGE="quay.io/cephcsi/cephcsi:v3.4.0" (default)
2023-08-12 17:21:57.410081 I | op-k8sutil: ROOK_CSI_REGISTRAR_IMAGE="k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0" (default)
2023-08-12 17:21:57.610353 I | op-k8sutil: ROOK_CSI_PROVISIONER_IMAGE="k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0" (default)
2023-08-12 17:21:57.809706 I | op-k8sutil: ROOK_CSI_ATTACHER_IMAGE="k8s.gcr.io/sig-storage/csi-attacher:v3.3.0" (default)
2023-08-12 17:21:58.010002 I | op-k8sutil: ROOK_CSI_SNAPSHOTTER_IMAGE="k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.0" (default)
2023-08-12 17:21:58.210425 I | op-k8sutil: ROOK_CSI_KUBELET_DIR_PATH="/var/lib/kubelet" (default)
2023-08-12 17:21:58.409693 I | op-k8sutil: CSI_VOLUME_REPLICATION_IMAGE="quay.io/csiaddons/volumereplication-operator:v0.1.0" (default)
2023-08-12 17:21:58.610307 I | op-k8sutil: ROOK_CSI_CEPHFS_POD_LABELS="" (default)
2023-08-12 17:21:58.810253 I | op-k8sutil: ROOK_CSI_RBD_POD_LABELS="" (default)
2023-08-12 17:21:58.810270 I | ceph-csi: detecting the ceph csi image version for image "quay.io/cephcsi/cephcsi:v3.4.0"
2023-08-12 17:21:59.010561 I | op-k8sutil: CSI_PROVISIONER_TOLERATIONS="" (default)
2023-08-12 17:21:59.409472 I | op-k8sutil: CSI_PROVISIONER_NODE_AFFINITY="" (default)
2023-08-12 17:21:59.612868 I | ceph-cluster-controller: detected ceph image version: "14.2.22-0 nautilus"
2023-08-12 17:21:59.612891 I | ceph-cluster-controller: validating ceph version from provided image
2023-08-12 17:22:00.409989 I | op-mon: parsing mon endpoints: b=192.168.1.10:6789,d=192.168.1.8:6789,c=192.168.1.9:6789
2023-08-12 17:22:00.609349 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2023-08-12 17:22:00.609472 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2023-08-12 17:22:00.920298 I | ceph-cluster-controller: cluster "rook-ceph": version "14.2.22-0 nautilus" detected for image "registry.cn-beijing.aliyuncs.com/yunionio/ceph:v14.2.22"
2023-08-12 17:22:00.957952 I | op-mon: start running mons
2023-08-12 17:22:01.209714 I | op-mon: parsing mon endpoints: b=192.168.1.10:6789,d=192.168.1.8:6789,c=192.168.1.9:6789
2023-08-12 17:22:01.810645 I | op-mon: saved mon endpoints to config map map[csi-cluster-config-json:[{"clusterID":"rook-ceph","monitors":["192.168.1.10:6789","192.168.1.8:6789","192.168.1.9:6789"]}] data:b=192.168.1.10:6789,d=192.168.1.8:6789,c=192.168.1.9:6789 mapping:{"node":{"b":{"Name":"gpu-worker-04","Hostname":"gpu-worker-04","Address":"192.168.1.10"},"c":{"Name":"storage-02","Hostname":"storage-02","Address":"192.168.1.9"},"d":{"Name":"storage-01","Hostname":"storage-01","Address":"192.168.1.8"}}} maxMonId:3]
2023-08-12 17:22:02.609987 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2023-08-12 17:22:02.610208 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2023-08-12 17:22:02.812899 I | ceph-csi: Detected ceph CSI image version: "v3.4.0"
2023-08-12 17:22:03.209609 I | op-k8sutil: CSI_FORCE_CEPHFS_KERNEL_CLIENT="true" (configmap)
2023-08-12 17:22:03.609660 I | op-k8sutil: CSI_CEPHFS_GRPC_METRICS_PORT="9091" (default)
2023-08-12 17:22:04.009809 I | op-k8sutil: CSI_CEPHFS_LIVENESS_METRICS_PORT="9081" (default)
2023-08-12 17:22:04.409959 I | op-k8sutil: CSI_RBD_GRPC_METRICS_PORT="9090" (default)
2023-08-12 17:22:04.810449 I | op-k8sutil: CSI_RBD_LIVENESS_METRICS_PORT="9080" (default)
2023-08-12 17:22:05.009922 I | op-mon: targeting the mon count 3
2023-08-12 17:22:05.015514 I | op-config: setting "global"="mon allow pool delete"="true" option to the mon configuration database
2023-08-12 17:22:05.210406 I | op-k8sutil: CSI_PLUGIN_PRIORITY_CLASSNAME="" (default)
2023-08-12 17:22:05.289295 I | op-config: successfully set "global"="mon allow pool delete"="true" option to the mon configuration database
2023-08-12 17:22:05.289314 I | op-config: setting "global"="mon cluster log file"="" option to the mon configuration database
2023-08-12 17:22:05.409583 I | op-k8sutil: CSI_PROVISIONER_PRIORITY_CLASSNAME="" (default)
2023-08-12 17:22:05.560086 I | op-config: successfully set "global"="mon cluster log file"="" option to the mon configuration database
2023-08-12 17:22:05.560114 I | op-config: setting "global"="osd scrub auto repair"="true" option to the mon configuration database
2023-08-12 17:22:05.610290 I | op-k8sutil: CSI_ENABLE_OMAP_GENERATOR="false" (default)
2023-08-12 17:22:05.809300 I | op-k8sutil: CSI_ENABLE_RBD_SNAPSHOTTER="true" (configmap)
2023-08-12 17:22:05.832840 I | op-config: successfully set "global"="osd scrub auto repair"="true" option to the mon configuration database
2023-08-12 17:22:05.832858 I | op-config: setting "global"="log to file"="false" option to the mon configuration database
2023-08-12 17:22:06.011495 I | op-k8sutil: CSI_ENABLE_CEPHFS_SNAPSHOTTER="true" (configmap)
2023-08-12 17:22:06.105990 I | op-config: successfully set "global"="log to file"="false" option to the mon configuration database
2023-08-12 17:22:06.106017 I | op-config: setting "global"="rbd_default_features"="3" option to the mon configuration database
2023-08-12 17:22:06.209803 I | op-k8sutil: CSI_ENABLE_VOLUME_REPLICATION="false" (configmap)
2023-08-12 17:22:06.376995 I | op-config: successfully set "global"="rbd_default_features"="3" option to the mon configuration database
2023-08-12 17:22:06.377018 I | op-config: deleting "log file" option from the mon configuration database
2023-08-12 17:22:06.410272 I | op-k8sutil: CSI_CEPHFS_PLUGIN_UPDATE_STRATEGY="RollingUpdate" (default)
2023-08-12 17:22:06.609945 I | op-k8sutil: CSI_RBD_PLUGIN_UPDATE_STRATEGY="RollingUpdate" (default)
2023-08-12 17:22:06.609972 I | ceph-csi: Kubernetes version is 1.15+
2023-08-12 17:22:06.683732 I | op-config: successfully deleted "log file" option from the mon configuration database
2023-08-12 17:22:06.683759 I | op-mon: checking for basic quorum with existing mons
2023-08-12 17:22:06.683769 I | op-mon: setting mon endpoints for hostnetwork mode
2023-08-12 17:22:06.683790 I | op-mon: setting mon endpoints for hostnetwork mode
2023-08-12 17:22:06.683798 I | op-mon: setting mon endpoints for hostnetwork mode
2023-08-12 17:22:06.810310 I | op-k8sutil: ROOK_CSI_RESIZER_IMAGE="k8s.gcr.io/sig-storage/csi-resizer:v1.3.0" (default)
2023-08-12 17:22:06.810338 W | ceph-csi: CSI Block volume expansion requires Kubernetes version >=1.16.0
2023-08-12 17:22:07.209609 I | op-k8sutil: CSI_LOG_LEVEL="" (default)
2023-08-12 17:22:07.810269 I | op-mon: saved mon endpoints to config map map[csi-cluster-config-json:[{"clusterID":"rook-ceph","monitors":["192.168.1.10:6789","192.168.1.8:6789","192.168.1.9:6789"]}] data:b=192.168.1.10:6789,d=192.168.1.8:6789,c=192.168.1.9:6789 mapping:{"node":{"b":{"Name":"gpu-worker-04","Hostname":"gpu-worker-04","Address":"192.168.1.10"},"c":{"Name":"storage-02","Hostname":"storage-02","Address":"192.168.1.9"},"d":{"Name":"storage-01","Hostname":"storage-01","Address":"192.168.1.8"}}} maxMonId:3]
2023-08-12 17:22:08.010359 I | op-k8sutil: CSI_PROVISIONER_REPLICAS="2" (configmap)
2023-08-12 17:22:08.410674 I | op-k8sutil: CSI_PROVISIONER_TOLERATIONS="" (default)
2023-08-12 17:22:08.809781 I | op-k8sutil: CSI_PROVISIONER_NODE_AFFINITY="" (default)
2023-08-12 17:22:09.009603 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2023-08-12 17:22:09.009826 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2023-08-12 17:22:09.210165 I | op-k8sutil: CSI_PLUGIN_TOLERATIONS="" (default)
2023-08-12 17:22:09.609845 I | op-k8sutil: CSI_PLUGIN_NODE_AFFINITY="" (default)
2023-08-12 17:22:09.836258 I | op-mon: deployment for mon rook-ceph-mon-b already exists. updating if needed
2023-08-12 17:22:09.847226 I | op-k8sutil: deployment "rook-ceph-mon-b" did not change, nothing to update
2023-08-12 17:22:09.847254 I | op-mon: waiting for mon quorum with [b d c]
2023-08-12 17:22:10.010179 I | op-k8sutil: CSI_RBD_PLUGIN_TOLERATIONS="" (default)
2023-08-12 17:22:10.409557 I | op-k8sutil: CSI_RBD_PLUGIN_NODE_AFFINITY="" (default)
2023-08-12 17:22:10.810141 I | op-k8sutil: CSI_RBD_PLUGIN_RESOURCE="" (default)
2023-08-12 17:22:11.014284 I | op-mon: mons running: [b d c]
2023-08-12 17:22:11.210262 I | op-k8sutil: CSI_RBD_PROVISIONER_TOLERATIONS="" (default)
2023-08-12 17:22:11.322252 I | op-mon: Monitors in quorum: [b c d]
2023-08-12 17:22:11.328191 I | op-mon: deployment for mon rook-ceph-mon-d already exists. updating if needed
2023-08-12 17:22:11.338999 I | op-k8sutil: deployment "rook-ceph-mon-d" did not change, nothing to update
2023-08-12 17:22:11.339031 I | op-mon: waiting for mon quorum with [b d c]
2023-08-12 17:22:11.409796 I | op-k8sutil: CSI_RBD_PROVISIONER_NODE_AFFINITY="" (default)
2023-08-12 17:22:11.809589 I | op-k8sutil: CSI_RBD_PROVISIONER_RESOURCE="" (default)
2023-08-12 17:22:11.834131 I | ceph-csi: successfully started CSI Ceph RBD driver
2023-08-12 17:22:12.414623 I | op-mon: mons running: [b d c]
2023-08-12 17:22:12.721242 I | op-mon: Monitors in quorum: [b c d]
2023-08-12 17:22:12.726765 I | op-mon: deployment for mon rook-ceph-mon-c already exists. updating if needed
2023-08-12 17:22:12.736967 I | op-k8sutil: deployment "rook-ceph-mon-c" did not change, nothing to update
2023-08-12 17:22:12.736998 I | op-mon: waiting for mon quorum with [b d c]
2023-08-12 17:22:13.210550 I | op-k8sutil: CSI_CEPHFS_PLUGIN_TOLERATIONS="" (default)
2023-08-12 17:22:13.610303 I | op-k8sutil: CSI_CEPHFS_PLUGIN_NODE_AFFINITY="" (default)
2023-08-12 17:22:13.814690 I | op-mon: mons running: [b d c]
2023-08-12 17:22:14.010521 I | op-k8sutil: CSI_CEPHFS_PLUGIN_RESOURCE="" (default)
2023-08-12 17:22:14.114366 I | op-mon: Monitors in quorum: [b c d]
2023-08-12 17:22:14.114412 I | op-mon: mons created: 3
2023-08-12 17:22:14.210492 I | op-k8sutil: CSI_CEPHFS_PROVISIONER_TOLERATIONS="" (default)
2023-08-12 17:22:14.409749 I | op-k8sutil: CSI_CEPHFS_PROVISIONER_NODE_AFFINITY="" (default)
2023-08-12 17:22:14.427886 I | op-mon: waiting for mon quorum with [b d c]
2023-08-12 17:22:14.610243 I | op-k8sutil: CSI_CEPHFS_PROVISIONER_RESOURCE="" (default)
2023-08-12 17:22:14.629980 I | ceph-csi: successfully started CSI CephFS driver
2023-08-12 17:22:15.615033 I | op-mon: mons running: [b d c]
2023-08-12 17:22:15.919829 I | op-mon: Monitors in quorum: [b c d]
2023-08-12 17:22:15.920887 I | cephclient: getting or creating ceph auth key "client.csi-rbd-provisioner"
2023-08-12 17:22:16.010415 I | op-k8sutil: CSI_RBD_FSGROUPPOLICY="ReadWriteOnceWithFSType" (configmap)
2023-08-12 17:22:16.019063 I | ceph-csi: CSIDriver object updated for driver "rook-ceph.rbd.csi.ceph.com"
2023-08-12 17:22:16.209538 I | op-k8sutil: CSI_CEPHFS_FSGROUPPOLICY="None" (configmap)
2023-08-12 17:22:16.215163 I | ceph-csi: CSIDriver object updated for driver "rook-ceph.cephfs.csi.ceph.com"
2023-08-12 17:22:16.233924 I | cephclient: getting or creating ceph auth key "client.csi-rbd-node"
2023-08-12 17:22:16.559352 I | cephclient: getting or creating ceph auth key "client.csi-cephfs-provisioner"
2023-08-12 17:22:16.872723 I | cephclient: getting or creating ceph auth key "client.csi-cephfs-node"
2023-08-12 17:22:17.810553 I | ceph-csi: created kubernetes csi secrets for cluster "rook-ceph"
2023-08-12 17:22:17.810581 I | cephclient: getting or creating ceph auth key "client.crash"
2023-08-12 17:22:18.210141 I | ceph-crashcollector-controller: created kubernetes crash collector secret for cluster "rook-ceph"
2023-08-12 17:22:18.522213 I | cephclient: successfully enabled msgr2 protocol
2023-08-12 17:22:18.522263 I | cephclient: create rbd-mirror bootstrap peer token "client.rbd-mirror-peer"
2023-08-12 17:22:18.522281 I | cephclient: getting or creating ceph auth key "client.rbd-mirror-peer"
2023-08-12 17:22:18.833854 I | cephclient: successfully created rbd-mirror bootstrap peer token for cluster "rook-ceph"
2023-08-12 17:22:18.852681 I | op-mgr: start running mgr
2023-08-12 17:22:18.852713 I | cephclient: getting or creating ceph auth key "mgr.a"
2023-08-12 17:22:19.218474 I | op-mgr: deployment for mgr rook-ceph-mgr-a already exists. updating if needed
2023-08-12 17:22:19.227502 I | op-k8sutil: deployment "rook-ceph-mgr-a" did not change, nothing to update
2023-08-12 17:22:19.231293 I | op-mgr: setting services to point to mgr "a"
2023-08-12 17:22:20.612701 I | op-mgr: no need to update service "rook-ceph-mgr"
2023-08-12 17:22:20.612730 I | op-mgr: no need to update service "rook-ceph-mgr-dashboard"
2023-08-12 17:22:20.622112 I | op-osd: start running osds in namespace "rook-ceph"
2023-08-12 17:22:20.622137 I | op-osd: wait timeout for healthy OSDs during upgrade or restart is "10m0s"
2023-08-12 17:22:20.627566 I | op-osd: start provisioning the OSDs on PVCs, if needed
2023-08-12 17:22:20.811519 I | op-osd: no storageClassDeviceSets defined to configure OSDs on PVCs
2023-08-12 17:22:20.811549 I | op-osd: start provisioning the OSDs on nodes, if needed
2023-08-12 17:22:21.015744 I | op-osd: 2 of the 2 storage nodes are valid
2023-08-12 17:22:21.414658 I | op-k8sutil: Removing previous job rook-ceph-osd-prepare-storage-01 to start a new one
2023-08-12 17:22:21.424118 I | op-k8sutil: batch job rook-ceph-osd-prepare-storage-01 still exists
2023-08-12 17:22:21.624096 I | op-mgr: successful modules: crash
2023-08-12 17:22:21.625597 I | op-mgr: successful modules: prometheus
2023-08-12 17:22:21.626311 I | op-config: setting "global"="osd_pool_default_pg_autoscale_mode"="on" option to the mon configuration database
2023-08-12 17:22:21.900900 I | op-config: successfully set "global"="osd_pool_default_pg_autoscale_mode"="on" option to the mon configuration database
2023-08-12 17:22:21.900928 I | op-config: setting "global"="mon_pg_warn_min_per_osd"="0" option to the mon configuration database
2023-08-12 17:22:22.177404 I | op-config: successfully set "global"="mon_pg_warn_min_per_osd"="0" option to the mon configuration database
2023-08-12 17:22:22.177431 I | op-mgr: successful modules: mgr module(s) from the spec
2023-08-12 17:22:24.427897 I | op-k8sutil: batch job rook-ceph-osd-prepare-storage-01 deleted
2023-08-12 17:22:24.432772 I | op-osd: started OSD provisioning job for node "storage-01"
2023-08-12 17:22:24.442866 I | op-k8sutil: Removing previous job rook-ceph-osd-prepare-storage-02 to start a new one
2023-08-12 17:22:24.453627 I | op-k8sutil: batch job rook-ceph-osd-prepare-storage-02 still exists
2023-08-12 17:22:26.629875 I | op-mgr: the dashboard secret was already generated
2023-08-12 17:22:27.063514 I | op-mgr: setting ceph dashboard "admin" login creds
2023-08-12 17:22:27.340395 E | op-mgr: failed modules: "dashboard". failed to initialize dashboard: failed to set login credentials for the ceph dashboard: failed to set login creds on mgr: failed to complete command for set dashboard creds: exit status 17
2023-08-12 17:22:27.457634 I | op-k8sutil: batch job rook-ceph-osd-prepare-storage-02 deleted
2023-08-12 17:22:27.466345 I | op-osd: started OSD provisioning job for node "storage-02"
2023-08-12 17:22:27.469806 I | op-osd: OSD orchestration status for node storage-01 is "orchestrating"
2023-08-12 17:22:27.469835 I | op-osd: OSD orchestration status for node storage-02 is "starting"
2023-08-12 17:22:28.658341 I | op-osd: OSD orchestration status for node storage-02 is "orchestrating"
2023-08-12 17:22:40.731383 I | op-mon: checking if multiple mons are on the same node
2023-08-12 17:22:41.486867 I | op-osd: OSD orchestration status for node storage-01 is "completed"
2023-08-12 17:22:41.486900 I | op-osd: creating OSD 1 on node "storage-01"
2023-08-12 17:22:41.510544 I | op-osd: creating OSD 2 on node "storage-01"
2023-08-12 17:22:41.527895 I | op-osd: creating OSD 3 on node "storage-01"
2023-08-12 17:22:41.552980 I | op-osd: creating OSD 4 on node "storage-01"
2023-08-12 17:22:43.423912 I | op-osd: OSD orchestration status for node storage-02 is "completed"
2023-08-12 17:22:43.423944 I | op-osd: creating OSD 5 on node "storage-02"
2023-08-12 17:22:43.444729 I | op-osd: creating OSD 6 on node "storage-02"
2023-08-12 17:22:43.464904 I | op-osd: creating OSD 7 on node "storage-02"
2023-08-12 17:22:43.486110 I | op-osd: creating OSD 8 on node "storage-02"
2023-08-12 17:22:43.829526 I | op-osd: finished running OSDs in namespace "rook-ceph"
2023-08-12 17:22:43.829549 I | ceph-cluster-controller: done reconciling ceph cluster in namespace "rook-ceph"
2023-08-12 17:22:43.838600 I | op-k8sutil: Reporting Event rook-ceph:rook-ceph Normal:ReconcileSucceeded:successfully configured CephCluster "rook-ceph/rook-ceph"
root@master-01:~/rook/cluster/examples/kubernetes/ceph#
```

OSDs Pods: 
```
kubectl logs -n rook-ceph --all-containers rook-ceph-osd-1-645dd74897-49z2t
+ OSD_ID=1
+ OSD_UUID=979b24d9-b371-4955-82f3-7eb18aba2563
+ OSD_STORE_FLAG=--bluestore
+ OSD_DATA_DIR=/var/lib/ceph/osd/ceph-1
+ CV_MODE=lvm
+ DEVICE=/dev/ceph-78dc49df-6f1c-4bf5-8612-e7c8e3489e29/osd-block-979b24d9-b371-4955-82f3-7eb18aba2563
+ ceph -n client.admin auth get-or-create osd.1 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring
[osd.1]
        key = AQC4pcpkiTkoKxAAuGk5nSTaWb/i19Rvensuwg==
+ [[ lvm == \l\v\m ]]
++ mktemp -d
+ TMP_DIR=/tmp/tmp.YyDGWKQtbq
+ ceph-volume lvm activate --no-systemd --bluestore 1 979b24d9-b371-4955-82f3-7eb18aba2563
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-1
Running command: /usr/bin/ceph-bluestore-tool --cluster=ceph prime-osd-dir --dev /dev/ceph-78dc49df-6f1c-4bf5-8612-e7c8e3489e29/osd-block-979b24d9-b371-4955-82f3-7eb18aba2563 --path /var/lib/ceph/osd/ceph-1 --no-mon-config
 stderr: failed to read label for /dev/ceph-78dc49df-6f1c-4bf5-8612-e7c8e3489e29/osd-block-979b24d9-b371-4955-82f3-7eb18aba2563: (2) No such file or directory
 stderr: 2023-08-12 17:49:31.217 7fd7c94ebec0 -1 bluestore(/dev/ceph-78dc49df-6f1c-4bf5-8612-e7c8e3489e29/osd-block-979b24d9-b371-4955-82f3-7eb18aba2563) _read_bdev_label failed to open /dev/ceph-78dc49df-6f1c-4bf5-8612-e7c8e3489e29/osd-block-979b24d9-b371-4955-82f3-7eb18aba2563: (2) No such file or directory
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 9, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 39, in __init__
    self.main(self.argv)
  File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 151, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 46, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 370, in main
    self.activate(args)
  File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 294, in activate
    activate_bluestore(lvs, args.no_systemd)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 194, in activate_bluestore
    process.run(prime_command)
  File "/usr/lib/python2.7/site-packages/ceph_volume/process.py", line 153, in run
    raise RuntimeError(msg)
RuntimeError: command returned non-zero exit status: 1
Error from server (BadRequest): container "chown-container-data-dir" in pod "rook-ceph-osd-1-645dd74897-49z2t" is waiting to start: PodInitializing
```

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of krew commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook Krew Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/krew-plugin)

**Environment**:
* OS (e.g. from /etc/os-release): Debian 12
* Kernel (e.g. `uname -a`): Linux master-01 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-1 (2023-07-14) x86_64 GNU/Linux
* Cloud provider or hardware configuration: Dell R730XD
* Rook version (use `rook version` inside of a Rook Pod): Release 1.7
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.11 (3cf40e2dca667f68c6ce3ff5cd94f01e711af894) pacific (stable)
* Kubernetes version (use `kubectl version`): {Major:"1", Minor:"15+", GitVersion:"v1.15.9-beta.0", GitCommit:"14ede42c4fe699a7078b566d89abc160f26857a2", GitTreeState:"clean", BuildDate:"2020-01-15T11:07:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Self-build k8s cluster
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): it is now unavailable

**Comment by sp98** [comment]
``` Error from server (BadRequest): container "chown-container-data-dir" in pod "rook-ceph-osd-1-645dd74897-49z2t" is waiting to start: PodInitializing``` 

One of the `init` containers of the OSD pod has still not started. So we need to first check why this init container didn't start. Can you share the `kubectl describe pod` output of this OSD pod. 

Also, you seem to be running an older rook version (1.7). Any chance you can try reboot with latest stable rook. Thanks.

**Comment by travisn** [comment]
From this error, it seems the device is not found anymore:
```
 stderr: failed to read label for /dev/ceph-78dc49df-6f1c-4bf5-8612-e7c8e3489e29/osd-block-979b24d9-b371-4955-82f3-7eb18aba2563: (2) No such file or directory
 stderr: 2023-08-12 17:49:31.217 7fd7c94ebec0 -1 bluestore(/dev/ceph-78dc49df-6f1c-4bf5-8612-e7c8e3489e29/osd-block-979b24d9-b371-4955-82f3-7eb18aba2563) _read_bdev_label failed to open /dev/ceph-78dc49df-6f1c-4bf5-8612-e7c8e3489e29/osd-block-979b24d9-b371-4955-82f3-7eb18aba2563: (2) No such file or directory
```

@C4a15Wh Do you still see the devices on the host?
