### ISSUE TITLE
v17.2 could not find osd.1 with osd_fsid 1ea4333d-f1c4-4e2f-8c25-7461efaaa4b0

### ISSUE THREAD

**Issue by schroedt** [rook/rook#12842]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Ceph does not create block on `sdb` drive on new kubernetes node. Instead folder is created:

```
root@kubernetes-worker01:/var/lib/rook/rook-ceph# ls -al
total 32
drwxr-xr-x 6 root root 4096 Sep  3 14:33 .
drwxr-xr-x 4 root root 4096 Sep  3 14:25 ..
drwxr-xr-x 2 root root 4096 Sep  3 14:28 6cd2a63d-1e5e-4192-9eef-0dd90656f8e8_05f3c199-1c29-4209-9981-23e9e1cf548d
drwxr-xr-x 2 root root 4096 Sep  3 14:27 6cd2a63d-1e5e-4192-9eef-0dd90656f8e8_1ea4333d-f1c4-4e2f-8c25-7461efaaa4b0
-rw------- 1 root root  152 Sep  3 14:40 client.admin.keyring
drwxr-xr-x 2  167  167 4096 Sep  3 14:25 crash
drwxr-xr-x 2  167  167 4096 Sep  3 14:33 log
-rw-r--r-- 1 root root  328 Sep  3 14:40 rook-ceph.config
```

lvs returns no drive:

```
root@kubernetes-worker01:/var/lib/rook/rook-ceph# lvs -o lv_tags
  LV Tags
         
```

OSD pod fails in init-container:

```
kubectl -n rook-ceph logs -f pod/rook-ceph-osd-1-cb7d96984-52qgb -c activate
+ OSD_ID=1
+ CEPH_FSID=6cd2a63d-1e5e-4192-9eef-0dd90656f8e8
+ OSD_UUID=1ea4333d-f1c4-4e2f-8c25-7461efaaa4b0
+ OSD_STORE_FLAG=--bluestore
+ OSD_DATA_DIR=/var/lib/ceph/osd/ceph-1
+ CV_MODE=lvm
+ DEVICE=/dev/ceph-47ee580f-9c70-4031-aed2-4a7bf7021b87/osd-block-1ea4333d-f1c4-4e2f-8c25-7461efaaa4b0
+ cp --no-preserve=mode /etc/temp-ceph/ceph.conf /etc/ceph/ceph.conf
+ python3 -c '
import configparser

config = configparser.ConfigParser()
config.read('\''/etc/ceph/ceph.conf'\'')

if not config.has_section('\''global'\''):
    config['\''global'\''] = {}

if not config.has_option('\''global'\'','\''fsid'\''):
    config['\''global'\'']['\''fsid'\''] = '\''6cd2a63d-1e5e-4192-9eef-0dd90656f8e8'\''

with open('\''/etc/ceph/ceph.conf'\'', '\''w'\'') as configfile:
    config.write(configfile)
'
+ ceph -n client.admin auth get-or-create osd.1 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring
[osd.1]
        key = AQBTifRkxA0TJxAAsMtyFxcZifYC+Xcrt9FWYA==
+ [[ lvm == \l\v\m ]]
++ mktemp -d
+ TMP_DIR=/tmp/tmp.6AJkeMOAgb
+ ceph-volume lvm activate --no-systemd --bluestore 1 1ea4333d-f1c4-4e2f-8c25-7461efaaa4b0
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 41, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 153, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/main.py", line 46, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 380, in main
    self.activate(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 278, in activate
    (osd_id, osd_fsid))
RuntimeError: could not find osd.1 with osd_fsid 1ea4333d-f1c4-4e2f-8c25-7461efaaa4b0
```

**Expected behavior:**
Rook-Ceph creates block on `sdb` drive on kubernetes node.

**How to reproduce it (minimal and precise):**
Create K8s cluster, Hardware issue on HDD. Re-create HDD on node and you're in the error.

**File(s) to submit**:
```


    #################################################################################################################
    # Define the settings for the rook-ceph cluster with common settings for a production cluster.
    # All nodes with available raw devices will be used for the Ceph cluster. At least three nodes are required
    # in this example. See the documentation for more details on storage settings available.
     
    # For example, to create the cluster:
    #   kubectl create -f crds.yaml -f common.yaml -f operator.yaml
    #   kubectl create -f cluster.yaml
    #################################################################################################################
     
    apiVersion: ceph.rook.io/v1
    kind: CephCluster
    metadata:
      name: rook-ceph
      namespace: rook-ceph # namespace:cluster
    spec:
      cephVersion:
        # The container image used to launch the Ceph daemon pods (mon, mgr, osd, mds, rgw).
        # v13 is mimic, v14 is nautilus, and v15 is octopus.
        # RECOMMENDATION: In production, use a specific version tag instead of the general v14 flag, which pulls the latest release and could result in different
        # versions running within the cluster. See tags available at https://hub.docker.com/r/ceph/ceph/tags/.
        # If you want to be more precise, you can always use a timestamp tag such ceph/ceph:v15.2.8-20201217
        # This tag might not contain a new Ceph version, just security fixes from the underlying operating system, which will reduce vulnerabilities
        image: quay.io/ceph/ceph:v17.2
        # Whether to allow unsupported versions of Ceph. Currently `nautilus` and `octopus` are supported.
        # Future versions such as `pacific` would require this to be set to `true`.
        # Do not set to true in production.
        allowUnsupported: false
      # The path on the host where configuration files will be persisted. Must be specified.
      # Important: if you reinstall the cluster, make sure you delete this directory from each host or else the mons will fail to start on the new cluster.
      # In Minikube, the '/data' directory is configured to persist across reboots. Use "/data/rook" in Minikube environment.
      dataDirHostPath: /var/lib/rook
      # Whether or not upgrade should continue even if a check fails
      # This means Ceph's status could be degraded and we don't recommend upgrading but you might decide otherwise
      # Use at your OWN risk
      # To understand Rook's upgrade process of Ceph, read https://rook.io/docs/rook/master/ceph-upgrade.html#ceph-version-upgrades
      skipUpgradeChecks: false
      # Whether or not continue if PGs are not clean during an upgrade
      continueUpgradeAfterChecksEvenIfNotHealthy: false
      mon:
        # Set the number of mons to be started. Must be an odd number, and is generally recommended to be 3.
        count: 3
        # The mons should be on unique nodes. For production, at least 3 nodes are recommended for this reason.
        # Mons should only be allowed on the same node for test environments where data loss is acceptable.
        allowMultiplePerNode: false
      mgr:
        modules:
        # Several modules should not need to be included in this list. The "dashboard" and "monitoring" modules
        # are already enabled by other settings in the cluster CR.
        - name: pg_autoscaler
          enabled: true
      # enable the ceph dashboard for viewing cluster status
      dashboard:
        enabled: true
        # serve the dashboard under a subpath (useful when you are accessing the dashboard via a reverse proxy)
        # urlPrefix: /ceph-dashboard
        # serve the dashboard at the given port.
        # port: 8443
        # serve the dashboard using SSL
        ssl: false
      # enable prometheus alerting for cluster
      monitoring:
        # requires Prometheus to be pre-installed
        enabled: true
        # namespace to deploy prometheusRule in. If empty, namespace of the cluster will be used.
        # Recommended:
        # If you have a single rook-ceph cluster, set the rulesNamespace to the same namespace as the cluster or keep it empty.
        # If you have multiple rook-ceph clusters in the same k8s cluster, choose the same namespace (ideally, namespace with prometheus
        # deployed) to set rulesNamespace for all the clusters. Otherwise, you will get duplicate alerts with multiple alert definitions.
        #rulesNamespace: rook-ceph
      network:
        # enable host networking
        #provider: host
        # EXPERIMENTAL: enable the Multus network provider
        #provider: multus
        #selectors:
          # The selector keys are required to be `public` and `cluster`.
          # Based on the configuration, the operator will do the following:
          #   1. if only the `public` selector key is specified both public_network and cluster_network Ceph settings will listen on that interface
          #   2. if both `public` and `cluster` selector keys are specified the first one will point to 'public_network' flag and the second one to 'cluster_network'
          #
          # In order to work, each selector value must match a NetworkAttachmentDefinition object in Multus
          #
          #public: public-conf --> NetworkAttachmentDefinition object name in Multus
          #cluster: cluster-conf --> NetworkAttachmentDefinition object name in Multus
        # Provide internet protocol version. IPv6, IPv4 or empty string are valid options. Empty string would mean IPv4
        #ipFamily: "IPv6"
      # enable the crash collector for ceph daemon crash collection
      crashCollector:
        disable: true
        # Uncomment daysToRetain to prune ceph crash entries older than the
        # specified number of days.
        #daysToRetain: 7
      # enable log collector, daemons will log on files and rotate
      # logCollector:
      #   enabled: true
      #   periodicity: 24h # SUFFIX may be 'h' for hours or 'd' for days.
      # automate [data cleanup process](https://github.com/rook/rook/blob/master/Documentation/ceph-teardown.md#delete-the-data-on-hosts) in cluster destruction.
      cleanupPolicy:
        # Since cluster cleanup is destructive to data, confirmation is required.
        # To destroy all Rook data on hosts during uninstall, confirmation must be set to "yes-really-destroy-data".
        # This value should only be set when the cluster is about to be deleted. After the confirmation is set,
        # Rook will immediately stop configuring the cluster and only wait for the delete command.
        # If the empty string is set, Rook will not destroy any data on hosts during uninstall.
        #confirmation: ""
        confirmation: ""
        # sanitizeDisks represents settings for sanitizing OSD disks on cluster deletion
        sanitizeDisks:
          # method indicates if the entire disk should be sanitized or simply ceph's metadata
          # in both case, re-install is possible
          # possible choices are 'complete' or 'quick' (default)
          method: complete
          # dataSource indicate where to get random bytes from to write on the disk
          # possible choices are 'zero' (default) or 'random'
          # using random sources will consume entropy from the system and will take much more time then the zero source
          dataSource: zero
          # iteration overwrite N times instead of the default (1)
          # takes an integer value
          iteration: 3
        # allowUninstallWithVolumes defines how the uninstall should be performed
        # If set to true, cephCluster deletion does not wait for the PVs to be deleted.
        allowUninstallWithVolumes: false
      # To control where various services will be scheduled by kubernetes, use the placement configuration sections below.
      # The example under 'all' would have all services scheduled on kubernetes nodes labeled with 'role=storage-node' and
      # tolerate taints with a key of 'storage-node'.
    #  placement:
    #    all:
    #      nodeAffinity:
    #        requiredDuringSchedulingIgnoredDuringExecution:
    #          nodeSelectorTerms:
    #          - matchExpressions:
    #            - key: role
    #              operator: In
    #              values:
    #              - storage-node
    #      podAffinity:
    #      podAntiAffinity:
    #      topologySpreadConstraints:
    #      tolerations:
    #      - key: storage-node
    #        operator: Exists
    #       - effect: noSchedule
    #         key: node-role.kubernetes.io/master
    # The above placement information can also be specified for mon, osd, and mgr components
    #    mon:
    # Monitor deployments may contain an anti-affinity rule for avoiding monitor
    # collocation on the same node. This is a required rule when host network is used
    # or when AllowMultiplePerNode is false. Otherwise this anti-affinity rule is a
    # preferred rule with weight: 50.
    #    osd:
    #    mgr:
    #    cleanup:
      annotations:
    #    all:
    #    mon:
    #    osd:
    #    cleanup:
    #    prepareosd:
    # If no mgr annotations are set, prometheus scrape annotations will be set by default.
    #    mgr:
      labels:
    #    all:
    #    mon:
    #    osd:
    #    cleanup:
    #    mgr:
    #    prepareosd:
      resources:
    # The requests and limits set here, allow the mgr pod to use half of one CPU core and 1 gigabyte of memory
    #    mgr:
    #      limits:
    #        cpu: "500m"
    #        memory: "1024Mi"
    #      requests:
    #        cpu: "500m"
    #        memory: "1024Mi"
    # The above example requests/limits can also be added to the mon and osd components
    #    mon:
    #    osd:
    #    prepareosd:
    #    crashcollector:
    #    logcollector:
    #    cleanup:
      # The option to automatically remove OSDs that are out and are safe to destroy.
      removeOSDsIfOutAndSafeToRemove: false
    #  priorityClassNames:
    #    all: rook-ceph-default-priority-class
    #    mon: rook-ceph-mon-priority-class
    #    osd: rook-ceph-osd-priority-class
    #    mgr: rook-ceph-mgr-priority-class
      storage: # cluster level storage configuration and selection
        useAllNodes: true
        useAllDevices: false
        deviceFilter: sdb
        config:
          # crushRoot: "custom-root" # specify a non-default root label for the CRUSH map
          # metadataDevice: "md0" # specify a non-rotational storage so ceph-volume will use it as block db device of bluestore.
          # databaseSizeMB: "1024" # uncomment if the disks are smaller than 100 GB
          # journalSizeMB: "1024"  # uncomment if the disks are 20 GB or smaller
          # osdsPerDevice: "1" # this value can be overridden at the node or device level
          # encryptedDevice: "true" # the default value for this option is "false"
    # Individual nodes and their config can be specified as well, but 'useAllNodes' above must be set to false. Then, only the named
    # nodes below will be used as storage resources.  Each node's 'name' field should match their 'kubernetes.io/hostname' label.
    #    nodes:
    #    - name: "172.17.4.201"
    #      devices: # specific devices to use for storage can be specified for each node
    #      - name: "sdb"
    #      - name: "nvme01" # multiple osds can be created on high performance devices
    #        config:
    #          osdsPerDevice: "5"
    #      - name: "/dev/disk/by-id/ata-ST4000DM004-XXXX" # devices can be specified using full udev paths
    #      config: # configuration can be specified at the node level which overrides the cluster level config
    #        storeType: filestore
    #    - name: "172.17.4.301"
    #      deviceFilter: "^sd."
      # The section for configuring management of daemon disruptions during upgrade or fencing.
      disruptionManagement:
        # If true, the operator will create and manage PodDisruptionBudgets for OSD, Mon, RGW, and MDS daemons. OSD PDBs are managed dynamically
        # via the strategy outlined in the [design](https://github.com/rook/rook/blob/master/design/ceph/ceph-managed-disruptionbudgets.md). The operator will
        # block eviction of OSDs by default and unblock them safely when drains are detected.
        managePodBudgets: false
        # A duration in minutes that determines how long an entire failureDomain like `region/zone/host` will be held in `noout` (in addition to the
        # default DOWN/OUT interval) when it is draining. This is only relevant when  `managePodBudgets` is `true`. The default value is `30` minutes.
        osdMaintenanceTimeout: 30
        # A duration in minutes that the operator will wait for the placement groups to become healthy (active+clean) after a drain was completed and OSDs came back up.
        # Operator will continue with the next drain if the timeout exceeds. It only works if `managePodBudgets` is `true`.
        # No values or 0 means that the operator will wait until the placement groups are healthy before unblocking the next drain.
        pgHealthCheckTimeout: 0
        # If true, the operator will create and manage MachineDisruptionBudgets to ensure OSDs are only fenced when the cluster is healthy.
        # Only available on OpenShift.
        manageMachineDisruptionBudgets: false
        # Namespace in which to watch for the MachineDisruptionBudgets.
        machineDisruptionBudgetNamespace: openshift-machine-api
     
      # healthChecks
      # Valid values for daemons are 'mon', 'osd', 'status'
      healthCheck:
        daemonHealth:
          mon:
            disabled: false
            interval: 45s
          osd:
            disabled: false
            interval: 60s
          status:
            disabled: false
            interval: 60s
        # Change pod liveness probe, it works for all mon,mgr,osd daemons
        livenessProbe:
          mon:
            disabled: false
          mgr:
            disabled: false
          osd:
            disabled: false

```

**Logs to submit**:

see above

**Cluster Status to submit**:

* Output of krew commands, if necessary
health ok.

**Environment**:
ubuntu

Linux Kubernetes-Master 5.15.0-82-generic #91-Ubuntu SMP Mon Aug 14 14:14:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:40:19Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:32:47Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

K8s, 1 Master, 7 Worker

**Comment by schroedt** [comment]
Any idea how to fix the OSD in the nodes?

**Comment by microyahoo** [comment]
because your lvs list is empty

**Comment by schroedt** [comment]
> because your lvs list is empty. https://github.com/ceph/ceph/blob/27edb758abfabf7755f17ac46b6f7c341e9ca1ab/src/ceph-volume/ceph_volume/devices/lvm/activate.py#L197

Thanks! I noticed /dev/sdb was not there. Rebooting helped.
