### ISSUE TITLE
Ceph v17.2.7 fails to create or start OSDs configured on PVs or LVs

### ISSUE THREAD

**Issue by travisn** [rook/rook#13136]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Ceph v17.2.7 is failing to start OSDs in certain configurations. 
- LVs as seen [here](https://github.com/rook/rook/issues/12099#issuecomment-1789342186)
- Backed by PVs when created with `storageClassDeviceSets` (cluster-on-pvc example) as seen in the attempt to update the CI to v17.2.7 in #13127 where the [CI is failing against the PVC configuration](https://github.com/rook/rook/actions/runs/6710059130/job/18266963086?pr=13127) of the Canary tests.

**Expected behavior:**
All OSD configurations should successfully be created and upgraded.

**How to reproduce it (minimal and precise):**

Create a v17.2.7 cluster or upgrade to Ceph v17.2.7 with OSDs on LVs or PVs.

The symptoms are that the OSDs fail to be created, as seen in the OSD prepare log:
```
[2023-10-31 17:29:08,090][ceph_volume.devices.raw.list][DEBUG ] inspecting devices: ['/mnt/set1-data-0bv5xb']
[2023-10-31 17:29:08,090][ceph_volume][ERROR ] exception caught by decorator
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 153, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 166, in main
    self.list(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 122, in list
    report = self.generate(args.device)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 91, in generate
    info_device = [info for info in info_devices if info['NAME'] == dev][0]
IndexError: list index out of range
2023-10-31 17:29:08.150895 C | rookcmd: failed to configure devices: failed to get device already provisioned by ceph-volume raw: failed to retrieve ceph-volume raw list results: failed ceph-volume call (see ceph-volume log above for more details): exit status 1
```

Or when an existing LV-based OSD starts, this issue was observed in the `activate` init container where the disk is not found:
```
activate + OSD_ID=0
stream logs failed container "expand-bluefs" in pod "rook-ceph-osd-0-d7bdb7874-snkx6" is waiting to start: PodInitializing for rook-ceph/rook-ceph-osd-0-d7bdb7874-snkx6 (expand-bluefs)
stream logs failed container "chown-container-data-dir" in pod "rook-ceph-osd-0-d7bdb7874-snkx6" is waiting to start: PodInitializing for rook-ceph/rook-ceph-osd-0-d7bdb7874-snkx6 (chown-container-data-dir)
stream logs failed container "osd" in pod "rook-ceph-osd-0-d7bdb7874-snkx6" is waiting to start: PodInitializing for rook-ceph/rook-ceph-osd-0-d7bdb7874-snkx6 (osd)
activate + CEPH_FSID=dda6c867-4047-4fb9-a744-1575da352c5d
activate + OSD_UUID=447c4553-d301-457a-b48d-69c1a6afe74a
activate + OSD_STORE_FLAG=--bluestore
activate + OSD_DATA_DIR=/var/lib/ceph/osd/ceph-0
activate + CV_MODE=raw
activate + DEVICE=/dev/mapper/vg_rook-lv_rook3
activate + cp --no-preserve=mode /etc/temp-ceph/ceph.conf /etc/ceph/ceph.conf
activate + python3 -c '
activate import configparser
activate 
activate config = configparser.ConfigParser()
activate config.read('\''/etc/ceph/ceph.conf'\'')
stream logs failed container "log-collector" in pod "rook-ceph-osd-0-d7bdb7874-snkx6" is waiting to start: PodInitializing for rook-ceph/rook-ceph-osd-0-d7bdb7874-snkx6 (log-collector)
activate 
activate if not config.has_section('\''global'\''):
activate     config['\''global'\''] = {}
activate 
activate if not config.has_option('\''global'\'','\''fsid'\''):
activate     config['\''global'\'']['\''fsid'\''] = '\''dda6c867-4047-4fb9-a744-1575da352c5d'\''
activate 
activate with open('\''/etc/ceph/ceph.conf'\'', '\''w'\'') as configfile:
activate     config.write(configfile)
activate '
activate + ceph -n client.admin auth get-or-create osd.0 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring
activate [osd.0]
activate     key = AQBCJEJlDLPvGxAAfuSxVKFq6S/sR/EzuGvbcg==
activate + [[ raw == \l\v\m ]]
activate ++ mktemp
activate + OSD_LIST=/tmp/tmp.RnodTkKWVr
activate + ceph-volume raw list /dev/mapper/vg_rook-lv_rook3
activate + cat /tmp/tmp.RnodTkKWVr
activate {}
activate + find_device
activate + python3 -c '
activate import sys, json
activate for _, info in json.load(sys.stdin).items():
activate     if info['\''osd_id'\''] == 0:
activate         print(info['\''device'\''], end='\'''\'')
activate         print('\''found device: '\'' + info['\''device'\''], file=sys.stderr) # log the disk we found to stderr
activate         sys.exit(0)  # don'\''t keep processing once the disk is found
activate sys.exit('\''no disk found with OSD ID 0'\'')
activate '
activate no disk found with OSD ID 0
activate + ceph-volume raw list
activate + cat /tmp/tmp.RnodTkKWVr
activate {}
activate ++ find_device
activate ++ python3 -c '
activate import sys, json
activate for _, info in json.load(sys.stdin).items():
activate     if info['\''osd_id'\''] == 0:
activate         print(info['\''device'\''], end='\'''\'')
activate         print('\''found device: '\'' + info['\''device'\''], file=sys.stderr) # log the disk we found to stderr
activate         sys.exit(0)  # don'\''t keep processing once the disk is found
activate sys.exit('\''no disk found with OSD ID 0'\'')
activate '
activate no disk found with OSD ID 0
activate + DEVICE=
Stream closed EOF for rook-ceph/rook-ceph-osd-0-d7bdb7874-snkx6 (activate)
stream logs failed container "osd" in pod "rook-ceph-osd-0-d7bdb7874-snkx6" is waiting to start: PodInitializing for rook-ceph/rook-ceph-osd-0-d7bdb7874-snkx6 (osd)
```

**Comment by travisn** [comment]
Ceph tracker created: https://tracker.ceph.com/issues/63391
@guits Could you take a look?

**Comment by travisn** [comment]
This looks related to https://github.com/ceph/ceph/pull/52429. Looking if there is a fix or workaround needed on the Rook side of this change...

**Comment by satoru-takeuchi** [comment]
If ceph/ceph#52429 is the root cause, we will also hit this problem in the upcoming v18.2.1. The rook's nightly build is with ceph/ceph:v18 (v18.2.0) but ceph/ceph$52429 is between v18.2.0 and main. 

> Looking if there is a fix or workaround needed on the Rook side of this change...

Do you already have a workaround plan? Or is this problem under investigation?

**Comment by travisn** [comment]
Agreed, this is also a blocker for v18.2.1. I was just chatting with @guits, he is looking into it, we should have a better understanding of the fix by tomorrow. Thus far there is not a workaround other than rolling back to v17.2.6.

**Comment by mdbooth** [comment]
As discussed in the PR, I don't think https://github.com/ceph/ceph/pull/54392 fixes the reported crash. I've submitted https://github.com/ceph/ceph/pull/54400, which I believe should fix it.

**Comment by mdbooth** [comment]
Incidentally, I notice this was reported against a test cluster, but I hit this on real hardware: https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/thread/74KIM6WHKT7UMCGEL27JQJSWMAGQW7U6/

**Comment by travisn** [comment]
Independent of the crash, the revert in https://github.com/ceph/ceph/pull/54392 is still needed to revert the change for LVs, otherwise Rook won't find the expected devices for the OSDs. This results in the device to be found again, which would then not cause the crash.

**Comment by mdbooth** [comment]
Ok. I think you'll need my patch first, though, because the code removed in https://github.com/ceph/ceph/pull/54392 can't be reached without my patch.

**Comment by mdbooth** [comment]
@travisn I've put my understanding of this issue in https://github.com/ceph/ceph/pull/54392#issuecomment-1802160948 btw. If you wanted to move forward with a fix in rook we could ignore an error return from the first invocation of `ceph-volume raw list` and continue to the full scan of all devices. In fact, this is probably more robust even if `ceph-volume` is fixed.

**Comment by mdbooth** [comment]
@travisn I've just noticed that the 2 sets of log output in your original report aren't the same issue. I think @guits is focussing on the second issue, hence the confusion. I believe https://github.com/ceph/ceph/pull/54400 is required to fix the first, which is also the crash I experienced.

**Comment by travisn** [comment]
It's the same fundamental issue that affects c-v both during OSD creation in the osd prepare job, and the OSD activate in existing OSDs, so we are looking forward to the fix in https://tracker.ceph.com/issues/63391.

**Comment by guits** [comment]
@travisn FYI, @rkachach is reporting issues he's currently facing with latest-reef images that I'm not able to reproduce for now, still under investigations... I'll update  this thread ASAP.

**Comment by guits** [comment]
@travisn FYI https://github.com/ceph/ceph/pull/54514

**Comment by guits** [comment]
@travisn any chance rook CI could test against `latest-<ceph-release>-devel` instead of just stable/released ceph tags?
If we could test with this tag we wouldn't have to wait a regression is introduced and released in ceph to catch it in rook CI.

**Comment by travisn** [comment]
> @travisn any chance rook CI could test against `latest-<ceph-release>-devel` instead of just stable/released ceph tags? If we could test with this tag we wouldn't have to wait a regression is introduced and released in ceph to catch it in rook CI.

@rkachach is opening an issue for the CI improvements to run our canary tests in the daily CI against those tags. We have other test suites that run against those tags, just not those canary tests with more combinations of OSDs.

**Comment by rkachach** [comment]
@travisn @guits I opened the issue https://github.com/rook/rook/issues/13226 to track this CI issue.

**Comment by travisn** [comment]
Still an issue, waiting for the fix to be released in v17.2.8. Note that this issue does not affect v18.

**Comment by jainasanthosh2023** [comment]
We recently upgraded to quincy 17.2.7 and when we try to rebuild/readding couple of bad osds after tearing up pv,pvc, zap device on host, and facing same issue as @travisn mentioned.
"failed to get device already provisioned by ceph-volume raw: failed to retrieve ceph-volume raw list results: failed ceph-volume call (see ceph-volume log above for more details" , my production cluster is in very bad state now, Do we have any workaround for this issue. Kindly help us.

**Comment by BlaineEXE** [comment]
Removing keepalive as Rook has deprecated v17 for the upcoming 1.16 release. 17.2.8 was already released, so anyone responding to stalebot nags should alert us if 17.2.8 is still bugged
