### ISSUE TITLE
Removing object store causing operator to crash

### ISSUE THREAD

**Issue by jpds** [rook/rook#1339]
Is this a bug report or feature request?
* Bug Report

**Bug Report**

What happened: My object store creation failed so I tried to remove it with:

`kubectl delete -f rook-object.yaml`

I noticed that the operator then went and did:

```
E1221 12:47:30.543107       7 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: no kind "Objectstore" is registered for version "rook.io/v1alpha1"
E1221 12:47:30.557792       7 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: no kind "Objectstore" is registered for version "rook.io/v1alpha1"
E1221 12:47:31.560564       7 runtime.go:66] Observed a panic: &runtime.TypeAssertionError{interfaceString:"interface {}", concreteString:"cache.DeletedFinalStateUnknown", assertedString:"*rgw.ObjectStore", missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *rgw.ObjectStore)
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:509
/usr/local/go/src/runtime/panic.go:491
/usr/local/go/src/runtime/iface.go:172
/home/rook/go/src/github.com/rook/rook/pkg/operator/rgw/controller.go:103
/home/rook/go/src/github.com/rook/rook/pkg/operator/rgw/controller.go:61
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:206
<autogenerated>:1
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:317
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:147
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:121
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:121
/usr/local/go/src/runtime/asm_amd64.s:2337
E1221 12:47:31.560763       7 runtime.go:66] Observed a panic: &runtime.TypeAssertionError{interfaceString:"interface {}", concreteString:"cache.DeletedFinalStateUnknown", assertedString:"*rgw.ObjectStore", missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *rgw.ObjectStore)
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:509
/usr/local/go/src/runtime/panic.go:491
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58
/usr/local/go/src/runtime/asm_amd64.s:509
/usr/local/go/src/runtime/panic.go:491
/usr/local/go/src/runtime/iface.go:172
/home/rook/go/src/github.com/rook/rook/pkg/operator/rgw/controller.go:103
/home/rook/go/src/github.com/rook/rook/pkg/operator/rgw/controller.go:61
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:206
<autogenerated>:1
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:317
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:147
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:121
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:121
/usr/local/go/src/runtime/asm_amd64.s:2337
panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *rgw.ObjectStore [recovered]
	panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *rgw.ObjectStore [recovered]
	panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *rgw.ObjectStore

goroutine 111 [running]:
github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111
panic(0x13c60a0, 0xc420ad4b00)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111
panic(0x13c60a0, 0xc420ad4b00)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/rook/rook/pkg/operator/rgw.(*ObjectStoreController).onDelete(0xc420375920, 0x140ade0, 0xc4202ddb20)
	/home/rook/go/src/github.com/rook/rook/pkg/operator/rgw/controller.go:103 +0x14b
github.com/rook/rook/pkg/operator/rgw.(*ObjectStoreController).(github.com/rook/rook/pkg/operator/rgw.onDelete)-fm(0x140ade0, 0xc4202ddb20)
	/home/rook/go/src/github.com/rook/rook/pkg/operator/rgw/controller.go:61 +0x3e
github.com/rook/rook/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(0xc420440d70, 0xc420440d80, 0xc420440d90, 0x140ade0, 0xc4202ddb20)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:206 +0x49
github.com/rook/rook/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnDelete(0xc42025a060, 0x140ade0, 0xc4202ddb20)
	<autogenerated>:1 +0x62
github.com/rook/rook/vendor/k8s.io/client-go/tools/cache.NewInformer.func1(0x13d5fc0, 0xc42031fde0, 0x13d5fc0, 0xc42031fde0)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:317 +0x38c
github.com/rook/rook/vendor/k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc4205760c0, 0xc4202aa2d0, 0x0, 0x0, 0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451 +0x268
github.com/rook/rook/vendor/k8s.io/client-go/tools/cache.(*controller).processLoop(0xc4202e6000)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:147 +0x40
github.com/rook/rook/vendor/k8s.io/client-go/tools/cache.(*controller).(github.com/rook/rook/vendor/k8s.io/client-go/tools/cache.processLoop)-fm()
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:121 +0x2a
github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420600fb0)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0x5e
github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420a87fb0, 0x3b9aca00, 0x0, 0x1344b01, 0x0)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98 +0xbd
github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420600fb0, 0x3b9aca00, 0x0)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
github.com/rook/rook/vendor/k8s.io/client-go/tools/cache.(*controller).Run(0xc4202e6000, 0x0)
	/home/rook/go/src/github.com/rook/rook/vendor/k8s.io/client-go/tools/cache/controller.go:121 +0x22e
created by github.com/rook/rook/vendor/github.com/rook/operator-kit.(*ResourceWatcher).Watch
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/rook/operator-kit/watcher.go:86 +0x2bd
```

**Environment**:
* OS (e.g. from /etc/os-release): Debian 9
* Kernel (e.g. `uname -a`): 4.13
* Cloud provider or hardware configuration: Bare metal
* Rook version (use `rook version` inside of a Rook Pod): v0.5.0-288.g0ceddcf
* Kubernetes version (use `kubectl version`): 1.8.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): kubespray
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)): HEALTH_OK

**Comment by kokhang** [comment]
@jpds the issue with `Objectstore` vs `ObjectStore` is that the former was created using TPR and the latter, it is expecting to find a CRD.

Did you deploy rook and the object store on a k8s 1.6 and then upgraded k8s?
We have a doc on this. https://github.com/rook/rook/blob/master/Documentation/upgrade.md#upgrading-kubernetes

I am hoping that once we have automatic upgrade done, we can solve this issue without manual intervention.

**Comment by jpds** [comment]
I did upgrade this cluster from a 1.7 version (can't remember which to 1.8).

I'm not seeing this issue with my new 1.8 based cluster, so I'm going to close this.
