### ISSUE TITLE
pvc based cluster prepare osd error

### ISSUE THREAD

**Issue by 13567436138** [rook/rook#13724]
**Is this a bug report or feature request?**
* Bug Report
```
 -1  ** ERROR: error creating empty object store in /var/lib/ceph/osd/ceph-1/: (16) Device or resource busy
[2024-02-08 04:22:15,290][ceph_volume.devices.raw.prepare][ERROR ] raw prepare was unable to complete
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 80, in safe_prepare
    self.prepare()
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 125, in prepare
    tmpfs,
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 57, in prepare_bluestore
    db=db
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/prepare.py", line 459, in osd_mkfs_bluestore
    raise RuntimeError('Command failed with exit code %s: %s' % (returncode, ' '.join(command)))
RuntimeError: Command failed with exit code 250: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid 4c1145fd-f6b2-4c0a-af84-89c9fd3a0186 --setuser ceph --setgroup ceph
[2024-02-08 04:22:15,291][ceph_volume.devices.raw.prepare][INFO  ] will rollback OSD ID creation
[2024-02-08 04:22:15,291][ceph_volume.process][INFO  ] Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.1 --yes-i-really-mean-it
[2024-02-08 04:22:15,915][ceph_volume.process][INFO  ] stderr purged osd.1
[2024-02-08 04:22:15,942][ceph_volume.process][INFO  ] Running command: /usr/bin/systemctl is-active ceph-osd@1
[2024-02-08 04:22:15,965][ceph_volume.process][INFO  ] stderr System has not been booted with systemd as init system (PID 1). Can't operate.
[2024-02-08 04:22:15,965][ceph_volume.process][INFO  ] stderr Failed to connect to bus: Host is down
[2024-02-08 04:22:15,988][ceph_volume.util.system][WARNING] Executable lvs not found on the host, will return lvs as-is
[2024-02-08 04:22:15,988][ceph_volume.process][INFO  ] Running command: lvs --noheadings --readonly --separator=";" -a --units=b --nosuffix -S tags={ceph.osd_id=1} -o lv_tags,lv_path,lv_name,vg_name,lv_uuid,lv_size
[2024-02-08 04:22:16,077][ceph_volume][ERROR ] exception caught by decorator
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 80, in safe_prepare
    self.prepare()
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 125, in prepare
    tmpfs,
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 57, in prepare_bluestore
    db=db
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/prepare.py", line 459, in osd_mkfs_bluestore
    raise RuntimeError('Command failed with exit code %s: %s' % (returncode, ' '.join(command)))
RuntimeError: Command failed with exit code 250: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid 4c1145fd-f6b2-4c0a-af84-89c9fd3a0186 --setuser ceph --setgroup ceph

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 153, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 160, in main
    self.safe_prepare(self.args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 84, in safe_prepare
    rollback_osd(self.args, self.osd_id)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/common.py", line 35, in rollback_osd
    Zap(['--destroy', '--osd-id', osd_id]).main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/zap.py", line 403, in main
    self.zap_osd()
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/zap.py", line 301, in zap_osd
    devices = find_associated_devices(self.args.osd_id, self.args.osd_fsid)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/zap.py", line 88, in find_associated_devices
    '%s' % osd_id or osd_fsid)
RuntimeError: Unable to find any LV for zapping OSD: 1
```
**Deviation from expected behavior:**
ceph cluster
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  finalizers:
  - cephcluster.ceph.rook.io
  name: rook-ceph
  namespace: rook-ceph
spec:
  annotations:
    mon:
      backup.velero.io/backup-volumes: ceph-daemon-data
    osd:
      backup.velero.io/backup-volumes: data
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.1
  cleanupPolicy:
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  crashCollector: {}
  csi:
    cephfs: {}
    readAffinity:
      enabled: false
  dashboard:
    enabled: true
    ssl: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
  external: {}
  healthCheck:
    daemonHealth:
      mon:
        interval: 45s
      osd:
        interval: 1m0s
      status:
        interval: 1m0s
    livenessProbe:
      mgr: {}
      mon: {}
      osd: {}
    startupProbe:
      mgr: {}
      mon: {}
      osd: {}
  logCollector:
    enabled: true
    maxLogSize: 500M
    periodicity: daily
  mgr:
    count: 2
    modules:
    - enabled: true
      name: pg_autoscaler
  mon:
    count: 3
    volumeClaimTemplate:
      metadata:
        name: mon
      spec:
        storageClassName: local-storage
        resources:
          requests:
            storage: 10Gi
  monitoring: {}
  network:
    connections:
      compression: {}
      encryption: {}
    hostNetwork: true
    multiClusterService: {}
  priorityClassNames:
    mgr: system-cluster-critical
    mon: system-node-critical
    osd: system-node-critical
  security:
    keyRotation:
      enabled: false
    kms: {}
  storage:
    flappingRestartIntervalHours: 0
    store: {}
    useAllDevices: false
    useAllNodes: false
    storageClassDeviceSets:
    - name: set1
      count: 8
      portable: false
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 20Gi
          storageClassName: local-storage
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
  waitTimeoutForHealthyOSDInMinutes: 10
```

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):1.13.1
* Storage backend version (e.g. for ceph do `ceph -v`):18.2.1
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by 13567436138** [comment]
```
root@storage-01:~# kubectl get pvc -n rook-ceph 
NAME               STATUS   VOLUME               CAPACITY   ACCESS MODES   STORAGECLASS    AGE
rook-ceph-mon-a    Bound    worker-02-hostpath   10Gi       RWO            local-storage   6m57s
rook-ceph-mon-b    Bound    worker-01-hostpath   10Gi       RWO            local-storage   6m56s
rook-ceph-mon-c    Bound    worker-03-hostpath   10Gi       RWO            local-storage   6m56s
set1-data-02jrzn   Bound    master-01-sdb        20Gi       RWO            local-storage   4m54s
set1-data-1f2vf4   Bound    worker-02-sdb        20Gi       RWO            local-storage   4m54s
set1-data-2lqs8c   Bound    master-01-sdc        20Gi       RWO            local-storage   4m54s
set1-data-36hrk5   Bound    worker-01-sdb        20Gi       RWO            local-storage   4m54s
set1-data-4mp9v5   Bound    master-01-sdd        100Gi      RWO            local-storage   4m53s
set1-data-5xgccr   Bound    worker-02-sdc        20Gi       RWO            local-storage   4m53s
set1-data-6qqfxh   Bound    worker-01-sdc        20Gi       RWO            local-storage   4m53s
set1-data-7q9mwt   Bound    worker-02-sdd        100Gi      RWO            local-storage   4m53s
```

**Comment by 13567436138** [comment]
because I installed directpv before,so I restart the host.and the error is going ,but no osd is started
```
Defaulted container "provision" out of: provision, copy-bins (init), blkdevmapper (init)
2024-02-08 05:28:58.715278 I | cephcmd: desired devices to configure osds: [{Name:/mnt/set1-data-5xgccr OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: InitialWeight: IsFilter:false IsDevicePathFilter:false}]
2024-02-08 05:28:58.717032 I | rookcmd: starting Rook v1.13.1 with arguments '/rook/rook ceph osd provision'
2024-02-08 05:28:58.717180 I | rookcmd: flag values: --cluster-id=8b639768-6d7e-4311-b48c-4146ba1db273, --cluster-name=rook-ceph, --data-device-filter=, --data-device-path-filter=, --data-devices=[{"id":"/mnt/set1-data-5xgccr","storeConfig":{"osdsPerDevice":1}}], --encrypted-device=false, --force-format=false, --help=false, --location=, --log-level=DEBUG, --metadata-device=, --node-name=set1-data-5xgccr, --osd-crush-device-class=, --osd-crush-initial-weight=, --osd-database-size=0, --osd-store-type=bluestore, --osd-wal-size=576, --osds-per-device=1, --pvc-backed-osd=true, --replace-osd=-1
2024-02-08 05:28:58.717241 I | ceph-spec: parsing mon endpoints: a=192.168.229.197:6789,b=192.168.229.196:6789,c=192.168.229.198:6789
2024-02-08 05:28:58.741029 I | op-osd: CRUSH location=root=default host=worker-02
2024-02-08 05:28:58.747402 I | cephcmd: crush location of osd: root=default host=worker-02
2024-02-08 05:28:58.747585 D | exec: Running command: dmsetup version
2024-02-08 05:28:58.760096 I | cephosd: Library version:   1.02.181-RHEL8 (2021-10-20)
Driver version:    4.48.0
2024-02-08 05:28:58.799869 D | cephclient: No ceph configuration override to merge as "rook-config-override" configmap is empty
2024-02-08 05:28:58.799896 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2024-02-08 05:28:58.800439 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2024-02-08 05:28:58.800538 D | cephclient: config file @ /etc/ceph/ceph.conf:
[global]
fsid                = 98163356-1cdb-47f2-b913-782a8e9cadc3
mon initial members = a b c
mon host            = [v2:192.168.229.197:3300,v1:192.168.229.197:6789],[v2:192.168.229.196:3300,v1:192.168.229.196:6789],[v2:192.168.229.198:3300,v1:192.168.229.198:6789]

[client.admin]
keyring = /var/lib/rook/rook-ceph/client.admin.keyring
2024-02-08 05:28:58.800543 I | cephosd: discovering hardware
2024-02-08 05:28:58.800560 D | exec: Running command: lsblk /mnt/set1-data-5xgccr --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME,MOUNTPOINT,FSTYPE
2024-02-08 05:28:58.807004 D | sys: lsblk output: "SIZE=\"21474836480\" ROTA=\"1\" RO=\"0\" TYPE=\"disk\" PKNAME=\"\" NAME=\"/dev/sdc\" KNAME=\"/dev/sdc\" MOUNTPOINT=\"\" FSTYPE=\"xfs\""
2024-02-08 05:28:58.807272 D | exec: Running command: sgdisk --print /mnt/set1-data-5xgccr
2024-02-08 05:28:58.810798 D | exec: Running command: udevadm info --query=property /dev/sdc
2024-02-08 05:28:58.864018 D | sys: udevadm info output: "DEVLINKS=/dev/disk/by-label/DIRECTPV /dev/disk/by-path/pci-0000:00:10.0-scsi-0:0:2:0 /dev/disk/by-uuid/50872083-5bb8-4dfb-9b73-71f8ae3999ed\nDEVNAME=/dev/sdc\nDEVPATH=/devices/pci0000:00/0000:00:10.0/host9/target9:0:2/9:0:2:0/block/sdc\nDEVTYPE=disk\nDISKSEQ=20\nID_BUS=scsi\nID_FS_LABEL=DIRECTPV\nID_FS_LABEL_ENC=DIRECTPV\nID_FS_TYPE=xfs\nID_FS_USAGE=filesystem\nID_FS_UUID=50872083-5bb8-4dfb-9b73-71f8ae3999ed\nID_FS_UUID_ENC=50872083-5bb8-4dfb-9b73-71f8ae3999ed\nID_MODEL=VMware_Virtual_S\nID_MODEL_ENC=VMware\\x20Virtual\\x20S\nID_PATH=pci-0000:00:10.0-scsi-0:0:2:0\nID_PATH_TAG=pci-0000_00_10_0-scsi-0_0_2_0\nID_REVISION=1.0\nID_SCSI=1\nID_TYPE=disk\nID_VENDOR=VMware_\nID_VENDOR_ENC=VMware\\x2c\\x20\nMAJOR=8\nMINOR=32\nSUBSYSTEM=block\nTAGS=:systemd:\nUSEC_INITIALIZED=6680496"
2024-02-08 05:28:58.864050 I | cephosd: creating and starting the osds
2024-02-08 05:28:58.864070 D | cephosd: desiredDevices are [{Name:/mnt/set1-data-5xgccr OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: InitialWeight: IsFilter:false IsDevicePathFilter:false}]
2024-02-08 05:28:58.864073 D | cephosd: context.Devices are:
2024-02-08 05:28:58.864087 D | cephosd: &{Name:/mnt/set1-data-5xgccr Parent: HasChildren:false DevLinks:/dev/disk/by-label/DIRECTPV /dev/disk/by-path/pci-0000:00:10.0-scsi-0:0:2:0 /dev/disk/by-uuid/50872083-5bb8-4dfb-9b73-71f8ae3999ed Size:21474836480 UUID:5767ec3a-6f3b-468a-8ed3-407f9c0ba046 Serial: Type:data Rotational:true Readonly:false Partitions:[] Filesystem:xfs Mountpoint: Vendor:VMware_ Model:VMware_Virtual_S WWN: WWNVendorExtension: Empty:false CephVolumeData: RealPath:/dev/sdc KernelName:sdc Encrypted:false}
2024-02-08 05:28:58.864103 I | cephosd: skipping device "/mnt/set1-data-5xgccr" because it contains a filesystem "xfs"
2024-02-08 05:28:58.981325 I | cephosd: configuring osd devices: {"Entries":{}}
2024-02-08 05:28:58.981350 I | cephosd: no new devices to configure. returning devices already configured with ceph-volume.
2024-02-08 05:28:58.981357 D | exec: Running command: pvdisplay -C -o lvpath --noheadings /mnt/set1-data-5xgccr
2024-02-08 05:28:59.028741 W | cephosd: failed to retrieve logical volume path for "/mnt/set1-data-5xgccr". exit status 5
2024-02-08 05:28:59.028919 D | exec: Running command: lsblk /mnt/set1-data-5xgccr --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME,MOUNTPOINT,FSTYPE
2024-02-08 05:28:59.033056 D | sys: lsblk output: "SIZE=\"21474836480\" ROTA=\"1\" RO=\"0\" TYPE=\"disk\" PKNAME=\"\" NAME=\"/dev/sdc\" KNAME=\"/dev/sdc\" MOUNTPOINT=\"\" FSTYPE=\"xfs\""
2024-02-08 05:28:59.040535 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm list  --format json
2024-02-08 05:29:01.250404 D | cephosd: {}
2024-02-08 05:29:01.250581 I | cephosd: 0 ceph-volume lvm osd devices configured on this node
2024-02-08 05:29:01.250640 D | exec: Running command: cryptsetup luksDump /mnt/set1-data-5xgccr
2024-02-08 05:29:01.264429 E | cephosd: failed to determine if the encrypted block "/mnt/set1-data-5xgccr" is from our cluster. failed to dump LUKS header for disk "/mnt/set1-data-5xgccr". Device /mnt/set1-data-5xgccr is not a valid LUKS device.: exit status 1
2024-02-08 05:29:01.264611 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log raw list /mnt/set1-data-5xgccr --format json
2024-02-08 05:29:02.227580 D | cephosd: {}
2024-02-08 05:29:02.227777 I | cephosd: 0 ceph-volume raw osd devices configured on this node
2024-02-08 05:29:02.227873 W | cephosd: skipping OSD configuration as no devices matched the storage settings for this node "set1-data-5xgccr"
```

**Comment by 13567436138** [comment]
is this the reason?
2024-02-08 05:33:31.759128 I | cephosd: skipping device "/mnt/set1-data-2lqs8c" because it contains a filesystem "xfs"
