### ISSUE TITLE
ceph is not healthy,osd not ready,based on openebs cstor

### ISSUE THREAD

**Issue by 13567436138** [rook/rook#13746]
**Is this a bug report or feature request?**
* Bug Report
```
2024-02-11 07:30:32.802750 E | op-config: failed to run command ceph [config assimilate-conf -i /var/lib/rook/488937334 -o /var/lib/rook/488937334.out]
2024-02-11 07:30:32.803066 E | op-config: failed to apply ceph settings:
2024-02-11 07:30:33.327603 E | ceph-cluster-controller: failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph monitors: failed to set Rook and/or user-defined Ceph config options after forcefully updating the existing mons: failed to apply default Ceph configurations: failed to set all keys: failed to set ceph config in the centralized mon configuration database; output: Interrupted
Traceback (most recent call last):
  File "/usr/bin/ceph", line 1327, in <module>
    retval = main()
  File "/usr/bin/ceph", line 1273, in main
    outf.write(outbuf)
TypeError: a bytes-like object is required, not 'str': exit status 1
2024-02-11 07:30:33.339149 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2024-02-11 07:30:33.594365 I | ceph-spec: parsing mon endpoints: a=192.168.229.137:6789,b=192.168.229.136:6789,c=192.168.229.135:6789
2024-02-11 07:30:34.193364 I | ceph-spec: detecting the ceph image version for image quay.io/ceph/ceph:v18.2.1...
2024-02-11 07:30:42.200376 E | ceph-cluster-controller: failed to get ceph daemons versions. failed to run 'ceph versions'. . timed out: exit status 1
2024-02-11 07:30:42.261345 E | ceph-spec: failed to update cluster condition to {Type:Ready Status:True Reason:ClusterCreated Message:Cluster created successfully LastHeartbeatTime:2024-02-11 07:30:42.200548324 +0000 UTC m=+990.370182389 LastTransitionTime:2024-02-11 07:25:55 +0000 UTC}. failed to update object "rook-ceph/rook-ceph" status: Operation cannot be fulfilled on cephclusters.ceph.rook.io "rook-ceph": the object has been modified; please apply your changes to the latest version and try again
2024-02-11 07:30:49.835483 W | op-mon: failed to check mon health. failed to get mon quorum status: mon quorum status failed: exit status 1
2024-02-11 07:30:53.575560 I | ceph-spec: detected ceph image version: "18.2.1-0 reef"
2024-02-11 07:30:53.575925 I | ceph-cluster-controller: validating ceph version from provided image
2024-02-11 07:30:53.673513 I | ceph-spec: parsing mon endpoints: a=192.168.229.137:6789,b=192.168.229.136:6789,c=192.168.229.135:6789
2024-02-11 07:30:53.769586 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2024-02-11 07:30:53.770101 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2024-02-11 07:31:02.796576 I | ceph-cluster-controller: cluster "rook-ceph": version "18.2.1-0 reef" detected for image "quay.io/ceph/ceph:v18.2.1"
2024-02-11 07:31:02.947258 I | op-mon: start running mons
2024-02-11 07:31:02.957404 I | ceph-spec: parsing mon endpoints: a=192.168.229.137:6789,b=192.168.229.136:6789,c=192.168.229.135:6789
2024-02-11 07:31:02.999791 I | op-mon: saved mon endpoints to config map map[csi-cluster-config-json:[{"clusterID":"rook-ceph","monitors":["192.168.229.137:6789","192.168.229.136:6789","192.168.229.135:6789"],"namespace":""}] data:a=192.168.229.137:6789,b=192.168.229.136:6789,c=192.168.229.135:6789 mapping:{"node":{"a":{"Name":"worker-02","Hostname":"worker-02","Address":"192.168.229.137"},"b":{"Name":"worker-01","Hostname":"worker-01","Address":"192.168.229.136"},"c":{"Name":"master-01","Hostname":"master-01","Address":"192.168.229.135"}}} maxMonId:2 outOfQuorum:]
2024-02-11 07:31:03.100860 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2024-02-11 07:31:03.101337 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2024-02-11 07:31:04.706300 I | op-mon: targeting the mon count 3
2024-02-11 07:31:04.729270 I | op-config: applying ceph settings:
[global]
mon allow pool delete   = true
mon cluster log file    = 
mon allow pool size one = true
2024-02-11 07:31:19.732453 I | exec: exec timeout waiting for process ceph to return. Sending interrupt signal to the process
2024-02-11 07:31:19.734617 E | op-config: failed to open assimilate output file /var/lib/rook/2815239879.out. open /var/lib/rook/2815239879.out: no such file or directory
2024-02-11 07:31:19.735029 E | op-config: failed to run command ceph [config assimilate-conf -i /var/lib/rook/2815239879 -o /var/lib/rook/2815239879.out]
2024-02-11 07:31:19.735072 E | op-config: failed to apply ceph settings:
2024-02-11 07:31:19.735162 E | op-config: failed to remove file "/var/lib/rook/2815239879.out". remove /var/lib/rook/2815239879.out: no such file or directory
2024-02-11 07:31:19.735217 W | op-mon: failed to set Rook and/or user-defined Ceph config options before starting mons; will retry after starting mons. failed to apply default Ceph configurations: failed to set all keys: failed to set ceph config in the centralized mon configuration database; output: Cluster connection aborted: exit status 1
2024-02-11 07:31:19.735249 I | op-mon: checking for basic quorum with existing mons
2024-02-11 07:31:19.735283 I | op-mon: setting mon "a" endpoints for hostnetwork mode
2024-02-11 07:31:19.735318 I | op-mon: setting mon "b" endpoints for hostnetwork mode
2024-02-11 07:31:19.735369 I | op-mon: setting mon "c" endpoints for hostnetwork mode
2024-02-11 07:31:19.829563 I | op-mon: saved mon endpoints to config map map[csi-cluster-config-json:[{"clusterID":"rook-ceph","monitors":["192.168.229.137:6789","192.168.229.136:6789","192.168.229.135:6789"],"namespace":""}] data:a=192.168.229.137:6789,b=192.168.229.136:6789,c=192.168.229.135:6789 mapping:{"node":{"a":{"Name":"worker-02","Hostname":"worker-02","Address":"192.168.229.137"},"b":{"Name":"worker-01","Hostname":"worker-01","Address":"192.168.229.136"},"c":{"Name":"master-01","Hostname":"master-01","Address":"192.168.229.135"}}} maxMonId:2 outOfQuorum:]
2024-02-11 07:31:19.978589 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2024-02-11 07:31:19.979265 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2024-02-11 07:31:20.298805 I | op-mon: deployment for mon rook-ceph-mon-a already exists. updating if needed
2024-02-11 07:31:20.314667 I | op-k8sutil: deployment "rook-ceph-mon-a" did not change, nothing to update
2024-02-11 07:31:20.314863 I | op-mon: waiting for mon quorum with [a b c]
2024-02-11 07:31:20.393471 I | op-mon: mons running: [a b c]
2024-02-11 07:31:41.817514 I | op-mon: mons running: [a b c]
2024-02-11 07:32:02.193429 I | op-mon: Monitors in quorum: [b c]
2024-02-11 07:32:02.223622 I | op-mon: deployment for mon rook-ceph-mon-b already exists. updating if needed
2024-02-11 07:32:02.310688 I | op-k8sutil: deployment "rook-ceph-mon-b" did not change, nothing to update
2024-02-11 07:32:02.311102 I | op-mon: waiting for mon quorum with [a b c]
2024-02-11 07:32:02.501077 I | op-mon: mons running: [a b c]
2024-02-11 07:32:24.194719 I | op-mon: mons running: [a b c]
2024-02-11 07:32:46.060845 I | op-mon: mons running: [a b c]
2024-02-11 07:33:07.394775 I | op-mon: mons running: [a b c]
2024-02-11 07:33:24.929288 E | ceph-cluster-controller: failed to get ceph status. failed to get status. . timed out: exit status 1
2024-02-11 07:33:31.798030 I | op-mon: mons running: [a b c]
2024-02-11 07:33:41.201379 E | ceph-cluster-controller: failed to get ceph daemons versions. failed to run 'ceph versions'. . timed out: exit status 1
2024-02-11 07:33:53.419330 I | op-mon: mons running: [a b c]
2024-02-11 07:34:14.843659 I | op-mon: mons running: [a b c]
2024-02-11 07:34:36.253808 I | op-mon: mons running: [a b c]
2024-02-11 07:34:57.499891 E | ceph-cluster-controller: failed to get ceph status. failed to get status. . timed out: exit status 1
2024-02-11 07:34:57.794859 I | op-mon: mons running: [a b c]
2024-02-11 07:35:15.019317 E | ceph-cluster-controller: failed to get ceph daemons versions. failed to run 'ceph versions'. . timed out: exit status 1
2024-02-11 07:35:20.517731 I | op-mon: mons running: [a b c]
2024-02-11 07:35:41.892423 I | op-mon: mons running: [a b c]
2024-02-11 07:36:03.157557 I | op-mon: mons running: [a b c]
2024-02-11 07:36:24.386136 I | op-mon: mons running: [a b c]
2024-02-11 07:36:31.398227 E | ceph-cluster-controller: failed to get ceph status. failed to get status. . timed out: exit status 1
2024-02-11 07:36:45.792379 I | op-mon: mons running: [a b c]
2024-02-11 07:36:47.699662 E | ceph-cluster-controller: failed to get ceph daemons versions. failed to run 'ceph versions'. . timed out: exit status 1
2024-02-11 07:37:07.337171 I | op-mon: mons running: [a b c]


2024-02-11 07:37:29.057667 I | op-mon: mons running: [a b c]
2024-02-11 07:37:42.900151 I | op-mon: Monitors in quorum: [b c]
2024-02-11 07:37:42.952345 I | op-mon: deployment for mon rook-ceph-mon-c already exists. updating if needed
2024-02-11 07:37:42.997228 I | op-k8sutil: deployment "rook-ceph-mon-c" did not change, nothing to update
2024-02-11 07:37:42.998640 I | op-mon: waiting for mon quorum with [a b c]
2024-02-11 07:37:43.094439 I | op-mon: mons running: [a b c]
2024-02-11 07:37:47.794884 I | op-mon: Monitors in quorum: [b c]
2024-02-11 07:37:47.796096 I | op-mon: mons created: 3
2024-02-11 07:38:05.302771 W | op-mon: failed to get ceph daemons versions; this likely means there is no cluster yet. failed to run 'ceph versions'. . timed out: exit status 1
2024-02-11 07:38:05.304201 I | op-mon: waiting for mon quorum with [a b c]
2024-02-11 07:38:05.392332 I | op-mon: mons running: [a b c]
2024-02-11 07:38:05.400163 E | ceph-cluster-controller: failed to get ceph status. failed to get status. . timed out: exit status 1
```

```
root@storage-b-01:~# kubectl get po -n rook-ceph 
NAME                                                  READY   STATUS             RESTARTS        AGE
csi-cephfsplugin-f9hjj                                2/2     Running            0               23m
csi-cephfsplugin-provisioner-77dbd656b7-56v2t         5/5     Running            0               23m
csi-cephfsplugin-provisioner-77dbd656b7-q5ckl         5/5     Running            0               23m
csi-cephfsplugin-r5xcq                                2/2     Running            0               23m
csi-cephfsplugin-r672t                                2/2     Running            0               23m
csi-cephfsplugin-vdzlx                                2/2     Running            0               23m
csi-nfsplugin-2xbm5                                   2/2     Running            0               23m
csi-nfsplugin-78pd7                                   2/2     Running            0               23m
csi-nfsplugin-ghhpk                                   2/2     Running            0               23m
csi-nfsplugin-provisioner-7458879f8b-56764            5/5     Running            0               23m
csi-nfsplugin-provisioner-7458879f8b-7wmgp            5/5     Running            0               23m
csi-nfsplugin-tk76f                                   2/2     Running            0               23m
csi-rbdplugin-22b4j                                   2/2     Running            0               23m
csi-rbdplugin-4jt4t                                   2/2     Running            0               23m
csi-rbdplugin-lcdt8                                   2/2     Running            0               23m
csi-rbdplugin-provisioner-687fb65c78-52jch            5/5     Running            0               23m
csi-rbdplugin-provisioner-687fb65c78-xqwbc            5/5     Running            0               23m
csi-rbdplugin-xgbbr                                   2/2     Running            0               23m
rook-ceph-crashcollector-master-01-5f9cfdd58-gq6j2    1/1     Running            0               17m
rook-ceph-crashcollector-worker-01-7fcf8c9d8d-cghb9   1/1     Running            0               20m
rook-ceph-crashcollector-worker-02-5c77dcd757-q99zz   1/1     Running            0               20m
rook-ceph-exporter-master-01-57bbc69ff4-bcqxl         1/1     Running            1 (13m ago)     16m
rook-ceph-exporter-worker-01-8b5d54756-rmb46          1/1     Running            0               20m
rook-ceph-exporter-worker-02-746cb7fd8f-l8dmm         1/1     Running            0               20m
rook-ceph-mgr-a-6fbd4cdb97-npcg7                      2/3     CrashLoopBackOff   7 (9s ago)      20m
rook-ceph-mgr-b-54d549b69d-spkvp                      3/3     Running            0               20m
rook-ceph-mon-a-755977ffbf-bn852                      2/2     Running            7 (6m13s ago)   22m
rook-ceph-mon-b-686f757478-prf7k                      1/2     CrashLoopBackOff   6 (2m27s ago)   21m
rook-ceph-mon-c-869bf9bd4d-xq7s7                      1/2     CrashLoopBackOff   7 (70s ago)     21m
rook-ceph-operator-6446566d79-8npx2                   1/1     Running            1 (26m ago)     59m
rook-ceph-osd-0-647fbc9fb-mbs7s                       2/2     Running            2 (10m ago)     17m
rook-ceph-osd-1-5979cff9c6-6lj4q                      2/2     Running            0               16m
rook-ceph-osd-2-76b896c-b7z9f                         2/2     Running            0               16m
rook-ceph-osd-3-5d7f669478-cn84c                      2/2     Running            0               16m
rook-ceph-osd-4-6558c7cb4b-n8cbz                      1/2     Running            1 (10m ago)     15m
rook-ceph-osd-5-566c89b6dd-6fln4                      1/2     Running            0               14m
rook-ceph-osd-6-cd4979b6-x7dxv                        1/2     Running            0               14m
rook-ceph-osd-prepare-set1-data-09pk44-g7bgw          0/1     Completed          0               19m
rook-ceph-osd-prepare-set1-data-1xdvmk-xvxsh          0/1     Completed          0               19m
rook-ceph-osd-prepare-set1-data-2qcg9l-tzsmz          0/1     Completed          0               19m
rook-ceph-osd-prepare-set1-data-34fqb7-vpn4q          0/1     Completed          0               19m
rook-ceph-osd-prepare-set1-data-49kmll-tnc4s          0/1     Completed          0               19m
rook-ceph-osd-prepare-set1-data-5k8nvj-pkgbk          0/1     Completed          0               19m
rook-ceph-osd-prepare-set1-data-6fglgq-gf4g8          0/1     Completed          0               19m
rook-discover-7hgkd                                   1/1     Running            1 (27m ago)     59m
rook-discover-w2vkz                                   1/1     Running            1 (26m ago)     59m
rook-discover-wfzb8                                   1/1     Running            1 (26m ago)     59m
rook-discover-zt76l                                   1/1     Running            1 (26m ago)     5
```

```
root@storage-b-01:~# kubectl get pod -n openebs 
NAME                                                              READY   STATUS    RESTARTS       AGE
cspc-operator-847f9ccc74-l759p                                    1/1     Running   2 (27m ago)    98m
cstor-disk-pool-4k76-db667d89c-r78jq                              3/3     Running   3 (27m ago)    87m
cstor-disk-pool-5vzh-5c76894f85-nk7p9                             3/3     Running   3 (27m ago)    87m
cstor-disk-pool-hpx8-77cfddc87c-st77d                             3/3     Running   3 (27m ago)    87m
cstor-disk-pool-x6gc-6dff796c59-w2bjw                             3/3     Running   3 (27m ago)    87m
cvc-operator-599f4b6f94-lmsfj                                     1/1     Running   1 (27m ago)    33m
openebs-cstor-admission-server-78b478b5c8-l6nv7                   1/1     Running   2 (27m ago)    98m
openebs-cstor-csi-controller-0                                    6/6     Running   12 (27m ago)   98m
openebs-cstor-csi-node-2hz72                                      2/2     Running   4 (27m ago)    98m
openebs-cstor-csi-node-cvd4x                                      2/2     Running   4 (27m ago)    98m
openebs-cstor-csi-node-djzxk                                      2/2     Running   4 (27m ago)    98m
openebs-cstor-csi-node-dzzlp                                      2/2     Running   4 (27m ago)    98m
openebs-ndm-85v45                                                 1/1     Running   2 (27m ago)    98m
openebs-ndm-b6r5b                                                 1/1     Running   2 (27m ago)    98m
openebs-ndm-cluster-exporter-7b6745666-4djxq                      1/1     Running   2 (27m ago)    98m
openebs-ndm-h24mb                                                 1/1     Running   2 (27m ago)    98m
openebs-ndm-k9dpd                                                 1/1     Running   2 (27m ago)    98m
openebs-ndm-node-exporter-fpkcc                                   1/1     Running   2 (27m ago)    98m
openebs-ndm-node-exporter-lkjx4                                   1/1     Running   2 (27m ago)    98m
openebs-ndm-node-exporter-mqlfp                                   1/1     Running   2 (27m ago)    98m
openebs-ndm-node-exporter-vjpbn                                   1/1     Running   2 (27m ago)    98m
openebs-ndm-operator-64944997b6-tzmng                             1/1     Running   2 (27m ago)    98m
pvc-391b0fc1-c931-45e0-a944-6115aa028520-target-fd6f75ff4-hwbjf   3/3     Running   0              23m
pvc-7e20d37c-bd99-432f-b6f3-1631ab2a7741-target-85d8d94dfcgtgfh   3/3     Running   0              20m
pvc-885ff2fe-fbc5-4713-a95a-e929dbfbf861-target-bdc9f59f5-8p52s   3/3     Running   1 (20m ago)    20m
pvc-90ce1b09-a296-4de9-94c6-a4aecb86f772-target-589ffd7f97tpjdc   3/3     Running   0              23m
pvc-971a6a5f-b713-4d56-b915-e3cac761ee7e-target-cf687f8b-4tqlp    3/3     Running   1 (20m ago)    20m
pvc-a3172d9d-c163-435f-a3d4-6fd84afcdad6-target-fd4fddd54-wq6jq   3/3     Running   2 (19m ago)    20m
pvc-bd73ef0b-6b8f-4631-8b00-b87868d5b793-target-5f99c5b6742l2w2   3/3     Running   2 (19m ago)    20m
pvc-c460b1b2-f9cb-49cf-b174-69aed2947df5-target-7857c44f5-7tkqc   3/3     Running   0              23m
pvc-cd78257b-0da6-41a8-ad7d-5219ce4393f4-target-579964c84ds44qt   3/3     Running   2 (19m ago)    19m
pvc-f7e3fb1d-dbe8-4597-b803-18d4e54f9e36-target-8659db4898dl4md   3/3     Running   0              20m
```
**Deviation from expected behavior:**

**Expected behavior:**

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary

**Logs to submit**:

* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

  To get logs, use `kubectl -n <namespace> logs <pod name>`
  When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
  Read [GitHub documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Cluster Status to submit**:

* Output of kubectl commands, if necessary

  To get the health of the cluster, use `kubectl rook-ceph health`
  To get the status of the cluster, use `kubectl rook-ceph ceph status`
  For more details, see the [Rook kubectl Plugin](https://rook.io/docs/rook/latest-release/Troubleshooting/kubectl-plugin)

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)):

**Comment by sp98** [comment]
@13567436138 Please provide
- Rook and ceph version
- `ceph status` output
- `rook-ceph-operator` logs
- Logs if the failure `mon` and `mgr` pods.

**Comment by rkachach** [comment]
@13567436138 In order to tag an issue as tag you have to explain clearly what's the current behavior versus expected behavior providing as much information as possible on how to reproduce the issue.

**Comment by 13567436138** [comment]
rook 1.3.1
ceph18.2.1

**Comment by 13567436138** [comment]
```
bash-4.4$ ceph -s
  cluster:
    id:     7e4a1d4e-7041-454f-bbf6-6784c7a6fc90
    health: HEALTH_WARN
            1 osds down
            Reduced data availability: 1 pg inactive
            Degraded data redundancy: 1 pg undersized
            16 daemons have recently crashed
 
  services:
    mon: 3 daemons, quorum a,b,c (age 19s)
    mgr: b(active, since 103s), standbys: a
    osd: 7 osds: 2 up (since 2m), 5 in (since 3d)
 
  data:
    pools:   1 pools, 1 pgs
    objects: 0 objects, 0 B
    usage:   28 MiB used, 5.0 GiB / 5 GiB avail
    pgs:     100.000% pgs not active
             1 undersized+peered
```

mgr mon is ok

**Comment by artakmkr** [comment]
Having the same issue here with K8S 1.28 deployed  on  KVM guests (3 cp and 3 worker) with CentOS Stream release 9. 
The same deploy of rook  (v1.13.5) on CentOS Stream release 8 is fine. 

I see the rook-ceph is based on CentOS 8. Can it run on workers running  CentOS 9 ?

**Comment by ktarplee** [comment]
I am seeing the same errors on a test cluster.  rook-ceph version v1.13.3.  Will try again with v1.13.5 soon.

```txt
Traceback (most recent call last):
  File "/usr/bin/ceph", line 1327, in <module>
    retval = main()
  File "/usr/bin/ceph", line 1273, in main
    outf.write(outbuf)
```

**Comment by ktarplee** [comment]
> I am seeing the same errors on a test cluster. rook-ceph version v1.13.3. Will try again with v1.13.5 soon.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/bin/ceph", line 1327, in <module>
>     retval = main()
>   File "/usr/bin/ceph", line 1273, in main
>     outf.write(outbuf)
> ```

My cluster issue finally resolved itself.  It just took a long time.  Those errors still seem out of place to me.

**Comment by artakmkr** [comment]
@ktarplee what's the operating system you are running k8s on?  Is it cloud and on-prem?

**Comment by 13567436138** [comment]
Ubuntu22 04

**Comment by robwithhair** [comment]
I'm getting the same errors in 1.14.0
```
2024-04-17 17:01:08.614976 I | op-mon: mons running: [b c a]
2024-04-17 17:01:09.123281 I | op-mon: Monitors in quorum: [a c]
2024-04-17 17:01:09.123750 I | op-config: applying ceph settings:
[global]
mon allow pool delete   = true
mon cluster log file    = 
mon allow pool size one = true
2024-04-17 17:01:24.125193 I | exec: exec timeout waiting for process ceph to return. Sending interrupt signal to the process
2024-04-17 17:01:24.154324 E | op-config: failed to run command ceph [config assimilate-conf -i /var/lib/rook/481101839 -o /var/lib/rook/481101839.out]
2024-04-17 17:01:24.154345 E | op-config: failed to apply ceph settings:
2024-04-17 17:01:24.178654 E | ceph-cluster-controller: failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph monitors: failed to set Rook and/or user-defined Ceph config options after forcefully updating the existing mons: failed to apply default Ceph configurations: failed to set all keys: failed to set ceph config in the centralized mon configuration database; output: Interrupted
Traceback (most recent call last):
  File "/usr/bin/ceph", line 1327, in <module>
    retval = main()
  File "/usr/bin/ceph", line 1273, in main
    outf.write(outbuf)
TypeError: a bytes-like object is required, not 'str': exit status 1
2024-04-17 17:01:24.184057 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
```
Trying to debug failing monitors where ceph status in toolbox hanging forever.

**Comment by alphabet5** [comment]
I'm seeing this same thing, rook 1.17.2, ceph v19.2.2-20250409

```
2025-05-19 18:27:16.911716 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2025-05-19 18:27:16.912101 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2025-05-19 18:27:18.506656 I | op-mon: targeting the mon count 5
2025-05-19 18:27:18.559805 I | op-config: applying ceph settings for "global"
2025-05-19 18:27:33.561811 I | exec: exec timeout waiting for process ceph to return. Sending interrupt signal to the process
2025-05-19 18:27:33.586869 E | op-config: failed to run command ceph [config assimilate-conf -i /var/lib/rook/2014468025 -o /var/lib/rook/2014468025.out]
2025-05-19 18:27:33.586903 E | op-config: failed to apply ceph settings for "global"
2025-05-19 18:27:33.587089 W | op-mon: failed to set Rook and/or user-defined Ceph config options before starting mons; will retry after starting mons. failed to apply default Ceph configurations: failed to set all keys: failed to set ceph config in the centralized mon configuration database; output: Interrupted
Traceback (most recent call last):
  File "/usr/bin/ceph", line 1327, in <module>
    retval = main()
  File "/usr/bin/ceph", line 1273, in main
    outf.write(outbuf)
TypeError: a bytes-like object is required, not 'str': exit status 1
```

I'm guessing this is a configuration error (this is a new cluster), but it looks like it's going to take some digging to figure out where.

**Comment by alphabet5** [comment]
The issue I had was old data not getting wiped between reinstalls, in the node local data directory.
