### ISSUE TITLE
After updating to `1.14.8` and creating a new cluster, whenever a node that hosted an OSD is recycled the activate init container for that OSD fails

### ISSUE THREAD

**Issue by travisn** [rook/rook#14436]
After updating to `1.14.8` and creating a new cluster, whenever a node that hosted an OSD is recycled the activate init container for that OSD fails with

<details><summary>osd log</summary>
<p>

```pytb
activate + CEPH_FSID=e03644bf-cea9-4117-a812-6d193a2b9a99
activate + OSD_UUID=e6d9527c-a1ed-4cc9-8b58-59d1d3160170
activate + OSD_STORE_FLAG=--bluestore
activate + OSD_DATA_DIR=/var/lib/ceph/osd/ceph-1
activate + CV_MODE=raw
activate + DEVICE=/dev/sdb
activate + cp --no-preserve=mode /etc/temp-ceph/ceph.conf /etc/ceph/ceph.conf
activate + python3 -c '
activate import configparser
stream logs failed container "expand-bluefs" in pod "rook-ceph-osd-1-7c99c8445f-74tdk" is waiting to start: PodInitializing for rook-ceph-cluster/rook-ceph-osd-1-7c99c8445f-74tdk (expand-bluefs)
stream logs failed container "chown-container-data-dir" in pod "rook-ceph-osd-1-7c99c8445f-74tdk" is waiting to start: PodInitializing for rook-ceph-cluster/rook-ceph-osd-1-7c99c8445f-74tdk (chown-container-data-dir)
activate 
activate config = configparser.ConfigParser()
activate config.read('\''/etc/ceph/ceph.conf'\'')
activate 
activate if not config.has_section('\''global'\''):
activate     config['\''global'\''] = {}
activate 
activate if not config.has_option('\''global'\'','\''fsid'\''):
activate     config['\''global'\'']['\''fsid'\''] = '\''e03644bf-cea9-4117-a812-6d193a2b9a99'\''
activate 
activate with open('\''/etc/ceph/ceph.conf'\'', '\''w'\'') as configfile:
activate     config.write(configfile)
activate '
activate + ceph -n client.admin auth get-or-create osd.1 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring
activate [osd.1]
activate     key = AQDjfYdm49RANBAAHIgyljiGqB/xhrwYz/Sdzg==
activate + [[ raw == \l\v\m ]]
activate ++ mktemp
activate + OSD_LIST=/tmp/tmp.joMfhApBMR
activate + ceph-volume raw list /dev/sdb
activate  stderr: lsblk: /dev/sdb: not a block device
activate Traceback (most recent call last):
activate   File "/usr/sbin/ceph-volume", line 11, in <module>
activate     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 41, in __init__
activate     self.main(self.argv)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
activate     return f(*a, **kw)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 153, in main
activate     terminal.dispatch(self.mapper, subcommand_args)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
activate     instance.main()
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
activate     terminal.dispatch(self.mapper, self.argv)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
activate     instance.main()
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 174, in main
activate     self.list(args)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
activate     return func(*a, **kw)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 130, in list
activate     report = self.generate(args.device)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 99, in generate
activate     info_devices.append(disk.lsblk(dev, abspath=True))
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/util/disk.py", line 245, in lsblk
activate     abspath=abspath)
activate   File "/usr/lib/python3.6/site-packages/ceph_volume/util/disk.py", line 337, in lsblk_all
activate     raise RuntimeError(f"Error: {err}")
activate RuntimeError: Error: ['lsblk: /dev/sdb: not a block device']
activate + echo ''
activate + cat /tmp/tmp.joMfhApBMR
activate 
activate + find_device
activate + python3 -c '
activate import sys, json
activate for _, info in json.load(sys.stdin).items():
activate     if info['\''osd_id'\''] == 1:
activate         print(info['\''device'\''], end='\'''\'')
activate         print('\''found device: '\'' + info['\''device'\''], file=sys.stderr) # log the disk we found to stderr
activate         sys.exit(0)  # don'\''t keep processing once the disk is found
activate sys.exit('\''no disk found with OSD ID 1'\'')
activate '
activate Traceback (most recent call last):
activate   File "<string>", line 3, in <module>
activate   File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
activate     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
activate   File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
activate     return _default_decoder.decode(s)
activate   File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
activate     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
activate   File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
activate     raise JSONDecodeError("Expecting value", s, err.value) from None
activate json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
activate + ceph-volume raw list
activate + cat /tmp/tmp.joMfhApBMR
activate {}
activate ++ find_device
activate ++ python3 -c '
activate import sys, json
activate for _, info in json.load(sys.stdin).items():
activate     if info['\''osd_id'\''] == 1:
activate         print(info['\''device'\''], end='\'''\'')
activate         print('\''found device: '\'' + info['\''device'\''], file=sys.stderr) # log the disk we found to stderr
activate         sys.exit(0)  # don'\''t keep processing once the disk is found
activate sys.exit('\''no disk found with OSD ID 1'\'')
activate '
activate no disk found with OSD ID 1
activate + DEVICE=
Stream closed EOF for rook-ceph-cluster/rook-ceph-osd-1-7c99c8445f-74tdk (activate)
```

</p>
</details> 

This is on GKE and we still have

```yaml
cephClusterSpec:
...
        storage:
          useAllNodes: true
          useAllDevices: false
          deviceFilter: "^/dev/disk/by-id/google-pvc-.*"
```

in the cluster configuration.

_Originally posted by @cameronraysmith in https://github.com/rook/rook/issues/13564#issuecomment-2211963361_

**Comment by travisn** [comment]
This sounds like a regression from #14374. 

@cameronraysmith Can you confirm that you don't hit this issue on v1.14.7? Did you find any workaround other than downgrading to v1.14.7?

**Comment by cameronraysmith** [comment]
> This sounds like a regression from #14374.

Thank you for migrating the issue. 

> @cameronraysmith Can you confirm that you don't hit this issue on v1.14.7? Did you find any workaround other than downgrading to v1.14.7?

Apologies I cannot. I upgraded from v1.14.5 to v1.14.8.


<details><summary>GKE-specific note</summary>
<p>

I would imagine this issue is not at all specific to GKE and that this is somewhat common knowledge, but if anyone else would like to test this there, I note that GKE requires `UBUNTU_CONTAINERD` images
https://github.com/rook/rook/issues/2448#issuecomment-2219331192 
as, to the best of my knowledge, all others lack the required rbd module.

</p>
</details>

**Comment by travisn** [comment]
@cameronraysmith So your OSDs are still all failing or you found a workaround? If still failing, hopefully you could resolve this by changing Rook to v1.14.7.

**Comment by cameronraysmith** [comment]
Yes thank you very much @travisn. I have removed this ceph cluster at this time, but will post here if I decide to retest with v1.14.7 or a future release.
