### ISSUE TITLE
OSD pods aren't created: SecurityContext.RunAsUser is forbidden

### ISSUE THREAD

**Issue by ITler** [rook/rook#1460]
Is this a bug report or feature request?

* Bug Report

**Bug Report**

What happened:
For simple testing if rook works on MS **AzureGermanCloud**, I'm running through Quickstart guide.
Without changing definitions, after basic applying, I see pods: 1 api, 2 managers, 3 mons, but **NO** osd
Manager0 pod logs:
```
2018-01-30 16:47:08.338024 I | ceph-mgr: 2018-01-30 16:47:08.337102 7f89b9adb700 -1 mgr load Traceback (most recent call last):
2018-01-30 16:47:08.338100 I | ceph-mgr:   File "/usr/local/lib/ceph/mgr/restful/__init__.py", line 1, in <module>
2018-01-30 16:47:08.338127 I | ceph-mgr:     from module import *  # NOQA
2018-01-30 16:47:08.338147 I | ceph-mgr:   File "/usr/local/lib/ceph/mgr/restful/module.py", line 17, in <module>
2018-01-30 16:47:08.338189 I | ceph-mgr:     from pecan import jsonify, make_app
2018-01-30 16:47:08.338223 I | ceph-mgr: ImportError: No module named pecan
2018-01-30 16:47:08.338242 I | ceph-mgr:
2018-01-30 16:47:08.338386 I | ceph-mgr: 2018-01-30 16:47:08.338291 7f89b9adb700 -1 mgr init Error loading module 'restful': (2) No such file or directory
2018-01-30 16:47:08.338486 I | ceph-mgr: 2018-01-30 16:47:08.338435 7f89b9adb700  1 mgr init Loading python module 'status'
2018-01-30 16:47:08.418003 I | ceph-mgr: 2018-01-30 16:47:08.417940 7f89b9adb700  1 mgr load Constructed class from module: status
2018-01-30 16:47:08.418280 I | ceph-mgr: 2018-01-30 16:47:08.418235 7f89b9adb700 -1 log_channel(cluster) log [ERR] : Failed to load ceph-mgr modules: restful
2018-01-30 16:47:08.418443 I | ceph-mgr: 2018-01-30 16:47:08.418409 7f89b9adb700  1 mgr start Creating threads for 1 modules
2018-01-30 16:47:08.418690 I | ceph-mgr: 2018-01-30 16:47:08.418628 7f89b9adb700  1 mgr send_beacon active
2018-01-30 16:47:10.065585 I | ceph-mgr: 2018-01-30 16:47:10.065061 7f89baadd700  1 mgr send_beacon active
2018-01-30 16:47:24.071911 I | ceph-mgr: 2018-01-30 16:47:24.071860 7f89baadd700  1 mgr.server send_report Not sending PG status to monitor yet, waiting for OSDs
2018-01-30 16:47:26.072956 I | ceph-mgr: 2018-01-30 16:47:26.072746 7f89baadd700  1 mgr send_beacon active
2018-01-30 16:47:26.073912 I | ceph-mgr: 2018-01-30 16:47:26.073636 7f89baadd700  1 mgr.server send_report Not sending PG status to monitor yet, waiting for OSDs
2018-01-30 16:47:28.073871 I | ceph-mgr: 2018-01-30 16:47:28.073782 7f89baadd700  1 mgr send_beacon active
[...]
2018-01-30 16:47:28.074757 I | ceph-mgr: 2018-01-30 16:47:28.074700 7f89baadd700  1 mgr.server send_report Not sending PG status to monitor yet, waiting for OSDs
2018-01-30 16:47:30.075027 I | ceph-mgr: 2018-01-30 16:47:30.074925 7f89baadd700  1 mgr send_beacon active
2018-01-30 16:47:30.076100 I | ceph-mgr: 2018-01-30 16:47:30.075861 7f89baadd700  1 mgr.server send_report Giving up on OSDs that haven't reported yet, sending potentially incomplete PG state to mon
[...]
```
Other pods don't show logs indicating an error state and look ok for my sake.

What you expected to happen:  
Get a simple complete and running setup as described in Quickstart. Get version `v.0.6.2` as working with the appropriate git tag, but seems this nevertheless provides `v.0.6.1`

How to reproduce it (minimal and precise):  

Like Quickstart says
1. apply `rook-operator.yaml`
2. wait until pods in `rook-system` are running
3. apply `rook-cluster.yaml`

In addition, I applied `rook-storageclass.yaml` as I would need it for my application pods.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 16.04.1
* Kernel (e.g. `uname -a`): 4.4.0-112-generic on k8s agents
* Cloud provider or hardware configuration: AzureGermanCloud
* Rook version (use `rook version` inside of a Rook Pod): `v.0.6.1`, but git tag is **v.0.6.2**
* Kubernetes version (use `kubectl version`): server 1.8.4, client 1.9.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): don't know... provided by azure/acs-engine
* Ceph status (use `ceph health` in the [Rook toolbox](https://Rook.io/docs/Rook/master/toolbox.html)): Rook toolbox container not accessible like described in the documentation, as pod is ***privileged*** and that's why `kubectl exec -it rook-toolbox bash` declines attaching

**Comment by jbw976** [comment]
Hi @ITler, do you happen to have the rook-operator pod logs that may give us more information about why no OSD pods were created?  The state of the Rook cluster CRD may also be useful.  These commands will get that information, feel free to add them to a [gist](https://gist.github.com/) and link it here in a comment.  Thanks!
```
kubectl -n rook-system logs -l app=rook-operator
kubectl -n rook get cluster rook -o yaml
```

**Comment by ITler** [comment]
Hello Jared,
thanks for offering help. See this gist:
https://gist.github.com/ITler/3f751a3323d13b22c6b1f022f62b3460
Again I want to mention, that I took sources from git tag `v.0.6.2`.

**Comment by jbw976** [comment]
Thanks for sharing the gist @ITler.  It looks like the Rook cluster is set to use all nodes for storage (`useAllNodes: true`) and that the operator successfully created a DaemonSet for the OSDs.  There must be something preventing the DaemonSet from starting up any OSD pods.  Can you also add the output from the following commands to your gist?
```
kubectl -n rook get pod -o wide
kubectl -n rook get ds rook-ceph-osd -o yaml
kubectl -n rook describe ds rook-ceph-osd
```

**Comment by ITler** [comment]
There it is. Found it... it is a problem with the daemon set, which I did not recognize before :-/

    Error creating: pods is forbidden: SecurityContext.RunAsUser is forbidden

See gist for details. 

Not sure, but my first search results seem to point to creating a [SecurityContext](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/), but I'm currently not that deep into that topic. Do you have a clue?

**Comment by galexrt** [comment]
@ITler This doc page should contain information on how to use/create a PodSecurityPolicy and other stuff to fix the issue you are experiencing, see: https://rook.io/docs/rook/master/rbac.html#rbac-for-podsecuritypolicies.

**Comment by ITler** [comment]
thank you @galexrt , will check asap and report back

**Comment by ITler** [comment]
@galexrt 
Unfortunately, I still face same issue even after applying the setting described in the document.

**Comment by ITler** [comment]
The reason could be, that AdmissionController was not activated. I can't check at the moment, so I close this for now and would re-open if still needing assistance
