### ISSUE TITLE
/rook/rook ceph osd provision takes a LOT of memory

### ISSUE THREAD

**Issue by KarlJorgensen** [rook/rook#14978]
* Bug Report

We have a rook/ceph cluster which is configured to use _all_ disks on the servers. Seems to work generally fine.

Then we added a couple of physical disks on one of the servers, configured them in the RAID controller (to get the disks exposed as single disks to the OS). They appear as expected in /dev, and we created an empty DOS partition table on each.

The disks are 1.8Tb and 3.6Tb respectively. The disks are healthy; no kernel complaints about IO timeouts, bad blocks or similar.

But ceph (or rook?) is failing to initialize the new disks: It starts a k8s job to prepare the server, discovers the disk and the container then proceeds to run `/rook/rook ceph osd provision`. All as expected so far.

But that process is using a LOT of memory, which then eventually ends up invoking the kernel OOM killer!

The server has 64Gb of memory, which it easily exhausted. I even tried (temporarily) adding 64Gb of swap without luck. (k8s does not like swap, so not making it permanent)

Output from top:

    top - 11:17:16 up 16:21,  8 users,  load average: 8.98, 11.79, 8.63                                                                                                                                                                       [0/56]
    Tasks: 357 total,   1 running, 356 sleeping,   0 stopped,   0 zombie
    %Cpu(s): 17.7 us,  6.3 sy,  0.0 ni, 67.5 id,  6.8 wa,  0.0 hi,  1.7 si,  0.0 st
    MiB Mem :  64243.4 total,    630.8 free,  62450.5 used,   1162.1 buff/cache
    MiB Swap:  65536.0 total,  38043.6 free,  27492.4 used.   1168.7 avail Mem

        PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
     787653 root      20   0  104.1g  59.5g   1280 S  10.9  94.9   4:27.29 /rook/rook ceph osd provision
       3860 root      20   0  791852 145416   5120 S  99.3   0.2  24:32.75 /usr/local/bin/ruby /usr/local/bundle/bin/fluentd --no-supervisor -q -r /usr/local/bundle/gems/fluent-plugin-elasticsearch-5.0.5/lib/fluent/plugin/elasticsearch_simple+
     732728 2016      20   0 5623032 117964  13696 S   0.0   0.2   0:24.96 /usr/local/bin/rook ceph operator
       2412 root      20   0 5615140  84452  25344 S 168.9   0.1  63:27.89 kubelet --cloud-provider= --hostname-override=3yfyr12.ops.recordsure.com --root-dir=/var/lib/kubelet --volume-plugin-dir=/var/lib/kubelet/volumeplugins --address=0.0.0+
       1415 root      20   0 9058976  70316  21888 S   1.7   0.1  40:23.45 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
       3849 root      20   0  427176  49636   2816 S  84.8   0.1  19:10.13 /usr/local/bin/ruby /usr/local/bundle/bin/fluentd --no-supervisor -q -r /usr/local/bundle/gems/fluent-plugin-elasticsearch-5.0.5/lib/fluent/plugin/elasticsearch_simple+
     768113 root      20   0 3122984  46404  19712 S   0.7   0.1   0:39.38 calico-node -felix

By now (after multiple reboots etc) the rook/ceph operator appears to have deleted the k8s deployments for the other OSDs on the same node, leaving us with reduced storage capacity. But the ceph cluster is healthy.

**Deviation from expected behavior:**

OOM killer invoked, which then kills the `/rook/rook` process

**Expected behavior:**

OSD provisioned without exhausting the memory

**Environment**:
* OS: Ubuntu 22.04
* Kernel: 6.8.0-48-generic
* Bare metal hardware: 64Gb of memory, 16 CPU cores
* Rook version: v1.14.0  (docker image: rook/ceph:v1.14.0)
* Storage backend version: ceph version 18.2.2 (531c0d11a1c5d39fbfe6aa8a521f023abf3bf3e2) reef (stable)
* Kubernetes version: v1.28.7
* Kubernetes cluster type: Rancher

I'm open to tweaking things to obtain more diagnostic information if that is helpful

**Comment by KarlJorgensen** [comment]
From `/proc/${pid}/status` : The process is using _way_ more memory than I'm comfortable with - 117Gb at this point (still growing - will be OOMkilled eventually):

```
Name:   rook
Umask:  0022
State:  S (sleeping)
Tgid:   956498
Ngid:   0
Pid:    956498
PPid:   956459
TracerPid:      0
Uid:    0       0       0       0
Gid:    0       0       0       0
FDSize: 64
Groups: 0 
NStgid: 956498  1
NSpid:  956498  1
NSpgid: 956498  1
NSsid:  956498  1
Kthread:        0
VmPeak: 117451376 kB
VmSize: 117451376 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:  61622208 kB
VmRSS:  57621312 kB
RssAnon:        57619264 kB
RssFile:            2048 kB
RssShmem:              0 kB
VmData: 111517588 kB
VmStk:       132 kB
VmExe:     27768 kB
VmLib:         8 kB
VmPTE:    211784 kB
VmSwap: 50424832 kB
HugetlbPages:          0 kB
CoreDumping:    0
THP_enabled:    1
untag_mask:     0xffffffffffffffff
Threads:        18
SigQ:   4/256452
SigPnd: 0000000000000000
ShdPnd: 0000000000000000
SigBlk: 0000000000000000
SigIgn: 0000000000000000
SigCgt: fffffffd7fc1feff
CapInh: 0000000000000000
CapPrm: 000001ffffffffff
CapEff: 000001ffffffffff
CapBnd: 000001ffffffffff
CapAmb: 0000000000000000
NoNewPrivs:     0
Seccomp:        0
Seccomp_filters:        0
Speculation_Store_Bypass:       thread vulnerable
SpeculationIndirectBranch:      conditional enabled
Cpus_allowed:   ffff,ffffffff
Cpus_allowed_list:      0-47
Mems_allowed:   00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:      0
voluntary_ctxt_switches:        1387
nonvoluntary_ctxt_switches:     21
x86_Thread_features:
x86_Thread_features_locked:
```

**Comment by guits** [comment]
@travisn not that I know. Do we know which call exactly is causing this issue? any log?

**Comment by KarlJorgensen** [comment]
Grabbed some logs:
- The rook-ceph-operator logs: [operator.log](https://github.com/user-attachments/files/17668154/operator.log). Probably not that interesting.
- the logs from the `prepare` k8s job (actually: the pod): 
[prepare.log](https://github.com/user-attachments/files/17668157/prepare.log)
  Last thing it says is:
```
2024-11-07 19:00:38.832371 I | cephclient: getting or creating ceph auth key "client.bootstrap-osd"
2024-11-07 19:00:38.832413 D | exec: Running command: ceph auth get-or-create-key client.bootstrap-osd mon allow profile bootstrap-osd --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json
2024-11-07 19:00:39.937621 I | cephosd: configuring new raw device "/dev/sdk"
2024-11-07 19:00:39.937657 D | exec: Running command: stdbuf -oL ceph-volume raw prepare --bluestore --data /dev/sdk
```
and that's it.

A couple of interesting things:
* I see _no noteworthy disk activity_. Only the root filesystem has activity. I'd expect preparation to be busy writing stuff to disk?
* The process which eats up all the memory is running `/rook/rook ceph osd provision` - which is *not* the command listed in `prepare.log` above

Out of curiosity, I have a `kill -STOP` to the `/rook/rook ceph osd provision` process (just to stop it from gobbling all the memory in the system, and give me some room to investigate). Obviously the growth of memory consumption stopped at this point.

Using `kubectx exec` into the `rook-ceph-osd-prepare` container and running the exact same command line in there yields this:
```
ceph-volume raw prepare --bluestore --data /dev/sdk
Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new f684c192-f7ca-430f-acab-c5a774f6f075
 stderr: Error EEXIST: entity osd.21 exists but key does not match
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 33, in <module>
    sys.exit(load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')())
  File "/usr/lib/python3.9/site-packages/ceph_volume/main.py", line 41, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.9/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.9/site-packages/ceph_volume/main.py", line 153, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.9/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.9/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.9/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.9/site-packages/ceph_volume/devices/raw/prepare.py", line 160, in main
    self.safe_prepare(self.args)
  File "/usr/lib/python3.9/site-packages/ceph_volume/devices/raw/prepare.py", line 80, in safe_prepare
    self.prepare()
  File "/usr/lib/python3.9/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.9/site-packages/ceph_volume/devices/raw/prepare.py", line 113, in prepare
    self.osd_id = prepare_utils.create_id(
  File "/usr/lib/python3.9/site-packages/ceph_volume/util/prepare.py", line 154, in create_id
    raise RuntimeError('Unable to create a new OSD id')
```
which looks like a clue!

So my next step was to run `ceph auth rm osd.21` (as we do not _have_ an OSD 21 - must have been a previously-removed OSD?) and issuing a `kill -CONT` to the `/rook/rook ceph osd provision` process.

So far, this seemed to have had no effect; the growth in memory consumption continued as before, so I ended up giving a proper `kill` instead (otherwise the box locks up). This obviously caused the `prepare` k8s job to fail, and k8s dutifully retried it.

And this time: No crazy memory growth! The OSDs got created for both disks, and things started working normally.

I can only conclude that the ceph auth key for a previously-removed OSD "got in the way". Which is strange, as the previously-failed disks were removed with `kubectl rook-ceph rook purge-osd` which _should_ have done "the right thing"?

I feel I've stumbled over some corner case the code was not fully prepared for.

And there must be some wonky code in `/rook/rook ceph osd provision` which does not handle the failure of the underlying command... Perhaps it retries it like crazy? (I can't really tell)

**Comment by guits** [comment]
> Grabbed some logs:
> 
> * The rook-ceph-operator logs: [operator.log](https://github.com/user-attachments/files/17668154/operator.log). Probably not that interesting.
> * the logs from the `prepare` k8s job (actually: the pod):
>   [prepare.log](https://github.com/user-attachments/files/17668157/prepare.log)
>   Last thing it says is:
> 
> ```
> 2024-11-07 19:00:38.832371 I | cephclient: getting or creating ceph auth key "client.bootstrap-osd"
> 2024-11-07 19:00:38.832413 D | exec: Running command: ceph auth get-or-create-key client.bootstrap-osd mon allow profile bootstrap-osd --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json
> 2024-11-07 19:00:39.937621 I | cephosd: configuring new raw device "/dev/sdk"
> 2024-11-07 19:00:39.937657 D | exec: Running command: stdbuf -oL ceph-volume raw prepare --bluestore --data /dev/sdk
> ```
> 
> and that's it.
> 
> A couple of interesting things:
> 
> * I see _no noteworthy disk activity_. Only the root filesystem has activity. I'd expect preparation to be busy writing stuff to disk?
> * The process which eats up all the memory is running `/rook/rook ceph osd provision` - which is _not_ the command listed in `prepare.log` above
> 
> Out of curiosity, I issued a `kill -STOP` to the `/rook/rook ceph osd provision` process (just to stop it from gobbling all the memory in the system, and give me some room to investigate). Obviously the growth of memory consumption stopped at this point.
> 
> Using `kubectl exec` into the `rook-ceph-osd-prepare` pod/container and running the exact same command line in there yields this:
> 
> ```
> ceph-volume raw prepare --bluestore --data /dev/sdk
> Running command: /usr/bin/ceph-authtool --gen-print-key
> Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new f684c192-f7ca-430f-acab-c5a774f6f075
>  stderr: Error EEXIST: entity osd.21 exists but key does not match
> Traceback (most recent call last):
>   File "/usr/sbin/ceph-volume", line 33, in <module>
>     sys.exit(load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')())
>   File "/usr/lib/python3.9/site-packages/ceph_volume/main.py", line 41, in __init__
>     self.main(self.argv)
>   File "/usr/lib/python3.9/site-packages/ceph_volume/decorators.py", line 59, in newfunc
>     return f(*a, **kw)
>   File "/usr/lib/python3.9/site-packages/ceph_volume/main.py", line 153, in main
>     terminal.dispatch(self.mapper, subcommand_args)
>   File "/usr/lib/python3.9/site-packages/ceph_volume/terminal.py", line 194, in dispatch
>     instance.main()
>   File "/usr/lib/python3.9/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
>     terminal.dispatch(self.mapper, self.argv)
>   File "/usr/lib/python3.9/site-packages/ceph_volume/terminal.py", line 194, in dispatch
>     instance.main()
>   File "/usr/lib/python3.9/site-packages/ceph_volume/devices/raw/prepare.py", line 160, in main
>     self.safe_prepare(self.args)
>   File "/usr/lib/python3.9/site-packages/ceph_volume/devices/raw/prepare.py", line 80, in safe_prepare
>     self.prepare()
>   File "/usr/lib/python3.9/site-packages/ceph_volume/decorators.py", line 16, in is_root
>     return func(*a, **kw)
>   File "/usr/lib/python3.9/site-packages/ceph_volume/devices/raw/prepare.py", line 113, in prepare
>     self.osd_id = prepare_utils.create_id(
>   File "/usr/lib/python3.9/site-packages/ceph_volume/util/prepare.py", line 154, in create_id
>     raise RuntimeError('Unable to create a new OSD id')
> ```
> 
> which looks like a clue!
> 
> So my next step was to run `ceph auth rm osd.21` (as we do not _have_ an OSD 21 - must have been a previously-removed OSD?) and issuing a `kill -CONT` to the `/rook/rook ceph osd provision` process.
> 
> So far, this seemed to have had no effect; the growth in memory consumption continued as before, so I ended up giving a proper `kill` instead (otherwise the box locks up). This obviously caused the `prepare` k8s job to fail, and k8s dutifully retried it.
> 
> And this time: No crazy memory growth! The OSDs got created for both disks, and things started working normally.
> 
> I can only conclude that the ceph auth key for a previously-removed OSD "got in the way". Which is strange, as the previously-failed disks were removed with `kubectl rook-ceph rook purge-osd` which _should_ have done "the right thing"?
> 
> I feel I've stumbled over some corner case the code was not fully prepared for.
> 
> And there must be some wonky code in `/rook/rook ceph osd provision` which does not handle the failure of the underlying command... Perhaps it retries it like crazy? (I can't really tell)

@KarlJorgensen thanks! nice debug.
It's hard to say, but that might indeed be a corner case.
I'm not sure if you can reproduce it easily. For what it's worth, what I can tell is that create_id() involves calling two commands: `ceph osd tree` (only if --osd-id is specified) and `ceph osd new`. One of these commands must have hung for some reason. Do you have any idea what the cluster state was like at that moment? Were all PGs "ok", or were there any unusual statuses?

**Comment by KarlJorgensen** [comment]
@guits I'm not sure how to reproduce it. Yet. And not really keen, as this is a production cluster which should not be subject to such experiments.

I _suspect_ that part of the reproduction would be to:
* create an auth key for the next-unused-osd-id (e.g. if you have 20 OSDs, create one for OSD 21)
* Add a new disk to the cluster - which would presumably try to become no 21

I doubt that whatever-command `/root/rook ceph ...` was running was *hung*: The `rook` process was quite happy gobbling up memory like mad and was using a fair bit of CPU. My first suspicion would that the command errored out (like when I tried it by hand), and `rook` retried it endlessly (probably saving the stdout/stderr in memory?). Studying the relevant source here should throw some light on that.

But there's more to it than that - if this was the _entire_ story then `rook` would have succeeded when removed the rogue auth key key and issued a `kill -CONT`.

The cluster state was healthy - by this time rook had removed the deployments for the other OSDs on the same server, ceph had marked the OSDs as "out", the cluster had finished rebalancing and everything was reporting OK.  There _may_ have been a couple of PGs undergoing scrubbing or deep scrubbing (usual stuff), but I doubt they are a factor here.

**Comment by KarlJorgensen** [comment]
Also: I very much suspect that removing an OSD by running `kubectl rook-ceph rook purge-osd` leaves the auth key behind.

So we have (at least) two elements to this problem:
* `kubectl rook-ceph rook purge-osd` must have failed to remove the auth key
* the provisioning of a new OSD (attempting to re-use the same OSD number) gets tripped up by the auth key already existing, and reacts badly to it
