### ISSUE TITLE
Failed to execute RBD image not found

### ISSUE THREAD

**Issue by tcrawford22** [rook/rook#14994]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
throwing a error when viewing all block images from the gui
![image](https://github.com/user-attachments/assets/6bba6771-32b9-428b-be52-bdcf507c83ae)

**Expected behavior:**
able to see all images in the gui in Block > Images

**How to reproduce it (minimal and precise):**
We had some snapshotvolumecontent that got stuck and we had to manually delete in k8s, and in rook-ceph
we used the following commands
kubectl delete volumesnapshotcontents
then on rook-ceph
rbd flatten "$POOL_NAME/$image"
rbd snap purge "$POOL_NAME/$image"
rbd rm "$POOL_NAME/$image"

some all we had to do was just
rbd rm "$POOL_NAME/$image"

others we had to flatten first to remove from their parent

After that, going to the gui on the dashboard it throws a error when trying to visit the images, this happened on our def and prod cluster

[clusters.txt](https://github.com/user-attachments/files/17707510/clusters.txt)

`debug 2024-11-11T18:46:01.768+0000 7f8851f31640  0 [dashboard ERROR exception] Dashboard Exception
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 72, in handle_rbd_error
    yield
  File "/usr/lib64/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib64/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/share/ceph/mgr/dashboard/controllers/rbd.py", line 94, in list
    return self._rbd_list(pool_name, offset=int(offset), limit=int(limit),
  File "/usr/share/ceph/mgr/dashboard/controllers/rbd.py", line 76, in _rbd_list
    images[i]['metadata'] = rbd_image_call(
  File "/usr/share/ceph/mgr/dashboard/services/rbd.py", line 138, in rbd_image_call
    return rbd_call(pool_name, namespace, _ioctx_func, image_name, func, *args, **kwargs)
  File "/usr/share/ceph/mgr/dashboard/services/rbd.py", line 130, in rbd_call
    return func(ioctx, *args, **kwargs)
  File "/usr/share/ceph/mgr/dashboard/services/rbd.py", line 135, in _ioctx_func
    with rbd.Image(ioctx, image_name) as img:
  File "rbd.pyx", line 2897, in rbd.Image.__init__
rbd.ImageNotFound: [errno 2] RBD image not found (error opening image b'csi-snap-1fa0e28d-daed-47fb-a750-ef228186073f' at snapshot None)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 47, in dashboard_exception_handler
    return handler(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/_base_controller.py", line 263, in inner
    ret = func(*args, **kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/_rest_controller.py", line 191, in wrapper
    return func(*vpath, **params)
  File "/usr/lib64/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib64/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 74, in handle_rbd_error
    raise DashboardException(e, component='rbd')
dashboard.exceptions.DashboardException: [errno 2] RBD image not found (error opening image b'csi-snap-1fa0e28d-daed-47fb-a750-ef228186073f' at snapshot None)`

kubectl -n rook-ceph exec -it deploy/rook-ceph-tools -- rbd ls -l replicapool
rbd: error opening csi-snap-1fa0e28d-daed-47fb-a750-ef228186073f: (2) No such file or directory
rbd: error opening csi-snap-3c1ddb08-3461-4c79-b5a8-b10fdf239581: (2) No such file or directory
NAME                                                                                        SIZE     PARENT  FMT  PROT  LOCK
csi-snap-2edbaada-b7f5-4b57-88de-40415f9c82ce                                                 8 GiB            2
csi-vol-0b10951c-9ec9-4b49-9f69-d7468ccfb0ba                                                 10 GiB            2
csi-vol-16000db2-fb26-4dcd-ba7a-c9b77549d322                                                 10 GiB            2
csi-vol-1637b9b3-774b-4f62-be85-53d2fce76dbe                                                 50 GiB            2
csi-vol-180798c7-cbc9-4db4-bc7d-ce6c8d4caa38                                                  8 GiB            2
csi-vol-1886319d-ca23-4193-85a0-7f9d22bb3e6a                                                 30 GiB            2
csi-vol-18b50038-2fa1-466e-a010-d3257464ab2b                                                  8 GiB            2
csi-vol-1ad697dc-3501-4ecd-bbcd-c6c89ae14691                                                  8 GiB            2
csi-vol-1b8f7299-9989-49ea-8302-e4991a12cebb                                                 10 GiB            2
csi-vol-1c3b5481-e234-40b9-a11c-89267207b227                                                 10 GiB            2
csi-vol-202eb499-499f-441c-9428-01fa83361d74                                                  8 GiB            2
csi-vol-2564c301-22dd-4f5a-974e-9b046c5e4f0c                                                 10 GiB            2
csi-vol-2b812791-2978-4263-9f39-c540349167d2                                                  5 GiB            2
csi-vol-2dc79d50-b5d3-4d04-ae55-5397f2d94c43                                                 10 GiB            2
csi-vol-3081b242-d5e4-46ec-aeac-705c19974d79                                                 20 GiB            2
csi-vol-3ad4868b-6492-4f65-9d54-d21e3ee165b5                                                  8 GiB            2
csi-vol-3caf35ac-0b32-4c48-983c-e97a72901c9a                                                 10 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535                                                  8 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535@csi-snap-89ac4e66-ce0d-4ec6-9551-581b1e881999    8 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535@csi-snap-5a4ea1b2-0c32-4018-824f-26bde1eec41f    8 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535@csi-snap-cc2fcd8e-d16b-47a1-8335-ed52a685e4fe    8 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535@csi-snap-6664385f-5086-4f5d-9f0b-730d1b9584bb    8 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535@csi-snap-d440bdd0-517c-4d01-9dc2-a4c7e85b01a1    8 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535@csi-snap-46bebacd-d900-4479-a578-1feeb9fe3cfa    8 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535@csi-snap-899bf1c8-c8be-4710-9a35-b4e9c96c84bf    8 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535@csi-snap-967dc09f-4835-4a0b-97cb-7395c66bbf8c    8 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535@csi-snap-5da0945e-28fd-464d-9723-12f91949e88e    8 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535@csi-snap-9dcde93b-769c-4bca-a7b5-f41f1545f97e    8 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535@csi-snap-93acba34-4698-4f28-a06a-00f59f5f4181    8 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535@csi-snap-054d01c6-0e45-4117-8d4b-8a07955c8262    8 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535@csi-snap-16db14fb-6377-467f-b6d9-3d245c6d0903    8 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535@csi-snap-c56aae79-9a6c-4670-a51d-2ef187a381d2    8 GiB            2
csi-vol-40690fbf-c5d4-46be-a180-1afc3734a535@csi-snap-962c8525-4071-4925-88a6-83df6c686fb7    8 GiB            2
csi-vol-42f4fc65-afca-444f-89e9-7c7f4a8e23af                                                  5 GiB            2
csi-vol-52577561-6422-49f6-85fd-1a197e9edcd1                                                  8 GiB            2
csi-vol-52577561-6422-49f6-85fd-1a197e9edcd1@csi-snap-6a70d44e-3e23-4f8f-bebc-ddacd4a8ab50    8 GiB            2
csi-vol-533fb397-9768-4c27-aaca-137bbb3dd78d                                                 10 GiB            2
csi-vol-57f380e6-38b3-47eb-938e-b890a51847c3                                                  8 GiB            2
csi-vol-5fcd64fb-e9af-47f4-8eb7-aad99193013b                                                  5 GiB            2
csi-vol-5fcd64fb-e9af-47f4-8eb7-aad99193013b@csi-snap-abbe04bd-59f7-425c-b3e1-b74e46b8c8fe    5 GiB            2
csi-vol-5fcd64fb-e9af-47f4-8eb7-aad99193013b@csi-snap-e33fed42-44dd-4e8f-9bab-992ddd4f4c0c    5 GiB            2
csi-vol-63b4d088-c8a1-4119-86bf-9290296f9d73                                                200 MiB            2
csi-vol-63b4d088-c8a1-4119-86bf-9290296f9d73@csi-snap-fdb398a0-91c0-494c-b543-5b11d6dcad88  200 MiB            2
csi-vol-66680875-a32d-47ea-a422-25721419dea6                                                  8 GiB            2
csi-vol-668b22bc-7b6f-4914-87d6-2480e0bb3cdb                                                  8 GiB            2
csi-vol-66c1a9f0-2b7f-4ede-af7a-aca8c8c68087                                                  8 GiB            2
csi-vol-691a8a05-5539-482c-a26b-74759e72f0c4                                                  8 GiB            2
csi-vol-698f5ab5-36ff-49b7-a005-7474c538a5a1                                                 10 GiB            2
csi-vol-6993f3fa-074e-46b0-ae3b-e88b77f4effa                                                  8 GiB            2
csi-vol-6afd1db5-f75c-4ee6-82ad-bce872151a52                                                  8 GiB            2
csi-vol-6afd1db5-f75c-4ee6-82ad-bce872151a52@csi-snap-544c45e6-2d9c-4da3-8f7c-8117accf40d2    8 GiB            2
csi-vol-6afd1db5-f75c-4ee6-82ad-bce872151a52@csi-snap-72f0bd91-bc30-420a-be5b-024dca84f9ef    8 GiB            2
csi-vol-6c34efc2-f9fc-485b-a343-3dad8f632014                                                  8 GiB            2
csi-vol-6c403a05-94bc-436b-8381-c724b24a2b35                                                  8 GiB            2
csi-vol-6c403a05-94bc-436b-8381-c724b24a2b35@csi-snap-fe2ee77e-b196-4fb6-b84a-dff8b4b96431    8 GiB            2
csi-vol-6d6304d4-7e79-44d9-93fa-5bcb4ad8a6d1                                                  8 GiB            2
csi-vol-740f8479-f690-476d-b68e-6c2343b3a43b                                                  8 GiB            2
csi-vol-740f8479-f690-476d-b68e-6c2343b3a43b@csi-snap-8db60d48-caf9-4c5d-a2ce-e3b7c4bbf1df    8 GiB            2
csi-vol-78adfa08-1367-4b73-9adc-9590956e8eb5                                                  1 GiB            2
csi-vol-7e0a669d-2416-4764-8bbb-4aaab54a6acd                                                  8 GiB            2
csi-vol-7e0a669d-2416-4764-8bbb-4aaab54a6acd@csi-snap-b753dded-9ef5-469c-b680-649ab1a0a511    8 GiB            2
csi-vol-8083bb4d-b82d-4788-9eb3-d1ff9611a30a                                                  8 GiB            2
csi-vol-809cecef-a607-4c0e-893b-4614cf161c54                                                  8 GiB            2
csi-vol-867e2bd9-752e-4dfb-a730-aab7867a40ac                                                  1 GiB            2
csi-vol-87d01e0a-b0c6-4531-a081-cc8149afe261                                                200 MiB            2
csi-vol-87d01e0a-b0c6-4531-a081-cc8149afe261@csi-snap-88825169-a6d8-4883-96c0-2311b50f0c18  200 MiB            2
csi-vol-87d01e0a-b0c6-4531-a081-cc8149afe261@csi-snap-ee18d05b-4531-4e1c-85dd-289f539fe2fb  200 MiB            2
csi-vol-8b7164a2-6ab9-4816-a1a3-87db8e747966                                                350 GiB            2
csi-vol-8b7164a2-6ab9-4816-a1a3-87db8e747966@csi-snap-ae94b363-e313-4b12-a160-90831ed05250  350 GiB            2
csi-vol-8fd3c05d-6d76-4ad6-ab95-c89b333aa75a                                                100 MiB            2
csi-vol-9c7071a8-fb2f-41cd-b8ec-103c23a7bca8                                                  8 GiB            2
csi-vol-a0539257-eb77-47d3-96b9-4a6899d4ec40                                                  1 GiB            2
csi-vol-aec74373-fe04-4657-b021-3e01771bf90c                                                 20 GiB            2
csi-vol-b00fbfdc-be95-444b-bf20-272ce6455789                                                 50 GiB            2
csi-vol-b1ca174f-01a5-4581-b5ab-beb3a9b4ff8a                                                  8 GiB            2
csi-vol-b9dffc53-abc1-430f-bb8b-be48d89c0f4b                                                  1 GiB            2
csi-vol-b9dffc53-abc1-430f-bb8b-be48d89c0f4b@csi-snap-405ad447-810e-4b38-9fa1-b012a8fce42a    1 GiB            2
csi-vol-b9dffc53-abc1-430f-bb8b-be48d89c0f4b@csi-snap-11e53052-e138-450b-9373-98039e8d5354    1 GiB            2
csi-vol-bc9eb8ac-c5de-465f-8d84-ec9445d5186b                                                 10 GiB            2
csi-vol-bde8bed0-3636-4ce3-951a-7b70b8609534                                                  8 GiB            2
csi-vol-be368907-5c55-4cc3-8b1f-413179ef9f57                                                  5 GiB            2
csi-vol-be368907-5c55-4cc3-8b1f-413179ef9f57@csi-snap-e6f77d11-8680-445c-93ce-72aeca8e1b30    5 GiB            2
csi-vol-c9e54cf5-e093-4ab0-89f7-21285ad3f2a5                                                  8 GiB            2
csi-vol-c9e54cf5-e093-4ab0-89f7-21285ad3f2a5@csi-snap-f3b09df6-b405-4c84-9173-426688726a61    8 GiB            2
csi-vol-ca16dfe2-e30e-49c4-bbe1-b613d840142d                                                  8 GiB            2
csi-vol-dbc98f65-0867-461a-b94a-6cf7ff873f09                                                 30 GiB            2
csi-vol-de16608d-1a3b-4796-a51c-8041a013f139                                                  8 GiB            2
csi-vol-e8ca01f0-e11b-4fba-9252-7fa9d82bdb4c                                                  8 GiB            2
csi-vol-ef58c93e-6954-45ba-b081-45ad508bcf0d                                                  8 GiB            2
csi-vol-f071f176-9095-4421-b58a-4bbaf6228084                                                  8 GiB            2
csi-vol-f1bd22b4-cc09-4e02-bede-2dbacbc2af52                                                 10 GiB            2
csi-vol-f73aef8b-7fbb-4433-9fbe-bbe933b1bc58                                                  8 GiB            2
rbd: listing images failed: (2) No such file or directory
command terminated with exit code 2

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.6 LTS
* Kernel (e.g. `uname -a`): 5.4.0-198-generic
* Cloud provider or hardware configuration: baremetal
* Rook version (use `rook version` inside of a Rook Pod): v1.13.5
* Storage backend version (e.g. for ceph do `ceph -v`): v18.2.4-20240724
* Kubernetes version (use `kubectl version`): v1.27.15
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest-release/Troubleshooting/ceph-toolbox/#interactive-toolbox)): Healthy

**Comment by rtoenniges** [comment]
I have the same error :-(
After recreate the missing image everything is working again but if I remove the image in ceph the error come back.
Is there any way to solve this?
