### ISSUE TITLE
Suggestion: Make the `rbd-data-pool-name` flag optional in `create-external-cluster-resources.py` script

### ISSUE THREAD

**Issue by MondayCha** [rook/rook#15039]
### Discussed in https://github.com/rook/rook/discussions/11390

<div type='discussions-op-text'>

<sup>Originally posted by **der-ali** December  6, 2022</sup>
Hallo,
i want only to create Cephfs volumes, so i am wondering why must i create a rbd data pool to use the create-external-cluster-resources.py script?</div>

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**

> [!note] 
> [Export config from the Ceph provider cluster](https://rook.io/docs/rook/latest/CRDs/Cluster/external-cluster/provider-export/#1-create-all-users-and-keys)

The feature should allow users to use the `create-external-cluster-resources.py` script to create Cephfs volumes without the mandatory requirement of creating an rbd data pool beforehand. 

This would provide more flexibility for those who are only dealing with Cephfs volume creation and have no use for the rbd data pool in their particular workflows.

**What is use case behind this feature:**

In many projects, there are scenarios where the sole requirement is to manage and create Cephfs volumes. 

**Environment**:

I'm currently facing difficulties in successfully exporting external Ceph, and as a result, I haven't managed to install Rook successfully yet. 

However, I've previously hosted an internal Ceph through Rook, and it worked quite well.

**Comment by subhamkrai** [comment]
@parth-gr please check this

**Comment by parth-gr** [comment]
I think its a product decision, @BlaineEXE @travisn please add your thoughts

**Comment by travisn** [comment]
The request certainly makes sense from an upstream perspective. Let's discuss.

**Comment by MondayCha** [comment]
**Background**: At our university, we use CephFS storage to manage files for hundreds of students working on our GPU computing cluster for several years. The cluster workload has been managed through Slurm. As a student at this university, I'm currently leading the migration effort from Slurm to Kubernetes.

After discussing with the professor, I learned that I can create an RBD on our existing Ceph cluster and import it through Rook, which should provide a temporary solution to my current challenges.

Nevertheless, I'm particularly keen on engaging with the issue and would welcome the opportunity to contribute to any emerging developments in this space.

**Comment by cra1gg** [comment]
Unstale, being blocked by this issue and I don't really like the idea of creating a rbd pool just to combat

**Comment by MondayCha** [comment]
After being blocked by this issue, I consulted my mentor, who agreed to proceed with the creation. I then created the RBD pool and successfully imported the external Ceph cluster. Currently, we are not using any RBD-related content. 

I think the script provided by Rook is great, as it simplifies the process of importing from external sources. However, the script is quite lengthy, and making the RBD-related logic optional might not be an easy task.

**Comment by subhamkrai** [comment]
@parth-gr ^^

**Comment by parth-gr** [comment]
@MondayCha yaa we had a discussion on this, @travisn should we go ahead to mark it optional, or having a small workaround to create a rbd pool is fine?

**Comment by baldugus** [comment]
Hello,

I'm currently trying to deploy rook with an external cluster using cephfs only and I'm getting this exception when running the create-external-cluster-resources.py script:

```
Execution Failed: The provided pool, '', does not exist
Traceback (most recent call last):
  File "/root/create-external-cluster-resources.py", line 2108, in <module>
    raise err
  File "/root/create-external-cluster-resources.py", line 2105, in <module>
    rjObj.main()
  File "/root/create-external-cluster-resources.py", line 2087, in main 
    generated_output = self.gen_shell_out()
  File "/root/create-external-cluster-resources.py", line 1737, in gen_shell_out
    self._gen_output_map()
  File "/root/create-external-cluster-resources.py", line 1584, in _gen_output_map
    self.validate_rbd_pool(self._arg_parser.rbd_data_pool_name)
  File "/root/create-external-cluster-resources.py", line 1329, in validate_rbd_pool
    raise ExecutionFailureException(
__main__.ExecutionFailureException: The provided pool, '', does not exist
```

Command line I've ran:

```
$ python3 create-external-cluster-resources.py --namespace rook-ceph --k8s-cluster-name k8s --cephfs-metadata-pool-name k8s_metadata --cephfs-data-pool-name k8s_data
```

Although #15358 removed the check for the `--rbd-data-pool-name` flag, there's still calls to RBD related functions in other places (like this _gen_output_map function).

Is this issue known?

**Comment by parth-gr** [comment]
@baldugus those call would be added later and would have broke the functionality, it is not a know issue, can you open a separate bug for this
