### ISSUE TITLE
ceph osd status AssertionError

### ISSUE THREAD

**Issue by reefland** [rook/rook#15222]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Trying to run `ceph osd status` results in `AssertionError`.

**Expected behavior:**

Expected to see status of osds.

**How to reproduce it (minimal and precise):**
```
bash-5.1$ ceph health detail 
HEALTH_OK
```
```
bash-5.1$ ceph -s
  cluster:
    id:     cb82340a-2eaf-4597-b83e-cc0e62a9d019
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum aa,aq,as (age 3d)
    mgr: a(active, since 11d), standbys: b
    mds: 1/1 daemons up, 1 hot standby
    osd: 11 osds: 9 up (since 43h), 9 in (since 42h)
    rgw: 2 daemons active (2 hosts, 1 zones)
 
  data:
    volumes: 1/1 healthy
    pools:   13 pools, 225 pgs
    objects: 124.90k objects, 411 GiB
    usage:   1.1 TiB used, 5.8 TiB / 6.9 TiB avail
    pgs:     225 active+clean
 
  io:
    client:   852 B/s rd, 171 KiB/s wr, 9 op/s rd, 9 op/s wr
 ```
I know I have a node down and 2 OSDs are offline, but I still expected this to work:
```
bash-5.1$ ceph osd status
Error EINVAL: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 1864, in _handle_command
    return CLICommand.COMMANDS[cmd['prefix']].call(self, cmd, inbuf)
  File "/usr/share/ceph/mgr/mgr_module.py", line 499, in call
    return self.func(mgr, **kwargs)
  File "/usr/share/ceph/mgr/status/module.py", line 337, in handle_osd_status
    assert metadata
AssertionError
```

Expected messages in operator log:
```
2024-12-28 17:14:51.957900 I | clusterdisruption-controller: osd is down in failure domain "k3s05". pg health: "all PGs in cluster are clean"
2024-12-28 17:15:22.185870 I | clusterdisruption-controller: osd "rook-ceph-osd-4" is down but no node drain is detected
2024-12-28 17:15:22.185966 I | clusterdisruption-controller: osd "rook-ceph-osd-8" is down but no node drain is detected
2024-12-28 17:15:22.670477 I | clusterdisruption-controller: osd is down in failure domain "k3s05". pg health: "all PGs in cluster are clean"
2024-12-28 17:15:52.910985 I | clusterdisruption-controller: osd "rook-ceph-osd-4" is down but no node drain is detected
2024-12-28 17:15:52.911092 I | clusterdisruption-controller: osd "rook-ceph-osd-8" is down but no node drain is detected
2024-12-28 17:15:53.193231 I | clusterdisruption-controller: osd is down in failure domain "k3s05". pg health: "all PGs in cluster are clean"
2024-12-28 17:16:23.463682 I | clusterdisruption-controller: osd "rook-ceph-osd-4" is down but no node drain is detected
2024-12-28 17:16:23.463794 I | clusterdisruption-controller: osd "rook-ceph-osd-8" is down but no node drain is detected
2024-12-28 17:16:23.869491 I | clusterdisruption-controller: osd is down in failure domain "k3s05". pg health: "all PGs in cluster are clean"
```

* Ceph Version:
```
bash-5.1$ ceph versions
{
    "mon": {
        "ceph version 19.2.0 (16063ff2022298c9300e49a547a16ffda59baf13) squid (stable)": 3
    },
    "mgr": {
        "ceph version 19.2.0 (16063ff2022298c9300e49a547a16ffda59baf13) squid (stable)": 2
    },
    "osd": {
        "ceph version 19.2.0 (16063ff2022298c9300e49a547a16ffda59baf13) squid (stable)": 9
    },
    "mds": {
        "ceph version 19.2.0 (16063ff2022298c9300e49a547a16ffda59baf13) squid (stable)": 2
    },
    "rgw": {
        "ceph version 19.2.0 (16063ff2022298c9300e49a547a16ffda59baf13) squid (stable)": 2
    },
    "overall": {
        "ceph version 19.2.0 (16063ff2022298c9300e49a547a16ffda59baf13) squid (stable)": 18
    }
}
```

**Environment**:
* OS (e.g. from /etc/os-release): `ubuntu 22.04.5`
* Kernel (e.g. `uname -a`):  `5.15.0-106-generic`
* Cloud provider or hardware configuration: `bare metal`
* Rook version (use `rook version` inside of a Rook Pod): `rook-version=v1.15.6`
* Storage backend version (e.g. for ceph do `ceph -v`):  `ceph-version=19.2.0-0`
* Kubernetes version (use `kubectl version`): `v1.30.8+k3s1`
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): `K3S`

**Comment by reefland** [comment]
While `ceph osd status` fails, `ceph osd tree` works:
```
$ ceph osd tree  
ID   CLASS  WEIGHT   TYPE NAME         STATUS  REWEIGHT  PRI-AFF
 -1         8.85074  root default                               
-22         1.36719      host dldsk01                           
  9   nvme  0.68359          osd.9         up   1.00000  1.00000
 10   nvme  0.68359          osd.10        up   1.00000  1.00000
 -5         0.68359      host k3s01                             
  0   nvme  0.68359          osd.0         up   1.00000  1.00000
 -3         0.97659      host k3s02                             
  1   nvme  0.97659          osd.1         up   1.00000  1.00000
 -7         0.68359      host k3s03                             
  2   nvme  0.68359          osd.2         up   1.00000  1.00000
 -9         1.36719      host k3s04                             
  3   nvme  0.68359          osd.3         up   1.00000  1.00000
  7    ssd  0.68359          osd.7         up   1.00000  1.00000
-11         1.95319      host k3s05                             
  8   nvme  0.97659          osd.8       down         0  1.00000
  4    ssd  0.97659          osd.4       down         0  1.00000
-19         1.81940      host k3s06                             
  5    ssd  0.90970          osd.5         up   1.00000  1.00000
  6    ssd  0.90970          osd.6         up   1.00000  1.00000
```

**Comment by reefland** [comment]
After removing the 2 failed OSDs using:
```
$ ceph osd crush remove osd.x
$ ceph osd rm osd.x
$ ceph auth del osd.x
```

It works again:
```
$ ceph osd status
ID  HOST      USED  AVAIL  WR OPS  WR DATA  RD OPS  RD DATA  STATE      
 0  k3s01     153G   546G      5     65.5k      2        0   exists,up  
 1  k3s02     168G   831G      0      204       3        0   exists,up  
 2  k3s03    97.4G   602G      0        0       0        0   exists,up  
 3  k3s04     112G   587G      0        0       3      106   exists,up  
 5  k3s06     122G   809G      0     56.7k      1        0   exists,up  
 6  k3s06     151G   779G      4     28.0k      2       16   exists,up  
 7  k3s04     118G   581G      0     7372       0        0   exists,up  
 9  dldsk01   105G   594G      0     4096       1        0   exists,up  
10  dldsk01   106G   593G      0     4915       0        0   exists,up  
```

**Comment by travisn** [comment]
@reefland Likely a ceph tracker is needed for this assertion. @rzarzynski ?

Do you have metadata devices configured or anything special about your OSDs? That's the only clue I see in the assertion: `assert metadata`:
```
bash-5.1$ ceph osd status
Error EINVAL: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 1864, in _handle_command
    return CLICommand.COMMANDS[cmd['prefix']].call(self, cmd, inbuf)
  File "/usr/share/ceph/mgr/mgr_module.py", line 499, in call
    return self.func(mgr, **kwargs)
  File "/usr/share/ceph/mgr/status/module.py", line 337, in handle_osd_status
    assert metadata
AssertionError
```

**Comment by reefland** [comment]
Nope, no metadata devices or anything special.  As a test I brought down another node and when 2 were down `ceph osd status` broke again, brought the node back up, let the recovery complete and `ceph osd status` worked just as expected.
