### ISSUE TITLE
rook keeps creating osd's forerever

### ISSUE THREAD

**Issue by mmack** [rook/rook#2288]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Operator creates me new osd's every 2 minutes or so
**Expected behavior:**
osd.1 should become active and up again

**How to reproduce it (minimal and precise):**
ok i try to explain everything what happened:

- We have 4 storage nodes (vmware vms's) which have /dev/sdb assined to rook/ceph
- 2 of the storage nodes had they're disk on the same storage pool which went out of space b/c of over-provisioning (don't ask :/).
- So we were left with 2 out of 4 nodes in a failed state.
- After cleaning up the datastore mess and moving the vms to a bigger datastore one node came up, one was in a failed-hd state (fscheck din't help - superblocks destroyed)
- ceph was in ERROR state afterwards, requests blocked...
- I then followed this commands and removed osd.1 (the node with the failed HD) out of the cluster. https://gist.github.com/cheethoe/49d9c1d0003e44423e54a060e0b3fbf1
- Ceph went back green but only with 3 osd's in.
- Since then rook keeps creating a lot of osd's. And osd.1 does not come up again.

**Environment**:
* OS (e.g. from /etc/os-release):
Container Linux by CoreOS 1855.5.0 (Rhyolite)
* Kernel (e.g. `uname -a`): 4.14.74-coreos
* Cloud provider or hardware configuration:
vmware
* Rook version (use `rook version` inside of a Rook Pod):
v0.8.1
* Kubernetes version (use `kubectl version`):
v.11.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
self-provisioned
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/Rook/master/toolbox.html))
```
[root@rook-tools-76b86756f5-sk9sj /]# ceph health
HEALTH_WARN noscrub,nodeep-scrub flag(s) set
[root@rook-tools-76b86756f5-sk9sj /]# ceph status
  cluster:
    id:     458603df-6cc0-4e66-9625-598f3aabfe29
    health: HEALTH_WARN
            noscrub,nodeep-scrub flag(s) set
 
  services:
    mon: 3 daemons, quorum rook-ceph-mon7,rook-ceph-mon8,rook-ceph-mon12
    mgr: a(active)
    osd: 23 osds: 3 up, 3 in
         flags noscrub,nodeep-scrub
 
  data:
    pools:   1 pools, 100 pgs
    objects: 26797 objects, 102381 MB
    usage:   201 GB used, 6024 GB / 6226 GB avail
    pgs:     100 active+clean
 
  io:
    client:   211 kB/s wr, 0 op/s rd, 6 op/s wr
 
[root@rook-tools-76b86756f5-sk9sj /]# ceph osd status
+----+-------------------------------------+-------+-------+--------+---------+--------+---------+------------+
| id |                 host                |  used | avail | wr ops | wr data | rd ops | rd data |   state    |
+----+-------------------------------------+-------+-------+--------+---------+--------+---------+------------+
| 0  | rook-ceph-osd-id-0-76dbcdbf7f-dk85f | 58.1G | 2017G |    0   |  4915   |    1   |     0   | exists,up  |
| 1  |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 2  | rook-ceph-osd-id-2-8649798fd8-4zqsh | 72.1G | 2003G |    0   |  2457   |    1   |     0   | exists,up  |
| 3  | rook-ceph-osd-id-3-7f676bf7b8-lz6zg | 71.5G | 2003G |    0   |     0   |    1   |     0   | exists,up  |
| 4  |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 5  |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 6  |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 7  |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 8  |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 9  |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 10 |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 11 |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 12 |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 13 |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 14 |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 15 |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 16 |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 17 |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 18 |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 19 |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 20 |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 21 |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
| 22 |                                     |    0  |    0  |    0   |     0   |    0   |     0   | exists,new |
+----+-------------------------------------+-------+-------+--------+---------+--------+---------+------------+
[root@rook-tools-76b86756f5-sk9sj /]# 
``` 
I found that stacktrace in the rook-ceph-osd-prepare pod: (node name was the failed host!)
```
2018-11-19 08:45:55.802352 I | op-k8sutil: format and nodeName longer than 63 chars, nodeName k8s-worker-26.lxstage.domain-xyz.com will be f759dfa0164b96e60d106fb59b0cd8b3
2018-11-19 08:45:55.808743 I | exec: Running command: lsblk /dev/sdb --bytes --pairs --output NAME,SIZE,TYPE,PKNAME
2018-11-19 08:45:55.811298 I | exec: Running command: udevadm info --query=property /dev/sdb2
2018-11-19 08:45:55.813509 I | exec: Running command: udevadm info --query=property /dev/sdb3
2018-11-19 08:45:55.815142 I | exec: Running command: udevadm info --query=property /dev/sdb1
2018-11-19 08:45:55.816819 I | sys: rook partition: ROOK-OSD19-DB
2018-11-19 08:45:55.816833 I | sys: rook partition: ROOK-OSD19-BLOCK
2018-11-19 08:45:55.816836 I | sys: rook partition: ROOK-OSD19-WAL
2018-11-19 08:45:55.816841 I | exec: Running command: udevadm info --query=property /dev/sdb
2018-11-19 08:45:55.818448 I | exec: Running command: sgdisk --zap-all /dev/sdb
2018-11-19 08:45:56.859065 I | zap sdb: GPT data structures destroyed! You may now partition the disk using fdisk or
2018-11-19 08:45:56.859087 I | zap sdb: other utilities.
2018-11-19 08:45:56.859411 I | exec: Running command: sgdisk --clear --mbrtogpt /dev/sdb
2018-11-19 08:45:57.886683 I | clear sdb: Creating new GPT entries.
2018-11-19 08:45:57.886707 I | clear sdb: The operation has completed successfully.
2018-11-19 08:45:57.887089 I | exec: Running command: sgdisk --new=1:2048:+1179648 --change-name=1:ROOK-OSD20-WAL --partition-guid=1:cdecb250-9f96-4050-8109-75a39549c537 --new=2:1181696:+41943040 --change-name=2:ROOK-OSD20-DB --partition-guid=2:a39c1ab3-1ac6-4004-9495-1061179a8b70 --largest-new=3 --change-name=3:ROOK-OSD20-BLOCK --partition-guid=3:0f8f10e0-cb17-40c6-a2d3-4fa0be6fb854 --disk-guid=188c60d4-a21d-40c1-8ad6-54377581d413 /dev/sdb
2018-11-19 08:45:58.909066 I | partition sdb: The operation has completed successfully.
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/rook/rook/pkg/operator/k8sutil.(*ConfigMapKVStore).SetValueWithLabels(0xc4203bc850, 0xc4201c0f40, 0x35, 0x122512c, 0x10, 0xc420204c80, 0x260, 0x0, 0x260, 0xc420204c80)
	/home/rook/go/src/github.com/rook/rook/pkg/operator/k8sutil/kvstore.go:85 +0x3b3
github.com/rook/rook/pkg/operator/k8sutil.(*ConfigMapKVStore).SetValue(0xc4203bc850, 0xc4201c0f40, 0x35, 0x122512c, 0x10, 0xc420204c80, 0x260, 0xc4200b8b38, 0xc4202f9570)
	/home/rook/go/src/github.com/rook/rook/pkg/operator/k8sutil/kvstore.go:57 +0x7d
github.com/rook/rook/pkg/operator/ceph/cluster/osd/config.(*PerfScheme).SaveScheme(0xc42053de80, 0xc4203bc850, 0xc4201c0f40, 0x35, 0x1, 0xc4200b8b38)
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/osd/config/scheme.go:137 +0xc4
github.com/rook/rook/pkg/daemon/ceph/osd.partitionOSD(0xc4204f8380, 0xc42016a6c0, 0xc420409b40, 0x3, 0xc42053c301)
	/home/rook/go/src/github.com/rook/rook/pkg/daemon/ceph/osd/device.go:226 +0x465
github.com/rook/rook/pkg/daemon/ceph/osd.formatDevice(0xc4204f8380, 0xc42016a6c0, 0x0, 0xc42004208f, 0x9, 0x240, 0x5000, 0x1400, 0xc4205dd408, 0x1, ...)
	/home/rook/go/src/github.com/rook/rook/pkg/daemon/ceph/osd/device.go:129 +0x289
github.com/rook/rook/pkg/daemon/ceph/osd.(*OsdAgent).prepareOSD(0xc4205ddc58, 0xc4204f8380, 0xc42016a6c0, 0x35, 0x2, 0x2)
	/home/rook/go/src/github.com/rook/rook/pkg/daemon/ceph/osd/agent.go:415 +0x44a
github.com/rook/rook/pkg/daemon/ceph/osd.(*OsdAgent).configureDevices(0xc4205ddc58, 0xc4204f8380, 0xc4200b83f8, 0xc4205dd7e0, 0x1, 0x1, 0x1221f2a, 0xd)
	/home/rook/go/src/github.com/rook/rook/pkg/daemon/ceph/osd/agent.go:169 +0x3b7
github.com/rook/rook/pkg/daemon/ceph/osd.Provision(0xc4204f8380, 0xc4205ddc58, 0x2, 0x1217b18)
	/home/rook/go/src/github.com/rook/rook/pkg/daemon/ceph/osd/daemon.go:111 +0x7f5
github.com/rook/rook/cmd/rook/ceph.prepareOSD(0x1a6ec60, 0x1a9a7b0, 0x0, 0x0, 0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/cmd/rook/ceph/osd.go:222 +0x7d1
github.com/rook/rook/vendor/github.com/spf13/cobra.(*Command).execute(0x1a6ec60, 0x1a9a7b0, 0x0, 0x0, 0x1a6ec60, 0x1a9a7b0)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/spf13/cobra/command.go:698 +0x46d
github.com/rook/rook/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1a6fb40, 0x1a6dd80, 0x1a6ff80, 0x1a6fd60)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/rook/rook/vendor/github.com/spf13/cobra.(*Command).Execute(0x1a6fb40, 0xc4200a4058, 0x0)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/home/rook/go/src/github.com/rook/rook/cmd/rook/main.go:30 +0x36


```

The ceph-osd-id-1 logs:
```
2018-11-19 08:58:08.172853 7f5d7ef3ad80  0 ceph version 12.2.7 (3ec878d1e53e1aeb47a9f619c49d9e7c0aa384d5) luminous (stable), process ceph-osd, pid 28210
2018-11-19 08:58:08.173084 7f5d7ef3ad80 -1 bluestore(/var/lib/rook/osd1/block) _read_bdev_label failed to open /var/lib/rook/osd1/block: (2) No such file or directory
2018-11-19 08:58:08.173129 7f5d7ef3ad80 -1 bluestore(/var/lib/rook/osd1/block) _read_bdev_label failed to open /var/lib/rook/osd1/block: (2) No such file or directory
2018-11-19 08:58:08.173157 7f5d7ef3ad80 -1 bluestore(/var/lib/rook/osd1/block) _read_bdev_label failed to open /var/lib/rook/osd1/block: (2) No such file or directory
2018-11-19 08:58:08.173169 7f5d7ef3ad80 -1 bluestore(/var/lib/rook/osd1/block) _read_bdev_label failed to open /var/lib/rook/osd1/block: (2) No such file or directory
2018-11-19 08:58:08.173084 7f5d7ef3ad80 -1 bluestore(/var/lib/rook/osd1/block) _read_bdev_label failed to open /var/lib/rook/osd1/block: (2) No such file or directory
2018-11-19 08:58:08.173129 7f5d7ef3ad80 -1 bluestore(/var/lib/rook/osd1/block) _read_bdev_label failed to open /var/lib/rook/osd1/block: (2) No such file or directory
2018-11-19 08:58:08.173157 7f5d7ef3ad80 -1 bluestore(/var/lib/rook/osd1/block) _read_bdev_label failed to open /var/lib/rook/osd1/block: (2) No such file or directory
2018-11-19 08:58:08.173169 7f5d7ef3ad80 -1 bluestore(/var/lib/rook/osd1/block) _read_bdev_label failed to open /var/lib/rook/osd1/block: (2) No such file or directory
starting osd.1 at - osd_data /var/lib/rook/osd1 /var/lib/ceph/osd/rook-ceph-1/journal
2018-11-19 08:58:08.175999 7f5d7ef3ad80  0 pidfile_write: ignore empty --pid-file
2018-11-19 08:58:08.203748 7f5d7ef3ad80  0 load: jerasure load: lrc load: isa 
2018-11-19 08:58:08.203850 7f5d7ef3ad80  1 bdev create path /var/lib/rook/osd1/block type kernel
2018-11-19 08:58:08.203862 7f5d7ef3ad80  1 bdev(0x563f42cd8c00 /var/lib/rook/osd1/block) open path /var/lib/rook/osd1/block
2018-11-19 08:58:08.203876 7f5d7ef3ad80 -1 bdev(0x563f42cd8c00 /var/lib/rook/osd1/block) open open got: (2) No such file or directory
2018-11-19 08:58:08.203876 7f5d7ef3ad80 -1 bdev(0x563f42cd8c00 /var/lib/rook/osd1/block) open open got: (2) No such file or directory
2018-11-19 08:58:08.204345 7f5d7ef3ad80 -1 bluestore(/var/lib/rook/osd1/block) _read_bdev_label failed to open /var/lib/rook/osd1/block: (2) No such file or directory
2018-11-19 08:58:08.204345 7f5d7ef3ad80 -1 bluestore(/var/lib/rook/osd1/block) _read_bdev_label failed to open /var/lib/rook/osd1/block: (2) No such file or directory
2018-11-19 08:58:08.204379 7f5d7ef3ad80  1 bdev create path /var/lib/rook/osd1/block type kernel
2018-11-19 08:58:08.204383 7f5d7ef3ad80  1 bdev(0x563f42cdaa00 /var/lib/rook/osd1/block) open path /var/lib/rook/osd1/block
2018-11-19 08:58:08.204388 7f5d7ef3ad80 -1 bdev(0x563f42cdaa00 /var/lib/rook/osd1/block) open open got: (2) No such file or directory
2018-11-19 08:58:08.204395 7f5d7ef3ad80 -1 osd.1 0 OSD:init: unable to mount object store
2018-11-19 08:58:08.204402 7f5d7ef3ad80 -1  ** ERROR: osd init failed: (2) No such file or directory
2018-11-19 08:58:08.204388 7f5d7ef3ad80 -1 bdev(0x563f42cdaa00 /var/lib/rook/osd1/block) open open got: (2) No such file or directory
2018-11-19 08:58:08.204395 7f5d7ef3ad80 -1 osd.1 0 OSD:init: unable to mount object store
2018-11-19 08:58:08.204402 7f5d7ef3ad80 -1  ** ERROR: osd init failed: (2) No such file or directory
```

If you you guys need anything else pls let me know,

Thanks.
Max

**Comment by BlaineEXE** [comment]
I think @travisn would be able to provide much better information here, but it would seem to me that cheethoe's steps to remove the OSD aren't really supportable. The steps manipulate the osd config map that Rook expects to manage itself (unless I am mistaken), and I don't think unexpected behavior after that is entirely surprising.

**Comment by mmack** [comment]
hehe ok :) so maybe the stacktrace can help you guys otherwise just close this issue...

**Comment by BlaineEXE** [comment]
FWIW, during development on an unrelated feature, I was encountering an issue where OSDs were continuously being created while trying to create a directory-based OSD on a read-only partition on my local disk. After a few days of sleeping on it and rereading this issue, I think there may be some behavior exposed here that we can make better. IMO, if an OSD fails to create, retrying the creation later is a reasonable thing to do, but it does seem unreasonable to not try to reuse the OSD id which was previously not created. 

This is definitely a corner case, and I wouldn't think it poses a risk for data loss, so I think the priority of changing this particular behavior will depend on if/how often this behavior manifests. I think the biggest impact Rook can take from this issue is to make sure that documented, safe workflows (whether manual steps or automatic ones) for manually managing problematic OSDs exist.

**Comment by mmack** [comment]
If you need more information or a look on the cluster ping me.

**Comment by BlaineEXE** [comment]
I can repro a situation similar to this one where I have no disks on one of my nodes and where my `dataDirHostPath` is on a btrfs partition, which Ceph does not support. This results in Rook attempting to create OSDs forever, and Ceph reports `33 osds 12 up, 12 in`, though there are only 12 disks available in the cluster.

I think there are pieces at play here:
- I disagree with the design decision that if a node has no disks that the `dataDirHostPath` should be used as an OSD on that node. I would expect that on my node with no disks, Rook should not attempt to create osds.
- The error condition I see here is that when Rook attempts to create my 13th OSD on this partition and fails, it should retry the creation using the same OSD number and not increase osd count indefinitely.

**Comment by BlaineEXE** [comment]
Thanks for the input @immesys. It's on my to-do list, and I hope to have it in master by the Rook's v1.0 release.

**Comment by shaas** [comment]
I am not able to re-produce this issue with v1.0 anymore.

**Comment by travisn** [comment]
Let's reopen if it is hit again...
