### ISSUE TITLE
ceph dashboard pop js load 500 error internal server error

### ISSUE THREAD

**Issue by grayglj** [rook/rook#2404]
ceph dashboard open successful,but the page keep pop-up error message : 500 - Internal Server Error

and i can see the ceph manager pod raise an error as below:

 File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib64/ceph/mgr/dashboard/controllers/summary.py", line 68, in __call__
    'rbd_mirroring': self._rbd_mirroring(),
  File "/usr/lib64/ceph/mgr/dashboard/controllers/summary.py", line 37, in _rbd_mirroring
    _, data = get_daemons_and_pools()
  File "/usr/lib64/ceph/mgr/dashboard/tools.py", line 212, in wrapper
    return rvc.run(fn, args, kwargs)
  File "/usr/lib64/ceph/mgr/dashboard/tools.py", line 194, in run
    raise self.exception
UnboundLocalError: local variable 'mirror_mode' referenced before assignment

rook version: rook/ceph:v0.9.0
ceph version: ceph/ceph:v13.2.2-20181023

**Comment by canadiannomad** [comment]
Same error rook version 0.9.1

**Comment by zdoherty** [comment]
I'm getting this same error, I see the following logged in the mgr pod logs right before the cherrypy error:

```
2019-01-07 02:08:44.253 7fda4be5a700 -1 librbd::api::Mirror: mode_get: failed to retrieve mirror mode: (1) Operation not permitted
```

rook version: rook/ceph:v0.9.1
ceph version: ceph/ceph:v13.2.2-20181206

**Comment by sinqinc** [comment]
Same here 

rook version: rook/ceph:v0.9.1
ceph version: ceph/ceph:v13.2.2-20181206

**Comment by emedina** [comment]
Also facing this issue:

```
rook version: rook/ceph:v0.9.1
ceph version: ceph/ceph:v13.2.2-20181206
```

**Comment by sebastian-philipp** [comment]
Was fixed in Nautilus by me: 

https://github.com/ceph/ceph/commit/dc616c7d724a2580927ff8fb1fbc070d83dd67ef#diff-24e410817ffc0acf57da283811f4aa03R98

Looks like we need to rebase it.

**Comment by sebastian-philipp** [comment]
Do you see a log entry somewhere in the mgr log that says something like `Failed to query mirror settings` ?

**Comment by christianhuening** [comment]
@sebastian-philipp well I have the above posted error. there's this in there:
`PermissionError: [errno 1] error getting mirror mode`

**Comment by sebastian-philipp** [comment]
workaround would be to fix the permission errors. Make sure the dashboard can in fact get the rbd mirror mode.

**Comment by travisn** [comment]
@sebastian-philipp thanks for the insight on the fix. A few questions:
- Any thoughts on why we would be hitting this so frequently in rook? 
- Does it require enabling of the rbd mirroring, or is this just hit by the dashboard even if the rbd mirroring is not configured? 
- Is the fix being backported to mimic?

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp thanks for the insight on the fix. A few questions:
> 
> * Any thoughts on why we would be hitting this so frequently in rook?

I'd guess this is special to Rook. I'd think of a missing permission that prevents the mgr from querying the rbd mirrors. A typical setup shouldn't hit this bug (otherwise we would have caught this earlier) 

> * Does it require enabling of the rbd mirroring, or is this just hit by the dashboard even if the rbd mirroring is not configured?

Nope. It's independent of actually using rbd mirroring. 

> * Is the fix being backported to mimic?

I'd say: yes.

**Comment by sebastian-philipp** [comment]
Has anyone seen this with a Nautilus cluster?

**Comment by sebastian-philipp** [comment]
Refers to http://tracker.ceph.com/issues/37870

**Comment by sebastian-philipp** [comment]
may relate to #2290

**Comment by sebastian-philipp** [comment]
We're now creating the mgr keyring in

https://github.com/rook/rook/pull/2290/files#diff-b0d5f3a5347e173debf150a8677e1248R102

as
```
mon allow profile mgr
mds allow *
osd allow *
```
I don't know, if `mon allow profile mgr` is sufficient for rbd mirroring

**Comment by grayglj** [comment]
> We're now creating the mgr keyring in
> 
> https://github.com/rook/rook/pull/2290/files#diff-b0d5f3a5347e173debf150a8677e1248R102
> 
> as
> 
> ```
> mon allow profile mgr
> mds allow *
> osd allow *
> ```
> I don't know, if `mon allow profile mgr` is sufficient for rbd mirroring

it's work for me, ceph auth caps mgr.a mon 'allow *' osd 'allow *' mds 'allow *' ,thanks very much.

**Comment by jmreicha** [comment]
Just ran into this, what is the fix?  Here's the error I'm seeing repeatedly in the logs.

```
2019-04-16 18:19:57.775 7f64ca8650 -1 librbd::api::Mirror: mode_get: failed to retrieve mirror mode: (1) Operation not permitted
2019-04-16 18:19:57.775 7f64ca8650 -1 librbd::api::Mirror: mode_get: failed to retrieve mirror mode: (1) Operation not permitted
2019-04-16 18:19:57.780 7f64ca8650  0 mgr[dashboard] Failed to query mirror mode replicapool
Traceback (most recent call last):
  File "/usr/lib64/ceph/mgr/dashboard/controllers/rbd_mirroring.py", line 94, in get_pools
    mirror_mode = rbdctx.mirror_mode_get(ioctx)
  File "rbd.pyx", line 1195, in rbd.RBD.mirror_mode_get (/home/jenkins-build/build/workspace/ceph-build/ARCH/arm64/AVAILABLE_ARCH/arm64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/13.2.5/rpm/el7/BUILD/ceph-13.2.5/build/src/pybind/rbd/pyrex/rbd.c:8543)
PermissionError: [errno 1] error getting mirror mode
```

**Comment by sebastian-philipp** [comment]
Looks like the dashboard cannot get the mirror_mode, but it no  longer causes an internal server error. See https://github.com/ceph/ceph/pull/26009
