### ISSUE TITLE
RBAC permissions issue when running ceph-mgr under minikube

### ISSUE THREAD

**Issue by jtlayton** [rook/rook#2683]
When trying to start up a rook cluster under minikube, I hit the following set of backtraces in the mgr when running "ceph orchestrator device ls" from the toolbox. It looks like a problem with RBAC:

```
debug 2019-02-20 18:37:07.827 7fb4e4f07700  0 log_channel(cluster) log [DBG] : pgmap v813: 0 pgs: ; 0 B data, 0 B used, 0 B / 0 B avail
debug 2019-02-20 18:37:09.199 7fb4e5f09700  0 log_channel(audit) log [DBG] : from='client.24131 v1:192.168.133.217:0/4251437209' entity='client.admin' cmd=[{"prefix": "orchestrator device ls", "target": ["mgr", ""]}]: dispatch
debug 2019-02-20 18:37:09.210 7fb4e670a700  1 mgr[rook] Failed to fetch device metadata: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'date': 'Wed, 20 Feb 2019 18:37:09 GMT', 'content-length': '390', 'content-type': 'application/json', 'x-content-type-options': 'nosniff'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:serviceaccount:rook-ceph:rook-ceph-mgr\" cannot list resource \"configmaps\" in API group \"\" in the namespace \"rook-ceph-system\": RBAC: role.rbac.authorization.k8s.io \"rook-ceph-mgr-system\" not found","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}


debug 2019-02-20 18:37:09.216 7fb4e670a700  0 mgr[rook] Completion <read op> threw an exception:
Traceback (most recent call last):
  File "/usr/share/ceph/mgr/rook/module.py", line 172, in wait
    c.execute()
  File "/usr/share/ceph/mgr/rook/module.py", line 57, in execute
    self._result = self.cb()
  File "/usr/share/ceph/mgr/rook/module.py", line 132, in <lambda>
    return RookReadCompletion(lambda: f(*args, **kwargs))
  File "/usr/share/ceph/mgr/rook/module.py", line 307, in get_inventory
    devs = self.rook_cluster.get_discovered_devices(node_list)
  File "/usr/share/ceph/mgr/rook/rook_cluster.py", line 100, in get_discovered_devices
    label_selector=label_selector)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 11854, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 11957, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'date': 'Wed, 20 Feb 2019 18:37:09 GMT', 'content-length': '390', 'content-type': 'application/json', 'x-content-type-options': 'nosniff'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:serviceaccount:rook-ceph:rook-ceph-mgr\" cannot list resource \"configmaps\" in API group \"\" in the namespace \"rook-ceph-system\": RBAC: role.rbac.authorization.k8s.io \"rook-ceph-mgr-system\" not found","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}


debug 2019-02-20 18:37:09.216 7fb4e670a700 -1 mgr handle_command module 'orchestrator_cli' command handler threw exception: [ApiException()]
debug 2019-02-20 18:37:09.218 7fb4e670a700 -1 mgr.server reply reply (22) Invalid argument Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 862, in _handle_command
    return CLICommand.COMMANDS[cmd['prefix']].call(self, cmd, inbuf)
  File "/usr/share/ceph/mgr/mgr_module.py", line 337, in call
    return self.func(mgr, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator_cli/module.py", line 21, in inner
    return func(*args, **kwargs)
  File "/usr/share/ceph/mgr/orchestrator_cli/module.py", line 81, in _list_devices
    self._orchestrator_wait([completion])
  File "/usr/share/ceph/mgr/orchestrator.py", line 845, in _orchestrator_wait
    raise Exception([getattr(c, 'error') for c in completions])
Exception: [ApiException()]
```
Do we need some special setup for this configuration? Or have I deployed minikube in the wrong way?

**Comment by travisn** [comment]
The error makes it look like the `rook-ceph-mgr-system` Role does not exist, which is defined in cluster.yaml [here](https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/ceph/cluster.yaml#L32). Do you see that role and role binding existing?
```
kubectl -n rook-ceph get role
kubectl -n rook-ceph-system get rolebinding
```

**Comment by jtlayton** [comment]
They seem to be present:
```
[jlayton@tleilax ceph]$ kubectl -n rook-ceph get role
NAME                   AGE
rook-ceph-mgr          1h
rook-ceph-mgr-system   1h
rook-ceph-osd          1h
[jlayton@tleilax ceph]$ kubectl -n rook-ceph get rolebinding 
NAME                     AGE
rook-ceph-cluster-mgmt   1h
rook-ceph-mgr            1h
rook-ceph-mgr-cluster    1h
rook-ceph-osd            1h
```

**Comment by jtlayton** [comment]
I wonder if this is wrong:
```
# Aspects of ceph-mgr that require access to the system namespace               
kind: Role                                                                      
apiVersion: rbac.authorization.k8s.io/v1beta1                                   
metadata:                                                                       
  name: rook-ceph-mgr-system                                                    
  namespace: rook-ceph                                                          
rules:                                                                          
- apiGroups:                                                                    
  - ""                                                                          
  resources:                                                                    
  - configmaps                                                                  
  verbs:                                                                        
  - get                                                                         
  - list                                                                        
  - watch                                                                       
```
The namespace in that Role is set to rook-ceph. Shouldn't that be rook-ceph-system? Changing that seems to allow ceph orchestrator device ls to work, but it still fails later when trying to do a get on a node object.

**Comment by travisn** [comment]
The role can be defined in the rook-ceph namespace. It's the namespace in the `RoleBinding` that should matter, which looks like it is already rook-ceph-system.

I believe what's missing is the namespace on the roleRef. Does this work for you?

```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr-system
  namespace: rook-ceph-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rook-ceph-mgr-system
  namespace: rook-ceph
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook-ceph
```

**Comment by jtlayton** [comment]
That didn't seem to work:
```
$ kubectl create -f ./bootstrap.yaml 
namespace "rook-ceph" created
serviceaccount "rook-ceph-osd" created
serviceaccount "rook-ceph-mgr" created
role.rbac.authorization.k8s.io "rook-ceph-osd" created
role.rbac.authorization.k8s.io "rook-ceph-mgr-system" created
role.rbac.authorization.k8s.io "rook-ceph-mgr" created
rolebinding.rbac.authorization.k8s.io "rook-ceph-cluster-mgmt" created
rolebinding.rbac.authorization.k8s.io "rook-ceph-osd" created
rolebinding.rbac.authorization.k8s.io "rook-ceph-mgr" created
error: error validating "./bootstrap.yaml": error validating data: ValidationError(RoleBinding.roleRef): unknown field "namespace" in io.k8s.api.rbac.v1beta1.RoleRef; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by travisn** [comment]
Ok, to reach into the other namespace, looks like we need a ClusterRole instead of Role:

```yaml
# Aspects of ceph-mgr that require access to the system namespace
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr-system
  namespace: rook-ceph
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
# Allow the ceph mgr to access the rook system resources necessary for the mgr modules
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rook-ceph-mgr-system
  namespace: rook-ceph-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-ceph-mgr-system
subjects:
- kind: ServiceAccount
  name: rook-ceph-mgr
  namespace: rook-ceph
```

**Comment by jtlayton** [comment]
This got resolved in this PR: https://github.com/rook/rook/pull/2697
