### ISSUE TITLE
SIGSEGV in etcdmgr queryDiscoveryService

### ISSUE THREAD

**Issue by jbw976** [rook/rook#297]
Just saw this when watching the early logs running `rookd` in a kubernetes cluster:
```
jared@jared-macbook ~/development/castle/go/src/github.com/rook/rook/demo/kubernetes (k8s-troubleshooting)
> kubectl logs rookd-1feba
2016-12-16 00:50:32.366857 I | util: loaded id from data dir
2016-12-16 00:50:32.366999 I | clusterd: Starting cluster. configDir=/var/lib/rook, nodeID=3c462f9df05b, url=https://discovery.etcd.io/bc6c1d333f726a0c36199456a0622460, members=, publicIPv4=10.2.4.6, privateIPv4=10.2.4.6, logLevel=INFO
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x77f69f]

goroutine 1 [running]:
panic(0x2471900, 0xc42000c050)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rook/rook/pkg/etcdmgr/bootstrap.queryDiscoveryService(0xc420191090, 0x47, 0x0, 0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/pkg/etcdmgr/bootstrap/discovery.go:84 +0x1df
github.com/rook/rook/pkg/etcdmgr/bootstrap.getClusterSize(0xc420010064, 0x3a, 0x0, 0x0, 0xc42015b6b8)
	/home/rook/go/src/github.com/rook/rook/pkg/etcdmgr/bootstrap/discovery.go:56 +0x6f
github.com/rook/rook/pkg/etcdmgr/bootstrap.isQuorumFull(0xc420010064, 0x3a, 0x2581030, 0x1, 0xc42015b6b8, 0x4be35c, 0xc42015b6c8, 0xc42015b6c8)
	/home/rook/go/src/github.com/rook/rook/pkg/etcdmgr/bootstrap/discovery.go:37 +0x4d
github.com/rook/rook/pkg/etcdmgr/bootstrap.GetEtcdClients(0x2589250, 0xd, 0xc420010064, 0x3a, 0xc420012033, 0x8, 0xc420153f30, 0xc, 0x2581f01, 0x4, ...)
	/home/rook/go/src/github.com/rook/rook/pkg/etcdmgr/bootstrap/client.go:24 +0x50
github.com/rook/rook/pkg/clusterd.StartJoinCluster(0xc420022730, 0x1, 0x1, 0x2589250, 0xd, 0xc420153f30, 0xc, 0xc420010064, 0x3a, 0x0, ...)
	/home/rook/go/src/github.com/rook/rook/pkg/clusterd/join.go:45 +0x13b4
main.joinCluster(0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/cmd/rookd/main.go:165 +0x994
main.startJoinCluster(0x3200d40, 0xb4b3d80, 0x0, 0x0, 0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/cmd/rookd/main.go:123 +0x154
github.com/rook/rook/vendor/github.com/spf13/cobra.(*Command).execute(0x3200d40, 0xc42000c210, 0x0, 0x0, 0x3200d40, 0xc42000c210)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/spf13/cobra/command.go:599 +0x234
github.com/rook/rook/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x3200d40, 0x3200f60, 0x3200b20, 0x3201180)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/spf13/cobra/command.go:689 +0x367
github.com/rook/rook/vendor/github.com/spf13/cobra.(*Command).Execute(0x3200d40, 0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/home/rook/go/src/github.com/rook/rook/cmd/rookd/main.go:74 +0x36
```

**Comment by bassam** [comment]
would be good to get a crash dump for this and get a backtrace in gdb.

**Comment by jbw976** [comment]
the default stack trace shows this line as the culprit: https://github.com/rook/rook/blob/master/pkg/etcdmgr/bootstrap/discovery.go#L84

I'm betting `resp` is nil, so we nil reference in the logging statement on `resp.StatusCode`

**Comment by jbw976** [comment]
I fixed the SIGSEGV in the logging statement, but that doesn't fix the underlying failure to reach the discovery service and then we still end up SIGSEGV in the `defer resp.Body.Close()` on this line: https://github.com/rook/rook/blob/master/pkg/etcdmgr/bootstrap/discovery.go#L93

We need to be more careful about accessing the resp pointer everywhere in that method and we need to figure out why we can't reach the discovery service.

FWIW, while the pod was in its retry loop below, a manual `curl` attempt from my Mac host during that time worked fine:
```
curl https://discovery.etcd.io/551b1ca85ad3ae481aa7f061b11cdc7f/_config/size
{"action":"get","node":{"key":"/_etcd/registry/551b1ca85ad3ae481aa7f061b11cdc7f/_config/size","value":"1","modifiedIndex":1226750001,"createdIndex":1226750001}}
```

### full logs:
```
kubectl logs -f rookd-amoo6 
2016-12-16 17:16:11.526965 I | util: loaded id from data dir
2016-12-16 17:16:11.527010 I | clusterd: Starting cluster. configDir=/var/lib/rook, nodeID=9a2083972ede, url=https://discovery.etcd.io/551b1ca85ad3ae481aa7f061b11cdc7f, members=, publicIPv4=10.2.42.6, privateIPv4=10.2.42.6, logLevel=INFO
2016-12-16 17:16:16.528354 W | etcdboot: failed to query discovery service on attempt 1/10. resp=<nil>, err=context deadline exceeded
2016-12-16 17:16:22.031248 W | etcdboot: failed to query discovery service on attempt 2/10. resp=<nil>, err=context deadline exceeded
2016-12-16 17:16:28.032967 W | etcdboot: failed to query discovery service on attempt 3/10. resp=<nil>, err=context deadline exceeded
2016-12-16 17:16:34.534739 W | etcdboot: failed to query discovery service on attempt 4/10. resp=<nil>, err=context deadline exceeded
2016-12-16 17:16:41.528607 W | etcdboot: failed to query discovery service on attempt 5/10. resp=<nil>, err=Get https://discovery.etcd.io/551b1ca85ad3ae481aa7f061b11cdc7f/_config/size: dial tcp: lookup discovery.etcd.io on 10.3.0.10:53: dial udp 10.3.0.10:53: i/o timeout
2016-12-16 17:16:49.030486 W | etcdboot: failed to query discovery service on attempt 6/10. resp=<nil>, err=context deadline exceeded
2016-12-16 17:16:57.033017 W | etcdboot: failed to query discovery service on attempt 7/10. resp=<nil>, err=context deadline exceeded
2016-12-16 17:17:05.533914 W | etcdboot: failed to query discovery service on attempt 8/10. resp=<nil>, err=context deadline exceeded
2016-12-16 17:17:14.029918 W | etcdboot: failed to query discovery service on attempt 9/10. resp=<nil>, err=Get https://discovery.etcd.io/551b1ca85ad3ae481aa7f061b11cdc7f/_config/size: dial tcp: lookup discovery.etcd.io on 10.3.0.10:53: dial udp 10.3.0.10:53: i/o timeout
2016-12-16 17:17:23.530562 W | etcdboot: failed to query discovery service on attempt 10/10. resp=<nil>, err=context deadline exceeded
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x782632]

goroutine 1 [running]:
panic(0x2480e80, 0xc42000c050)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/rook/rook/pkg/etcdmgr/bootstrap.queryDiscoveryService(0xc420190ff0, 0x47, 0x0, 0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/pkg/etcdmgr/bootstrap/discovery.go:93 +0x292
github.com/rook/rook/pkg/etcdmgr/bootstrap.getClusterSize(0xc420010064, 0x3a, 0x0, 0x0, 0xc4201596b8)
	/home/rook/go/src/github.com/rook/rook/pkg/etcdmgr/bootstrap/discovery.go:56 +0x6f
github.com/rook/rook/pkg/etcdmgr/bootstrap.isQuorumFull(0xc420010064, 0x3a, 0x25905b0, 0x1, 0xc4201596b8, 0x4c122c, 0xc4201596c8, 0xc4201596c8)
	/home/rook/go/src/github.com/rook/rook/pkg/etcdmgr/bootstrap/discovery.go:37 +0x4d
github.com/rook/rook/pkg/etcdmgr/bootstrap.GetEtcdClients(0x25987d0, 0xd, 0xc420010064, 0x3a, 0xc420012033, 0x9, 0xc420151f30, 0xc, 0x2591481, 0x4, ...)
	/home/rook/go/src/github.com/rook/rook/pkg/etcdmgr/bootstrap/client.go:24 +0x50
github.com/rook/rook/pkg/clusterd.StartJoinCluster(0xc420022720, 0x1, 0x1, 0x25987d0, 0xd, 0xc420151f30, 0xc, 0xc420010064, 0x3a, 0x0, ...)
	/home/rook/go/src/github.com/rook/rook/pkg/clusterd/join.go:45 +0x13b4
main.joinCluster(0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/cmd/rookd/main.go:165 +0x994
main.startJoinCluster(0x3207d40, 0xb4df980, 0x0, 0x0, 0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/cmd/rookd/main.go:123 +0x154
github.com/rook/rook/vendor/github.com/spf13/cobra.(*Command).execute(0x3207d40, 0xc42000c210, 0x0, 0x0, 0x3207d40, 0xc42000c210)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/spf13/cobra/command.go:599 +0x234
github.com/rook/rook/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x3207d40, 0x3207f60, 0x3207b20, 0x3208180)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/spf13/cobra/command.go:689 +0x367
github.com/rook/rook/vendor/github.com/spf13/cobra.(*Command).Execute(0x3207d40, 0x0, 0x0)
	/home/rook/go/src/github.com/rook/rook/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/home/rook/go/src/github.com/rook/rook/cmd/rookd/main.go:74 +0x36
```
