### ISSUE TITLE
Seeing kubelet 1.15.0 crashing in volume_stat_calculator

### ISSUE THREAD

**Issue by dimm0** [rook/rook#3383]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
In kubelet logs see a bunch of:

```
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: E0702 18:32:46.202895   41906 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: goroutine 5465 [running]:
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3991f00, 0x775cdd0)
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: panic(0x3991f00, 0x775cdd0)
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: /usr/local/go/src/runtime/panic.go:522 +0x1b5
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).parsePodVolumeStats(0xc0011773b0, 0xc0009510d0, 0xb, 0xc00279c9c0, 0x0, 0xc0009510d0, 0xb, 0x0, 0x0, 0x0, ...)
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:141 +0x73
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).calcAndStoreStats(0xc0011773b0)
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:125 +0x753
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1.1()
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:65 +0x2a
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0011b13d0)
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0011b13d0, 0xdf8475800, 0x3ff0000000000000, 0xc000cd8d01, 0xc000653560)
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: created by k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1
Jul 02 18:32:46 prp-gpu-5.t2.ucsd.edu kubelet[41906]: /workspace/anago-v1.15.0-rc.1.19+e8462b5b5dc258/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:64 +0x9d
```

Should I submit it to kubernetes or it's something with rook? Is it tested with 1.15?

**Expected behavior:**
No errors

**How to reproduce it (minimal and precise):**
Use with k8s 1.15

**Environment**:
* OS (e.g. from /etc/os-release):
Centos 7.6
* Kernel (e.g. `uname -a`):
Linux prp-gpu-5.t2.ucsd.edu 5.0.10-1.el7.x86_64 #1 SMP Sat May 4 04:59:54 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
1.0.2
* Kubernetes version (use `kubectl version`):
1.15.0
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
The integration tests for the master branch are [passing on 1.15](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/PR-3328/3/pipeline/54) with #3328. I don't see why this would be different in v1.0.2 compared to master. 

Yes I would recommend opening an issue in k8s as this isn't in the rook code path. Perhaps the issues is in the flex driver stats collected by the kubelet?

**Comment by dimm0** [comment]
Ok, closing. Thanks
