### ISSUE TITLE
RuntimeError: could not find osd.0 with fsid

### ISSUE THREAD

**Issue by liuyongqing1** [rook/rook#3693]
yes
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

Server abnormal shutdown，Rook failed to anticipate using an already existing disk，

**Expected behavior:**

Rook should use the previous disk

**How to reproduce it (minimal and precise):**

I don't

**File(s) to submit**:

![image](https://user-images.githubusercontent.com/13477384/63680503-688e9d00-c826-11e9-982e-5eea68bacc98.png)

Normally, only 0,1,2 osd, after three machines abnormally shut down, they came out 3,5,7 and before 0,1,2 reported the following error:

2019-08-26 08:42:25.821521 I | rookcmd: starting Rook v0.9.3 with arguments '/rook/rook ceph osd start -- --foreground --id 0 --osd-uuid e9cf3618-76f3-4ebc-af3a-1d9c42e6d5fe --conf /var/lib/rook/osd0/rook-ceph.config --cluster ceph'
2019-08-26 08:42:25.833585 I | rookcmd: flag values: --help=false, --log-level=INFO, --osd-id=0, --osd-store-type=filestore, --osd-uuid=e9cf3618-76f3-4ebc-af3a-1d9c42e6d5fe
2019-08-26 08:42:25.833593 I | cephmon: parsing mon endpoints:
2019-08-26 08:42:25.833598 W | cephmon: ignoring invalid monitor
2019-08-26 08:42:25.855985 I | exec: Running command: ceph-volume lvm activate --no-systemd --filestore 0 e9cf3618-76f3-4ebc-af3a-1d9c42e6d5fe
2019-08-26 08:42:27.133718 I | -->  RuntimeError: could not find osd.0 with fsid e9cf3618-76f3-4ebc-af3a-1d9c42e6d5fe
failed to activate osd. Failed to complete '': exit status 1.

The new 0 7 osd rook-ceph-osd-prepare uses the directory
![image](https://user-images.githubusercontent.com/13477384/63680693-d89d2300-c826-11e9-85dc-09c5e8443704.png)

We are using this environment in production environment, please help me to see how to recover data。

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): Centos 7.4
* Kernel (e.g. `uname -a`):3.10.0-693.el7.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): rook: v0.9.3
* Storage backend version (e.g. for ceph do `ceph -v`):ceph version 13.2.2
* Kubernetes version (use `kubectl version`):1.9.11
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox] HEALTH_WARN 1 filesystem is degraded; 2 MDSs report slow metadata IOs; 2 osds down; Reduced data availability: 300 pgs inactive; mon a is low on available space(https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by liuyongqing1** [comment]
anybody help？ @travisn

**Comment by stephan2012** [comment]
Facing the same issue after unplanned outage:

```
$ kubectl logs -n rook-ceph rook-ceph-osd-0-5bfd75fdc-7bv4g
2019-11-18 15:09:42.949556 I | rookcmd: starting Rook v1.1.6 with arguments '/rook/rook ceph osd start -- --foreground --id 0 --fsid 7ac3028a-47ca-4a9a-8d67-3688a957c9a0 --cluster ceph --setuser ceph --setgroup ceph --setuser-match-path /var/lib/rook/osd0 --default-log-to-file false --ms-learn-addr-from-peer=false'
2019-11-18 15:09:42.949632 I | rookcmd: flag values: --help=false, --log-flush-frequency=5s, --log-level=INFO, --lv-path=, --operator-image=, --osd-id=0, --osd-store-type=bluestore, --osd-uuid=b2e074f0-de6b-4d68-b542-39372a54510a, --pvc-backed-osd=false, --service-account=
2019-11-18 15:09:42.949639 I | op-mon: parsing mon endpoints: e=172.31.23.51:6789,d=172.31.247.71:6789,f=172.31.124.102:6789
2019-11-18 15:09:43.142517 I | cephcmd: CRUSH location=root=default host=n0206 zone=dc2
2019-11-18 15:09:43.186077 I | cephosd: Successfully updated lvm config file
2019-11-18 15:09:43.188186 I | exec: Running command: stdbuf -oL ceph-volume lvm activate --no-systemd --bluestore 0 b2e074f0-de6b-4d68-b542-39372a54510a
2019-11-18 15:09:47.501827 I | Traceback (most recent call last):
2019-11-18 15:09:47.501868 I |   File "/usr/sbin/ceph-volume", line 9, in <module>
2019-11-18 15:09:47.501874 I |     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
2019-11-18 15:09:47.501878 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 38, in __init__
2019-11-18 15:09:47.501882 I |     self.main(self.argv)
2019-11-18 15:09:47.501885 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
2019-11-18 15:09:47.501889 I |     return f(*a, **kw)
2019-11-18 15:09:47.501893 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 149, in main
2019-11-18 15:09:47.501897 I |     terminal.dispatch(self.mapper, subcommand_args)
2019-11-18 15:09:47.501900 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2019-11-18 15:09:47.501903 I |     instance.main()
2019-11-18 15:09:47.501907 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 40, in main
2019-11-18 15:09:47.501910 I |     terminal.dispatch(self.mapper, self.argv)
2019-11-18 15:09:47.501914 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2019-11-18 15:09:47.501918 I |     instance.main()
2019-11-18 15:09:47.501921 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 341, in main
2019-11-18 15:09:47.501924 I |     self.activate(args)
2019-11-18 15:09:47.501928 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
2019-11-18 15:09:47.501931 I |     return func(*a, **kw)
2019-11-18 15:09:47.501935 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 251, in activate
2019-11-18 15:09:47.505562 I |     raise RuntimeError('could not find osd.%s with fsid %s' % (osd_id, osd_fsid))
2019-11-18 15:09:47.505587 I | RuntimeError: could not find osd.0 with fsid b2e074f0-de6b-4d68-b542-39372a54510a
failed to activate osd. Failed to complete '': exit status 1. 
```

**Comment by stephan2012** [comment]
Looks like LVM information is lost?

```
[0|root@n0204:~]# pvs
  PV         VG   Fmt  Attr PSize   PFree 
  /dev/sda1  vg00 lvm2 a--  <75.00g     0 
  /dev/sdb        lvm2 ---   25.00g 25.00g

[0|root@n0204:~]# lvs
  LV      VG   Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lv_boot vg00 -wi-ao---- 488.00m                                                    
  lv_root vg00 -wi-ao---- <74.52g               
```

There is a Volume Group backup in `/etc/lvm/backup`  available:

```
[0|root@n0204:~]# ll /etc/lvm/backup/
total 8
-rw------- 1 root root 1818 Nov 18 16:48 ceph-4f3eabb7-0d91-4fcd-b848-0a7a87fdf17e
-rw------- 1 root root 1713 Nov 11 14:15 vg00
```

However, restoring it does not really help:

```
[0|root@n0204:~]# vgcfgrestore ceph-4f3eabb7-0d91-4fcd-b848-0a7a87fdf17e
  Restored volume group ceph-4f3eabb7-0d91-4fcd-b848-0a7a87fdf17e

[0|root@n0204:~]# vgs
  VG                                        #PV #LV #SN Attr   VSize   VFree
  ceph-4f3eabb7-0d91-4fcd-b848-0a7a87fdf17e   1   1   0 wz--n-  24.00g    0 
  vg00                                        1   2   0 wz--n- <75.00g    0 

[0|root@n0204:~]# lvs
  LV                                            VG                                        Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  osd-data-2d40367e-e661-4e04-8bfa-e38d7ef2c079 ceph-4f3eabb7-0d91-4fcd-b848-0a7a87fdf17e -wi-------  24.00g                                                    
  lv_boot                                       vg00                                      -wi-ao---- 488.00m                                                    
  lv_root                                       vg00                                      -wi-ao---- <74.52g                   
```

Unfortunately, this does not really help:

```
$ kubectl logs -n rook-ceph rook-ceph-osd-1-766c6685db-h46cv
2019-11-18 15:49:09.928977 I | rookcmd: starting Rook v1.1.6 with arguments '/rook/rook ceph osd start -- --foreground --id 1 --fsid 7ac3028a-47ca-4a9a-8d67-3688a957c9a0 --cluster ceph --setuser ceph --setgroup ceph --setuser-match-path /var/lib/rook/osd1 --default-log-to-file false --ms-learn-addr-from-peer=false'
2019-11-18 15:49:09.929060 I | rookcmd: flag values: --help=false, --log-flush-frequency=5s, --log-level=INFO, --lv-path=, --operator-image=, --osd-id=1, --osd-store-type=bluestore, --osd-uuid=45d2bf5d-41fb-4df1-af55-e0b2e2a25e8f, --pvc-backed-osd=false, --service-account=
2019-11-18 15:49:09.929065 I | op-mon: parsing mon endpoints: d=172.31.247.71:6789,f=172.31.124.102:6789,e=172.31.23.51:6789
2019-11-18 15:49:09.954983 I | cephcmd: CRUSH location=root=default host=n0204 zone=dc1
2019-11-18 15:49:09.956316 I | cephosd: Successfully updated lvm config file
2019-11-18 15:49:09.956337 I | exec: Running command: stdbuf -oL ceph-volume lvm activate --no-systemd --bluestore 1 45d2bf5d-41fb-4df1-af55-e0b2e2a25e8f
2019-11-18 15:49:10.259902 I | Running command: /bin/mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-1
2019-11-18 15:49:10.356001 I | Running command: /usr/sbin/restorecon /var/lib/ceph/osd/ceph-1
2019-11-18 15:49:10.444190 I | Running command: /bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-1
2019-11-18 15:49:10.552554 I | Running command: /bin/ceph-bluestore-tool --cluster=ceph prime-osd-dir --dev /dev/ceph-4f3eabb7-0d91-4fcd-b848-0a7a87fdf17e/osd-data-2d40367e-e661-4e04-8bfa-e38d7ef2c079 --path /var/lib/ceph/osd/ceph-1 --no-mon-config
2019-11-18 15:49:10.740147 I |  stderr: failed to read label for /dev/ceph-4f3eabb7-0d91-4fcd-b848-0a7a87fdf17e/osd-data-2d40367e-e661-4e04-8bfa-e38d7ef2c079: (2) No such file or directory
2019-11-18 15:49:10.745012 I | Traceback (most recent call last):
2019-11-18 15:49:10.745063 I |   File "/usr/sbin/ceph-volume", line 9, in <module>
2019-11-18 15:49:10.745129 I |     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
2019-11-18 15:49:10.745143 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 38, in __init__
2019-11-18 15:49:10.745507 I |     self.main(self.argv)
2019-11-18 15:49:10.745713 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
2019-11-18 15:49:10.746153 I |     return f(*a, **kw)
2019-11-18 15:49:10.746350 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 149, in main
2019-11-18 15:49:10.746510 I |     terminal.dispatch(self.mapper, subcommand_args)
2019-11-18 15:49:10.746705 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2019-11-18 15:49:10.747063 I |     instance.main()
2019-11-18 15:49:10.747242 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 40, in main
2019-11-18 15:49:10.747449 I |     terminal.dispatch(self.mapper, self.argv)
2019-11-18 15:49:10.747665 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2019-11-18 15:49:10.748070 I |     instance.main()
2019-11-18 15:49:10.748088 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 341, in main
2019-11-18 15:49:10.748493 I |     self.activate(args)
2019-11-18 15:49:10.748513 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
2019-11-18 15:49:10.748941 I |     return func(*a, **kw)
2019-11-18 15:49:10.749265 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 265, in activate
2019-11-18 15:49:10.749530 I |     activate_bluestore(lvs, no_systemd=args.no_systemd)
2019-11-18 15:49:10.749720 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 172, in activate_bluestore
2019-11-18 15:49:10.749967 I |     process.run(prime_command)
2019-11-18 15:49:10.750371 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/process.py", line 153, in run
2019-11-18 15:49:10.750496 I |     raise RuntimeError(msg)
2019-11-18 15:49:10.750652 I | RuntimeError: command returned non-zero exit status: 1
failed to activate osd. Failed to complete '': exit status 1. 
```
