### ISSUE TITLE
cannot find osd.12 with fsid x

### ISSUE THREAD

**Issue by bmillemathias-1a** [rook/rook#4547]
Similar to issue #3693 it seems

**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
We found that one of the OSD daemons pod was in constant LoopCrashBackOff since few days, it was working fine before.
The logs entries of the container are
```
2019-12-19 12:00:38.234842 I | rookcmd: starting Rook v1.1.7 with arguments '/rook/rook ceph osd start -- --foreground --id 12 --fsid c415bf0a-e623-4780-9490-c32c3a2914ce --cluster ceph --setuser ceph --setgroup ceph --setuser-match-path /var/lib/rook/osd12 --default-log-to-file false --ms-learn-addr-from-peer=false'
2019-12-19 12:00:38.234960 I | rookcmd: flag values: --help=false, --log-flush-frequency=5s, --log-level=INFO, --lv-path=, --operator-image=, --osd-id=12, --osd-store-type=bluestore, --osd-uuid=b77af586-f542-4658-848f-69c3d48a3f00, --pvc-backed-osd=false, --service-account=
2019-12-19 12:00:38.234966 I | op-mon: parsing mon endpoints: b=10.224.186.251:6789,c=10.224.136.152:6789,d=10.224.143.41:6789,e=10.224.26.0:6789,a=10.224.202.240:6789
2019-12-19 12:00:38.246583 I | cephcmd: CRUSH location=root=default host=bht10312-os-amadeus-net zone=muc-a1
2019-12-19 12:00:38.247995 I | cephosd: Successfully updated lvm config file
2019-12-19 12:00:38.248007 I | exec: Running command: stdbuf -oL ceph-volume lvm activate --no-systemd --bluestore 12 b77af586-f542-4658-848f-69c3d48a3f00
2019-12-19 12:00:38.676221 I | Traceback (most recent call last):
2019-12-19 12:00:38.676280 I |   File "/usr/sbin/ceph-volume", line 9, in <module>
2019-12-19 12:00:38.676286 I |     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
2019-12-19 12:00:38.676289 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 38, in __init__
2019-12-19 12:00:38.676295 I |     self.main(self.argv)
2019-12-19 12:00:38.676299 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
2019-12-19 12:00:38.676302 I |     return f(*a, **kw)
2019-12-19 12:00:38.676305 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 149, in main
2019-12-19 12:00:38.676308 I |     terminal.dispatch(self.mapper, subcommand_args)
2019-12-19 12:00:38.676311 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2019-12-19 12:00:38.676315 I |     instance.main()
2019-12-19 12:00:38.676318 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 40, in main
2019-12-19 12:00:38.676322 I |     terminal.dispatch(self.mapper, self.argv)
2019-12-19 12:00:38.676326 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2019-12-19 12:00:38.676353 I |     instance.main()
2019-12-19 12:00:38.676362 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 341, in main
2019-12-19 12:00:38.676410 I |     self.activate(args)
2019-12-19 12:00:38.676415 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
2019-12-19 12:00:38.676421 I |     return func(*a, **kw)
2019-12-19 12:00:38.676426 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 251, in activate
2019-12-19 12:00:38.676465 I |     raise RuntimeError('could not find osd.%s with fsid %s' % (osd_id, osd_fsid))
2019-12-19 12:00:38.676483 I | RuntimeError: could not find osd.12 with fsid b77af586-f542-4658-848f-69c3d48a3f00
failed to activate osd. Failed to complete '': exit status 1. 
```
we did not find any error at PV / VG / LVM level and the node state is OK, other OSDs on the same node are fine. We use one block device per OSD on bare metal servers.
I don't remember having issue on this node.

**Expected behavior:**
Looking to understand the root cause and fix, possibly inform you about a potential bug ?

**How to reproduce it (minimal and precise):**
Don't know how to reproduce that.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

**Environment**:
* OS (e.g. from /etc/os-release): rhcos 4.2
* Kernel (e.g. `uname -a`): `Linux worker-2.mycorp.co 4.18.0-80.11.2.el8_0.x86_64 #1 SMP Sun Sep 15 11:24:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`
* Cloud provider or hardware configuration: bare metal HP DL 360 class
* Rook version (use `rook version` inside of a Rook Pod): 1.1.7
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.4
* Kubernetes version (use `kubectl version`): "v1.14.0+724e12f93f"
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Openshift 4.2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_WARN Reduced data availability: 1 pg inactive`

**Comment by ghurel-redhat** [comment]
It turned out that the cause was a hardware failure on the bare-metal node (the physical drive is dead).

One remark though:
The following line in the failing osd pod log output is a bit misleading for any ceph rookie:
```
RuntimeError: could not find osd.12 with fsid b77af586-f542-4658-848f-69c3d48a3f00
```
The fsid in this line refers to the osd_fsid, not the ceph cluster fsid.
While in the  config file `/var/lib/rook/osd12/rook-ceph.config` on the  bare-metal node, the fsid field refers to the ceph cluster fsid.

The command `lvs -o lv_tags` was helpul to get the various osd_fsid.

**Comment by mykaul** [comment]
Proposed to clarify the error message via https://github.com/ceph/ceph/pull/32351
