### ISSUE TITLE
Provisioned nodes don't come up after node reboot

### ISSUE THREAD

**Issue by dimm0** [rook/rook#4757]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
After successfully adding a node, I reboot the machine, and OSD doesn't come up with:

```
+ OSD_ID=8
+ OSD_UUID=ad95b483-4524-4804-a27f-0d721d7f07cd
+ OSD_STORE_FLAG=--bluestore
++ mktemp -d
+ TMP_DIR=/tmp/tmp.87rG6I48DZ
+ OSD_DATA_DIR=/var/lib/ceph/osd/ceph-8
+ ceph-volume lvm activate --no-systemd --bluestore 8 ad95b483-4524-4804-a27f-0d721d7f07cd
Running command: /bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-8
Running command: /bin/ceph-bluestore-tool --cluster=ceph prime-osd-dir --dev /dev/ceph-857394a4-b159-4965-aba4-eadcd191c7c4/osd-data-c1238f72-07e1-4a6b-806b-9f2661b72948 --path /var/lib/ceph/osd/ceph-8 --no-mon-config
 stderr: failed to read label for /dev/ceph-857394a4-b159-4965-aba4-eadcd191c7c4/osd-data-c1238f72-07e1-4a6b-806b-9f2661b72948: (2) No such file or directory
 stderr: 2020-01-28 19:53:05.514 7fbcbe0c5c00 -1 bluestore(/dev/ceph-857394a4-b159-4965-aba4-eadcd191c7c4/osd-data-c1238f72-07e1-4a6b-806b-9f2661b72948) _read_bdev_label failed to open /dev/ceph-857394a4-b159-4965-aba4-eadcd191c7c4/osd-data-c1238f72-07e1-4a6b-806b-9f2661b72948: (2) No such file or directory
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 9, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 38, in __init__
    self.main(self.argv)
  File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 149, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 40, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 341, in main
    self.activate(args)
  File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 265, in activate
    activate_bluestore(lvs, no_systemd=args.no_systemd)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 172, in activate_bluestore
    process.run(prime_command)
  File "/usr/lib/python2.7/site-packages/ceph_volume/process.py", line 153, in run
    raise RuntimeError(msg)
RuntimeError: command returned non-zero exit status: 1
```

**Expected behavior:**
Can reboot a node

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod):
1.2.2

**Comment by dimm0** [comment]
I see the LVM on the node:
```
[root@k8s-haosu-09 ~]# pvdisplay
  --- Physical volume ---
  PV Name               /dev/nvme0n1
  VG Name               ceph-857394a4-b159-4965-aba4-eadcd191c7c4
  PV Size               5.82 TiB / not usable <646.34 MiB
  Allocatable           yes (but full)
  PE Size               1.00 GiB
  Total PE              5961
  Free PE               0
  Allocated PE          5961
  PV UUID               qPCfda-qR1X-dD07-6rm2-W2Rq-tT4G-oGE0pe
```

**Comment by dimm0** [comment]
```
[root@k8s-haosu-09 ~]# lvdisplay
  --- Logical volume ---
  LV Path                /dev/ceph-857394a4-b159-4965-aba4-eadcd191c7c4/osd-data-c1238f72-07e1-4a6b-806b-9f2661b72948
  LV Name                osd-data-c1238f72-07e1-4a6b-806b-9f2661b72948
  VG Name                ceph-857394a4-b159-4965-aba4-eadcd191c7c4
  LV UUID                VW1rAQ-3P6K-J0J9-3CUT-biv9-rfbl-87qzo0
  LV Write Access        read/write
  LV Creation host, time rook-ceph-osd-prepare-k8s-haosu-09.sdsc.optiputer.net-mdjbl, 2020-01-28 00:24:52 -0800
  LV Status              available
  # open                 0
  LV Size                5.82 TiB
  Current LE             5961
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     8192
  Block device           253:0
```

**Comment by dimm0** [comment]
Hmm... Looks good after several reboots...
Will look more

**Comment by dimm0** [comment]
Needed lvm2 package installed
