### ISSUE TITLE
Node provision fails

### ISSUE THREAD

**Issue by dimm0** [rook/rook#4761]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Node provision fails most of the time. Prepare log attached.

**Expected behavior:**
Not fails

**File(s) to submit**:

[prepare.log](https://github.com/rook/rook/files/4125498/prepare.log)

**Environment**:
* Rook version (use `rook version` inside of a Rook Pod):
1.2.2
* Kubernetes version (use `kubectl version`):
1.17.1

**Comment by dimm0** [comment]
[ceph-volume.log](https://github.com/rook/rook/files/4125525/ceph-volume.log)

**Comment by travisn** [comment]
The critical issue is the core dump
```
2020-01-28 23:54:45.841837 I | exec: Running command: ceph-volume lvm batch --prepare
2020-01-28 23:55:03.341942 I | cephosd: device nvme0n1 to be configured by ceph-volume
2020-01-28 23:55:03.441843 I | cephosd: 0/0 pre-ceph-volume osd devices succeeded on this node
2020-01-28 23:55:03.641863 I | exec: Running command: ceph auth get-or-create-key client.bootstrap-osd mon allow profile bootstrap-osd --connect-timeout=15 --cluster=rook-haosu --conf=/var/lib/rook/rook-haosu/rook-haosu.config --keyring=/var/lib/rook/rook-haosu/client.admin.keyring --format json --out-file /tmp/833606600
2020-01-28 23:55:41.741896 I | exec: timed out
failed to configure devices: failed to configure devices with ceph-volume: failed to generate osd keyring: failed to get or create auth key for client.bootstrap-osd: failed get-or-create-key client.bootstrap-osd: signal: segmentation fault (core dumped)
```

@leseb any ideas on this one?

**Comment by dimm0** [comment]
It's in dmesg!!

```
[ 1047.810806] ceph[73718]: segfault at 8 ip 00007f23abe5b940 sp 00007f23a418cd28 error 4 in libceph-common.so.0[7f23abb30000+999000]
[ 1047.810812] Code: d0 eb c7 90 66 0f 1f 44 00 00 e9 ab ff ff ff 90 66 2e 0f 1f 84 00 00 00 00 00 48 8d 47 08 c3 90 66 2e 0f 1f 84 00 00 00 00 00 <48> 83 7f 08 00 0f 95 c0 c3 90 66 0f 1f 44 00 00 53 48 89 fb e8 47
[ 1287.506756] ceph[7429]: segfault at 8 ip 00007fa5603d2940 sp 00007fa558703d28 error 4 in libceph-common.so.0[7fa5600a7000+999000]
[ 1287.506770] Code: d0 eb c7 90 66 0f 1f 44 00 00 e9 ab ff ff ff 90 66 2e 0f 1f 84 00 00 00 00 00 48 8d 47 08 c3 90 66 2e 0f 1f 84 00 00 00 00 00 <48> 83 7f 08 00 0f 95 c0 c3 90 66 0f 1f 44 00 00 53 48 89 fb e8 47
[ 1324.308157] perf: interrupt took too long (3132 > 3126), lowering kernel.perf_event_max_sample_rate to 63000
[ 1358.083473] IPv6: ADDRCONF(NETDEV_CHANGE): cali0ec2a45189a: link becomes ready
[ 1525.897943] ceph[23989]: segfault at 8 ip 00007f73d2ca5940 sp 00007f73cafd6d28 error 4 in libceph-common.so.0[7f73d297a000+999000]
[ 1525.897949] Code: d0 eb c7 90 66 0f 1f 44 00 00 e9 ab ff ff ff 90 66 2e 0f 1f 84 00 00 00 00 00 48 8d 47 08 c3 90 66 2e 0f 1f 84 00 00 00 00 00 <48> 83 7f 08 00 0f 95 c0 c3 90 66 0f 1f 44 00 00 53 48 89 fb e8 47
[ 1820.090596] ceph[41923]: segfault at 8 ip 00007f90436ee940 sp 00007f903ba1fd28 error 4 in libceph-common.so.0[7f90433c3000+999000]
[ 1820.090608] Code: d0 eb c7 90 66 0f 1f 44 00 00 e9 ab ff ff ff 90 66 2e 0f 1f 84 00 00 00 00 00 48 8d 47 08 c3 90 66 2e 0f 1f 84 00 00 00 00 00 <48> 83 7f 08 00 0f 95 c0 c3 90 66 0f 1f 44 00 00 53 48 89 fb e8 47
[ 2139.895143] ceph[61255]: segfault at 8 ip 00007fd9d53e2940 sp 00007fd9cd713d28 error 4 in libceph-common.so.0[7fd9d50b7000+999000]
[ 2139.895151] Code: d0 eb c7 90 66 0f 1f 44 00 00 e9 ab ff ff ff 90 66 2e 0f 1f 84 00 00 00 00 00 48 8d 47 08 c3 90 66 2e 0f 1f 84 00 00 00 00 00 <48> 83 7f 08 00 0f 95 c0 c3 90 66 0f 1f 44 00 00 53 48 89 fb e8 47
```

**Comment by leseb** [comment]
ceph version?

**Comment by leseb** [comment]
low memory limits on the prepare job?

**Comment by leseb** [comment]
oh ok

```
[2020-01-28 21:12:29,961][ceph_volume.process][INFO  ] stderr Error EEXIST: entity osd.9 exists but key does not match
[2020-01-28 21:12:29,961][ceph_volume.devices.lvm.prepare][ERROR ] lvm prepare was unable to complete
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/prepare.py", line 219, in safe_prepare
    self.prepare()
  File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/prepare.py", line 259, in prepare
    self.osd_id = prepare_utils.create_id(osd_fsid, json.dumps(secrets), osd_id=self.args.osd_id)
  File "/usr/lib/python2.7/site-packages/ceph_volume/util/prepare.py", line 170, in create_id
    raise RuntimeError('Unable to create a new OSD id')
RuntimeError: Unable to create a new OSD id
[2020-01-28 21:12:30,261][ceph_volume.devices.lvm.prepare][INFO  ] will rollback OSD ID creation
[2020-01-28 21:12:30,262][ceph_volume][ERROR ] exception caught by decorator
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 149, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 40, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 325, in main
    self.execute()
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 288, in execute
    self.strategy.execute()
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py", line 122, in execute
    Prepare(command).main()
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/prepare.py", line 365, in main
    self.safe_prepare(self.args)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/prepare.py", line 219, in safe_prepare
    self.prepare()
  File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/prepare.py", line 259, in prepare
    self.osd_id = prepare_utils.create_id(osd_fsid, json.dumps(secrets), osd_id=self.args.osd_id)
  File "/usr/lib/python2.7/site-packages/ceph_volume/util/prepare.py", line 170, in create_id
    raise RuntimeError('Unable to create a new OSD id')
RuntimeError: Unable to create a new OSD id
```


Looks like this OSD exists already.
So you likely removed the osd.9 but not its key.

Run `ceph auth del osd.9`. That should fix your issue.

**Comment by dimm0** [comment]
Latest Ceph, v14.2.6-20200115

> low memory limits on the prepare job?
Those jobs use around a hundred megabytes, and have limit of 4G. Also I checked all other components, no resource bottlenecks...

I found the osd.9 later and fixed it, still hitting the issue

Have 5 more nodes to provision now :)
