### ISSUE TITLE
Rook prepare pod failed to initialize the device

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#4911]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The prepare pod exit after failure of initializing the device. 

**Expected behavior:**
The prepare pod should succeed. 

**How to reproduce it (minimal and precise):**

Try to scale down a failed osd and recover it.
1). Follow up the to Remove an OSD. ( https://rook.io/docs/rook/v1.2/ceph-osd-mgmt.html )
2). The disk is cleaned up by "Cleaning up a Cluster" (https://rook.io/docs/rook/v1.2/ceph-teardown.html#delete-the-data-on-hosts)
3). Restart the operator. But the osd can't start on this disk. 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
```
2020-02-24 16:37:14.541278 I | op-osd: osd orchestration status for node csto-bcmt-09-worker-01 is failed
2020-02-24 16:37:14.541345 E | op-osd: orchestration for node csto-bcmt-09-worker-01 failed: &{OSDs:[] Status:failed PvcBackedOSD:false Message:failed to configure devices: failed to configure devices with ceph-volume: failed to initialize devices: failed ceph-volume: Failed to complete '': exit status 1. }
2020-02-24 16:37:14.541359 I | op-osd: 6/6 node(s) completed osd provisioning
2020-02-24 16:37:14.541583 E | op-cluster: failed to create cluster in namespace "rook-ceph". failed to start the osds: 1 failures encountered while running osds in namespace rook-ceph: orchestration for node csto-bcmt-09-worker-01 failed: &{OSDs:[] Status:failed PvcBackedOSD:false Message:failed to configure devices: failed to configure devices with ceph-volume: failed to initialize devices: failed ceph-volume: Failed to complete '': exit status 1. }
```
* Crashing pod(s) logs, if necessary
```
2020-02-24 16:36:58.087150 I | sys: Device found - vdg
2020-02-24 16:36:58.087157 I | exec: Running command: udevadm info --query=property /dev/vdg
2020-02-24 16:36:58.089414 I | cephosd: "vdg" found in the desired devices
2020-02-24 16:36:58.089439 I | cephosd: device "vdg" is selected by the device filter/name "vdg"
2020-02-24 16:36:58.103048 I | cephosd: configuring osd devices: {"Entries":{"vdg":{"Data":-1,"Metadata":null,"Config":{"Name":"vdg","OSDsPerDevice":1,"MetadataDevice":"","DatabaseSizeMB":0,"DeviceClass":"","IsFilter":false,"IsDevicePathFilter":false},"LegacyPartitionsFound":false,"PersistentDevicePaths":["/dev/disk/by-id/virtio-60e143dd-6063-4671-b","/dev/disk/by-path/pci-0000:00:0c.0","/dev/disk/by-path/virtio-pci-0000:00:0c.0"]}}}
2020-02-24 16:36:58.103073 I | exec: Running command: ceph-volume lvm batch --prepare
2020-02-24 16:36:59.199424 I | cephosd: device vdg to be configured by ceph-volume
2020-02-24 16:36:59.199451 I | cephosd: 0/0 pre-ceph-volume osd devices succeeded on this node
2020-02-24 16:36:59.210862 I | exec: Running command: ceph auth get-or-create-key client.bootstrap-osd mon allow profile bootstrap-osd --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/301171228
2020-02-24 16:37:00.642664 I | cephosd: Successfully updated lvm config file "/etc/lvm/lvm.conf"
2020-02-24 16:37:00.642757 I | cephosd: configuring new device vdg
2020-02-24 16:37:00.642791 I | cephosd: Base command - stdbuf
2020-02-24 16:37:00.642837 I | cephosd: immediateReportArgs - stdbuf
2020-02-24 16:37:00.642851 I | cephosd: immediateExecuteArgs - [-oL ceph-volume lvm batch --prepare --bluestore --yes --osds-per-device 1 /dev/vdg]
2020-02-24 16:37:00.642878 I | exec: Running command: stdbuf -oL ceph-volume lvm batch --prepare --bluestore --yes --osds-per-device 1 /dev/vdg --report
2020-02-24 16:37:04.712246 I | 
2020-02-24 16:37:04.712310 I | Total OSDs: 1
2020-02-24 16:37:04.712315 I | 
2020-02-24 16:37:04.712318 I |   Type            Path                                                    LV Size         % of device
2020-02-24 16:37:04.712322 I | ----------------------------------------------------------------------------------------------------
2020-02-24 16:37:04.712325 I |   [data]          /dev/vdg                                                9.00 GB         100%
2020-02-24 16:37:04.721956 I | exec: Running command: stdbuf -oL ceph-volume lvm batch --prepare --bluestore --yes --osds-per-device 1 /dev/vdg
2020-02-24 16:37:08.530869 I | Running command: /usr/sbin/vgcreate -s 1G --force --yes ceph-56f6d672-89c3-41d4-87f7-924cf075bbda /dev/vdg
2020-02-24 16:37:08.922782 I |  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will manage logical volume symlinks in device directory.
2020-02-24 16:37:08.923216 I |  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will obtain device list by scanning device directory.
2020-02-24 16:37:09.007884 I |  stdout: Physical volume "/dev/vdg" successfully created.
2020-02-24 16:37:09.055800 I |  stdout: Volume group "ceph-56f6d672-89c3-41d4-87f7-924cf075bbda" successfully created
2020-02-24 16:37:09.480392 I | Running command: /usr/sbin/lvcreate --yes -l 9 -n osd-data-7e21307a-3ed9-4faa-a403-8894937612e0 ceph-56f6d672-89c3-41d4-87f7-924cf075bbda
2020-02-24 16:37:09.879951 I |  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will manage logical volume symlinks in device directory.
2020-02-24 16:37:09.880266 I |  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will obtain device list by scanning device directory.
2020-02-24 16:37:09.905802 I |  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, device-mapper library will manage device nodes in device directory.
2020-02-24 16:37:09.915483 I |  stdout: Logical volume "osd-data-7e21307a-3ed9-4faa-a403-8894937612e0" created.
2020-02-24 16:37:12.959862 I | Running command: /bin/ceph-authtool --gen-print-key
2020-02-24 16:37:13.430058 I | Running command: /bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new 3b528094-beff-4d8a-a92e-b4b1280163ef
2020-02-24 16:37:14.371706 I |  stderr: Error EEXIST: entity osd.3 exists but key does not match
2020-02-24 16:37:14.513439 I | Traceback (most recent call last):
2020-02-24 16:37:14.513693 I |   File "/usr/sbin/ceph-volume", line 9, in <module>
2020-02-24 16:37:14.514006 I |     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
2020-02-24 16:37:14.514252 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 38, in __init__
2020-02-24 16:37:14.514387 I |     self.main(self.argv)
2020-02-24 16:37:14.514459 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
2020-02-24 16:37:14.515322 I |     return f(*a, **kw)
2020-02-24 16:37:14.515391 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 149, in main
2020-02-24 16:37:14.515505 I |     terminal.dispatch(self.mapper, subcommand_args)
2020-02-24 16:37:14.515544 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2020-02-24 16:37:14.515646 I |     instance.main()
2020-02-24 16:37:14.515683 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 40, in main
2020-02-24 16:37:14.515803 I |     terminal.dispatch(self.mapper, self.argv)
2020-02-24 16:37:14.515838 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2020-02-24 16:37:14.515939 I |     instance.main()
2020-02-24 16:37:14.516012 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
2020-02-24 16:37:14.516100 I |     return func(*a, **kw)
2020-02-24 16:37:14.516137 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 325, in main
2020-02-24 16:37:14.516257 I |     self.execute()
2020-02-24 16:37:14.516294 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 288, in execute
2020-02-24 16:37:14.516408 I |     self.strategy.execute()
2020-02-24 16:37:14.516457 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py", line 122, in execute
2020-02-24 16:37:14.516607 I |     Prepare(command).main()
2020-02-24 16:37:14.516661 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/prepare.py", line 365, in main
2020-02-24 16:37:14.516796 I |     self.safe_prepare(self.args)
2020-02-24 16:37:14.516856 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/prepare.py", line 219, in safe_prepare
2020-02-24 16:37:14.517020 I |     self.prepare()
2020-02-24 16:37:14.517175 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
2020-02-24 16:37:14.517251 I |     return func(*a, **kw)
2020-02-24 16:37:14.517304 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/prepare.py", line 259, in prepare
2020-02-24 16:37:14.517416 I |     self.osd_id = prepare_utils.create_id(osd_fsid, json.dumps(secrets), osd_id=self.args.osd_id)
2020-02-24 16:37:14.517458 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/util/prepare.py", line 170, in create_id
2020-02-24 16:37:14.517567 I |     raise RuntimeError('Unable to create a new OSD id')
2020-02-24 16:37:14.517754 I | RuntimeError: Unable to create a new OSD id
failed to configure devices: failed to configure devices with ceph-volume: failed to initialize devices: failed ceph-volume: Failed to complete '': exit status 1. 

```
After the prep pod restarted again, it shows below failure messages.
```
2020-02-24 16:38:43.030570 I | exec: Running command: sgdisk --print /dev/vdg
2020-02-24 16:38:43.033692 I | exec: Running command: udevadm info --query=property /dev/vdg
2020-02-24 16:38:43.036183 I | exec: Running command: lsblk --noheadings --list -o NAME /dev/vdg
2020-02-24 16:38:43.039833 I | exec: Running command: udevadm info --query=property /dev/ceph--56f6d672--89c3--41d4--87f7--924cf075bbda-osd--data--7e21307a--3ed9--4faa--a403--8894937612e0
2020-02-24 16:38:43.042027 W | inventory: failed to get udev info for device "vdg", skipping it. Failed to complete 'udevadm info ceph--56f6d672--89c3--41d4--87f7--924cf075bbda-osd--data--7e21307a--3ed9--4faa--a403--8894937612e0': exit status 4. Unknown device, --name=, --path=, or absolute path in /dev/ or /sys expected.
```

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): centos 7
* Kernel (e.g. `uname -a`): 3.10.0-1062.9.1.el7.x86_64
* Cloud provider or hardware configuration: openstack
* Rook version (use `rook version` inside of a Rook Pod): v1.2.4
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.7-0
* Kubernetes version (use `kubectl version`): v1.15.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Tectonic
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by leseb** [comment]
You likely forgot to remove osd.3, `ceph auth del osd.3`.

**Comment by yanchicago** [comment]
Thanks for quick response. I've found that too. I did "ceph purge" and the osd was removed. But somehow, the auth is leftover.

**Comment by sotmir** [comment]
Thank you @leseb for the solution
