### ISSUE TITLE
Prepare pod is in crashLoopBackOff state if a disk is too small and the operator keeps orchestrating 

### ISSUE THREAD

**Issue by yanchicago** [rook/rook#4996]
**Is this a bug report or feature request?**
* Bug Report
The operator keeps orchestrating when the prepare pod is crashed on a small disk.  

**Deviation from expected behavior:**
The prepare pod crashed unexpectedly. 

**Expected behavior:**
The prepare pod should fail and skip the device and continue to the next device.  

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary
```
1). prepare pod state
rook-ceph-osd-prepare-csto-bcmt-09-worker-01-pg6tb    0/1     CrashLoopBackOff   5          5m38s   192.168.1.128   csto-bcmt-09-worker-01    <none>           <none>
rook-ceph-osd-prepare-csto-bcmt-09-worker-02-b4rfq    0/1     CrashLoopBackOff   5          5m38s   192.168.1.249   csto-bcmt-09-worker-02    <none>           <none>
rook-ceph-osd-prepare-csto-bcmt-09-worker-03-dq6xf    0/1     CrashLoopBackOff   5          5m35s   192.168.1.59    csto-bcmt-09-worker-03    <none>           <none>

2). Failed on device vdd which is 5G
# lsblk | grep vdd
vdd                                                                                                  253:48   0    5G  0 disk 

2). prepare pod crash log

# knc logs rook-ceph-osd-prepare-csto-bcmt-09-worker-01-pg6tb
2020-03-10 15:09:59.517932 I | cephcmd: desired devices to configure osds: [{Name:vdc OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: IsFilter:false} {Name:vde OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: IsFilter:false} {Name:vdd OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: IsFilter:false} {Name:vdk OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: IsFilter:false}]
2020-03-10 15:09:59.520723 I | rookcmd: starting Rook v1.1.7 with arguments '/rook/rook ceph osd provision'
2020-03-10 15:09:59.520750 I | rookcmd: flag values: --cluster-id=a1371ac6-caf0-4acd-ba45-d411812895d2, --data-device-filter=, --data-devices=vdc:1:::,vde:1:::,vdd:1:::,vdk:1:::, --data-directories=, --encrypted-device=false, --force-format=false, --help=false, --location= zone=zone1 region=regionOne, --log-flush-frequency=5s, --log-level=INFO, --metadata-device=, --node-name=csto-bcmt-09-worker-01, --operator-image=, --osd-database-size=0, --osd-journal-size=5120, --osd-store=bluestore, --osd-wal-size=576, --osds-per-device=1, --pvc-backed-osd=false, --service-account=, --topology-aware=true
2020-03-10 15:09:59.520759 I | op-mon: parsing mon endpoints: b=10.254.222.142:6789,c=10.254.163.92:6789,a=10.254.73.208:6789
2020-03-10 15:09:59.534161 I | cephcmd: CRUSH location=root=default host=csto-bcmt-09-worker-01 zone=zone1 region=regionOne
2020-03-10 15:09:59.534178 I | cephcmd: crush location of osd: root=default host=csto-bcmt-09-worker-01 zone=zone1 region=regionOne
2020-03-10 15:09:59.547007 I | cephconfig: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2020-03-10 15:09:59.547159 I | cephconfig: generated admin config in /var/lib/rook/rook-ceph
2020-03-10 15:09:59.547336 I | cephosd: discovering hardware
2020-03-10 15:09:59.547362 I | exec: Running command: lsblk --all --noheadings --list --output KNAME
2020-03-10 15:09:59.554420 I | exec: Running command: lsblk /dev/sr0 --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2020-03-10 15:09:59.557425 W | inventory: skipping device sr0: unsupported diskType rom
2020-03-10 15:09:59.557446 I | exec: Running command: lsblk /dev/vda --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2020-03-10 15:09:59.560318 I | exec: Running command: sgdisk --print /dev/vda
2020-03-10 15:09:59.571038 I | exec: Running command: udevadm info --query=property /dev/vda
2020-03-10 15:09:59.577096 I | exec: Running command: lsblk /dev/vda1 --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2020-03-10 15:09:59.580780 I | exec: Running command: udevadm info --query=property /dev/vda1
2020-03-10 15:09:59.583277 I | exec: Running command: lsblk /dev/vdb --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2020-03-10 15:09:59.586045 I | exec: Running command: sgdisk --print /dev/vdb
2020-03-10 15:09:59.588739 I | exec: Running command: udevadm info --query=property /dev/vdb
2020-03-10 15:09:59.591349 I | exec: Running command: lsblk /dev/vdc --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2020-03-10 15:09:59.594926 I | exec: Running command: sgdisk --print /dev/vdc
2020-03-10 15:09:59.598330 I | exec: Running command: udevadm info --query=property /dev/vdc
2020-03-10 15:09:59.600902 I | exec: Running command: lsblk /dev/dm-0 --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2020-03-10 15:09:59.603662 W | inventory: skipping device dm-0: unsupported diskType lvm
2020-03-10 15:09:59.603685 I | exec: Running command: lsblk /dev/vdd --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2020-03-10 15:09:59.606532 I | exec: Running command: sgdisk --print /dev/vdd
2020-03-10 15:09:59.609708 I | exec: Running command: udevadm info --query=property /dev/vdd
2020-03-10 15:09:59.612196 I | exec: Running command: lsblk /dev/vde --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2020-03-10 15:09:59.619223 I | exec: Running command: sgdisk --print /dev/vde
2020-03-10 15:09:59.622539 I | exec: Running command: udevadm info --query=property /dev/vde
2020-03-10 15:09:59.625057 I | exec: Running command: lsblk /dev/vdf --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2020-03-10 15:09:59.627806 I | exec: Running command: sgdisk --print /dev/vdf
2020-03-10 15:09:59.630454 I | exec: Running command: udevadm info --query=property /dev/vdf
2020-03-10 15:09:59.632887 I | exec: Running command: lsblk /dev/vdg --bytes --nodeps --pairs --output SIZE,ROTA,RO,TYPE,PKNAME
2020-03-10 15:09:59.635701 I | exec: Running command: sgdisk --print /dev/vdg
2020-03-10 15:09:59.638925 I | exec: Running command: udevadm info --query=property /dev/vdg
2020-03-10 15:09:59.641239 I | cephosd: creating and starting the osds
2020-03-10 15:09:59.641258 I | exec: Running command: lsblk /dev/vda --bytes --pairs --output NAME,SIZE,TYPE,PKNAME
2020-03-10 15:09:59.644205 I | sys: Output: NAME="vda" SIZE="107374182400" TYPE="disk" PKNAME=""
NAME="vda1" SIZE="107373116928" TYPE="part" PKNAME="vda"
2020-03-10 15:09:59.644225 I | sys: Device found - vda
2020-03-10 15:09:59.644234 I | exec: Running command: udevadm info --query=property /dev/vda1
2020-03-10 15:09:59.646716 I | sys: non-rook partition: 
2020-03-10 15:09:59.646736 I | exec: Running command: udevadm info --query=property /dev/vda
2020-03-10 15:09:59.649042 I | cephosd: skipping device vda that is in use (not by rook). fs: , ownPartitions: false
2020-03-10 15:09:59.649061 I | exec: Running command: lsblk /dev/vdb --bytes --pairs --output NAME,SIZE,TYPE,PKNAME
2020-03-10 15:09:59.651722 I | sys: Output: NAME="vdb" SIZE="42949672960" TYPE="disk" PKNAME=""
2020-03-10 15:09:59.651743 I | sys: Device found - vdb
2020-03-10 15:09:59.651750 I | exec: Running command: udevadm info --query=property /dev/vdb
2020-03-10 15:09:59.654230 I | cephosd: skipping device vdb that is in use (not by rook). fs: ext4, ownPartitions: true
2020-03-10 15:09:59.654268 I | exec: Running command: lsblk /dev/vdc --bytes --pairs --output NAME,SIZE,TYPE,PKNAME
2020-03-10 15:09:59.657162 I | sys: Output: NAME="vdc" SIZE="37580963840" TYPE="disk" PKNAME=""
NAME="ceph--d448e159--c3d3--4c7f--b45c--d786aaa19ebe-osd--data--8f5f8cdd--d96b--450b--82eb--db8687441635" SIZE="36507222016" TYPE="lvm" PKNAME="vdc"
2020-03-10 15:09:59.657183 I | sys: Device found - vdc
2020-03-10 15:09:59.657194 I | exec: Running command: udevadm info --query=property /dev/vdc
2020-03-10 15:09:59.659557 I | cephosd: skipping device vdc that is in use (not by rook). fs: LVM2_member, ownPartitions: true
2020-03-10 15:09:59.659576 I | exec: Running command: lsblk /dev/vdd --bytes --pairs --output NAME,SIZE,TYPE,PKNAME
2020-03-10 15:09:59.662221 I | sys: Output: NAME="vdd" SIZE="5368709120" TYPE="disk" PKNAME=""
2020-03-10 15:09:59.662244 I | sys: Device found - vdd
2020-03-10 15:09:59.662250 I | exec: Running command: udevadm info --query=property /dev/vdd
2020-03-10 15:09:59.664524 I | cephosd: vdd found in the desired devices
2020-03-10 15:09:59.664548 I | exec: Running command: lsblk /dev/vde --bytes --pairs --output NAME,SIZE,TYPE,PKNAME
2020-03-10 15:09:59.666981 I | sys: Output: NAME="vde" SIZE="2147483648" TYPE="disk" PKNAME=""
2020-03-10 15:09:59.667001 I | sys: Device found - vde
2020-03-10 15:09:59.667007 I | exec: Running command: udevadm info --query=property /dev/vde
2020-03-10 15:09:59.669195 I | cephosd: skipping device vde that is in use (not by rook). fs: ext4, ownPartitions: true
2020-03-10 15:09:59.669211 I | exec: Running command: lsblk /dev/vdf --bytes --pairs --output NAME,SIZE,TYPE,PKNAME
2020-03-10 15:09:59.671858 I | sys: Output: NAME="vdf" SIZE="2147483648" TYPE="disk" PKNAME=""
2020-03-10 15:09:59.671880 I | sys: Device found - vdf
2020-03-10 15:09:59.671888 I | exec: Running command: udevadm info --query=property /dev/vdf
2020-03-10 15:09:59.674204 I | cephosd: skipping device vdf that is in use (not by rook). fs: ext4, ownPartitions: true
2020-03-10 15:09:59.674222 I | exec: Running command: lsblk /dev/vdg --bytes --pairs --output NAME,SIZE,TYPE,PKNAME
2020-03-10 15:09:59.676728 I | sys: Output: NAME="vdg" SIZE="10737418240" TYPE="disk" PKNAME=""
2020-03-10 15:09:59.676752 I | sys: Device found - vdg
2020-03-10 15:09:59.676762 I | exec: Running command: udevadm info --query=property /dev/vdg
2020-03-10 15:09:59.679414 I | cephosd: skipping device vdg that does not match the device filter/list ([{vdc 1  0  false} {vde 1  0  false} {vdd 1  0  false} {vdk 1  0  false}]). <nil>
2020-03-10 15:09:59.692895 I | cephosd: configuring osd devices: {"Entries":{"vdd":{"Data":-1,"Metadata":null,"Config":{"Name":"vdd","OSDsPerDevice":1,"MetadataDevice":"","DatabaseSizeMB":0,"DeviceClass":"","IsFilter":false},"LegacyPartitionsFound":false}}}
2020-03-10 15:09:59.693042 I | exec: Running command: ceph-volume lvm batch --prepare
2020-03-10 15:10:00.688728 I | cephosd: device vdd to be configured by ceph-volume
2020-03-10 15:10:00.688762 I | cephosd: 0/0 pre-ceph-volume osd devices succeeded on this node
2020-03-10 15:10:00.689198 I | exec: Running command: ceph auth get-or-create-key client.bootstrap-osd mon allow profile bootstrap-osd --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/455269811
2020-03-10 15:10:01.196808 I | cephosd: Successfully updated lvm config file
2020-03-10 15:10:01.196853 I | cephosd: configuring new device vdd
2020-03-10 15:10:01.196864 I | cephosd: Base command - stdbuf
2020-03-10 15:10:01.196868 I | cephosd: immediateReportArgs - stdbuf
2020-03-10 15:10:01.196880 I | cephosd: immediateExecuteArgs - [-oL ceph-volume lvm batch --prepare --bluestore --yes --osds-per-device 1 /dev/vdd]
2020-03-10 15:10:01.196896 I | exec: Running command: stdbuf -oL ceph-volume lvm batch --prepare --bluestore --yes --osds-per-device 1 /dev/vdd --report
2020-03-10 15:10:05.036143 I | Traceback (most recent call last):
2020-03-10 15:10:05.036355 I |   File "/usr/sbin/ceph-volume", line 9, in <module>
2020-03-10 15:10:05.036461 I |     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
2020-03-10 15:10:05.036507 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 38, in __init__
2020-03-10 15:10:05.036577 I |     self.main(self.argv)
2020-03-10 15:10:05.036625 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
2020-03-10 15:10:05.036716 I |     return f(*a, **kw)
2020-03-10 15:10:05.036764 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 149, in main
2020-03-10 15:10:05.036860 I |     terminal.dispatch(self.mapper, subcommand_args)
2020-03-10 15:10:05.036909 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2020-03-10 15:10:05.036992 I |     instance.main()
2020-03-10 15:10:05.037032 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 40, in main
2020-03-10 15:10:05.037100 I |     terminal.dispatch(self.mapper, self.argv)
2020-03-10 15:10:05.037144 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2020-03-10 15:10:05.037223 I |     instance.main()
2020-03-10 15:10:05.037290 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
2020-03-10 15:10:05.037369 I |     return func(*a, **kw)
2020-03-10 15:10:05.037414 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 320, in main
2020-03-10 15:10:05.037520 I |     self._get_strategy()
2020-03-10 15:10:05.037566 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 303, in _get_strategy
2020-03-10 15:10:05.037678 I |     self.strategy = strategy.with_auto_devices(self.args, unused_devices)
2020-03-10 15:10:05.037724 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py", line 25, in with_auto_devices
2020-03-10 15:10:05.037795 I |     return cls(args, devices)
2020-03-10 15:10:05.037851 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py", line 20, in __init__
2020-03-10 15:10:05.037921 I |     self.validate_compute()
2020-03-10 15:10:05.037961 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/strategies.py", line 30, in validate_compute
2020-03-10 15:10:05.038064 I |     self.validate()
2020-03-10 15:10:05.038115 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py", line 61, in validate
2020-03-10 15:10:05.038203 I |     self.data_devs, osds_per_device=self.osds_per_device
2020-03-10 15:10:05.038247 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/validators.py", line 15, in minimum_device_size
2020-03-10 15:10:05.038332 I |     raise RuntimeError(msg % (device_size, device.path))
2020-03-10 15:10:05.038434 I | RuntimeError: Unable to use device 4.00 GB /dev/vdd, LVs would be smaller than 5GB
failed to configure devices. failed to configure devices with ceph-volume. failed to initialize devices. failed ceph-volume report. Failed to complete '': exit status 1. 
```
 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): CentOS 7
* Kernel (e.g. `uname -a`): Linux csto-bcmt-09-worker-02 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: openstack
* Rook version (use `rook version` inside of a Rook Pod): v1.1.7
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.4
* Kubernetes version (use `kubectl version`): v1.15.4
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Tectonic
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by leseb** [comment]
The error is pretty self-explanatory. Also, you should consider upgrading to 1.2.X, this error will go away. Thanks.
