### ISSUE TITLE
CephCluster CR is correct but the metadata device is applied incorrectly

### ISSUE THREAD

**Issue by shikhar7** [rook/rook#5300]
**Environment**:
* OS: RHEL 7.7
* Cloud provider or hardware configuration: Openshift
* Rook version: v1.3.1
* Storage backend version: ceph v15.2.0
* Kubernetes version : v1.11+
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):Openshift

When i am trying to use metadatadevice (which was working in rook 1.2.7 with ceph v14.2.8) it is the osd prepare pod is failing and giving the following error.
`2020-04-20 10:44:10.880645 D | exec: Running command: stdbuf -oL ceph-volume lvm batch --prepare --bluestore --yes --dmcrypt --osds-per-device 1 /dev/vdb /dev/vdc --db-devices /dev/vdc --report
2020-04-20 10:44:32.018194 D | exec: Traceback (most recent call last):
2020-04-20 10:44:32.018275 D | exec:   File "/usr/sbin/ceph-volume", line 9, in <module>
2020-04-20 10:44:32.018320 D | exec:     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
2020-04-20 10:44:32.018340 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 39, in __init__
2020-04-20 10:44:32.018355 D | exec:     self.main(self.argv)
2020-04-20 10:44:32.018375 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
2020-04-20 10:44:32.018385 D | exec:     return f(*a, **kw)
2020-04-20 10:44:32.018400 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 150, in main
2020-04-20 10:44:32.018406 D | exec:     terminal.dispatch(self.mapper, subcommand_args)
2020-04-20 10:44:32.018411 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2020-04-20 10:44:32.018417 D | exec:     instance.main()
2020-04-20 10:44:32.018422 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 42, in main
2020-04-20 10:44:32.018428 D | exec:     terminal.dispatch(self.mapper, self.argv)
2020-04-20 10:44:32.018434 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2020-04-20 10:44:32.018458 D | exec:     instance.main()
2020-04-20 10:44:32.018490 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
2020-04-20 10:44:32.018499 D | exec:     return func(*a, **kw)
2020-04-20 10:44:32.018510 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 318, in main
2020-04-20 10:44:32.018532 D | exec:     self._get_explicit_strategy()
2020-04-20 10:44:32.018577 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 329, in _get_explicit_strategy
2020-04-20 10:44:32.018599 D | exec:     self._ensure_disjoint_device_lists()
2020-04-20 10:44:32.018625 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 380, in _ensure_disjoint_device_lists
2020-04-20 10:44:32.018636 D | exec:     raise Exception('Device lists are not disjoint')
2020-04-20 10:44:32.018661 D | exec: Exception: Device lists are not disjoint
failed to configure devices: failed to initialize devices: failed ceph-volume report: exit status 1`

**Comment by xin478** [comment]
me too
`  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: false
    deviceFilter: ^sd[c-d]
    config:
      metadataDevice: "sdb"
      storeType: bluestore`

**Comment by AntonioMeireles** [comment]
same here too :(

**Comment by travisn** [comment]
Looks like the error indicates that the device vdc is being used as both a data device and metadata device. What is your cluster CR? 
```
ceph-volume lvm batch --prepare --bluestore --yes --dmcrypt --osds-per-device 1 /dev/vdb /dev/vdc --db-devices /dev/vdc --report
...
raise Exception('Device lists are not disjoint')
```

@xin478 You also see the error `Device lists are not disjoint`? This should be solvable with different cluster CR settings.

**Comment by AntonioMeireles** [comment]
yes... this one is subtle ...  fwiw snippet bellow seems to **work**
```
 config:
      storeType: bluestore
      osdsPerDevice: '1'
    devices:
      - name: 'sda'
        config:
          metadataDevice: 'sdc'
      - name: 'sdb'
        config:
          metadataDevice: 'sdc'
      - name: 'sdd'
        config:
          metadataDevice: 'sdc'
      - name: 'sde'
        config:
          metadataDevice: 'sdc'
      - name: 'sdf'
        config:
          metadataDevice: 'sdc'
      - name: 'nvme0n1p2'
        config:
          osdsPerDevice: '4' 
```
but compact one (that i had originally)...
```
 config:
      storeType: bluestore
      osdsPerDevice: '1'
      metadataDevice: 'sdc'
    devices:
      - name: 'sda'
      - name: 'sdb'
      - name: 'sdd'
      - name: 'sde'
      - name: 'sdf'
      - name: 'nvme0n1p2'
        config:
          metadataDevice: 
          osdsPerDevice: '4'
```
gives  error that originated this issue. almost midnight here, will try to provide more usefull data tomorrow morning! (@travisn thanks for your quick reply!)

**Comment by xin478** [comment]
@travisn thanks for reply. When I trying to config it like this,

```  
storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: false
    deviceFilter: ^sd[c-d]
    config:
      metadataDevice: "sdb"
      storeType: bluestore
```

I see log in rook-ceph-osd-prepare , as
``` 
2020-04-23 03:33:03.844390 I | rookcmd: starting Rook v1.3.1 with arguments '/rook/rook ceph osd provision'
2020-04-23 03:33:03.844481 I | rookcmd: flag values: --cluster-id=c9fd2b29-847c-11ea-ac6e-4cd98f545a1b, --data-device-filter=^sd[c-d], --data-device-path-filter=, --data-devices=, --encrypted-device=false, --force-format=false, --help=false, --location=, --log-flush-frequency=5s, --log-level=DEBUG, --metadata-device=sdb, --node-name=192.168.21.181, --operator-image=, --osd-database-size=0, --osd-store=, --osd-wal-size=576, --osds-per-device=1, --pvc-backed-osd=false, --service-account=
......
2020-04-23 03:33:49.782178 I | cephosd: configuring osd devices: {"Entries":{"sdb":{"Data":-1,"Metadata":[],"Config":{"Name":"","OSDsPerDevice":0,"MetadataDevice":"","DatabaseSizeMB":0,"DeviceClass":"","IsFilter":false,"IsDevicePathFilter":false},"PersistentDevicePaths":null},"sdc":{"Data":-1,"Metadata":null,"Config":{"Name":"^sd[c-d]","OSDsPerDevice":1,"MetadataDevice":"","DatabaseSizeMB":0,"DeviceClass":"","IsFilter":true,"IsDevicePathFilter":false},"PersistentDevicePaths":["/dev/disk/by-id/scsi-35000c500bcfbac0b","/dev/disk/by-id/wwn-0x5000c500bcfbac0b","/dev/disk/by-path/pci-0000:02:00.0-scsi-0:0:4:0"]},"sdd":{"Data":-1,"Metadata":null,"Config":{"Name":"^sd[c-d]","OSDsPerDevice":1,"MetadataDevice":"","DatabaseSizeMB":0,"DeviceClass":"","IsFilter":true,"IsDevicePathFilter":false},"PersistentDevicePaths":["/dev/disk/by-id/scsi-35000c500bcfb3d97","/dev/disk/by-id/wwn-0x5000c500bcfb3d97","/dev/disk/by-path/pci-0000:02:00.0-scsi-0:0:5:0"]}}}
......
2020-04-23 03:33:49.782849 D | exec: Running command: ceph auth get-or-create-key client.bootstrap-osd mon allow profile bootstrap-osd --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/054025927
2020-04-23 03:33:50.448788 I | cephosd: configuring new device sdb
2020-04-23 03:33:50.448819 I | cephosd: using sdb as metadataDevice for device /dev/sdb and let ceph-volume lvm batch decide how to create volumes
2020-04-23 03:33:50.448830 I | cephosd: configuring new device sdc
2020-04-23 03:33:50.448839 I | cephosd: using sdb as metadataDevice for device /dev/sdc and let ceph-volume lvm batch decide how to create volumes
2020-04-23 03:33:50.448853 I | cephosd: configuring new device sdd
2020-04-23 03:33:50.448861 I | cephosd: using sdb as metadataDevice for device /dev/sdd and let ceph-volume lvm batch decide how to create volumes
2020-04-23 03:33:50.448880 D | exec: Running command: stdbuf -oL ceph-volume lvm batch --prepare --bluestore --yes --osds-per-device 1 /dev/sdb /dev/sdc /dev/sdd --db-devices /dev/sdb --report
2020-04-23 03:34:13.719689 D | exec: Traceback (most recent call last):
2020-04-23 03:34:13.719747 D | exec:   File "/usr/sbin/ceph-volume", line 9, in <module>
2020-04-23 03:34:13.719754 D | exec:     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
2020-04-23 03:34:13.719763 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 39, in __init__
2020-04-23 03:34:13.719768 D | exec:     self.main(self.argv)
2020-04-23 03:34:13.719772 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
2020-04-23 03:34:13.719777 D | exec:     return f(*a, **kw)
2020-04-23 03:34:13.719782 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 150, in main
2020-04-23 03:34:13.719789 D | exec:     terminal.dispatch(self.mapper, subcommand_args)
2020-04-23 03:34:13.719793 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2020-04-23 03:34:13.719807 D | exec:     instance.main()
2020-04-23 03:34:13.719817 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 42, in main
2020-04-23 03:34:13.719828 D | exec:     terminal.dispatch(self.mapper, self.argv)
2020-04-23 03:34:13.719835 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2020-04-23 03:34:13.719898 D | exec:     instance.main()
2020-04-23 03:34:13.719915 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
2020-04-23 03:34:13.719923 D | exec:     return func(*a, **kw)
2020-04-23 03:34:13.719929 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 318, in main
2020-04-23 03:34:13.719973 D | exec:     self._get_explicit_strategy()
2020-04-23 03:34:13.719982 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 329, in _get_explicit_strategy
2020-04-23 03:34:13.720045 D | exec:     self._ensure_disjoint_device_lists()
2020-04-23 03:34:13.720054 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 380, in _ensure_disjoint_device_lists
2020-04-23 03:34:13.722255 D | exec:     raise Exception('Device lists are not disjoint')
2020-04-23 03:34:13.722285 D | exec: Exception: Device lists are not disjoint
failed to configure devices: failed to initialize devices: failed ceph-volume report: exit status 1

```

**Comment by shikhar7** [comment]
@travisn I am also seeing the same issue with same config as @xin478 .
