### ISSUE TITLE
rook-edgefs-mgr fails to start due to EAFNOSUPPORT

### ISSUE THREAD

**Issue by dmittendorf** [rook/rook#5323]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The `rook-edgefs-mgr` container within the `rook-edgefs-mgr` fails to start on a new install.

**Expected behavior:**
The `rook-edgefs-mgr` container starts successfully.

**How to reproduce it (minimal and precise):**
- Install version 1.2 .27 of rook-edgefs
- Deploy new Cluster

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```
apiVersion: edgefs.rook.io/v1
kind: Cluster
metadata:
  name: rook-edgefs
  namespace: rook-edgefs
spec:
  edgefsImageName: edgefs/edgefs:1.2.170
  serviceAccount: rook-edgefs-cluster
  dataDirHostPath: /var/lib/edgefs
  storage: # cluster level storage configuration and selection
    useAllNodes: true
    useAllDevices: true
```

* Operator's logs, if necessary
```
2020-04-23 18:55:05.183863 I | edgefs-op-cluster: new cluster rook-edgefs added to namespace rook-edgefs
2020-04-23 18:55:05.183993 I | edgefs-op-cluster: starting cluster in namespace rook-edgefs
2020-04-23 18:55:11.222861 W | edgefs-op-cluster: UseAllNodes prevents future cluster changes! Specify nodes to deploy via `nodes:` collection.
2020-04-23 18:55:11.228906 I | edgefs-op-cluster: DevicesResurrect options: {NeedToResurrect:false NeedToZap:false NeedToWait:false SlaveContainers:0}
2020-04-23 18:55:11.240589 I | edgefs-op-cluster: [worker1.mydomain.com] available devices: 
2020-04-23 18:55:11.240636 I | edgefs-op-cluster: 	Name: sdb, Size: 1000.0 GiB, Type: disk, Rotational: true, Empty: true
2020-04-23 18:55:11.250079 I | op-k8sutil: format and nodeName longer than 63 chars, nodeName worker1.mydomain.com will be 288164d267f5496ec6125ca229180368
2020-04-23 18:55:11.602789 I | edgefs-op-cluster: [worker1.mydomain.com] selected devices: 
2020-04-23 18:55:11.602827 I | edgefs-op-cluster: 	Name: sdb, Type: HDD, Size: 1000.0 GiB
2020-04-23 18:55:11.602981 I | edgefs-op-target: MaxContainerCapacity: 132.0 TiB, TotalCapacity: 1000.0 GiB
2020-04-23 18:55:12.200289 I | edgefs-op-cluster: [worker2.mydomain.com] available devices: 
2020-04-23 18:55:12.200337 I | edgefs-op-cluster: 	Name: sdb, Size: 1000.0 GiB, Type: disk, Rotational: true, Empty: true
2020-04-23 18:55:12.800945 I | op-k8sutil: format and nodeName longer than 63 chars, nodeName worker2.mydomain.com will be a8f9a8e05387af0557dc43cd9e62ff21
2020-04-23 18:55:13.204896 I | edgefs-op-cluster: [worker2.mydomain.com] selected devices: 
2020-04-23 18:55:13.204938 I | edgefs-op-cluster: 	Name: sdb, Type: HDD, Size: 1000.0 GiB
2020-04-23 18:55:13.204999 I | edgefs-op-target: MaxContainerCapacity: 132.0 TiB, TotalCapacity: 1000.0 GiB
2020-04-23 18:55:13.805682 I | edgefs-op-cluster: [worker3.mydomain.com] available devices: 
2020-04-23 18:55:13.805724 I | edgefs-op-cluster: 	Name: sdb, Size: 1000.0 GiB, Type: disk, Rotational: true, Empty: true
2020-04-23 18:55:14.401575 I | op-k8sutil: format and nodeName longer than 63 chars, nodeName worker3.mydomain.com will be 5d42557807d1be8d87e0720269ed6e32
2020-04-23 18:55:14.805328 I | edgefs-op-cluster: [worker3.mydomain.com] selected devices: 
2020-04-23 18:55:14.805376 I | edgefs-op-cluster: 	Name: sdb, Type: HDD, Size: 1000.0 GiB
2020-04-23 18:55:14.805422 I | edgefs-op-target: MaxContainerCapacity: 132.0 TiB, TotalCapacity: 1000.0 GiB
2020-04-23 18:55:14.805554 I | edgefs-op-cluster: [rook-edgefs] DeploymentConfig: 
2020-04-23 18:55:14.805566 I | edgefs-op-cluster: DeploymentType: rtrd
2020-04-23 18:55:14.805572 I | edgefs-op-cluster: TransportKey: rtrd
2020-04-23 18:55:14.805580 I | edgefs-op-cluster: Directories: []
2020-04-23 18:55:14.805588 I | edgefs-op-cluster: NeedPrivileges: true
2020-04-23 18:55:14.805597 I | edgefs-op-cluster: 	Node [worker1.mydomain.com] devices:
2020-04-23 18:55:14.805616 I | edgefs-op-cluster: 		Container[0] Device: /dev/sdb, Name: scsi-0QEMU_QEMU_HARDDISK_017b3cec-263e-4360-b, Journal: 
2020-04-23 18:55:14.805632 I | edgefs-op-cluster: 	Node [worker2.mydomain.com] devices:
2020-04-23 18:55:14.805641 I | edgefs-op-cluster: 		Container[0] Device: /dev/sdb, Name: scsi-0QEMU_QEMU_HARDDISK_c9960f58-2761-44cd-a, Journal: 
2020-04-23 18:55:14.805648 I | edgefs-op-cluster: 	Node [worker3.mydomain.com] devices:
2020-04-23 18:55:14.805656 I | edgefs-op-cluster: 		Container[0] Device: /dev/sdb, Name: scsi-0QEMU_QEMU_HARDDISK_3fdb33e4-d5a5-44c0-b, Journal: 
2020-04-23 18:55:14.805665 I | edgefs-op-cluster: Labeling host `worker1.mydomain.com` as [rook-edgefs] cluster's target node
2020-04-23 18:55:15.010280 I | edgefs-op-cluster: Labeling host `worker2.mydomain.com` as [rook-edgefs] cluster's target node
2020-04-23 18:55:15.208915 I | edgefs-op-cluster: Labeling host `worker3.mydomain.com` as [rook-edgefs] cluster's target node
2020-04-23 18:55:15.604652 I | edgefs-op-prepare: start running prepare pods
2020-04-23 18:55:15.613653 I | edgefs-op-prepare: host-prepare job started
2020-04-23 18:55:40.295206 I | edgefs-op-prepare: Job host-prepare-worker1.mydomain.com reported complete
2020-04-23 18:55:40.304775 I | edgefs-op-prepare: Deleted job host-prepare-worker1.mydomain.com
2020-04-23 18:55:40.304805 I | edgefs-op-prepare: start running prepare pods
2020-04-23 18:55:40.324015 I | edgefs-op-prepare: host-prepare job started
2020-04-23 18:55:56.917911 I | edgefs-op-prepare: Job host-prepare-worker2.mydomain.com reported complete
2020-04-23 18:55:56.929187 I | edgefs-op-prepare: Deleted job host-prepare-worker2.mydomain.com
2020-04-23 18:55:56.929228 I | edgefs-op-prepare: start running prepare pods
2020-04-23 18:55:56.939644 I | edgefs-op-prepare: host-prepare job started
2020-04-23 18:56:16.296750 I | edgefs-op-prepare: Job host-prepare-worker3.mydomain.com reported complete
2020-04-23 18:56:16.308222 I | edgefs-op-prepare: Deleted job host-prepare-worker3.mydomain.com
2020-04-23 18:56:16.331891 I | edgefs-op-target: start running targets in namespace rook-edgefs
2020-04-23 18:56:16.331922 I | edgefs-op-target: Target Image is edgefs/edgefs:1.2.170
2020-04-23 18:56:16.341873 I | edgefs-op-target: headless service rook-edgefs-target started in namespace rook-edgefs
2020-04-23 18:56:16.353378 I | edgefs-op-target: stateful set rook-edgefs-target created in namespace rook-edgefs
2020-04-23 18:56:16.353465 I | edgefs-op-mgr: start running mgr
2020-04-23 18:56:16.353476 I | edgefs-op-mgr: Mgr Image is edgefs/edgefs:1.2.170
2020-04-23 18:56:16.367318 I | edgefs-op-mgr: rook-edgefs-mgr deployment started
2020-04-23 18:56:16.452338 I | edgefs-op-mgr: mgr service started
2020-04-23 18:56:16.512770 I | edgefs-op-mgr: restapi service started
2020-04-23 18:56:16.565099 I | edgefs-op-mgr: ui service started
2020-04-23 18:56:16.565126 I | edgefs-op-cluster: Done creating [rook-edgefs] Edgefs cluster instance
2020-04-23 18:56:16.588428 I | edgefs-op-cluster: succeeded creating and initializing EdgeFS cluster in namespace rook-edgefs
2020-04-23 18:56:16.588475 I | edgefs-op-nfs: start watching nfs resources in namespace rook-edgefs
2020-04-23 18:56:16.588501 I | edgefs-op-s3: start watching s3 resources in namespace rook-edgefs
2020-04-23 18:56:16.588514 I | edgefs-op-swift: start watching swift resources in namespace rook-edgefs
2020-04-23 18:56:16.588534 I | edgefs-op-s3x: start watching s3x resources in namespace rook-edgefs
2020-04-23 18:56:16.588545 I | edgefs-op-iscsi: start watching iscsi resources in namespace rook-edgefs
2020-04-23 18:56:16.588577 I | edgefs-op-isgw: start watching isgw resources in namespace rook-edgefs
```

* Crashing pod(s) logs, if necessary

```
Running in container
Populating /opt/nedge/etc from /opt/nedge/etc.target
Configured /opt/nedge/etc/ccow/ccow.json
Broker configuration adjusted.
Starting mgmt in foreground.
Thu, 23 Apr 2020 19:28:31 GMT info REST API backends to process: 11
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Auth API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Cluster API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: iSCSI Target API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Msite API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: NFS API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Service API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Swagger spec
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Sysconfig API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: System API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Tenant API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: REST testing API
Thu, 23 Apr 2020 19:28:31 GMT info Prometheus exporter listening on 0.0.0.0:8881/metrics
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Job API
Thu, 23 Apr 2020 19:28:31 GMT info REST HTTPS server successfully configured.
Thu, 23 Apr 2020 19:28:31 GMT info REST API backends to process: 11
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Auth API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Cluster API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: iSCSI Target API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Msite API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: NFS API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Service API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Swagger spec
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Sysconfig API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: System API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Tenant API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: REST testing API
Thu, 23 Apr 2020 19:28:31 GMT info Loading API for backend: Job API

Error: listen EAFNOSUPPORT
    at errnoException (net.js:911:11)
    at Server._listen2 (net.js:1030:19)
    at listen (net.js:1071:10)
    at net.js:1153:9
    at dns.js:72:18
    at process._tickCallback (node.js:458:13)
```

**Environment**:
* OS (e.g. from /etc/os-release): 
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration: 
* Rook version (use `rook version` inside of a Rook Pod): 1.2.27
* Storage backend version (e.g. for ceph do `ceph -v`):  edgefs 1.2.170
* Kubernetes version (use `kubectl version`): 1.18.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by dyusupov** [comment]
Could you try with edgefs/edgefs:1.3.22 image?

**Comment by bnason** [comment]
I've also having this issue. I'm using 1.3.35 for the edgefs image tag. I tried 1.3.22 as well and it had the same result
