### ISSUE TITLE
OSD's not starting with Ceph 15.2.x

### ISSUE THREAD

**Issue by Techinica** [rook/rook#5389]
**Is this a bug report or feature request?**
* Bug Report
This is probably a ceph container issue, but not sure where to open an issue if that's the case.

**Deviation from expected behavior:**
OSD's not starting, activate container is failing.

`
+ OSD_ID=40
+ OSD_UUID=e8023d7c-0c31-45e8-b4a6-b9d3bb4820f0
+ OSD_STORE_FLAG=--bluestore
+ OSD_DATA_DIR=/var/lib/ceph/osd/ceph-40
+ CV_MODE=lvm
+ DEVICE=
+ METADATA_DEVICE=
+ [[ lvm == \l\v\m ]]
++ mktemp -d
+ TMP_DIR=/tmp/tmp.x7dcehCwXz
+ ceph-volume lvm activate --no-systemd --bluestore 40 e8023d7c-0c31-45e8-b4a6-b9d3bb4820f0
exception caught by decorator
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 113, in main
    description=self.help(),
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 46, in help
    ceph_path=self.stat_ceph_conf(),
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 82, in stat_ceph_conf
    configuration.load(conf.path)
  File "/usr/lib/python3.6/site-packages/ceph_volume/configuration.py", line 59, in load
    parser.read_conf(trimmed_conf)
  File "/usr/lib/python3.6/site-packages/ceph_volume/configuration.py", line 227, in read_conf
    self.read_file(conffile)
  File "/usr/lib64/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.6/site-packages/ceph_volume/configuration.py", line 145, in _read
    line = fp.readline()
  File "/usr/lib/python3.6/site-packages/ceph_volume/configuration.py", line 33, in readline
    line = self.fp.readline()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 29: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 39, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 113, in main
    description=self.help(),
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 46, in help
    ceph_path=self.stat_ceph_conf(),
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 82, in stat_ceph_conf
    configuration.load(conf.path)
  File "/usr/lib/python3.6/site-packages/ceph_volume/configuration.py", line 59, in load
    parser.read_conf(trimmed_conf)
  File "/usr/lib/python3.6/site-packages/ceph_volume/configuration.py", line 227, in read_conf
    self.read_file(conffile)
  File "/usr/lib64/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.6/site-packages/ceph_volume/configuration.py", line 145, in _read
    line = fp.readline()
  File "/usr/lib/python3.6/site-packages/ceph_volume/configuration.py", line 33, in readline
    line = self.fp.readline()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 29: ordinal not in range(128)
`

After some digging I found this was due to the locale in the container being set to POSIX instead of UTF-8.

As a work-around (probably not the best way thought) I edited the deployments of the OSD's, modifying the activate container's command to include:

yum -y install glibc-locale-source glibc-langpack-en
mkdir -p  /usr/lib/locale/
localedef -c -f UTF-8 -i en_US en_US.UTF-8
source ~/.bashrc

**Expected behavior:**
OSD's should start

**How to reproduce it (minimal and precise):**
Upgraded from 14.2.8 to 15.2.1, also tried 15.2.0 with the same result.

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 19.10
* Kernel (e.g. `uname -a`): 5.3.0-46-generic 
* Rook version (use `rook version` inside of a Rook Pod): 1.3.2
* Storage backend version (e.g. for ceph do `ceph -v`): 1.5.21
* Kubernetes version (use `kubectl version`): 1.17.4

**Comment by leseb** [comment]
Which container image are you using?

**Comment by Techinica** [comment]
image: ceph/ceph:v15.2.1

**Comment by leseb** [comment]
@dsavineau thoughts on this lang issue?

**Comment by dsavineau** [comment]
This remains me https://github.com/ceph/ceph-ansible/commit/7e5e4229b794c354d9cc7a5951f00356ea3418c4 but I'm surprise that the issue wasn't present on nautilus first.

**Comment by Techinica** [comment]
For the sake of testing, I tried adding the PYTHONIOENCODING: utf-8 environment variable to the activiate container on one of my OSD's instead of the above-mentioned work-around. It wasn't sufficient.

This also illustrates the POSIX problem.

`$ docker run ceph/ceph:v15.2.1 locale
Unable to find image 'ceph/ceph:v15.2.1' locally  
v15.2.1: Pulling from ceph/ceph  
8a29a15cefae: Pull complete   
c333427cf577: Pull complete  
Digest: sha256:37ec86e35b4c8858cf7a804cfb116da512786a3994f17f2c544e075e96e6c751
Status: Downloaded newer image for ceph/ceph:v15.2.1  
LANG=  
LC_CTYPE="POSIX"  
LC_NUMERIC="POSIX"  
LC_TIME="POSIX"  
LC_COLLATE="POSIX"  
LC_MONETARY="POSIX"  
LC_MESSAGES="POSIX"  
LC_PAPER="POSIX"  
LC_NAME="POSIX"  
LC_ADDRESS="POSIX"  
LC_TELEPHONE="POSIX"  
LC_MEASUREMENT="POSIX"  
LC_IDENTIFICATION="POSIX"  
LC_ALL=  
`
