### ISSUE TITLE
Upgrade fails from 1.2.7 to 1.3.X: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by TeroPihlaja** [rook/rook#5498]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference) 

**Expected behavior:**
Operator doesn't crash and starts upgrade process

**How to reproduce it (minimal and precise):**
Not sure how to reproduce. I can reproduce it by trying upgrade from 1.2.7 to 1.3.0 or 1.3.3.

**File(s) to submit**:
```
2020-05-18 09:39:29.892669 I | rookcmd: starting Rook v1.3.0 with arguments '/usr/local/bin/rook ceph operator' 
2020-05-18 09:39:29.892920 I | rookcmd: flag values: --add_dir_header=false, --alsologtostderr=false, --csi-cephfs-plugin-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin.yaml, --csi-cephfs-provisioner-dep-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin-provisioner-dep.yaml, --csi-cephfs-provisioner-sts-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin-provisioner-sts.yaml, --csi-rbd-plugin-template-path=/etc/ceph-csi/rbd/csi-rbdplugin.yaml, --csi-rbd-provisioner-dep-template-path=/etc/ceph-csi/rbd/csi-rbdplugin-provisioner-dep.yaml, --csi-rbd-provisioner-sts-template-path=/etc/ceph-csi/rbd/csi-rbdplugin-provisioner-sts.yaml, --enable-discovery-daemon=true, --enable-flex-driver=false, --enable-machine-disruption-budget=false, --help=false, --kubeconfig=, --log-flush-frequency=5s, --log-level=INFO, --log_backtrace_at=:0, --log_dir=, --log_file=, --log_file_max_size=1800, --logtostderr=true, --master=, --mon-healthcheck-interval=45s, --mon-out-timeout=10m0s, --operator-image=, --service-account=, --skip_headers=false, --skip_log_headers=false, --stderrthreshold=2, --v=0, --vmodule= 
2020-05-18 09:39:29.892934 I | cephcmd: starting operator 
2020-05-18 09:39:29.990670 I | op-discover: rook-discover daemonset already exists, updating ... 
2020-05-18 09:39:30.009787 I | operator: rook-provisioner ceph.rook.io/block started using ceph.rook.io flex vendor dir 
I0518 09:39:30.009930       6 leaderelection.go:242] attempting to acquire leader lease  rook-ceph/ceph.rook.io-block... 
2020-05-18 09:39:30.010519 I | operator: rook-provisioner rook.io/block started using rook.io flex vendor dir 
2020-05-18 09:39:30.010559 I | operator: Watching all namespaces for cluster CRDs 
2020-05-18 09:39:30.010575 I | op-cluster: start watching clusters in all namespaces 
I0518 09:39:30.010616       6 leaderelection.go:242] attempting to acquire leader lease  rook-ceph/rook.io-block... 
2020-05-18 09:39:30.010654 I | op-cluster: Enabling hotplug orchestration: ROOK_DISABLE_DEVICE_HOTPLUG=false 
2020-05-18 09:39:30.010681 I | operator: setting up the controller-runtime manager 
2020-05-18 09:39:30.194019 I | op-cluster: starting cluster in namespace rook-ceph 
2020-05-18 09:39:30.920876 I | operator: starting the controller-runtime manager 
2020-05-18 09:39:31.505195 I | ceph-csi: detecting the ceph csi image version for image "quay.io/cephcsi/cephcsi:v2.0.1" 
2020-05-18 09:39:33.732772 I | ceph-spec: "ceph-file-controller": operator is not ready to run ceph command, cannot reconcile yet. 
2020-05-18 09:39:34.316773 I | ceph-csi: Detected ceph CSI image version: "v2.0.1" 
2020-05-18 09:39:34.366558 I | ceph-csi: successfully created csi config map "rook-ceph-csi-config" 
2020-05-18 09:39:37.518121 I | ceph-csi: CSIDriver CRD already had been registered for "rook-ceph.rbd.csi.ceph.com" 
2020-05-18 09:39:37.527757 I | ceph-csi: CSIDriver CRD already had been registered for "rook-ceph.cephfs.csi.ceph.com" 
2020-05-18 09:39:37.527804 I | operator: successfully started Ceph CSI driver(s) 
2020-05-18 09:39:43.594838 I | op-cluster: detecting the ceph image version for image ceph/ceph:v14.2.4-20190917... 
2020-05-18 09:39:44.017581 I | ceph-spec: "ceph-file-controller": operator is not ready to run ceph command, cannot reconcile yet. 
2020-05-18 09:39:46.047015 I | op-cluster: Detected ceph image version: "14.2.4-0 nautilus" 
2020-05-18 09:39:46.047090 E | op-cluster: failed the ceph version check. the version does not meet the minimum version "14.2.5-0 nautilus" 
2020-05-18 09:39:46.047111 I | op-client: start watching client resources in namespace "rook-ceph" 
2020-05-18 09:39:46.047124 I | op-bucket-prov: Ceph Bucket Provisioner launched 
I0518 09:39:46.049411       6 manager.go:118] objectbucket.io/provisioner-manager "msg"="starting provisioner"  "name"="ceph.rook.io/bucket" 
E0518 09:39:46.049452       6 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference) 
goroutine 45 [running]: 
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1df0c80, 0x35de520) 
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:74 +0xa3 
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0) 
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:48 +0x82 
panic(0x1df0c80, 0x35de520) 
	/usr/local/go/src/runtime/panic.go:679 +0x1b2 
github.com/rook/rook/pkg/operator/ceph/cluster.(*ClusterController).initializeCluster(0xc00049b280, 0xc000172900, 0xc00034a000) 
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/controller.go:520 +0x512 
github.com/rook/rook/pkg/operator/ceph/cluster.(*ClusterController).onAdd(0xc00049b280, 0x208f8c0, 0xc0003e7c00) 
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/controller.go:290 +0x36a 
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...) 
	/home/rook/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/controller.go:198 
k8s.io/client-go/tools/cache.newInformer.func1(0x1e24d20, 0xc0006c4040, 0x1, 0xc0006c4040) 
	/home/rook/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/controller.go:370 +0x1b6 
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0008e4c60, 0xc00078a090, 0x0, 0x0, 0x0, 0x0) 
	/home/rook/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/delta_fifo.go:422 +0x230 
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000364800) 
	/home/rook/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/controller.go:153 +0x40 
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0009aafb0) 
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152 +0x5e 
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc003d27fb0, 0x3b9aca00, 0x0, 0xc0003e6e01, 0xc000590cc0) 
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153 +0xf8 
k8s.io/apimachinery/pkg/util/wait.Until(...) 
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88 
k8s.io/client-go/tools/cache.(*controller).Run(0xc000364800, 0xc000590cc0) 
	/home/rook/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/controller.go:125 +0x2fd 
created by github.com/rook/rook/pkg/operator/k8sutil.WatchCR 
	/home/rook/go/src/github.com/rook/rook/pkg/operator/k8sutil/customresource.go:68 +0x1ac 
I0518 09:39:46.213514       6 leaderelection.go:252] successfully acquired lease rook-ceph/rook.io-block 
I0518 09:39:46.213707       6 controller.go:780] Starting provisioner controller rook.io/block_rook-ceph-operator-85c78858b-smbzn_d7640b21-91f0-465e-92e2-56f3f51bf6ff! 
I0518 09:39:46.213771       6 event.go:281] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"rook-ceph", Name:"rook.io-block", UID:"10dcf62a-de35-40a0-aa62-2084649f8a28", APIVersion:"v1", ResourceVersion:"99171895", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' rook-ceph-operator-85c78858b-smbzn_d7640b21-91f0-465e-92e2-56f3f51bf6ff became leader 
I0518 09:39:46.314051       6 controller.go:829] Started provisioner controller rook.io/block_rook-ceph-operator-85c78858b-smbzn_d7640b21-91f0-465e-92e2-56f3f51bf6ff! 
I0518 09:39:46.485446       6 leaderelection.go:252] successfully acquired lease rook-ceph/ceph.rook.io-block 
I0518 09:39:46.485642       6 event.go:281] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"rook-ceph", Name:"ceph.rook.io-block", UID:"339462b0-f678-4741-9d1c-bb3e2c6ada7d", APIVersion:"v1", ResourceVersion:"99171898", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' rook-ceph-operator-85c78858b-smbzn_712b2a02-8d11-467b-ab0b-5fd986c45282 became leader 
I0518 09:39:46.485721       6 controller.go:780] Starting provisioner controller ceph.rook.io/block_rook-ceph-operator-85c78858b-smbzn_712b2a02-8d11-467b-ab0b-5fd986c45282! 
I0518 09:39:47.086065       6 controller.go:829] Started provisioner controller ceph.rook.io/block_rook-ceph-operator-85c78858b-smbzn_712b2a02-8d11-467b-ab0b-5fd986c45282! 
2020-05-18 09:39:54.319765 I | ceph-spec: "ceph-file-controller": operator is not ready to run ceph command, cannot reconcile yet. 
2020-05-18 09:40:04.608829 I | ceph-spec: "ceph-file-controller": operator is not ready to run ceph command, cannot reconcile yet. 
2020-05-18 09:40:14.996777 I | ceph-spec: "ceph-file-controller": operator is not ready to run ceph command, cannot reconcile yet. 
2020-05-18 09:40:25.323463 I | ceph-spec: "ceph-file-controller": operator is not ready to run ceph command, cannot reconcile yet. 
panic: runtime error: invalid memory address or nil pointer dereference 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x17f7c5b] 
goroutine 822 [running]: 
github.com/rook/rook/pkg/operator/ceph/cluster/mon.(*Cluster).checkHealth(0xc0002eb180, 0x0, 0x0) 
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mon/health.go:82 +0xab 
github.com/rook/rook/pkg/operator/ceph/cluster/mon.(*HealthChecker).Check(0xc000b621c0, 0xc0000bc0c0) 
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mon/health.go:70 +0x13c 
created by github.com/rook/rook/pkg/operator/ceph/cluster.(*ClusterController).initializeCluster 
	/home/rook/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/controller.go:516 +0x387 
```

```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ceph.rook.io/v1","kind":"CephCluster","metadata":{"annotations":{},"name":"rook-ceph","namespace":"rook-ceph"},"spec":{"cephVersion":{"image":"ceph/ceph:v14.2.4-20190917"},"crashCollector":{"disable":false},"dashboard":{"enabled":true,"ssl":true},"dataDirHostPath":"/var/lib/rook","disruptionManagement":{"machineDisruptionBudgetNamespace":"openshift-machine-api","osdMaintenanceTimeout":30},"external":{"enable":false},"mgr":{},"mon":{"count":3},"monitoring":{"rulesNamespace":"rook-ceph"},"network":{"hostNetwork":false,"provider":"","selectors":null},"rbdMirroring":{"workers":0},"removeOSDsIfOutAndSafeToRemove":false,"storage":{"config":null,"nodes":[{"config":null,"directories":[{"config":null,"path":"/rook/storage-dir"}],"name":"z","resources":{"limits":{"memory":"4Gi"}}},{"config":null,"directories":[{"config":null,"path":"/rook/storage-dir"}],"name":"y2","resources":{"limits":{"memory":"4Gi"}}},{"config":null,"directories":[{"config":null,"path":"/rook/storage-dir"}],"name":"y3","resources":{"limits":{"memory":"4Gi"}}},{"config":null,"directories":[{"config":null,"path":"/rook/storage-dir"}],"name":"y4","resources":{"limits":{"memory":"4Gi"}}},{"config":null,"directories":[{"config":null,"path":"/rook/storage-dir"}],"name":"x","resources":{"limits":{"memory":"4Gi"}}}],"storageClassDeviceSets":null,"useAllDevices":false}}}
  creationTimestamp: "2020-03-13T17:01:38Z"
  finalizers:
  - cephcluster.ceph.rook.io
  generation: 91525
  name: rook-ceph
  namespace: rook-ceph
  resourceVersion: "99170961"
  selfLink: /apis/ceph.rook.io/v1/namespaces/rook-ceph/cephclusters/rook-ceph
  uid: cb151e37-4e10-4b48-8513-eae25d8096db
spec:
  cephVersion:
    image: ceph/ceph:v14.2.4-20190917
  cleanupPolicy:
    deleteDataDirOnHosts: ""
  crashCollector:
    disable: false
  dashboard:
    enabled: true
    ssl: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    machineDisruptionBudgetNamespace: openshift-machine-api
    osdMaintenanceTimeout: 30
  external:
    enable: false
  mgr: {}
  mon:
    count: 3
  monitoring:
    rulesNamespace: rook-ceph
  network:
    hostNetwork: false
    provider: ""
    selectors: null
  rbdMirroring:
    workers: 0
  removeOSDsIfOutAndSafeToRemove: false
  storage:
    config: null
    nodes:
    - config: null
      directories:
      - config: null
        path: /rook/storage-dir
      name: z
      resources:
        limits:
          memory: 4Gi
    - config: null
      directories:
      - config: null
        path: /rook/storage-dir
      name: y2
      resources:
        limits:
          memory: 4Gi
    - config: null
      devices:
      - config: null
        name: xvdb
      name: y4
      resources:
        limits:
          memory: 4Gi
    - config: null
      devices:
      - config: null
        name: sda5
      name: x
      resources:
        limits:
          memory: 4Gi
    - config: null
      devices:
      - config: null
        name: xvdb
      name: y3
      resources:
        limits:
          memory: 4Gi
    - config: null
      devices:
      - config: null
        name: xvdb
      name: y5
      resources:
        limits:
          memory: 4Gi
    storageClassDeviceSets: null
    useAllDevices: false
status:
  ceph:
    details:
      PG_NOT_DEEP_SCRUBBED:
        message: 48 pgs not deep-scrubbed in time
        severity: HEALTH_WARN
      PG_NOT_SCRUBBED:
        message: 20 pgs not scrubbed in time
        severity: HEALTH_WARN
    health: HEALTH_WARN
    lastChanged: "2020-05-12T20:20:54Z"
    lastChecked: "2020-05-18T09:37:50Z"
    previousHealth: HEALTH_OK
  conditions:
  - lastHeartbeatTime: "2020-05-18T09:38:28Z"
    lastTransitionTime: "2020-05-18T09:38:28Z"
    status: "False"
    type: Failure
  - lastHeartbeatTime: "2020-05-18T09:38:28Z"
    lastTransitionTime: "2020-05-18T09:38:28Z"
    status: "False"
    type: Ignored
  - lastHeartbeatTime: "2020-05-18T09:38:28Z"
    lastTransitionTime: "2020-05-18T09:38:28Z"
    status: "False"
    type: Upgrading
  state: Created
  version:
    image: ceph/ceph:v14.2.4-20190917
    version: 14.2.4-0
```

**Environment**:
* OS (e.g. from /etc/os-release):
Fedora CoreOS
* Kernel (e.g. `uname -a`):
Linux x 5.5.17-200.fc31.x86_64 #1 SMP Mon Apr 13 15:29:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration:
Rancher kubernetes on Fedora CoreOS
* Rook version (use `rook version` inside of a Rook Pod):
1.3.X
* Storage backend version (e.g. for ceph do `ceph -v`):
v14.2.4-20190917
* Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
Rancher

**Comment by travisn** [comment]
The stack trace from v1.3.0 looks like [this line](https://github.com/rook/rook/blob/release-1.3/pkg/operator/ceph/cluster/controller.go#L551) with the issue in the latest release-1.3 branch. @leseb Thoughts on why the `cluster.Info` wouldn't be populated at this point? Seems like the cluster.Info should always be populated by `configureLocalCephCluster()`, right?

**Comment by leseb** [comment]
> The stack trace from v1.3.0 looks like [this line](https://github.com/rook/rook/blob/release-1.3/pkg/operator/ceph/cluster/controller.go#L551) with the issue in the latest release-1.3 branch. @leseb Thoughts on why the `cluster.Info` wouldn't be populated at this point? Seems like the cluster.Info should always be populated by `configureLocalCephCluster()`, right?

`cluster.Info` is probably initialized but not the CephVersion, looking.

**Comment by leseb** [comment]
Also this line seems to help:

`2020-05-18 09:39:46.047090 E | op-cluster: failed the ceph version check. the version does not meet the minimum version "14.2.5-0 nautilus" 
`

**Comment by leseb** [comment]
Looks like we should not return `nil` here: https://github.com/rook/rook/blob/release-1.3/pkg/operator/ceph/cluster/controller.go#L463

**Comment by travisn** [comment]
Good catch, the error checking should have stopped the reconcile from continuing and hitting that issue.

**Comment by leseb** [comment]
master does not have the bug though

**Comment by travisn** [comment]
@TeroPihlaja Can you confirm that updating to a supported version of Ceph (14.2.5 or newer) will fix the issue? If so, I would suggest we close the issue since it's already fixed in master. It doesn't appear urgent to backport for 1.3.

**Comment by TeroPihlaja** [comment]
Looks like updating to 14.2.5 seems to fix the issue. Thanks.

**Comment by leseb** [comment]
Closed with https://github.com/rook/rook/pull/5503
