### ISSUE TITLE
Encrypted OSD Provisioning Fails

### ISSUE THREAD

**Issue by eknudtson** [rook/rook#5736]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Adding a new block device to the Ceph Cluster CRD w/ encryption enabled results in a failure of the prepare pod.

**Expected behavior:**
Adding a new block device with encryption enabled to the Cluster CRD would result in a working OSD.

**How to reproduce it (minimal and precise):**
Using Rook 1.3.5, I added an empty OSD to a worker.   This OSD was sgdisk zapped.  

Attempting to add the OSD in the CRD resulted in an error in the worker prepare pod.  The OSD deployment was created but crashlooped.  A LVM devicemapper entry was created for the device, as well as a LUKS encrypted device.

**File(s) to submit**:

logs from worker prepare pod:

```
2020-06-30 03:07:12.717822 I | cephcmd: desired devices to configure osds: [{Name:sdb OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: IsFilter:false IsDevicePathFilter:false}]
2020-06-30 03:07:12.718919 I | rookcmd: starting Rook v1.3.5 with arguments '/rook/rook ceph osd provision'
2020-06-30 03:07:12.718928 I | rookcmd: flag values: --cluster-id=6b853702-103e-11e9-88da-3cfdfec471f8, --data-device-filter=, --data-device-path-filter=, --data-devices=sdb:1:::, --encrypted-device=true, --force-format=false, --help=false, --location=, --log-flush-frequency=5s, --log-level=DEBUG, --metadata-device=, --node-name=worker-abc.example.com, --operator-image=, --osd-database-size=0, --osd-store=, --osd-wal-size=576, --osds-per-device=1, --pvc-backed-osd=false, --service-account=
2020-06-30 03:07:12.718934 I | op-mon: parsing mon endpoints: am=10.21.217.5:6789,al=10.21.142.161:6789,ah=10.21.221.219:6789
2020-06-30 03:07:12.724890 I | op-osd: CRUSH location=root=default host=worker-abc.example.com region=pdx zone=a8
2020-06-30 03:07:12.724900 I | cephcmd: crush location of osd: root=default host=worker-abc.example.com region=pdx zone=a8
2020-06-30 03:07:12.728666 I | cephconfig: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2020-06-30 03:07:12.728723 I | cephconfig: generated admin config in /var/lib/rook/rook-ceph
2020-06-30 03:07:12.728807 D | cephosd: config file @ /etc/ceph/ceph.conf: [global]
fsid                = 0a564ded-1bc9-4f85-ac05-b61b6bc716f9
mon initial members = am al ah
mon host            = [v2:10.21.217.5:3300,v1:10.21.217.5:6789],[v2:10.21.142.161:3300,v1:10.21.142.161:6789],[v2:10.21.221.219:3300,v1:10.21.221.219:6789]
public addr         = 10.20.38.28
cluster addr        = 10.20.38.28

[client.admin]
keyring = /var/lib/rook/rook-ceph/client.admin.keyring

2020-06-30 03:07:12.728811 I | cephosd: discovering hardware
2020-06-30 03:07:12.728819 D | exec: Running command: lsblk --all --noheadings --list --output KNAME
2020-06-30 03:07:12.731214 D | exec: Running command: lsblk /dev/sda --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME
2020-06-30 03:07:12.732738 D | exec: Running command: sgdisk --print /dev/sda
2020-06-30 03:07:12.734408 D | exec: Running command: udevadm info --query=property /dev/sda
2020-06-30 03:07:12.735778 D | exec: Running command: lsblk --noheadings --pairs /dev/sda
2020-06-30 03:07:12.737826 I | inventory: skipping device "sda" because it has child, considering the child instead.
2020-06-30 03:07:12.737846 D | exec: Running command: lsblk /dev/sda1 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME
2020-06-30 03:07:12.739245 D | exec: Running command: udevadm info --query=property /dev/sda1
2020-06-30 03:07:12.740516 D | exec: Running command: lsblk /dev/sda2 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME
2020-06-30 03:07:12.741908 D | exec: Running command: udevadm info --query=property /dev/sda2
2020-06-30 03:07:12.743194 D | exec: Running command: lsblk /dev/dm-0 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME
2020-06-30 03:07:12.744516 W | inventory: skipping device "dm-0" because 'lsblk' failed. unsupported diskType crypt
2020-06-30 03:07:12.744524 D | exec: Running command: lsblk /dev/dm-1 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME
2020-06-30 03:07:12.745846 D | exec: Running command: sgdisk --print /dev/dm-1
2020-06-30 03:07:12.747588 D | exec: Running command: udevadm info --query=property /dev/dm-1
2020-06-30 03:07:12.749072 D | exec: Running command: lsblk /dev/sdb --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME
2020-06-30 03:07:12.750516 D | exec: Running command: sgdisk --print /dev/sdb
2020-06-30 03:07:12.757639 D | exec: Running command: udevadm info --query=property /dev/sdb
2020-06-30 03:07:12.758908 D | exec: Running command: lsblk --noheadings --pairs /dev/sdb
2020-06-30 03:07:12.760498 D | exec: Running command: lsblk /dev/sdc --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME
2020-06-30 03:07:12.761980 D | exec: Running command: sgdisk --print /dev/sdc
2020-06-30 03:07:12.768972 D | exec: Running command: udevadm info --query=property /dev/sdc
2020-06-30 03:07:12.770267 D | exec: Running command: lsblk --noheadings --pairs /dev/sdc
2020-06-30 03:07:12.771861 D | inventory: discovered disks are [0xc000432ea0 0xc000433200 0xc0004337a0 0xc000266120 0xc000266360]
2020-06-30 03:07:12.771866 I | cephosd: creating and starting the osds
2020-06-30 03:07:12.771877 D | cephosd: desiredDevices are [{Name:sdb OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: IsFilter:false IsDevicePathFilter:false}]
2020-06-30 03:07:12.771882 D | cephosd: context.Devices are [0xc000432ea0 0xc000433200 0xc0004337a0 0xc000266120 0xc000266360]
2020-06-30 03:07:12.771887 I | cephosd: skipping device "sda1" because it contains a filesystem "xfs"
2020-06-30 03:07:12.771892 I | cephosd: skipping device "sda2" because it contains a filesystem "crypto_LUKS"
2020-06-30 03:07:12.771895 I | cephosd: skipping 'dm' device "dm-1"
2020-06-30 03:07:12.771898 D | exec: Running command: lsblk /dev/sdb --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME
2020-06-30 03:07:12.773281 D | exec: Running command: ceph-volume inventory --format json /dev/sdb
2020-06-30 03:07:15.698177 I | cephosd: device "sdb" is available.
2020-06-30 03:07:15.698194 I | cephosd: "sdb" found in the desired devices
2020-06-30 03:07:15.698197 I | cephosd: device "sdb" is selected by the device filter/name "sdb"
2020-06-30 03:07:15.698206 D | exec: Running command: lsblk /dev/sdc --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME
2020-06-30 03:07:15.700046 D | exec: Running command: ceph-volume inventory --format json /dev/sdc
2020-06-30 03:07:18.598071 I | cephosd: device "sdc" is available.
2020-06-30 03:07:18.598099 I | cephosd: skipping device "sdc" that does not match the device filter/list ([{sdb 1  0  false false}]). <nil>
2020-06-30 03:07:18.602332 I | cephosd: configuring osd devices: {"Entries":{"sdb":{"Data":-1,"Metadata":null,"Config":{"Name":"sdb","OSDsPerDevice":1,"MetadataDevice":"","DatabaseSizeMB":0,"DeviceClass":"","IsFilter":false,"IsDevicePathFilter":false},"PersistentDevicePaths":["/dev/disk/by-id/ata-INTEL_SSDSC2KB038T7_BTYS825301N63P8EGN","/dev/disk/by-id/wwn-0x55cd2e414f7ce507","/dev/disk/by-path/pci-0000:00:11.5-ata-2.0"]}}}
2020-06-30 03:07:18.602375 I | cephclient: getting or creating ceph auth key "client.bootstrap-osd"
2020-06-30 03:07:18.602519 D | exec: Running command: ceph auth get-or-create-key client.bootstrap-osd mon allow profile bootstrap-osd --connect-timeout=15 --cluster=rook-ceph --conf=/var/lib/rook/rook-ceph/rook-ceph.config --name=client.admin --keyring=/var/lib/rook/rook-ceph/client.admin.keyring --format json --out-file /tmp/844847137
2020-06-30 03:07:18.928256 I | cephosd: configuring new device sdb
2020-06-30 03:07:18.928275 I | cephosd: Base command - stdbuf
2020-06-30 03:07:18.928313 I | cephosd: immediateReportArgs - stdbuf
2020-06-30 03:07:18.928326 I | cephosd: immediateExecuteArgs - [-oL ceph-volume lvm batch --prepare --bluestore --yes --dmcrypt --osds-per-device 1 /dev/sdb]
2020-06-30 03:07:18.928334 D | exec: Running command: stdbuf -oL ceph-volume lvm batch --prepare --bluestore --yes --dmcrypt --osds-per-device 1 /dev/sdb --report
2020-06-30 03:07:22.169441 D | exec:
2020-06-30 03:07:22.169470 D | exec: Total OSDs: 1
2020-06-30 03:07:22.169473 D | exec:
2020-06-30 03:07:22.169476 D | exec:   Type            Path                                                    LV Size         % of device
2020-06-30 03:07:22.169479 D | exec: ----------------------------------------------------------------------------------------------------
2020-06-30 03:07:22.169481 D | exec:   [data]          /dev/sdb                                                3.49 TB         100%
2020-06-30 03:07:22.176286 D | exec: Running command: stdbuf -oL ceph-volume lvm batch --prepare --bluestore --yes --dmcrypt --osds-per-device 1 /dev/sdb
2020-06-30 03:07:25.425991 D | exec: Running command: /usr/sbin/vgcreate --force --yes ceph-6dcab0d5-8dc0-4b84-aa9f-38a3b140875c /dev/sdb
2020-06-30 03:07:25.766433 D | exec:  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will manage logical volume symlinks in device directory.
2020-06-30 03:07:25.766616 D | exec:  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will obtain device list by scanning device directory.
2020-06-30 03:07:25.768383 D | exec:  stderr: WARNING: Failed to connect to lvmetad. Falling back to device scanning.
2020-06-30 03:07:25.812787 D | exec:  stdout: Physical volume "/dev/sdb" successfully created.
2020-06-30 03:07:25.826671 D | exec:  stdout: Volume group "ceph-6dcab0d5-8dc0-4b84-aa9f-38a3b140875c" successfully created
2020-06-30 03:07:26.202704 D | exec: Running command: /usr/sbin/lvcreate --yes -l 915707 -n osd-data-b9eaf55c-1f06-4a74-b9e5-acd122b53397 ceph-6dcab0d5-8dc0-4b84-aa9f-38a3b140875c
2020-06-30 03:07:26.542637 D | exec:  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will manage logical volume symlinks in device directory.
2020-06-30 03:07:26.542851 D | exec:  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will obtain device list by scanning device directory.
2020-06-30 03:07:26.544627 D | exec:  stderr: WARNING: Failed to connect to lvmetad. Falling back to device scanning.
2020-06-30 03:07:26.555647 D | exec:  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, device-mapper library will manage device nodes in device directory.
2020-06-30 03:07:26.566917 D | exec:  stdout: Logical volume "osd-data-b9eaf55c-1f06-4a74-b9e5-acd122b53397" created.
2020-06-30 03:07:29.133532 D | exec: Running command: /usr/bin/ceph-authtool --gen-print-key
2020-06-30 03:07:29.501377 D | exec: Running command: /usr/bin/ceph-authtool --gen-print-key
2020-06-30 03:07:29.869200 D | exec: Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new fa01e680-16e7-4183-90fc-3b5ec5f95458
2020-06-30 03:07:31.628449 D | exec: Running command: /usr/bin/ceph-authtool --gen-print-key
2020-06-30 03:07:31.999366 D | exec: Running command: /usr/sbin/cryptsetup --batch-mode --key-file - luksFormat /dev/ceph-6dcab0d5-8dc0-4b84-aa9f-38a3b140875c/osd-data-b9eaf55c-1f06-4a74-b9e5-acd122b53397
2020-06-30 03:07:36.068328 D | exec: Running command: /usr/sbin/cryptsetup --key-file - --allow-discards luksOpen /dev/ceph-6dcab0d5-8dc0-4b84-aa9f-38a3b140875c/osd-data-b9eaf55c-1f06-4a74-b9e5-acd122b53397 eBKXBs-mNUp-802r-dWJD-YJaS-cLId-Z96fFg
2020-06-30 03:07:38.561101 D | exec: Running command: /usr/bin/mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-4
2020-06-30 03:07:38.901903 D | exec: Running command: /usr/bin/chown -R ceph:ceph /dev/mapper/eBKXBs-mNUp-802r-dWJD-YJaS-cLId-Z96fFg
2020-06-30 03:07:39.240089 D | exec: Running command: /usr/bin/ln -s /dev/mapper/eBKXBs-mNUp-802r-dWJD-YJaS-cLId-Z96fFg /var/lib/ceph/osd/ceph-4/block
2020-06-30 03:07:39.578074 D | exec: Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/osd/ceph-4/activate.monmap
2020-06-30 03:07:40.201489 D | exec:  stderr: got monmap epoch 80
2020-06-30 03:07:40.213272 D | exec: Running command: /usr/bin/ceph-authtool /var/lib/ceph/osd/ceph-4/keyring --create-keyring --name osd.4 --add-key AQBxrPpeKzHKHRAAI/OdYWfnYYuvf605voG4Tg==
2020-06-30 03:07:40.583432 D | exec:  stdout: creating /var/lib/ceph/osd/ceph-4/keyring
2020-06-30 03:07:40.583695 D | exec:  stdout: added entity osd.4 auth(key=AQBxrPpeKzHKHRAAI/OdYWfnYYuvf605voG4Tg==)
2020-06-30 03:07:40.584833 D | exec: Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-4/keyring
2020-06-30 03:07:40.924627 D | exec: Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-4/
2020-06-30 03:07:41.266299 D | exec: Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 4 --monmap /var/lib/ceph/osd/ceph-4/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-4/ --osd-uuid fa01e680-16e7-4183-90fc-3b5ec5f95458 --setuser ceph --setgroup ceph
2020-06-30 03:07:42.605867 D | exec:  stderr: 2020-06-30 03:07:41.664 7f8098752a80 -1 bluestore(/var/lib/ceph/osd/ceph-4/) _read_fsid unparsable uuid
2020-06-30 03:07:42.609788 D | exec: --> Was unable to complete a new OSD, will rollback changes
2020-06-30 03:07:42.609792 D | exec: Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.4 --yes-i-really-mean-it
2020-06-30 03:07:43.296924 D | exec:  stderr: purged osd.4
2020-06-30 03:07:43.310191 D | exec: Traceback (most recent call last):
2020-06-30 03:07:43.310202 D | exec:   File "/usr/sbin/ceph-volume", line 9, in <module>
2020-06-30 03:07:43.310208 D | exec:     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
2020-06-30 03:07:43.310211 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 39, in __init__
2020-06-30 03:07:43.310214 D | exec:     self.main(self.argv)
2020-06-30 03:07:43.310217 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
2020-06-30 03:07:43.310221 D | exec:     return f(*a, **kw)
2020-06-30 03:07:43.310224 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 150, in main
2020-06-30 03:07:43.310247 D | exec:     terminal.dispatch(self.mapper, subcommand_args)
2020-06-30 03:07:43.310250 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2020-06-30 03:07:43.310272 D | exec:     instance.main()
2020-06-30 03:07:43.310276 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 42, in main
2020-06-30 03:07:43.310280 D | exec:     terminal.dispatch(self.mapper, self.argv)
2020-06-30 03:07:43.310284 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2020-06-30 03:07:43.310308 D | exec:     instance.main()
2020-06-30 03:07:43.310311 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
2020-06-30 03:07:43.310316 D | exec:     return func(*a, **kw)
2020-06-30 03:07:43.310322 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 328, in main
2020-06-30 03:07:43.310358 D | exec:     self.execute()
2020-06-30 03:07:43.310361 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 291, in execute
2020-06-30 03:07:43.310389 D | exec:     self.strategy.execute()
2020-06-30 03:07:43.310393 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py", line 122, in execute
2020-06-30 03:07:43.310410 D | exec:     Prepare(command).main()
2020-06-30 03:07:43.310414 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/prepare.py", line 402, in main
2020-06-30 03:07:43.310460 D | exec:     self.safe_prepare()
2020-06-30 03:07:43.310464 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/prepare.py", line 250, in safe_prepare
2020-06-30 03:07:43.310490 D | exec:     self.prepare()
2020-06-30 03:07:43.310493 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
2020-06-30 03:07:43.310497 D | exec:     return func(*a, **kw)
2020-06-30 03:07:43.310501 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/prepare.py", line 355, in prepare
2020-06-30 03:07:43.310543 D | exec:     osd_fsid,
2020-06-30 03:07:43.310546 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/prepare.py", line 119, in prepare_bluestore
2020-06-30 03:07:43.310561 D | exec:     db=db
2020-06-30 03:07:43.310565 D | exec:   File "/usr/lib/python2.7/site-packages/ceph_volume/util/prepare.py", line 463, in osd_mkfs_bluestore
2020-06-30 03:07:43.310609 D | exec:     raise RuntimeError('Command failed with exit code %s: %s' % (returncode, ' '.join(command)))
2020-06-30 03:07:43.310627 D | exec: RuntimeError: Command failed with exit code 250: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 4 --monmap /var/lib/ceph/osd/ceph-4/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-4/ --osd-uuid fa01e680-16e7-4183-90fc-3b5ec5f95458 --setuser ceph --setgroup ceph
failed to configure devices: failed to initialize devices: failed ceph-volume: exit status 1
```

**Environment**:
* OS (e.g. from /etc/os-release):Centos 7
* Kernel (e.g. `uname -a`): 3.10.0-1127.13.1.el7.x86_64
* Cloud provider or hardware configuration: baremetal
* Rook version (use `rook version` inside of a Rook Pod): 1.3.5
* Storage backend version (e.g. for ceph do `ceph -v`): 14.2.10
* Kubernetes version (use `kubectl version`): 1.17.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): baremetal
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): healthy

**Comment by eknudtson** [comment]
I just confirmed that this isn't just for encrypted OSDs, as I thought. I'm unable to provision a non-LUKS OSD with the same issue: 

```
2020-06-30 04:18:01.299473 D | exec: Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 4 --monmap /var/lib/ceph/osd/ceph-4/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-4/ --osd-uuid 2809b5ee-b224-401b-b989-d1456700b8c4 --setuser ceph --setgroup ceph
2020-06-30 04:18:02.645859 D | exec:  stderr: 2020-06-30 04:18:01.696 7f8094baea80 -1 bluestore(/var/lib/ceph/osd/ceph-4/) _read_fsid unparsable uuid
```

**Comment by leseb** [comment]
Looks like a ceph-volume bug :-/, could you please open a tracker bug here https://tracker.ceph.com/ against the ceph-volume component? Thanks.

**Comment by eknudtson** [comment]
Will do, thanks!

**Comment by eknudtson** [comment]
What's odd is that I have a staging rook/ceph cluster with the exact same configuration - I'm able to rebuild OSDs there with no problem.  Any ideas what I might look into?

**Comment by eknudtson** [comment]
I'm pretty sure I tracked down the problem here.

I had memory limits/requests set to 100Mi on prepare pods.  In our staging environment, our drives are 300G HDDs.  In prod, they're 3.5Ti SSDs.  Dmesg logs seem to indicate the prod variants were being oomkilled.

Sorry about that!

**Comment by leseb** [comment]
@eknudtson no worries, I'm closing this since it's solved :).
