### ISSUE TITLE
CI: Object bucket health status intermittently fails in the CI

### ISSUE THREAD

**Issue by travisn** [rook/rook#5840]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
In the CI, we are periodically seeing the following failure as seen in a [master build log](https://jenkins.rook.io/blue/rest/organizations/jenkins/pipelines/rook/pipelines/rook/branches/master/runs/2078/nodes/60/steps/125/log/?start=0) today.
```
    --- FAIL: TestCephSmokeSuite/TestObjectStorage_SmokeTest (202.71s)
        suite.go:62: test panicked: runtime error: invalid memory address or nil pointer dereference
            goroutine 1330 [running]:
            runtime/debug.Stack(0xc00067d588, 0x181f800, 0x2aca8b0)
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
            github.com/stretchr/testify/suite.failOnPanic(0xc0001a1e00)
            	/home/rook/go/pkg/mod/github.com/stretchr/testify@v1.4.0/suite/suite.go:62 +0x57
            panic(0x181f800, 0x2aca8b0)
            	/usr/local/go/src/runtime/panic.go:679 +0x1b2
            github.com/rook/rook/tests/integration.runObjectE2ETest(0xc00091b130, 0xc000725e90, 0xc0006e3780, 0xc0006e3790, 0xc0001a1e00, 0x1a491d8, 0x8)
            	/home/rook/go/src/github.com/rook/rook/tests/integration/ceph_base_object_test.go:87 +0x7cc
            github.com/rook/rook/tests/integration.(*SmokeSuite).TestObjectStorage_SmokeTest(0xc0007f77c0)
            	/home/rook/go/src/github.com/rook/rook/tests/integration/ceph_smoke_test.go:118 +0x64
            reflect.Value.call(0xc000904cc0, 0xc0000a59a0, 0x13, 0x1a43ac8, 0x4, 0xc0006dfef8, 0x1, 0x1, 0xc00094fd40, 0x40a35a, ...)
            	/usr/local/go/src/reflect/value.go:460 +0x5f6
            reflect.Value.Call(0xc000904cc0, 0xc0000a59a0, 0x13, 0xc00094fef8, 0x1, 0x1, 0x44b1f7, 0x1f95480, 0x2a7cc60)
            	/usr/local/go/src/reflect/value.go:321 +0xb4
            github.com/stretchr/testify/suite.Run.func2(0xc0001a1e00)
            	/home/rook/go/pkg/mod/github.com/stretchr/testify@v1.4.0/suite/suite.go:133 +0x31f
            testing.tRunner(0xc0001a1e00, 0xc00080e580)
            	/usr/local/go/src/testing/testing.go:909 +0xc9
            created by testing.(*T).Run
            	/usr/local/go/src/testing/testing.go:960 +0x350
```

This failure is that the object status or bucket status is nil in this check:
```
	// Check object store status
	objectStore, err := k8sh.RookClientset.CephV1().CephObjectStores(namespace).Get(storeName, metav1.GetOptions{})
	assert.Nil(s.T(), err)
	assert.Equal(s.T(), cephv1.ConditionHealthy, objectStore.Status.BucketStatus.Health)
```

**Expected behavior:**
The CI should pass consistently.

**How to reproduce it (minimal and precise):**

Look at the CI results for failed builds.

**Comment by travisn** [comment]
Fixed with #6001
