### ISSUE TITLE
Rook 1.4.1 unable to create all OSDs configured

### ISSUE THREAD

**Issue by okossuth** [rook/rook#6148]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
An OSD is missing after trying to install rook 1.4.1 with default cluster-on-pvc.yaml. Rook 1.3.X works flawlessly. 
**Expected behavior:**
All three OSDs should be created and configured

```
$ kubectl get pod -A -n rook-ceph
NAMESPACE     NAME                                                        READY   STATUS      RESTARTS   AGE
kube-system   cilium-2ggbr                                                1/1     Running     0          40m
kube-system   cilium-bthrn                                                1/1     Running     0          39m
kube-system   cilium-operator-7c59b5d8d-jrbv4                             1/1     Running     0          41m
kube-system   cilium-v9r96                                                1/1     Running     0          35m
kube-system   coredns-6b6854dcbf-j2czr                                    1/1     Running     0          41m
kube-system   coredns-6b6854dcbf-jltvv                                    1/1     Running     0          39m
kube-system   csi-do-node-5bcxw                                           2/2     Running     0          39m
kube-system   csi-do-node-g5sfm                                           2/2     Running     0          40m
kube-system   csi-do-node-xtbvj                                           2/2     Running     0          35m
kube-system   do-node-agent-bvgwg                                         1/1     Running     0          40m
kube-system   do-node-agent-mw8vw                                         1/1     Running     0          35m
kube-system   do-node-agent-vc4cb                                         1/1     Running     0          39m
kube-system   kube-proxy-5l8p7                                            1/1     Running     0          40m
kube-system   kube-proxy-g9ww2                                            1/1     Running     0          39m
kube-system   kube-proxy-jg9sq                                            1/1     Running     0          35m
rook-ceph     csi-cephfsplugin-nnzbw                                      3/3     Running     0          24m
rook-ceph     csi-cephfsplugin-p9fmm                                      3/3     Running     0          24m
rook-ceph     csi-cephfsplugin-provisioner-598854d87f-t999m               6/6     Running     0          24m
rook-ceph     csi-cephfsplugin-provisioner-598854d87f-xwzpk               6/6     Running     0          24m
rook-ceph     csi-cephfsplugin-wtcqs                                      3/3     Running     0          24m
rook-ceph     csi-rbdplugin-2dkzb                                         3/3     Running     0          24m
rook-ceph     csi-rbdplugin-dxrzp                                         3/3     Running     0          24m
rook-ceph     csi-rbdplugin-hdddd                                         3/3     Running     0          24m
rook-ceph     csi-rbdplugin-provisioner-866ccdc6f7-czbt7                  6/6     Running     0          24m
rook-ceph     csi-rbdplugin-provisioner-866ccdc6f7-qz8lw                  6/6     Running     0          24m
rook-ceph     rook-ceph-crashcollector-rook-pool-3gdhs-7fd49c875c-z2gvm   1/1     Running     0          23m
rook-ceph     rook-ceph-crashcollector-rook-pool-3gdki-597cf58bf6-wdkpt   1/1     Running     0          23m
rook-ceph     rook-ceph-crashcollector-rook-pool-3gdkv-5757888f-4rm4j     1/1     Running     0          23m
rook-ceph     rook-ceph-mgr-a-7fbd9f8b6-zw24p                             1/1     Running     0          22m
rook-ceph     rook-ceph-mon-a-5994cc5c54-7vxfb                            1/1     Running     0          23m
rook-ceph     rook-ceph-mon-b-5c4585c8c4-hq8rl                            1/1     Running     0          23m
rook-ceph     rook-ceph-mon-c-7847656468-zmkxw                            1/1     Running     0          23m
rook-ceph     rook-ceph-operator-58496b74f9-m8xrz                         1/1     Running     0          27m
rook-ceph     rook-ceph-osd-0-74df4ffd64-6dv2t                            1/1     Running     0          22m
rook-ceph     rook-ceph-osd-1-6dcd85cbf7-ss5cs                            1/1     Running     0          22m
rook-ceph     rook-ceph-osd-prepare-set1-data-0-vzphp-9bz2n               0/1     Completed   0          22m
rook-ceph     rook-ceph-osd-prepare-set1-data-1-2rx72-gj5lm               0/1     Completed   0          22m
rook-ceph     rook-ceph-osd-prepare-set1-data-2-2dh5w-g47ql               0/1     Completed   0          21m
rook-ceph     rook-ceph-tools-6bdcd78654-8pvzn                            1/1     Running     0          3m
rook-ceph     rook-discover-g5pv2                                         1/1     Running     0          26m
rook-ceph     rook-discover-lvz5h                                         1/1     Running     0          26m
rook-ceph     rook-discover-t7c2m                                         1/1     Running     0          26m
```

```
$ kubectl logs rook-ceph-osd-prepare-set1-data-2-2dh5w-g47ql  -n rook-ceph 
2020-08-24 21:22:08.067059 I | cephcmd: desired devices to configure osds: [{Name:/mnt/set1-data-2-2dh5w OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: IsFilter:false IsDevicePathFilter:false}]
2020-08-24 21:22:08.068432 I | rookcmd: starting Rook v1.4.1 with arguments '/rook/rook ceph osd provision'
2020-08-24 21:22:08.068480 I | rookcmd: flag values: --cluster-id=939756e5-31a0-4fbb-9f2c-a3335753fe3e, --data-device-filter=, --data-device-path-filter=, --data-devices=[{"id":"/mnt/set1-data-2-2dh5w","storeConfig":{"osdsPerDevice":1}}], --drive-groups=, --encrypted-device=false, --force-format=false, --help=false, --location=, --log-flush-frequency=5s, --log-level=DEBUG, --metadata-device=, --node-name=set1-data-2-2dh5w, --operator-image=, --osd-database-size=0, --osd-store=, --osd-wal-size=576, --osds-per-device=1, --pvc-backed-osd=true, --service-account=
2020-08-24 21:22:08.068590 I | op-mon: parsing mon endpoints: a=10.245.74.242:6789,b=10.245.40.123:6789,c=10.245.124.61:6789
2020-08-24 21:22:08.082970 I | op-osd: CRUSH location=root=default host=set1-data-2-2dh5w region=nyc1
2020-08-24 21:22:08.083026 I | cephcmd: crush location of osd: root=default host=set1-data-2-2dh5w region=nyc1
2020-08-24 21:22:08.089720 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2020-08-24 21:22:08.089809 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2020-08-24 21:22:08.089972 D | cephosd: config file @ /etc/ceph/ceph.conf: [global]
fsid                = 722f84a2-7a9a-430f-89a9-96b550e28245
mon initial members = b c a
mon host            = [v2:10.245.40.123:3300,v1:10.245.40.123:6789],[v2:10.245.124.61:3300,v1:10.245.124.61:6789],[v2:10.245.74.242:3300,v1:10.245.74.242:6789]
public addr         = 10.244.1.141
cluster addr        = 10.244.1.141

[client.admin]
keyring = /var/lib/rook/rook-ceph/client.admin.keyring

2020-08-24 21:22:08.089982 I | cephosd: discovering hardware
2020-08-24 21:22:08.089997 D | exec: Running command: lsblk /mnt/set1-data-2-2dh5w --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-08-24 21:22:08.092705 D | exec: Running command: sgdisk --print /mnt/set1-data-2-2dh5w
2020-08-24 21:22:08.094964 D | exec: Running command: udevadm info --query=property /dev/sdb
2020-08-24 21:22:08.099900 I | cephosd: creating and starting the osds
2020-08-24 21:22:08.105666 D | cephosd: No Drive Groups configured.
2020-08-24 21:22:08.105688 D | cephosd: desiredDevices are [{Name:/mnt/set1-data-2-2dh5w OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: IsFilter:false IsDevicePathFilter:false}]
2020-08-24 21:22:08.105694 D | cephosd: context.Devices are [0xc0002beea0]
2020-08-24 21:22:08.105893 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log raw list /mnt/set1-data-2-2dh5w --format json
2020-08-24 21:22:08.343184 E | cephosd: Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 39, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 150, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 110, in main
    self.list(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 66, in list
    report = self.generate(args.device)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 54, in generate
    whoami = oj[dev]['whoami']
KeyError: 'whoami'
2020-08-24 21:22:08.343205 E | cephosd: [2020-08-24 21:22:08,297][ceph_volume.main][INFO  ] Running command: ceph-volume --log-path /tmp/ceph-log raw list /mnt/set1-data-2-2dh5w --format json
[2020-08-24 21:22:08,298][ceph_volume.devices.raw.list][DEBUG ] Examining /mnt/set1-data-2-2dh5w
[2020-08-24 21:22:08,298][ceph_volume.process][INFO  ] Running command: /usr/bin/ceph-bluestore-tool show-label --dev /mnt/set1-data-2-2dh5w
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout {
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "/mnt/set1-data-2-2dh5w": {
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "osd_uuid": "8a88c47e-47c1-4c57-9919-6bcf9bb8da69",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "size": 107374182400,
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "btime": "2020-08-24T21:21:28.277976+0000",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "description": "main",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "bfm_blocks": "1638400",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "bfm_blocks_per_key": "128",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "bfm_bytes_per_block": "65536",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "bfm_size": "107374182400",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "bluefs": "1",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "kv_backend": "rocksdb",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "mkfs_done": "yes"
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout }
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout }
[2020-08-24 21:22:08,318][ceph_volume][ERROR ] exception caught by decorator
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 150, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 110, in main
    self.list(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 66, in list
    report = self.generate(args.device)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 54, in generate
    whoami = oj[dev]['whoami']
KeyError: 'whoami'
2020-08-24 21:22:08.343244 I | cephosd: skipping device "/mnt/set1-data-2-2dh5w": failed to detect if there is already an osd. failed to retrieve ceph-volume raw list results: failed ceph-volume call (see ceph-volume log above for more details): exit status 1.
2020-08-24 21:22:08.343312 I | cephosd: configuring osd devices: {"Entries":{}}
2020-08-24 21:22:08.343317 I | cephosd: no new devices to configure. returning devices already configured with ceph-volume.
2020-08-24 21:22:08.343323 D | exec: Running command: pvdisplay -C -o lvpath --noheadings /mnt/set1-data-2-2dh5w
2020-08-24 21:22:08.460005 W | cephosd: failed to retrieve logical volume path for "/mnt/set1-data-2-2dh5w". exit status 5
2020-08-24 21:22:08.460042 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm list  --format json
2020-08-24 21:22:08.855576 D | cephosd: {}
2020-08-24 21:22:08.855626 I | cephosd: 0 ceph-volume lvm osd devices configured on this node
2020-08-24 21:22:08.855722 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log raw list /mnt/set1-data-2-2dh5w --format json
2020-08-24 21:22:09.089374 E | cephosd: Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 39, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 150, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 110, in main
    self.list(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 66, in list
    report = self.generate(args.device)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 54, in generate
    whoami = oj[dev]['whoami']
KeyError: 'whoami'
2020-08-24 21:22:09.089407 E | cephosd: [2020-08-24 21:22:08,297][ceph_volume.main][INFO  ] Running command: ceph-volume --log-path /tmp/ceph-log raw list /mnt/set1-data-2-2dh5w --format json
[2020-08-24 21:22:08,298][ceph_volume.devices.raw.list][DEBUG ] Examining /mnt/set1-data-2-2dh5w
[2020-08-24 21:22:08,298][ceph_volume.process][INFO  ] Running command: /usr/bin/ceph-bluestore-tool show-label --dev /mnt/set1-data-2-2dh5w
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout {
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "/mnt/set1-data-2-2dh5w": {
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "osd_uuid": "8a88c47e-47c1-4c57-9919-6bcf9bb8da69",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "size": 107374182400,
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "btime": "2020-08-24T21:21:28.277976+0000",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "description": "main",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "bfm_blocks": "1638400",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "bfm_blocks_per_key": "128",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "bfm_bytes_per_block": "65536",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "bfm_size": "107374182400",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "bluefs": "1",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "kv_backend": "rocksdb",
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout "mkfs_done": "yes"
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout }
[2020-08-24 21:22:08,317][ceph_volume.process][INFO  ] stdout }
[2020-08-24 21:22:08,318][ceph_volume][ERROR ] exception caught by decorator
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 150, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 110, in main
    self.list(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 66, in list
    report = self.generate(args.device)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 54, in generate
    whoami = oj[dev]['whoami']
KeyError: 'whoami'
[2020-08-24 21:22:08,685][ceph_volume.main][INFO  ] Running command: ceph-volume --log-path /tmp/ceph-log lvm list  --format json
[2020-08-24 21:22:08,685][ceph_volume.process][INFO  ] Running command: /usr/sbin/lvs --noheadings --readonly --separator=";" -a -S  -o lv_tags,lv_path,lv_name,vg_name,lv_uuid,lv_size
[2020-08-24 21:22:08,836][ceph_volume.process][INFO  ] stderr Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will manage logical volume symlinks in device directory.
[2020-08-24 21:22:08,836][ceph_volume.process][INFO  ] stderr Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will obtain device list by scanning device directory.
[2020-08-24 21:22:09,041][ceph_volume.main][INFO  ] Running command: ceph-volume --log-path /tmp/ceph-log raw list /mnt/set1-data-2-2dh5w --format json
[2020-08-24 21:22:09,042][ceph_volume.devices.raw.list][DEBUG ] Examining /mnt/set1-data-2-2dh5w
[2020-08-24 21:22:09,042][ceph_volume.process][INFO  ] Running command: /usr/bin/ceph-bluestore-tool show-label --dev /mnt/set1-data-2-2dh5w
[2020-08-24 21:22:09,070][ceph_volume.process][INFO  ] stdout {
[2020-08-24 21:22:09,070][ceph_volume.process][INFO  ] stdout "/mnt/set1-data-2-2dh5w": {
[2020-08-24 21:22:09,070][ceph_volume.process][INFO  ] stdout "osd_uuid": "8a88c47e-47c1-4c57-9919-6bcf9bb8da69",
[2020-08-24 21:22:09,070][ceph_volume.process][INFO  ] stdout "size": 107374182400,
[2020-08-24 21:22:09,070][ceph_volume.process][INFO  ] stdout "btime": "2020-08-24T21:21:28.277976+0000",
[2020-08-24 21:22:09,070][ceph_volume.process][INFO  ] stdout "description": "main",
[2020-08-24 21:22:09,070][ceph_volume.process][INFO  ] stdout "bfm_blocks": "1638400",
[2020-08-24 21:22:09,071][ceph_volume.process][INFO  ] stdout "bfm_blocks_per_key": "128",
[2020-08-24 21:22:09,071][ceph_volume.process][INFO  ] stdout "bfm_bytes_per_block": "65536",
[2020-08-24 21:22:09,071][ceph_volume.process][INFO  ] stdout "bfm_size": "107374182400",
[2020-08-24 21:22:09,071][ceph_volume.process][INFO  ] stdout "bluefs": "1",
[2020-08-24 21:22:09,071][ceph_volume.process][INFO  ] stdout "kv_backend": "rocksdb",
[2020-08-24 21:22:09,071][ceph_volume.process][INFO  ] stdout "mkfs_done": "yes"
[2020-08-24 21:22:09,071][ceph_volume.process][INFO  ] stdout }
[2020-08-24 21:22:09,071][ceph_volume.process][INFO  ] stdout }
[2020-08-24 21:22:09,071][ceph_volume][ERROR ] exception caught by decorator
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 150, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 110, in main
    self.list(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 66, in list
    report = self.generate(args.device)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 54, in generate
    whoami = oj[dev]['whoami']
KeyError: 'whoami'
2020-08-24 21:22:09.089452 I | cephosd: failed to get device already provisioned by ceph-volume raw. failed to retrieve ceph-volume raw list results: failed ceph-volume call (see ceph-volume log above for more details): exit status 1
2020-08-24 21:22:09.089461 W | cephosd: skipping OSD configuration as no devices matched the storage settings for this node "set1-data-2-2dh5w"
```

```
# ceph status
  cluster:
    id:     722f84a2-7a9a-430f-89a9-96b550e28245
    health: HEALTH_WARN
            Degraded data redundancy: 1 pg undersized
            OSD count 2 < osd_pool_default_size 3
 
  services:
    mon: 3 daemons, quorum a,b,c (age 21m)
    mgr: a(active, since 20m)
    osd: 2 osds: 2 up (since 20m), 2 in (since 20m)
 
  data:
    pools:   1 pools, 1 pgs
    objects: 0 objects, 0 B
    usage:   2.0 GiB used, 198 GiB / 200 GiB avail
    pgs:     1 active+undersized
```

**Environment**:
* OS (e.g. from /etc/os-release): Debian
* Kernel (e.g. `uname -a`): 4.19.0-0.bpo.6-amd64
* Cloud provider or hardware configuration: DigitalOcean
* Rook version (use `rook version` inside of a Rook Pod): 1.4.1
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)
* Kubernetes version (use `kubectl version`): 1.18.6
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): DigitalOcean managed kubernetes
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): Health_Warn

**Comment by okossuth** [comment]
Just adding the PVC information too:
```
$ kubectl get pvc -n rook-ceph
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS       AGE
rook-ceph-mon-a     Bound    pvc-cfa142ed-c5da-4ad9-94ef-d97fb601fe30   10Gi       RWO            do-block-storage   40m
rook-ceph-mon-b     Bound    pvc-ca575596-f98e-4fb9-8be5-6c9185e0b744   10Gi       RWO            do-block-storage   40m
rook-ceph-mon-c     Bound    pvc-fe2855fc-1205-4d06-aee5-defb4bc4dee0   10Gi       RWO            do-block-storage   40m
set1-data-0-vzphp   Bound    pvc-bd3e1183-b55b-41c6-9703-2ccdab5709a3   100Gi      RWO            do-block-storage   38m
set1-data-1-2rx72   Bound    pvc-a86cce73-d5ad-4eee-972c-a037f4b98e7e   100Gi      RWO            do-block-storage   38m
set1-data-2-2dh5w   Bound    pvc-90acaa51-11f8-464a-a41d-4b6af2417552   100Gi      RWO            do-block-storage   38m
```

**Comment by travisn** [comment]
@okossuth It sounds like you're hitting #5996. The fix is merged and will be included in v1.4.2, planned for tomorrow.

**Comment by okossuth** [comment]
@travisn Cool as soon 1.4.2 is out i will try it and update this issue. Thanks!

**Comment by okossuth** [comment]
@travisn Just tested rook 1.4.2 and finally the OSDs are created and configured successfully. Thanks!

**Comment by adabuleanu** [comment]
I am running rook 1.7.3 and seeing this in an environment with low IOPS. Please see attached [ceph.log](https://github.com/rook/rook/files/7241720/ceph.log) file for details

**Comment by travisn** [comment]
@adabuleanu What issue are you seeing? But instead of commenting on this issue, please join the [Rook Slack](http://slack.rook.io/) or open a new [discussion](https://github.com/rook/rook/discussions).
