### ISSUE TITLE
Ceph cannot create new OSD on clear disks

### ISSUE THREAD

**Issue by aido93** [rook/rook#6363]
**Is this a bug report or feature request?**

* Bug Report

**Bug Report**
Ceph cannot see existing disk

**Expected behavior:**
OSD can be successfully created.
**Deviation from expected behavior:**
OSD-prepare job creates ceph disk and I can check that it is created by `ls /dev` and `ls /dev/ceph-d685e6ed-a877-41c2-8b6d-9d94f994953f` from container and from host. But next job cannot see created disk (No such file or directory) but I also can check from container and from host that it exists. 
**How to reproduce it (minimal and precise):**

I don't know. I just follow official manual (https://github.com/rook/rook/blob/master/Documentation/ceph-quickstart.md#create-a-rook-ceph-cluster)
**File(s) to submit**:

* Cluster CR (custom ressource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

```
$ sudo lvm version
  LVM version:     2.02.185(2)-RHEL7 (2019-05-13)
  Library version: 1.02.158-RHEL7 (2019-05-13)
  Driver version:  4.34.0
  Configuration:   ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-default-dm-run-dir=/run --with-default-run-dir=/run/lvm --with-default-pid-dir=/run --with-default-locking-dir=/run/lock/lvm --with-usrlibdir=/usr/lib64 --enable-lvm1_fallback --enable-fsadm --with-pool=internal --enable-write_install --with-user= --with-group= --with-device-uid=0 --with-device-gid=6 --with-device-mode=0660 --enable-pkgconfig --enable-applib --enable-cmdlib --enable-dmeventd --enable-blkid_wiping --enable-python2-bindings --with-cluster=internal --with-clvmd=corosync --enable-cmirrord --with-udevdir=/usr/lib/udev/rules.d --enable-udev_sync --with-thin=internal --enable-lvmetad --with-cache=internal --enable-lvmpolld --enable-lvmlockd-dlm --enable-lvmlockd-sanlock --enable-dmfilemapd
$ kubectl -n rook-ceph logs rook-ceph-osd-prepare-node3-lk7pk
2020-10-03 20:54:48.602935 I | rookcmd: starting Rook v1.4.4 with arguments '/rook/rook ceph osd provision'
2020-10-03 20:54:48.603021 I | rookcmd: flag values: --cluster-id=e6aa3243-03b3-11eb-9587-ac1f6bbbc68c, --data-device-filter=all, --data-device-path-filter=, --data-devices=, --drive-groups=, --encrypted-device=false, --force-format=false, --help=false, --location=, --log-flush-frequency=5s, --log-level=DEBUG, --metadata-device=, --node-name=node3, --operator-image=, --osd-database-size=0, --osd-store=, --osd-wal-size=576, --osds-per-device=1, --pvc-backed-osd=false, --service-account=
2020-10-03 20:54:48.603031 I | op-mon: parsing mon endpoints: b=10.43.99.107:6789,c=10.43.214.111:6789,a=10.43.197.163:6789
2020-10-03 20:54:48.615858 I | op-osd: CRUSH location=root=default host=node3
2020-10-03 20:54:48.615880 I | cephcmd: crush location of osd: root=default host=node3
2020-10-03 20:54:48.615890 D | exec: Running command: nsenter --mount=/rootfs/proc/1/ns/mnt -- /usr/sbin/lvm --help
2020-10-03 20:54:48.627862 I | cephosd: successfully called nsenter
2020-10-03 20:54:48.627896 I | cephosd: binary "/usr/sbin/lvm" found on the host, proceeding with osd preparation
2020-10-03 20:54:48.636645 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2020-10-03 20:54:48.636723 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2020-10-03 20:54:48.636801 D | cephosd: config file @ /etc/ceph/ceph.conf: [global]
fsid                = 0f721594-d9ab-405e-a065-4ed3256dffe1
mon initial members = b c a
mon host            = [v2:10.43.99.107:3300,v1:10.43.99.107:6789],[v2:10.43.214.111:3300,v1:10.43.214.111:6789],[v2:10.43.197.163:3300,v1:10.43.197.163:6789]
public addr         = 10.42.2.104
cluster addr        = 10.42.2.104

[client.admin]
keyring = /var/lib/rook/rook-ceph/client.admin.keyring

2020-10-03 20:54:48.636808 I | cephosd: discovering hardware
2020-10-03 20:54:48.636815 D | exec: Running command: lsblk --all --noheadings --list --output KNAME
2020-10-03 20:54:48.640941 D | exec: Running command: lsblk /dev/sda --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.643788 D | exec: Running command: sgdisk --print /dev/sda
2020-10-03 20:54:48.647335 D | exec: Running command: udevadm info --query=property /dev/sda
2020-10-03 20:54:48.653517 D | exec: Running command: lsblk --noheadings --pairs /dev/sda
2020-10-03 20:54:48.667648 I | inventory: skipping device "sda" because it has child, considering the child instead.
2020-10-03 20:54:48.667680 D | exec: Running command: lsblk /dev/sda1 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.670036 D | exec: Running command: udevadm info --query=property /dev/sda1
2020-10-03 20:54:48.676480 D | exec: Running command: lsblk /dev/sda2 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.679058 D | exec: Running command: udevadm info --query=property /dev/sda2
2020-10-03 20:54:48.685369 D | exec: Running command: lsblk /dev/sda3 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.687730 D | exec: Running command: udevadm info --query=property /dev/sda3
2020-10-03 20:54:48.694136 D | exec: Running command: lsblk /dev/sdb --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.697598 D | exec: Running command: sgdisk --print /dev/sdb
2020-10-03 20:54:48.702948 D | exec: Running command: udevadm info --query=property /dev/sdb
2020-10-03 20:54:48.710754 D | exec: Running command: lsblk --noheadings --pairs /dev/sdb
2020-10-03 20:54:48.724563 I | inventory: skipping device "sdb" because it has child, considering the child instead.
2020-10-03 20:54:48.724611 D | exec: Running command: lsblk /dev/nbd0 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.727320 W | inventory: skipping device "nbd0". diskType is empty
2020-10-03 20:54:48.727340 D | exec: Running command: lsblk /dev/nbd1 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.730619 W | inventory: skipping device "nbd1". diskType is empty
2020-10-03 20:54:48.730649 D | exec: Running command: lsblk /dev/nbd2 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.733279 W | inventory: skipping device "nbd2". diskType is empty
2020-10-03 20:54:48.733323 D | exec: Running command: lsblk /dev/nbd3 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.737425 W | inventory: skipping device "nbd3". diskType is empty
2020-10-03 20:54:48.737469 D | exec: Running command: lsblk /dev/nbd4 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.740007 W | inventory: skipping device "nbd4". diskType is empty
2020-10-03 20:54:48.740034 D | exec: Running command: lsblk /dev/nbd5 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.742368 W | inventory: skipping device "nbd5". diskType is empty
2020-10-03 20:54:48.742392 D | exec: Running command: lsblk /dev/nbd6 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.745976 W | inventory: skipping device "nbd6". diskType is empty
2020-10-03 20:54:48.745999 D | exec: Running command: lsblk /dev/nbd7 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.749721 W | inventory: skipping device "nbd7". diskType is empty
2020-10-03 20:54:48.749761 D | exec: Running command: lsblk /dev/nbd8 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.753297 W | inventory: skipping device "nbd8". diskType is empty
2020-10-03 20:54:48.753324 D | exec: Running command: lsblk /dev/nbd9 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.757827 W | inventory: skipping device "nbd9". diskType is empty
2020-10-03 20:54:48.757847 D | exec: Running command: lsblk /dev/nbd10 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.759837 W | inventory: skipping device "nbd10". diskType is empty
2020-10-03 20:54:48.759856 D | exec: Running command: lsblk /dev/nbd11 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.761832 W | inventory: skipping device "nbd11". diskType is empty
2020-10-03 20:54:48.761849 D | exec: Running command: lsblk /dev/nbd12 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.763664 W | inventory: skipping device "nbd12". diskType is empty
2020-10-03 20:54:48.763680 D | exec: Running command: lsblk /dev/nbd13 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.765441 W | inventory: skipping device "nbd13". diskType is empty
2020-10-03 20:54:48.765470 D | exec: Running command: lsblk /dev/nbd14 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.767306 W | inventory: skipping device "nbd14". diskType is empty
2020-10-03 20:54:48.767325 D | exec: Running command: lsblk /dev/nbd15 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.769537 W | inventory: skipping device "nbd15". diskType is empty
2020-10-03 20:54:48.769555 D | exec: Running command: lsblk /dev/dm-0 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.775819 D | exec: Running command: sgdisk --print /dev/dm-0
2020-10-03 20:54:48.779010 D | exec: Running command: udevadm info --query=property /dev/dm-0
2020-10-03 20:54:48.788261 D | exec: Running command: lsblk /dev/dm-1 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.790358 D | exec: Running command: sgdisk --print /dev/dm-1
2020-10-03 20:54:48.794693 D | exec: Running command: udevadm info --query=property /dev/dm-1
2020-10-03 20:54:48.800392 D | inventory: discovered disks are [0xc00034eea0 0xc00034f320 0xc00034f680 0xc00023c480 0xc000210900]
2020-10-03 20:54:48.800410 I | cephosd: creating and starting the osds
2020-10-03 20:54:48.809397 D | cephosd: No Drive Groups configured.
2020-10-03 20:54:48.809462 D | cephosd: desiredDevices are [{Name:all OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: IsFilter:true IsDevicePathFilter:false}]
2020-10-03 20:54:48.809481 D | cephosd: context.Devices are [0xc00034eea0 0xc00034f320 0xc00034f680 0xc00023c480 0xc000210900]
2020-10-03 20:54:48.809503 D | exec: Running command: udevadm info --query=property /dev/sda1
2020-10-03 20:54:48.818620 D | exec: Running command: lsblk /dev/sda1 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-10-03 20:54:48.822010 D | exec: Running command: ceph-volume inventory --format json /dev/sda1
2020-10-03 20:54:49.434203 I | cephosd: skipping device "sda1": ["Insufficient space (<5GB)"].
2020-10-03 20:54:49.434229 I | cephosd: skipping device "sda2" because it contains a filesystem "ext3"
2020-10-03 20:54:49.434236 I | cephosd: skipping device "sda3" because it contains a filesystem "LVM2_member"
2020-10-03 20:54:49.434242 I | cephosd: skipping 'dm' device "dm-0"
2020-10-03 20:54:49.434247 I | cephosd: skipping 'dm' device "dm-1"
2020-10-03 20:54:49.434349 I | cephosd: configuring osd devices: {"Entries":{}}
2020-10-03 20:54:49.434360 I | cephosd: no new devices to configure. returning devices already configured with ceph-volume.
2020-10-03 20:54:49.434510 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm list  --format json
2020-10-03 20:54:49.794633 D | cephosd: {
    "1": [
        {
            "devices": [
                "/dev/sdb"
            ],
            "lv_name": "osd-data-6a20264a-d973-4d4a-aa3b-6c7579a2f1ce",
            "lv_path": "/dev/ceph-d685e6ed-a877-41c2-8b6d-9d94f994953f/osd-data-6a20264a-d973-4d4a-aa3b-6c7579a2f1ce",
            "lv_size": "931.51g",
            "lv_tags": "ceph.block_device=/dev/ceph-d685e6ed-a877-41c2-8b6d-9d94f994953f/osd-data-6a20264a-d973-4d4a-aa3b-6c7579a2f1ce,ceph.block_uuid=aJ1s3W-yxQE-D3ZM-Qu0y-gJMH-D8ts-B9d7a2,ceph.cephx_lockbox_secret=,ceph.cluster_fsid=0f721594-d9ab-405e-a065-4ed3256dffe1,ceph.cluster_name=ceph,ceph.crush_device_class=None,ceph.encrypted=0,ceph.osd_fsid=01caae9a-7e52-41db-bb6d-1d1ca0f66cf5,ceph.osd_id=1,ceph.osdspec_affinity=,ceph.type=block,ceph.vdo=0",
            "lv_uuid": "aJ1s3W-yxQE-D3ZM-Qu0y-gJMH-D8ts-B9d7a2",
            "name": "osd-data-6a20264a-d973-4d4a-aa3b-6c7579a2f1ce",
            "path": "/dev/ceph-d685e6ed-a877-41c2-8b6d-9d94f994953f/osd-data-6a20264a-d973-4d4a-aa3b-6c7579a2f1ce",
            "tags": {
                "ceph.block_device": "/dev/ceph-d685e6ed-a877-41c2-8b6d-9d94f994953f/osd-data-6a20264a-d973-4d4a-aa3b-6c7579a2f1ce",
                "ceph.block_uuid": "aJ1s3W-yxQE-D3ZM-Qu0y-gJMH-D8ts-B9d7a2",
                "ceph.cephx_lockbox_secret": "",
                "ceph.cluster_fsid": "0f721594-d9ab-405e-a065-4ed3256dffe1",
                "ceph.cluster_name": "ceph",
                "ceph.crush_device_class": "None",
                "ceph.encrypted": "0",
                "ceph.osd_fsid": "01caae9a-7e52-41db-bb6d-1d1ca0f66cf5",
                "ceph.osd_id": "1",
                "ceph.osdspec_affinity": "",
                "ceph.type": "block",
                "ceph.vdo": "0"
            },
            "type": "block",
            "vg_name": "ceph-d685e6ed-a877-41c2-8b6d-9d94f994953f"
        }
    ]
}
2020-10-03 20:54:49.794793 I | cephosd: osdInfo has 1 elements. [{Name:osd-data-6a20264a-d973-4d4a-aa3b-6c7579a2f1ce Path:/dev/ceph-d685e6ed-a877-41c2-8b6d-9d94f994953f/osd-data-6a20264a-d973-4d4a-aa3b-6c7579a2f1ce Tags:{OSDFSID:01caae9a-7e52-41db-bb6d-1d1ca0f66cf5 Encrypted:0 ClusterFSID:0f721594-d9ab-405e-a065-4ed3256dffe1} Type:block}]
2020-10-03 20:54:49.794810 I | cephosd: 1 ceph-volume lvm osd devices configured on this node
2020-10-03 20:54:49.794829 I | cephosd: devices = [{ID:1 Cluster:ceph UUID:01caae9a-7e52-41db-bb6d-1d1ca0f66cf5 DevicePartUUID: BlockPath:/dev/ceph-d685e6ed-a877-41c2-8b6d-9d94f994953f/osd-data-6a20264a-d973-4d4a-aa3b-6c7579a2f1ce MetadataPath: WalPath: SkipLVRelease:false Location: LVBackedPV:false CVMode:lvm Store:bluestore}]

$ kubectl -n rook-ceph logs rook-ceph-osd-1-54b7788f4f-9vbxt activate
+ OSD_ID=1
+ OSD_UUID=01caae9a-7e52-41db-bb6d-1d1ca0f66cf5
+ OSD_STORE_FLAG=--bluestore
+ OSD_DATA_DIR=/var/lib/ceph/osd/ceph-1
+ CV_MODE=lvm
+ DEVICE=/dev/ceph-d685e6ed-a877-41c2-8b6d-9d94f994953f/osd-data-6a20264a-d973-4d4a-aa3b-6c7579a2f1ce
+ METADATA_DEVICE=
+ WAL_DEVICE=
+ [[ lvm == \l\v\m ]]
++ mktemp -d
+ TMP_DIR=/tmp/tmp.GVw9BLIjNg
+ ceph-volume lvm activate --no-systemd --bluestore 1 01caae9a-7e52-41db-bb6d-1d1ca0f66cf5
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-1
Running command: /usr/bin/ceph-bluestore-tool --cluster=ceph prime-osd-dir --dev /dev/ceph-d685e6ed-a877-41c2-8b6d-9d94f994953f/osd-data-6a20264a-d973-4d4a-aa3b-6c7579a2f1ce --path /var/lib/ceph/osd/ceph-1 --no-mon-config
 stderr: failed to read label for /dev/ceph-d685e6ed-a877-41c2-8b6d-9d94f994953f/osd-data-6a20264a-d973-4d4a-aa3b-6c7579a2f1ce: (2) No such file or directory
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 39, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 150, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/main.py", line 42, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 341, in main
    self.activate(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 265, in activate
    activate_bluestore(lvs, no_systemd=args.no_systemd)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 172, in activate_bluestore
    process.run(prime_command)
  File "/usr/lib/python3.6/site-packages/ceph_volume/process.py", line 153, in run
    raise RuntimeError(msg)
RuntimeError: command returned non-zero exit status: 1
```

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux 7
* Kernel (e.g. `uname -a`): Linux node3 4.4.194-1.el7.elrepo.x86_64 #1 SMP Sat Sep 21 09:30:26 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: Rancher on baremetal
* Rook version (use `rook version` inside of a Rook Pod): v1.4.4
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 15.2.4 (7447c15c6ff58d7fce91843b705a268a1917325c) octopus (stable)
* Kubernetes version (use `kubectl version`): v1.14.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_WARN Reduced data availability: 1 pg inactive; Degraded data redundancy: 1 pg undersized; OSD count 1 < osd_pool_default_size 3

**Comment by leseb** [comment]
Maybe something is broken in ceph-volume in 15.2.4. I have no idea what's going on :-(

**Comment by aido93** [comment]
How can I verify it?

**Comment by leseb** [comment]
Please open a tracker bug https://tracker.ceph.com/ under the ceph-volume component. Thanks.
