### ISSUE TITLE
When upgrading to rook-1.1.9, osd reports Unable to find expected configuration key: "fsid" from section "global"

### ISSUE THREAD

**Issue by mengjinmm** [rook/rook#6446]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
All osd pods in a Error or CrashLoopBackOff state

**How to reproduce it (minimal and precise):**
We initially installed rook-0.9.3 version, and then upgraded to rook-1.0.6 version. At this time, the cluster is normal and the status is HEALTH_OK, but when upgrading from rook-1.0.6 to 1.1.9, the osd status is ERROR

POD Status:
`kubectl get pods -n rook-ceph -o wide`
```
NAME                                        READY     STATUS             RESTARTS   AGE
rook-ceph-mds-aps-a-688bc6bb7b-2xtbf        1/1       Running            0          3h
rook-ceph-mds-aps-b-67ff88d6c6-qbz9r        1/1       Running            0          3h
rook-ceph-mgr-a-7b557cc876-cr88q            1/1       Running            0          3h
rook-ceph-mon-d-7d6cc4c8c8-sh846            1/1       Running            0          6h
rook-ceph-mon-e-6f47b6dfc8-nh2mx            1/1       Running            0          6h
rook-ceph-mon-f-57cf875c4d-jvldl            1/1       Running            0          6h
rook-ceph-osd-0-576b6567d7-lpvh5            0/1       CrashLoopBackOff   14         47m
rook-ceph-osd-1-585fbb7b87-7ng6t            0/1       CrashLoopBackOff   3          2m
rook-ceph-osd-2-68d5f5d7cb-kdrww            0/1       CrashLoopBackOff   47         3h
rook-ceph-osd-prepare-172.20.50.191-9dh6t   0/1       Completed          0          48m
rook-ceph-osd-prepare-172.20.50.244-96cnw   0/1       Completed          0          48m
rook-ceph-osd-prepare-172.20.50.74-pxs7c    0/1       Completed          0          48m
rook-ceph-tools-654c747fdb-ztsnc            1/1       Running            0          19h
```

Logs
```
2020-10-16 06:17:27.034448 I | rookcmd: starting Rook v1.1.9 with arguments '/rook/rook ceph osd start -- --foreground --id 1 --fsid e7052dc4-0a95-4832-8497-733e4215a7ee --cluster ceph --setuser ceph --setgroup ceph --setuser-match-path /var/lib/rook/osd1 --osd-journal= --default-log-to-file false'
2020-10-16 06:17:27.071837 I | rookcmd: flag values: --help=false, --log-flush-frequency=5s, --log-level=INFO, --lv-path=, --operator-image=, --osd-id=1, --osd-store-type=filestore, --osd-uuid=4c93c583-216f-47e0-8313-225c736fc84d, --pvc-backed-osd=false, --service-account=
2020-10-16 06:17:27.071851 I | op-mon: parsing mon endpoints: d=ip1:6789,e=ip2:6789,f=ip3:6789
2020-10-16 06:17:27.073609 I | cephcmd: CRUSH location=root=default host=ip1
2020-10-16 06:17:27.170104 I | cephosd: Successfully updated lvm config file
2020-10-16 06:17:27.170150 I | exec: Running command: stdbuf -oL ceph-volume lvm activate --no-systemd --filestore 1 4c93c583-216f-47e0-8313-225c736fc84d
2020-10-16 06:17:32.936519 I | Traceback (most recent call last):
2020-10-16 06:17:32.936648 I |   File "/usr/sbin/ceph-volume", line 9, in <module>
2020-10-16 06:17:32.936665 I |     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
2020-10-16 06:17:32.936668 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 38, in __init__
2020-10-16 06:17:32.936682 I |     self.main(self.argv)
2020-10-16 06:17:32.936685 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
2020-10-16 06:17:32.936688 I |     return f(*a, **kw)
2020-10-16 06:17:32.936704 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 148, in main
2020-10-16 06:17:32.936706 I |     terminal.dispatch(self.mapper, subcommand_args)
2020-10-16 06:17:32.936709 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 182, in dispatch
2020-10-16 06:17:32.936712 I |     instance.main()
2020-10-16 06:17:32.936714 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 40, in main
2020-10-16 06:17:32.936717 I |     terminal.dispatch(self.mapper, self.argv)
2020-10-16 06:17:32.936719 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 182, in dispatch
2020-10-16 06:17:32.936722 I |     instance.main()
2020-10-16 06:17:32.936724 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 339, in main
2020-10-16 06:17:32.936729 I |     self.activate(args)
2020-10-16 06:17:32.936734 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
2020-10-16 06:17:32.936737 I |     return func(*a, **kw)
2020-10-16 06:17:32.936746 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 265, in activate
2020-10-16 06:17:32.936842 I |     activate_filestore(lvs, no_systemd=args.no_systemd)
2020-10-16 06:17:32.936858 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/activate.py", line 64, in activate_filestore
2020-10-16 06:17:32.936863 I |     prepare_utils.mount_osd(source, osd_id, is_vdo=is_vdo)
2020-10-16 06:17:32.936867 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/util/prepare.py", line 308, in mount_osd
2020-10-16 06:17:32.936957 I |     split=' ',
2020-10-16 06:17:32.936967 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/configuration.py", line 105, in get_list
2020-10-16 06:17:32.936975 I |     self.is_valid()
2020-10-16 06:17:32.936990 I |   File "/usr/lib/python2.7/site-packages/ceph_volume/configuration.py", line 76, in is_valid
2020-10-16 06:17:32.937007 I |     raise exceptions.ConfigurationKeyError('global', 'fsid')
2020-10-16 06:17:32.937046 I | ceph_volume.exceptions.ConfigurationKeyError: Unable to find expected configuration key: "fsid" from section "global"
failed to activate osd. Failed to complete '': exit status 1.
```

**Environment**:
* OS (e.g. from /etc/os-release): centos7
* Kernel (e.g. `uname -a`): 3.10.0-693.el7.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.1.9
* Storage backend version (e.g. for ceph do `ceph -v`): v14.2.1
* Kubernetes version (use `kubectl version`): v1.11.10
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

After investigation, we found that in version 1.0.6, the default-config-dir defined in osd is EmptyDir
> Volumes:
  **default-config-dir:**
    Type:    **EmptyDir** (a temporary directory that shares a pod's lifetime)
    Medium:
Mounts:
      /dev from devices (rw)
      **/etc/ceph from ceph-default-config-dir (rw)**
      /rook from rook-binaries (rw)
      /run/udev from run-udev (rw)
      /var/lib/rook from rook-data (rw)
      /var/log/ceph from rook-ceph-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rook-ceph-osd-token-8b5d8 (ro)

But in version 1.1.9, /ect/ceph is ConfigMap rook-config-override
`kubectl describe pods -n rook-ceph rook-ceph-osd-1-585fbb7b87-pkhbs`
> Mounts:
      **/etc/ceph from rook-config-override (ro)**
      /var/lib/rook from rook-data (rw)
      /var/log/ceph from rook-ceph-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from rook-ceph-osd-token-2zf56 (ro)
Volumes:
  **rook-config-override:**
    Type:      **ConfigMap** (a volume populated by a ConfigMap)
    Name:      rook-config-override
    Optional:  false

This results in no corresponding ceph.conf file in the /etc/ceph directory in the osd pod
`kubectl exec -it rook-ceph-osd-1-bb85fb988-gf95f -n rook-ceph bash`
```
# ll
total 0
lrwxrwxrwx 1 root root 16 Oct 16 06:37 ceph.conf -> ..data/ceph.conf
#cat ceph.conf
#Is empty

```

**Comment by leseb** [comment]
Can you try to add a content like so in the ConfigMap rook-config-override:

```text
[global]
fsid = <cluster fsid>
```

Thanks.

**Comment by mengjinmm** [comment]
I tried to add the relevant configuration in the ConfigMap like you said
`kubectl describe cm rook-config-override -n rook-ceph`
```
Name:         rook-config-override
Namespace:    rook-ceph
Labels:       <none>
Annotations:  <none>

Data
====
config:
----
[global]
fsid = e7052dc4-0a95-4832-8497-733e4215a7ee
```
osd can run normally and the status becomes RUNNING,but when I check the log, I find WARNING
```
2020-10-21 09:20:55.079780 I | 2020-10-21 09:20:55.078 7f9239d8ad80 -1 Falling back to public interface
2020-10-21 09:20:55.322091 I |  **** WARNING: no btrfs AND (no journal OR journal not in writeahead mode)**
2020-10-21 09:20:55.322133 I |              For non-btrfs volumes, a writeahead journal is required to
2020-10-21 09:20:55.322138 I |              maintain on-disk consistency in the event of a crash.  Your conf
2020-10-21 09:20:55.322199 I |              should include something like:
2020-10-21 09:20:55.322211 I |         osd journal = /path/to/journal_device_or_file
2020-10-21 09:20:55.322214 I |         filestore journal writeahead = true
2020-10-21 09:20:55.322217 I |  **** WARNING: No osd journal is configured: write latency may be high.**
2020-10-21 09:20:55.322221 I |              If you will not be using an osd journal, write latency may be
2020-10-21 09:20:55.322225 I |              relatively high.  It can be reduced somewhat by lowering
2020-10-21 09:20:55.322230 I |              filestore_max_sync_interval, but lower values mean lower write
2020-10-21 09:20:55.322235 I |              throughput, especially with spinning disks.
2020-10-21 09:20:55.705538 I | 2020-10-21 09:20:55.704 7f9239d8ad80 -1 osd.0 130 log_to_monitors {default=true}
2020-10-21 09:20:55.715044 I | 2020-10-21 09:20:55.713 7f922c397700 -1 osd.0 130 set_numa_affinity unable to identify public interface 'eth0' numa node: (2) No such file or directory
```
Whether these errors will have an impact in use

**Comment by leseb** [comment]
> I tried to add the relevant configuration in the ConfigMap like you said
> `kubectl describe cm rook-config-override -n rook-ceph`
> 
> ```
> Name:         rook-config-override
> Namespace:    rook-ceph
> Labels:       <none>
> Annotations:  <none>
> 
> Data
> ====
> config:
> ----
> [global]
> fsid = e7052dc4-0a95-4832-8497-733e4215a7ee
> ```
> 
> osd can run normally and the status becomes RUNNING,but when I check the log, I find WARNING
> 
> ```
> 2020-10-21 09:20:55.079780 I | 2020-10-21 09:20:55.078 7f9239d8ad80 -1 Falling back to public interface
> 2020-10-21 09:20:55.322091 I |  **** WARNING: no btrfs AND (no journal OR journal not in writeahead mode)**
> 2020-10-21 09:20:55.322133 I |              For non-btrfs volumes, a writeahead journal is required to
> 2020-10-21 09:20:55.322138 I |              maintain on-disk consistency in the event of a crash.  Your conf
> 2020-10-21 09:20:55.322199 I |              should include something like:
> 2020-10-21 09:20:55.322211 I |         osd journal = /path/to/journal_device_or_file
> 2020-10-21 09:20:55.322214 I |         filestore journal writeahead = true
> 2020-10-21 09:20:55.322217 I |  **** WARNING: No osd journal is configured: write latency may be high.**
> 2020-10-21 09:20:55.322221 I |              If you will not be using an osd journal, write latency may be
> 2020-10-21 09:20:55.322225 I |              relatively high.  It can be reduced somewhat by lowering
> 2020-10-21 09:20:55.322230 I |              filestore_max_sync_interval, but lower values mean lower write
> 2020-10-21 09:20:55.322235 I |              throughput, especially with spinning disks.
> 2020-10-21 09:20:55.705538 I | 2020-10-21 09:20:55.704 7f9239d8ad80 -1 osd.0 130 log_to_monitors {default=true}
> 2020-10-21 09:20:55.715044 I | 2020-10-21 09:20:55.713 7f922c397700 -1 osd.0 130 set_numa_affinity unable to identify public interface 'eth0' numa node: (2) No such file or directory
> ```
> 
> Whether these errors will have an impact in use

So this is a filestore OSD?

**Comment by mengjinmm** [comment]
> > I tried to add the relevant configuration in the ConfigMap like you said
> > `kubectl describe cm rook-config-override -n rook-ceph`
> > ```
> > Name:         rook-config-override
> > Namespace:    rook-ceph
> > Labels:       <none>
> > Annotations:  <none>
> > 
> > Data
> > ====
> > config:
> > ----
> > [global]
> > fsid = e7052dc4-0a95-4832-8497-733e4215a7ee
> > ```
> > 
> > 
> > osd can run normally and the status becomes RUNNING,but when I check the log, I find WARNING
> > ```
> > 2020-10-21 09:20:55.079780 I | 2020-10-21 09:20:55.078 7f9239d8ad80 -1 Falling back to public interface
> > 2020-10-21 09:20:55.322091 I |  **** WARNING: no btrfs AND (no journal OR journal not in writeahead mode)**
> > 2020-10-21 09:20:55.322133 I |              For non-btrfs volumes, a writeahead journal is required to
> > 2020-10-21 09:20:55.322138 I |              maintain on-disk consistency in the event of a crash.  Your conf
> > 2020-10-21 09:20:55.322199 I |              should include something like:
> > 2020-10-21 09:20:55.322211 I |         osd journal = /path/to/journal_device_or_file
> > 2020-10-21 09:20:55.322214 I |         filestore journal writeahead = true
> > 2020-10-21 09:20:55.322217 I |  **** WARNING: No osd journal is configured: write latency may be high.**
> > 2020-10-21 09:20:55.322221 I |              If you will not be using an osd journal, write latency may be
> > 2020-10-21 09:20:55.322225 I |              relatively high.  It can be reduced somewhat by lowering
> > 2020-10-21 09:20:55.322230 I |              filestore_max_sync_interval, but lower values mean lower write
> > 2020-10-21 09:20:55.322235 I |              throughput, especially with spinning disks.
> > 2020-10-21 09:20:55.705538 I | 2020-10-21 09:20:55.704 7f9239d8ad80 -1 osd.0 130 log_to_monitors {default=true}
> > 2020-10-21 09:20:55.715044 I | 2020-10-21 09:20:55.713 7f922c397700 -1 osd.0 130 set_numa_affinity unable to identify public interface 'eth0' numa node: (2) No such file or directory
> > ```
> > 
> > 
> > Whether these errors will have an impact in use
> 
> So this is a filestore OSD?

Yes, this is the osd log
