### ISSUE TITLE
ci: run external script create-external-cluster-resources.py unit tests randomly fails

### ISSUE THREAD

**Issue by leseb** [rook/rook#6665]
Failure is:

```
Successfully thrown error: Not a valid IP address: 10.103..212.133
..E.....
======================================================================
ERROR: test_monitoring_endpoint_validation (etc.ceph.create-external-cluster-resources.TestRadosJSON)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/etc/ceph/create-external-cluster-resources.py", line 982, in test_monitoring_endpoint_validation
    mon_ip, mon_port = self.rjObj.get_active_ceph_mgr()
  File "/etc/ceph/create-external-cluster-resources.py", line 367, in get_active_ceph_mgr
    self._invalid_endpoint(monitoring_endpoint)
  File "/etc/ceph/create-external-cluster-resources.py", line 214, in _invalid_endpoint
    "Out of range IP addresses: {}".format(ipv4))
etc.ceph.create-external-cluster-resources.ExecutionFailureException: Out of range IP addresses: 172.9.255.46

----------------------------------------------------------------------
Ran 8 tests in 0.176s

FAILED (errors=1)
Successfully thrown error: Not a proper endpoint: 10.103.212.133::8000, <IPv4>:<PORT>, format is expected
Successfully thrown error: Not a valid IP address: 10.10.103.212.133
```

Example https://github.com/rook/rook/pull/6553/checks?check_run_id=1417094023

**Comment by leseb** [comment]
Another one from https://github.com/rook/rook/pull/6693/checks?check_run_id=1443638305

```
I am tearing down the setup

.E......
======================================================================
ERROR: test_method_main_output (etc.ceph.create-external-cluster-resources.TestRadosJSON)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/etc/ceph/create-external-cluster-resources.py", line 812, in test_method_main_output
    self.rjObj.main()
  File "/etc/ceph/create-external-cluster-resources.py", line 761, in main
    generated_output = self.gen_json_out()
  File "/etc/ceph/create-external-cluster-resources.py", line 595, in gen_json_out
    self._gen_output_map()
  File "/etc/ceph/create-external-cluster-resources.py", line 580, in _gen_output_map
    self.out_map['MONITORING_ENDPOINT_PORT'] = self.get_active_ceph_mgr()
  File "/etc/ceph/create-external-cluster-resources.py", line 367, in get_active_ceph_mgr
    self._invalid_endpoint(monitoring_endpoint)
  File "/etc/ceph/create-external-cluster-resources.py", line 214, in _invalid_endpoint
    "Out of range IP addresses: {}".format(ipv4))
etc.ceph.create-external-cluster-resources.ExecutionFailureException: Out of range IP addresses: 172.9.255.236
```

**Comment by leseb** [comment]
One new one:

```
----------------------------------------------------------------------
Ran 8 tests in 0.197s

OK
I am in setup
AQBOgrNeAFgcGBAAvGqKOAD0D3xxmVY0R912dg==

I am tearing down the setup


I am in setup
JSON Output
[{"name": "rook-ceph-mon-endpoints", "kind": "ConfigMap", "data": {"data": "a=10.110.205.174:6789", "maxMonId": "0", "mapping": "{}"}}, {"name": "rook-ceph-mon", "kind": "Secret", "data": {"admin-secret": "admin-secret", "fsid": "af4e1673-0b72-402d-990a-22d2919d0f1c", "mon-secret": "mon-secret"}}, {"name": "rook-ceph-operator-creds", "kind": "Secret", "data": {"userID": "client.healthchecker", "userKey": "AQDFkbNeft5bFRAATndLNUSEKruozxiZi3lrdA=="}}, {"name": "rook-csi-rbd-node", "kind": "Secret", "data": {"userID": "csi-rbd-node", "userKey": "AQBOgrNeHbK1AxAAubYBeV8S1U/GPzq5SVeq6g=="}}, {"name": "ceph-rbd", "kind": "StorageClass", "data": {"pool": "abc"}}, {"name": "monitoring-endpoint", "kind": "CephCluster", "data": {"MonitoringEndpoint": "172.9.80.251", "MonitoringPort": "9283"}}, {"name": "rook-csi-rbd-provisioner", "kind": "Secret", "data": {"userID": "csi-rbd-provisioner", "userKey": "AQBNgrNe1geyKxAA8ekViRdE+hss5OweYBkwNg=="}}, {"name": "rook-csi-cephfs-provisioner", "kind": "Secret", "data": {"adminID": "csi-cephfs-provisioner", "adminKey": "AQBOgrNeAFgcGBAAvGqKOAD0D3xxmVY0R912dg=="}}, {"name": "rook-csi-cephfs-node", "kind": "Secret", "data": {"adminID": "csi-cephfs-node", "adminKey": "AQBOgrNeENunKxAAPCmgE7R6G8DcXnaJ1F32qg=="}}, {"name": "cephfs", "kind": "StorageClass", "data": {"fsName": "myfs", "pool": "myfs-data0"}}, {"name": "ceph-rgw", "kind": "StorageClass", "data": {"endpoint": "10.10.212.122:9000", "poolPrefix": "default"}}]



Shell Output
export ROOK_EXTERNAL_FSID=af4e1673-0b72-402d-990a-22d2919d0f1c
export ROOK_EXTERNAL_USERNAME=client.healthchecker
export ROOK_EXTERNAL_CEPH_MON_DATA=a=10.110.205.174:6789
export ROOK_EXTERNAL_USER_SECRET=AQDFkbNeft5bFRAATndLNUSEKruozxiZi3lrdA==
export CSI_RBD_NODE_SECRET_SECRET=AQBOgrNeHbK1AxAAubYBeV8S1U/GPzq5SVeq6g==
export CSI_RBD_PROVISIONER_SECRET=AQBNgrNe1geyKxAA8ekViRdE+hss5OweYBkwNg==
export CEPHFS_POOL_NAME=myfs-data0
export CEPHFS_FS_NAME=myfs
export CSI_CEPHFS_NODE_SECRET=AQBOgrNeENunKxAAPCmgE7R6G8DcXnaJ1F32qg==
export CSI_CEPHFS_PROVISIONER_SECRET=AQBOgrNeAFgcGBAAvGqKOAD0D3xxmVY0R912dg==
export RGW_ENDPOINT=10.10.212.122:9000
export MONITORING_ENDPOINT=172.9.80.251
export MONITORING_ENDPOINT_PORT=9283
export RBD_POOL_NAME=abc
export RGW_POOL_PREFIX=default



Non compatible output (--abcd)
Exception thrown successfully: Unsupported format: abcd

I am tearing down the setup


I am in setup
MonIP: 10.22.31.131, MonPort: 9283
MonIP: 10.177.3.81, MonPort: 9283
MonIP: 172.9.15.77, MonPort: 9283
MonIP: 172.9.15.77, MonPort: 9283
Exception thrown successfully: Not a valid IP address: 10.22.31.131.43
Exception thrown successfully: 'prometheus' service port must listen on 9283. You can change it with 'ceph config set mgr mgr/prometheus/server_port 9283'.

Exception thrown successfully: Out of range port number: 90320
Exception thrown successfully: Out of range port number: 73422
Exception thrown successfully: 'prometheus' service port must listen on 9283. You can change it with 'ceph config set mgr mgr/prometheus/server_port 9283'.


I am tearing down the setup


I am in setup
Modified JSON Cmd Out: [{'name': 'myfs', 'metadata_pool': 'myfs-metadata', 'metadata_pool_id': 2, 'data_pool_ids': [3], 'data_pools': ['myfs-data0', 'myfs-data1']}]
WARNING: Multiple data pools detected: ['myfs-data0', 'myfs-data1']
Using the data-pool: 'myfs-data1'

Successfully thrown error: Provided data-pool-name: 'myfs-data3', doesn't match from the data-pools' list: ['myfs-data0', 'myfs-data1']
Successfully thrown error: Provided data-pool-name: 'myfs-data3', doesn't match from the data-pools' list: []

I am tearing down the setup


I am in setup
As we are returning silently, no error thrown as expected
Successfully thrown error: Filesystem provided, 'myfs-2-non-existing-fs-name', is not found in the fs-list: '['myfs', 'myfs-2']'
Successfully thrown error: Filesystem provided, 'myfs-2-non-existing-fs-name', is not found in the fs-list: '[]'

I am tearing down the setup


I am in setup
Successfully thrown error.
Error: 'auth get-or-create client.healthchecker' command failed
Error: b'Dummy Error'

I am tearing down the setup


I am in setup
Updated user, client.healthchecker, successfully.

Updated user, client.healthchecker, successfully.


I am tearing down the setup


I am in setup
Successfully thrown error: Out of range port number: 238000
Successfully thrown error: Out of range IP addresses: 10.1033.212.133
Successfully thrown error: Not a valid IP address: 10.103..212.133
Successfully thrown error: Not a proper endpoint: 10.103.212.133::8000, <IPv4>:<PORT>, format is expected
Successfully thrown error: Not a valid IP address: 10.10.103.212.133

I am tearing down the setup

command terminated with exit code 139
```

**Comment by travisn** [comment]
Haven't seen this for a while, let's reopen if we see it again.

**Comment by leseb** [comment]
Actually, it could still occur and the fix is in https://github.com/rook/rook/pull/7217
