### ISSUE TITLE
Random unit test failures on TestStartMGR and TestCheckHealth

### ISSUE THREAD

**Issue by leseb** [rook/rook#6698]
Example job: https://github.com/rook/rook/pull/6693/checks?check_run_id=1449156427

```
2020-11-24T17:33:54.9642743Z === RUN   TestStartMGR
2020-11-24T17:33:54.9643526Z 2020-11-24 17:33:54.945500 I | op-mgr: start running mgr
2020-11-24T17:33:54.9644367Z --- FAIL: TestStartMGR (0.00s)
2020-11-24T17:33:54.9645113Z panic: runtime error: invalid memory address or nil pointer dereference
2020-11-24T17:33:54.9646083Z 	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2020-11-24T17:33:54.9647065Z 	panic: runtime error: invalid memory address or nil pointer dereference
2020-11-24T17:33:54.9647923Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1209827]
2020-11-24T17:33:54.9648420Z 
2020-11-24T17:33:54.9648814Z goroutine 40 [running]:
2020-11-24T17:33:54.9649426Z testing.tRunner.func1(0xc0000db600)
2020-11-24T17:33:54.9650347Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:874 +0x3a3
2020-11-24T17:33:54.9650998Z panic(0x160e7e0, 0x264d9f0)
2020-11-24T17:33:54.9651695Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
2020-11-24T17:33:54.9652449Z github.com/tevino/abool.(*AtomicBool).UnSet(0x0)
2020-11-24T17:33:54.9653239Z 	/home/runner/go/pkg/mod/github.com/tevino/abool@v1.2.0/bool.go:33 +0x7
2020-11-24T17:33:54.9653858Z panic(0x160e7e0, 0x264d9f0)
2020-11-24T17:33:54.9654556Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
2020-11-24T17:33:54.9655292Z github.com/tevino/abool.(*AtomicBool).IsSet(...)
2020-11-24T17:33:54.9656079Z 	/home/runner/go/pkg/mod/github.com/tevino/abool@v1.2.0/bool.go:38
2020-11-24T17:33:54.9657396Z github.com/rook/rook/pkg/operator/ceph/controller.CheckForCancelledOrchestration(0xc000417200, 0xc000500800)
2020-11-24T17:33:54.9658928Z 	/home/runner/go/src/github.com/rook/rook/pkg/operator/ceph/controller/controller_utils.go:56 +0x76
2020-11-24T17:33:54.9659984Z github.com/rook/rook/pkg/operator/ceph/cluster/mgr.(*Cluster).Start(0xc00040ae00, 0xc00040ae38, 0xc0000d5920)
2020-11-24T17:33:54.9661141Z 	/home/runner/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mgr/mgr.go:118 +0x1b1
2020-11-24T17:33:54.9662099Z github.com/rook/rook/pkg/operator/ceph/cluster/mgr.TestStartMGR(0xc0000db600)
2020-11-24T17:33:54.9663139Z 	/home/runner/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mgr/mgr_test.go:73 +0x59e
2020-11-24T17:33:54.9663938Z testing.tRunner(0xc0000db600, 0x18ab3a8)
2020-11-24T17:33:54.9664727Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:909 +0xc9
2020-11-24T17:33:54.9665382Z created by testing.(*T).Run
2020-11-24T17:33:54.9666086Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:960 +0x350
2020-11-24T17:33:54.9666889Z FAIL	github.com/rook/rook/pkg/operator/ceph/cluster/mgr	0.031s
2020-11-24T17:33:58.3465901Z === RUN   TestCreateClusterSecrets
2020-11-24T17:33:58.3468922Z 2020-11-24 17:33:58.334105 I | op-mon: COMMAND: ceph-authtool [--create-keyring ns/mon.keyring --gen-key -n mon. --cap mon 'allow *']
2020-11-24T17:33:58.3471363Z 2020-11-24 17:33:58.334291 I | op-mon: COMMAND: ceph-authtool [--create-keyring ns/client.admin.keyring --gen-key -n client.admin --cap mon 'allow *' --cap osd 'allow *' --cap mgr 'allow *' --cap mds 'allow']
2020-11-24T17:33:58.3473523Z 2020-11-24 17:33:58.334343 I | op-mon: creating mon secrets for a new cluster
2020-11-24T17:33:58.3474940Z --- PASS: TestCreateClusterSecrets (0.00s)
2020-11-24T17:33:58.3475985Z === RUN   TestMonFlattening
2020-11-24T17:33:58.3477307Z 2020-11-24 17:33:58.334758 I | op-mon: parsing mon endpoints: foo=1.2.3.4:5000
2020-11-24T17:33:58.3478655Z 2020-11-24 17:33:58.334773 I | op-mon: parsing mon endpoints: foo=1.2.3.4:5000,bar=2.3.4.5:6000
2020-11-24T17:33:58.3479869Z --- PASS: TestMonFlattening (0.00s)
2020-11-24T17:33:58.3481190Z === RUN   TestCheckHealth
2020-11-24T17:33:58.3482492Z 2020-11-24 17:33:58.334954 E | cephclient: clusterInfo is nil
2020-11-24T17:33:58.3483717Z 2020-11-24 17:33:58.334989 I | op-mon: initial mons: map[a:0xc0004eee80]
2020-11-24T17:33:58.3485255Z 2020-11-24 17:33:58.335251 I | op-mon: adding mons. currently 1 mons are in quorum and the desired count is 3.
2020-11-24T17:33:58.3486511Z --- FAIL: TestCheckHealth (0.00s)
2020-11-24T17:33:58.3487663Z panic: runtime error: invalid memory address or nil pointer dereference
2020-11-24T17:33:58.3491976Z 	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2020-11-24T17:33:58.3493246Z 	panic: runtime error: invalid memory address or nil pointer dereference
2020-11-24T17:33:58.3494258Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11cb377]
2020-11-24T17:33:58.3494878Z 
2020-11-24T17:33:58.3495418Z goroutine 9 [running]:
2020-11-24T17:33:58.3496124Z testing.tRunner.func1(0xc000474800)
2020-11-24T17:33:58.3497207Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:874 +0x3a3
2020-11-24T17:33:58.3498007Z panic(0x15fe9e0, 0x262ce20)
2020-11-24T17:33:58.3498838Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
2020-11-24T17:33:58.3499836Z github.com/tevino/abool.(*AtomicBool).UnSet(0x0)
2020-11-24T17:33:58.3500774Z 	/home/runner/go/pkg/mod/github.com/tevino/abool@v1.2.0/bool.go:33 +0x7
2020-11-24T17:33:58.3501549Z panic(0x15fe9e0, 0x262ce20)
2020-11-24T17:33:58.3502366Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
2020-11-24T17:33:58.3503244Z github.com/tevino/abool.(*AtomicBool).IsSet(...)
2020-11-24T17:33:58.3504155Z 	/home/runner/go/pkg/mod/github.com/tevino/abool@v1.2.0/bool.go:38
2020-11-24T17:33:58.3505737Z github.com/rook/rook/pkg/operator/ceph/controller.CheckForCancelledOrchestration(0xc0004c4240, 0xc00003eb00)
2020-11-24T17:33:58.3507647Z 	/home/runner/go/src/github.com/rook/rook/pkg/operator/ceph/controller/controller_utils.go:56 +0x76
2020-11-24T17:33:58.3509000Z github.com/rook/rook/pkg/operator/ceph/cluster/mon.(*Cluster).assignMons(0xc0004be480, 0xc0004ef380, 0x3, 0x4, 0x0, 0x0)
2020-11-24T17:33:58.3510201Z 	/home/runner/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mon/mon.go:726 +0x132
2020-11-24T17:33:58.3511857Z github.com/rook/rook/pkg/operator/ceph/cluster/mon.(*Cluster).startMons(0xc0004be480, 0x3, 0x183cf4f, 0x49)
2020-11-24T17:33:58.3513082Z 	/home/runner/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mon/mon.go:229 +0xc2
2020-11-24T17:33:58.3514299Z github.com/rook/rook/pkg/operator/ceph/cluster/mon.(*Cluster).checkHealth(0xc0004be480, 0x0, 0x0)
2020-11-24T17:33:58.3515519Z 	/home/runner/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mon/health.go:214 +0xea5
2020-11-24T17:33:58.3516643Z github.com/rook/rook/pkg/operator/ceph/cluster/mon.TestCheckHealth(0xc000474800)
2020-11-24T17:33:58.3517748Z 	/home/runner/go/src/github.com/rook/rook/pkg/operator/ceph/cluster/mon/health_test.go:92 +0x6e2
2020-11-24T17:33:58.3518671Z testing.tRunner(0xc000474800, 0x1893380)
2020-11-24T17:33:58.3519470Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:909 +0xc9
2020-11-24T17:33:58.3520124Z created by testing.(*T).Run
2020-11-24T17:33:58.3520851Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:960 +0x350
2020-11-24T17:33:58.3521652Z FAIL	github.com/rook/rook/pkg/operator/ceph/cluster/mon	0.028s
```

**Comment by leseb** [comment]
NOTABUG
