### ISSUE TITLE
Crashloop and high CPU on csi-cephfsplugin-provisioner

### ISSUE THREAD

**Issue by maximilize** [rook/rook#6782]
**Is this a bug report or feature request?**
* Bug Report

I have cephfs running in production, together with `external-snapshotter v3.0.2`. It seems that there are some issues with snapshotting.

One `csi-cephfsplugin-provisioner` pod is always at very high CPU, specifically the `csi-cephfsplugin` container. It's mostly near to 2 CPU cores usage, and after a quite long time (in the logs attached about 30 minutes), the pod crashes.

**How to reproduce it (minimal and precise):**

1. Create a cephfs filesystem
2. Use https://github.com/kubernetes-csi/external-snapshotter for snapshots
3. For example use the snapshot feature of `velero`, or create a snapshot of the filesystem manually.

**File(s) to submit**:
[csi-cephfsplugin.log](https://github.com/rook/rook/files/5647338/csi-cephfsplugin.log)

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04
* Cloud provider or hardware configuration: Bare metal
* Rook version (use `rook version` inside of a Rook Pod): v1.5.3
* Storage backend version (e.g. for ceph do `ceph -v`): v15.2.7
* Kubernetes version (use `kubectl version`): v1.19.3
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): RKE
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): Healthy

**Comment by maximilize** [comment]
The snapshots got stuck in `ReadyToUse=false` state. After deleting the failed snapshots, the provisioner was working normal again. However, there is a bug when creating snapshots in some cases, causing high CPU load for the provisioner.

**Comment by travisn** [comment]
@maximilize Please open an issue in the [ceph-csi](https://www.github.com/ceph/ceph-csi) repo for this. CSI issues need to be addressed there, and then will be integrated to Rook. Thanks!

**Comment by Madhu-1** [comment]
@maximilize what is the cephcsi version  you are using, we had a bug in cephcsi for cephfs snapshot and clone and its fixed now https://github.com/ceph/ceph-csi/pull/1671


>2020-12-05T15:17:39.484648350Z E1205 15:17:39.484553       1 snapshot.go:68] ID: 12872 Req-ID: snapshot-fdc8a577-a9ce-4458-94cf-0d9f8c63d060 failed to create subvolume snapshot csi-snap-0315b5fb-370d-11eb-b29b-12ad88af303e csi-vol-f7e87189-2da7-11eb-b453-9a748bd01905 in fs myfs with Error: an error (exit status 22) and stdError (Error EINVAL: Traceback (most recent call last):
2020-12-05T15:17:39.484669931Z   File "/usr/share/ceph/mgr/volumes/fs/operations/snapshot_util.py", line 14, in mksnap
2020-12-05T15:17:39.484672616Z     fs.mkdir(snappath, 0o755)
2020-12-05T15:17:39.484674499Z   File "cephfs.pyx", line 907, in cephfs.LibCephFS.mkdir
2020-12-05T15:17:39.484676383Z cephfs.Error: error in mkdir /volumes/csi/csi-vol-f7e87189-2da7-11eb-b453-9a748bd01905/a7744e5e-820c-4700-95d0-91c53c6f3020/.snap/csi-snap-0315b5fb-370d-11eb-b29b-12ad88af303e: Too many links [Errno 31]
2020-12-05T15:17:39.484678437Z 
2020-12-05T15:17:39.484680461Z During handling of the above exception, another exception occurred:
2020-12-05T15:17:39.484693936Z 
2020-12-05T15:17:39.484695539Z Traceback (most recent call last):
2020-12-05T15:17:39.484697132Z   File "/usr/share/ceph/mgr/mgr_module.py", line 1177, in _handle_command
2020-12-05T15:17:39.484698795Z     return self.handle_command(inbuf, cmd)
2020-12-05T15:17:39.484700318Z   File "/usr/share/ceph/mgr/volumes/module.py", line 367, in handle_command
2020-12-05T15:17:39.484701961Z     return handler(inbuf, cmd)
2020-12-05T15:17:39.484703484Z   File "/usr/share/ceph/mgr/volumes/module.py", line 467, in _cmd_fs_subvolume_snapshot_create
2020-12-05T15:17:39.484705127Z     group_name=cmd.get('group_name', None))
2020-12-05T15:17:39.484706650Z   File "/usr/share/ceph/mgr/volumes/fs/volume.py", line 305, in create_subvolume_snapshot
2020-12-05T15:17:39.484708363Z     subvolume.create_snapshot(snapname)
2020-12-05T15:17:39.484709876Z   File "/usr/share/ceph/mgr/volumes/fs/operations/versions/subvolume_v1.py", line 202, in create_snapshot
2020-12-05T15:17:39.484711609Z     mksnap(self.fs, snappath)
2020-12-05T15:17:39.484713112Z   File "/usr/share/ceph/mgr/volumes/fs/operations/snapshot_util.py", line 18, in mksnap
2020-12-05T15:17:39.484714745Z     raise VolumeException(-e.args[0], e.args[1])
2020-12-05T15:17:39.484716278Z TypeError: bad operand type for unary -: 'str'
2020-12-05T15:17:39.484717791Z 

Looks like you are hitting the limit, you can have maximum of 100 snapshots on a subvolume not more than that.

**Comment by maximilize** [comment]
@Madhu-1 The limit of 100 snapshots was reached, thanks for pointing this out. Issue solved.

I don't test the ceph-csi patch for now since I'm working with the stable rook-ceph branch.
