### ISSUE TITLE
osd not created on fresh ubuntu 20.04 installation

### ISSUE THREAD

**Issue by cfuntis** [rook/rook#6889]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
OSD not created.

**Expected behavior:**
After adding a new disk under ubunto 20.04, rook should create a new OSD Pod.

**How to reproduce it (minimal and precise):**
Existing Rook/Ceph Cluster with 3 OSD running on RancherOS, removed OSD 1 and tried to replace the Node/OSD with a new one (OS Ubuntu 20.04 instead of RancherOS) 

**File(s) to submit**:

rook-ceph-operator:
```
2020-12-29 08:34:28.467964 I | op-osd: osd orchestration status for node regice is starting
2020-12-29 08:34:28.467975 I | op-osd: 2/4 node(s) completed osd provisioning, resource version 185201610
2020-12-29 08:34:28.713479 I | op-osd: osd orchestration status for node rayquaza is computingDiff
2020-12-29 08:34:28.972915 I | op-osd: osd orchestration status for node rayquaza is orchestrating
2020-12-29 08:34:29.616378 I | op-osd: osd orchestration status for node rayquaza is completed
2020-12-29 08:34:29.616408 I | op-osd: starting 1 osd daemons on node rayquaza
2020-12-29 08:34:29.616424 I | cephclient: getting or creating ceph auth key "osd.0"
2020-12-29 08:34:29.906745 I | op-osd: duplicate env var "POD_NAMESPACE" skipped on container "osd"
2020-12-29 08:34:29.906773 I | op-osd: duplicate env var "NODE_NAME" skipped on container "osd"
2020-12-29 08:34:29.936159 I | op-k8sutil: deployment "rook-ceph-osd-0" did not change, nothing to update
2020-12-29 08:34:29.952196 I | op-osd: osd orchestration status for node regice is computingDiff
2020-12-29 08:34:30.016910 I | op-osd: osd orchestration status for node regice is orchestrating
2020-12-29 08:34:30.098720 I | cephclient: command failed for set dashboard creds. trying again...
2020-12-29 08:34:30.372192 W | cephclient: failed to set mgr module mode "upmap". trying again...
2020-12-29 08:34:33.511965 I | op-osd: osd orchestration status for node regice is failed
2020-12-29 08:34:33.512047 E | op-osd: orchestration for node regice failed: &{OSDs:[] Status:failed PvcBackedOSD:false Message:failed to configure devices: failed to initialize devices: failed ceph-volume: exit status 1}
2020-12-29 08:34:33.512067 I | op-osd: 4/4 node(s) completed osd provisioning
```

rook-ceph-osd-prepare:
```
2020-12-29 08:34:34.016063 I | rookcmd: starting Rook v1.4.8 with arguments '/rook/rook ceph osd provision'
2020-12-29 08:34:34.016119 I | rookcmd: flag values: --cluster-id=a98bfc5e-f408-11e9-9200-000c29f4e2c5, --data-device-filter=^sdb, --data-device-path-filter=, --data-devices=, --drive-groups=, --encrypted-device=false, --force-format=false, --help=false, --location=, --log-flush-frequency=5s, --log-level=DEBUG, --metadata-device=, --node-name=regice, --operator-image=, --osd-database-size=0, --osd-store=, --osd-wal-size=576, --osds-per-device=1, --pvc-backed-osd=false, --service-account=
2020-12-29 08:34:34.016123 I | op-mon: parsing mon endpoints: be=10.43.8.19:6789,ay=10.43.76.75:6789,ax=10.43.183.191:6789
2020-12-29 08:34:34.033755 I | op-osd: CRUSH location=root=default host=regice
2020-12-29 08:34:34.033791 I | cephcmd: crush location of osd: root=default host=regice
2020-12-29 08:34:34.033810 D | exec: Running command: nsenter --mount=/rootfs/proc/1/ns/mnt -- /usr/sbin/lvm --help
2020-12-29 08:34:34.052558 I | cephosd: successfully called nsenter
2020-12-29 08:34:34.052604 I | cephosd: binary "/usr/sbin/lvm" found on the host, proceeding with osd preparation
2020-12-29 08:34:34.074113 D | cephclient: No ceph configuration override to merge as "rook-config-override" configmap is empty
2020-12-29 08:34:34.074157 I | cephclient: writing config file /var/lib/rook/rook-ceph/rook-ceph.config
2020-12-29 08:34:34.074391 I | cephclient: generated admin config in /var/lib/rook/rook-ceph
2020-12-29 08:34:34.074624 D | cephosd: config file @ /etc/ceph/ceph.conf: [global]
fsid                = 688315d3-311e-46f9-aa0d-29fdb17d6d6c
mon initial members = ax be ay
mon host            = [v2:10.43.183.191:3300,v1:10.43.183.191:6789],[v2:10.43.8.19:3300,v1:10.43.8.19:6789],[v2:10.43.76.75:3300,v1:10.43.76.75:6789]
public addr         = 10.42.6.72
cluster addr        = 10.42.6.72
[client.admin]
keyring = /var/lib/rook/rook-ceph/client.admin.keyring
2020-12-29 08:34:34.074653 I | cephosd: discovering hardware
2020-12-29 08:34:34.074674 D | exec: Running command: lsblk --all --noheadings --list --output KNAME
2020-12-29 08:34:34.081146 D | exec: Running command: lsblk /dev/loop0 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.085425 W | inventory: skipping device "loop0". unsupported diskType loop
2020-12-29 08:34:34.085468 D | exec: Running command: lsblk /dev/loop1 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.089680 W | inventory: skipping device "loop1". unsupported diskType loop
2020-12-29 08:34:34.089763 D | exec: Running command: lsblk /dev/loop2 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.094587 W | inventory: skipping device "loop2". unsupported diskType loop
2020-12-29 08:34:34.094611 D | exec: Running command: lsblk /dev/loop3 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.098970 W | inventory: skipping device "loop3". unsupported diskType loop
2020-12-29 08:34:34.098994 D | exec: Running command: lsblk /dev/loop4 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.103370 W | inventory: skipping device "loop4". unsupported diskType loop
2020-12-29 08:34:34.103401 D | exec: Running command: lsblk /dev/loop5 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.107702 W | inventory: skipping device "loop5". unsupported diskType loop
2020-12-29 08:34:34.107730 D | exec: Running command: lsblk /dev/loop6 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.111725 W | inventory: skipping device "loop6". diskType is empty
2020-12-29 08:34:34.111796 D | exec: Running command: lsblk /dev/loop7 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.115751 W | inventory: skipping device "loop7". diskType is empty
2020-12-29 08:34:34.115790 D | exec: Running command: lsblk /dev/sda --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.119986 D | exec: Running command: sgdisk --print /dev/sda
2020-12-29 08:34:34.125849 D | exec: Running command: udevadm info --query=property /dev/sda
2020-12-29 08:34:34.140994 D | exec: Running command: lsblk --noheadings --pairs /dev/sda
2020-12-29 08:34:34.151186 I | inventory: skipping device "sda" because it has child, considering the child instead.
2020-12-29 08:34:34.151263 D | exec: Running command: lsblk /dev/sda1 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.156117 D | exec: Running command: udevadm info --query=property /dev/sda1
2020-12-29 08:34:34.170166 D | exec: Running command: lsblk /dev/sda2 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.176006 D | exec: Running command: udevadm info --query=property /dev/sda2
2020-12-29 08:34:34.184649 D | exec: Running command: lsblk /dev/sda3 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.189648 D | exec: Running command: udevadm info --query=property /dev/sda3
2020-12-29 08:34:34.201089 D | exec: Running command: lsblk /dev/sdb --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.205408 D | exec: Running command: sgdisk --print /dev/sdb
2020-12-29 08:34:34.211000 D | exec: Running command: udevadm info --query=property /dev/sdb
2020-12-29 08:34:34.222993 D | exec: Running command: lsblk --noheadings --pairs /dev/sdb
2020-12-29 08:34:34.231556 I | inventory: skipping device "sdb" because it has child, considering the child instead.
2020-12-29 08:34:34.231584 D | exec: Running command: lsblk /dev/sr0 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.235793 W | inventory: skipping device "sr0". unsupported diskType rom
2020-12-29 08:34:34.235860 D | exec: Running command: lsblk /dev/dm-0 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.238505 D | exec: Running command: sgdisk --print /dev/dm-0
2020-12-29 08:34:34.244122 D | exec: Running command: udevadm info --query=property /dev/dm-0
2020-12-29 08:34:34.249448 D | exec: Running command: lsblk /dev/dm-1 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.252172 D | exec: Running command: sgdisk --print /dev/dm-1
2020-12-29 08:34:34.256625 D | exec: Running command: udevadm info --query=property /dev/dm-1
2020-12-29 08:34:34.263701 D | inventory: discovered disks are [0xc0001db7a0 0xc0001b1e60 0xc0001aaea0 0xc000156900 0xc0001477a0]
2020-12-29 08:34:34.263716 I | cephosd: creating and starting the osds
2020-12-29 08:34:34.275778 D | cephosd: No Drive Groups configured.
2020-12-29 08:34:34.275835 D | cephosd: desiredDevices are [{Name:^sdb OSDsPerDevice:1 MetadataDevice: DatabaseSizeMB:0 DeviceClass: IsFilter:true IsDevicePathFilter:false}]
2020-12-29 08:34:34.275849 D | cephosd: context.Devices are [0xc0001db7a0 0xc0001b1e60 0xc0001aaea0 0xc000156900 0xc0001477a0]
2020-12-29 08:34:34.275861 D | exec: Running command: udevadm info --query=property /dev/sda1
2020-12-29 08:34:34.280466 D | exec: Running command: lsblk /dev/sda1 --bytes --nodeps --pairs --paths --output SIZE,ROTA,RO,TYPE,PKNAME,NAME,KNAME
2020-12-29 08:34:34.284938 D | exec: Running command: ceph-volume inventory --format json /dev/sda1
2020-12-29 08:34:34.810627 I | cephosd: skipping device "sda1": ["Insufficient space (<5GB)"].
2020-12-29 08:34:34.810663 I | cephosd: skipping device "sda2" because it contains a filesystem "ext4"
2020-12-29 08:34:34.810674 I | cephosd: skipping device "sda3" because it contains a filesystem "LVM2_member"
2020-12-29 08:34:34.810683 I | cephosd: skipping 'dm' device "dm-0"
2020-12-29 08:34:34.810690 I | cephosd: skipping 'dm' device "dm-1"
2020-12-29 08:34:34.810849 I | cephosd: configuring osd devices: {"Entries":{}}
2020-12-29 08:34:34.810857 I | cephosd: no new devices to configure. returning devices already configured with ceph-volume.
2020-12-29 08:34:34.811166 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm list  --format json
2020-12-29 08:34:35.127372 D | cephosd: {}
2020-12-29 08:34:35.127428 I | cephosd: 0 ceph-volume lvm osd devices configured on this node
2020-12-29 08:34:35.127441 W | cephosd: skipping OSD configuration as no devices matched the storage settings for this node "regice"
```

lsblk:
```
NAME                                                                                                 MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0                                                                                                  7:0    0 55.3M  1 loop /snap/core18/1885
loop1                                                                                                  7:1    0 55.4M  1 loop /snap/core18/1944
loop2                                                                                                  7:2    0 70.6M  1 loop /snap/lxd/16922
loop3                                                                                                  7:3    0 67.8M  1 loop /snap/lxd/18150
loop4                                                                                                  7:4    0   31M  1 loop /snap/snapd/9721
loop5                                                                                                  7:5    0 31.1M  1 loop /snap/snapd/10492
sda                                                                                                    8:0    0   40G  0 disk 
├─sda1                                                                                                 8:1    0    1M  0 part 
├─sda2                                                                                                 8:2    0    1G  0 part /boot
└─sda3                                                                                                 8:3    0   19G  0 part 
  └─ubuntu--vg-ubuntu--lv                                                                            253:0    0   19G  0 lvm  /
sdb                                                                                                    8:16   0  550G  0 disk 
└─ceph--65dace2d--7750--4623--8176--efc8ce1acf4e-osd--data--0f81a840--2513--4530--a3c1--ca011c0d9ae0 253:1    0  550G  0 lvm  
sr0                                                                                                   11:0    1  914M  0 rom
```

**Environment**:
* OS: Ubuntu 20.04.1 LTS (Focal Fossa)
* Kernel: 5.4.0-58-generic
* Rook version: v1.4.8
* Storage backend version: ceph/ceph:v15.2.4-20200819
* Kubernetes version: v1.17.6
* Kubernetes cluster type: Kubernetes on VMs provided by VMWare EXSi (Rancher v2.4.6)
* Storage backend status: HEALTH_ERR 1 filesystem is offline

**Comment by leseb** [comment]
@cfuntis which disk are you expecting to become an OSD?

**Comment by cfuntis** [comment]
from "lsblk": sdb - disk was unused before, ceph-** are automatically created from the operator but not found (tried multiple time, cleaned everything as described in the documentation)

**Comment by leseb** [comment]
Make sure you remove the `dm` before each attempt. Rook refuses dm devices.

That should do the trick.

**Comment by leseb** [comment]
> Make sure you remove the `dm` before each attempt. Rook refuses dm devices. Like `dmsetup remove`.
> 
> That should do the trick.

**Comment by zerkms** [comment]
Just experienced it as well: identical symptoms. Reverted to 1.4.3 to get the operator working back.

**Comment by leseb** [comment]
> Just experienced it as well: identical symptoms. Reverted to 1.4.3 to get the operator working back.
> 
> Regarding "Make sure you remove the dm before each attempt." --- in my case there were no `dm`s, since I restarted a node between every attempt.
> 
> My steps were:
> 
> 1. Zap the disk
> 2. Reboot node
> 3. Add it to the rook/ceph cluster
> 
> Observed behaviour: on an empty disk (double checked with `lsblk`) provisioner creates pvs/vgs/lvs but does not add it to the cluster
> 
> Configmap for the node looked as expected
> 
> ```
> {
> 	"devices": "[{\"name\":\"sdb\",\"parent\":\"\",\"hasChildren\":false,\"devLinks\":\"/dev/disk/by-id/ata-QEMU_HARDDISK_QM00003 /dev/disk/by-path/pci-0000:00:1f.2-ata-2\",\"size\":26843545600,\"uuid\":\"75a082fc-0dc3-4fd4-928f-5f9f771575a9\",\"serial\":\"QEMU_HARDDISK_QM00003\",\"type\":\"disk\",\"rotational\":false,\"readOnly\":false,\"Partitions\":null,\"filesystem\":\"\",\"vendor\":\"\",\"model\":\"QEMU_HARDDISK\",\"wwn\":\"\",\"wwnVendorExtension\":\"\",\"empty\":true,\"cephVolumeData\":\"{\\\"path\\\":\\\"/dev/sdb\\\",\\\"available\\\":true,\\\"rejected_reasons\\\":[],\\\"sys_api\\\":{\\\"removable\\\":\\\"0\\\",\\\"ro\\\":\\\"0\\\",\\\"vendor\\\":\\\"ATA\\\",\\\"model\\\":\\\"QEMU HARDDISK\\\",\\\"rev\\\":\\\"2.5+\\\",\\\"sas_address\\\":\\\"\\\",\\\"sas_device_handle\\\":\\\"\\\",\\\"support_discard\\\":\\\"512\\\",\\\"rotational\\\":\\\"0\\\",\\\"nr_requests\\\":\\\"64\\\",\\\"scheduler_mode\\\":\\\"mq-deadline\\\",\\\"partitions\\\":{},\\\"sectors\\\":0,\\\"sectorsize\\\":\\\"512\\\",\\\"size\\\":26843545600.0,\\\"human_readable_size\\\":\\\"25.00 GB\\\",\\\"path\\\":\\\"/dev/sdb\\\",\\\"locked\\\":0},\\\"lvs\\\":[]}\",\"real-path\":\"/dev/sdb\",\"kernel-name\":\"sdb\"}]"
> }
> ```
> 
> After I reverted to 1.4.3 (previously used version before upgrading to 1.4.8) - exactly the same steps succeeded with no problems.

Please share the complete prepare pod logs.

**Comment by zerkms** [comment]
I don't have it handy, but it looked the same like in the original post. Next week I'm planning to iteratively upgrade from 1.4.3 to 1.4.8 one version at a time to find at what version exactly it was broken. When I do that I will share prepare pod logs. Anything else you'd like me to capture in particular when I find it?

**Comment by leseb** [comment]
The prepare job logs are all we need as well as some `lsblk` outputs from the machines.

**Comment by zerkms** [comment]
Okay, in my case it was a dangling `ceph auth` for the `osd` and the prepare was crashing quickly and docker happily cleaned up logs before I checked them. But now as I knew where to look at I could catch it:

```
2021-01-20 03:05:50.681726 I | cephosd: immediateExecuteArgs - [-oL ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --osds-per-device 1 /dev/sdb]
2021-01-20 03:05:50.681733 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --osds-per-device 1 /dev/sdb --report
2021-01-20 03:05:51.157833 D | exec: 
2021-01-20 03:05:51.157863 D | exec: Total OSDs: 1
2021-01-20 03:05:51.157870 D | exec: 
2021-01-20 03:05:51.157874 D | exec:   Type            Path                                                    LV Size         % of device
2021-01-20 03:05:51.157878 D | exec: ----------------------------------------------------------------------------------------------------
2021-01-20 03:05:51.157881 D | exec:   [data]          /dev/sdb                                                34.00 GB        100.0%
2021-01-20 03:05:51.174428 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --osds-per-device 1 /dev/sdb
2021-01-20 03:05:52.543383 D | exec: Running command: /usr/sbin/vgcreate --force --yes ceph-40a74784-1b0b-4899-9032-67594f6c4435 /dev/sdb
2021-01-20 03:05:52.543430 D | exec:  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will manage logical volume symlinks in device directory.
2021-01-20 03:05:52.543436 D | exec:  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will obtain device list by scanning device directory.
2021-01-20 03:05:52.543439 D | exec:  stdout: Physical volume "/dev/sdb" successfully created.
2021-01-20 03:05:52.543442 D | exec:  stdout: Volume group "ceph-40a74784-1b0b-4899-9032-67594f6c4435" successfully created
2021-01-20 03:05:52.543444 D | exec: Running command: /usr/sbin/lvcreate --yes -l 8959 -n osd-data-2eb23cb1-b7d9-466d-9363-44c257f71ef0 ceph-40a74784-1b0b-4899-9032-67594f6c4435
2021-01-20 03:05:52.543445 D | exec:  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will manage logical volume symlinks in device directory.
2021-01-20 03:05:52.543447 D | exec:  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will obtain device list by scanning device directory.
2021-01-20 03:05:52.543448 D | exec:  stderr: Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, device-mapper library will manage device nodes in device directory.
2021-01-20 03:05:52.543450 D | exec:  stdout: Logical volume "osd-data-2eb23cb1-b7d9-466d-9363-44c257f71ef0" created.
2021-01-20 03:05:52.543452 D | exec: Running command: /usr/bin/ceph-authtool --gen-print-key
2021-01-20 03:05:52.543454 D | exec: Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new f3e79961-869d-41af-9e3f-687ae7ce1352
2021-01-20 03:05:52.543455 D | exec:  stderr: Error EEXIST: entity osd.3 exists but key does not match
2021-01-20 03:05:52.546588 D | exec: Traceback (most recent call last):
2021-01-20 03:05:52.546603 D | exec:   File "/usr/sbin/ceph-volume", line 11, in <module>
2021-01-20 03:05:52.546606 D | exec:     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
2021-01-20 03:05:52.546609 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 39, in __init__
2021-01-20 03:05:52.546611 D | exec:     self.main(self.argv)
2021-01-20 03:05:52.546614 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
2021-01-20 03:05:52.546616 D | exec:     return f(*a, **kw)
2021-01-20 03:05:52.546618 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 150, in main
2021-01-20 03:05:52.546620 D | exec:     terminal.dispatch(self.mapper, subcommand_args)
2021-01-20 03:05:52.546624 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2021-01-20 03:05:52.546626 D | exec:     instance.main()
2021-01-20 03:05:52.546628 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/main.py", line 42, in main
2021-01-20 03:05:52.546630 D | exec:     terminal.dispatch(self.mapper, self.argv)
2021-01-20 03:05:52.546635 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2021-01-20 03:05:52.546653 D | exec:     instance.main()
2021-01-20 03:05:52.546665 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
2021-01-20 03:05:52.546668 D | exec:     return func(*a, **kw)
2021-01-20 03:05:52.546671 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 328, in main
2021-01-20 03:05:52.546674 D | exec:     self.execute()
2021-01-20 03:05:52.546677 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 291, in execute
2021-01-20 03:05:52.546679 D | exec:     self.strategy.execute()
2021-01-20 03:05:52.546681 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py", line 122, in execute
2021-01-20 03:05:52.546683 D | exec:     Prepare(command).main()
2021-01-20 03:05:52.546685 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/prepare.py", line 398, in main
2021-01-20 03:05:52.546702 D | exec:     self.safe_prepare()
2021-01-20 03:05:52.546704 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/prepare.py", line 246, in safe_prepare
2021-01-20 03:05:52.546706 D | exec:     self.prepare()
2021-01-20 03:05:52.546708 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
2021-01-20 03:05:52.546710 D | exec:     return func(*a, **kw)
2021-01-20 03:05:52.546713 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/prepare.py", line 286, in prepare
2021-01-20 03:05:52.546715 D | exec:     self.osd_id = prepare_utils.create_id(osd_fsid, json.dumps(secrets), osd_id=self.args.osd_id)
2021-01-20 03:05:52.546717 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/util/prepare.py", line 170, in create_id
2021-01-20 03:05:52.546719 D | exec:     raise RuntimeError('Unable to create a new OSD id')
2021-01-20 03:05:52.546721 D | exec: RuntimeError: Unable to create a new OSD id
```

In other words: in my case `ceph auth rm osd.3` was a solution.

But: I still think it's a bug that in case if prepare crashes like in this case - it leaves the device in a case that requires active intervention (like zapping the disk first).
