### ISSUE TITLE
need help,rbd can create pvc but cephfs cannot

### ISSUE THREAD

**Issue by yyt6200** [rook/rook#7156]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
cephfs create pvc,but pvc is pending.

**Expected behavior:**
cephfs ceate pvc 

**How to reproduce it (minimal and precise):**
#kubernetes v1.18.8 on Centos 7
kubectl apply -f ceph/common.yaml
kubectl apply -f ceph/operator.yaml
kubectl apply -f ceph/cluster.yaml
kubectl apply -f ceph/filesystem-test.yaml
kubectl apply -f ceph/toolbox.yaml
kubectl apply -f ceph/csi/cephfs/stroageclass.yaml
kubectl apply -f ceph/csi/rbd/stroageclass.yaml

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

```
# kubectl -n rook-ceph get pod
csi-cephfsplugin-6xbjq                                  3/3     Running     0          6d7h
csi-cephfsplugin-c625v                                  3/3     Running     0          6d7h
csi-cephfsplugin-gjlfv                                  3/3     Running     0          6d7h
csi-cephfsplugin-provisioner-64c8898766-446c2           6/6     Running     0          6d7h
csi-cephfsplugin-provisioner-64c8898766-ntwlg           6/6     Running     0          6d7h
csi-cephfsplugin-qd9fc                                  3/3     Running     0          6d7h
csi-cephfsplugin-qfp6n                                  3/3     Running     0          6d7h
csi-cephfsplugin-sz9cn                                  3/3     Running     0          6d7h
csi-rbdplugin-bj84w                                     3/3     Running     0          6d7h
csi-rbdplugin-dmjds                                     3/3     Running     0          6d7h
csi-rbdplugin-jngq5                                     3/3     Running     0          6d7h
csi-rbdplugin-provisioner-5ddffb7c49-c8glh              6/6     Running     0          6d7h
csi-rbdplugin-provisioner-5ddffb7c49-fzr8f              6/6     Running     0          6d7h
csi-rbdplugin-sf5tl                                     3/3     Running     0          6d7h
csi-rbdplugin-tl6lr                                     3/3     Running     0          6d7h
csi-rbdplugin-z55sc                                     3/3     Running     0          6d7h
rook-ceph-crashcollector-k8s-master2-6c8c79c7df-nprlg   1/1     Running     0          6d7h
rook-ceph-crashcollector-k8s-node1-67cf7c86cd-qm449     1/1     Running     0          130m
rook-ceph-crashcollector-k8s-node2-d6d5b59c5-fzwpd      1/1     Running     0          130m
rook-ceph-crashcollector-k8s-node3-84675f58f8-95bps     1/1     Running     0          6d7h
rook-ceph-mds-myfs-a-6ddfdfdbd9-slx75                   1/1     Running     0          130m
rook-ceph-mds-myfs-b-7978679f6c-v8vhl                   1/1     Running     0          130m
rook-ceph-mds-myfs-c-5dbcb88f-c5fwr                     1/1     Running     0          130m
rook-ceph-mds-myfs-d-7497f6cd7f-xtqcl                   1/1     Running     0          130m
rook-ceph-mds-myfs-e-5dc4f4b5-zkx7t                     1/1     Running     0          130m
rook-ceph-mds-myfs-f-7f5fcdfb8c-gpgg2                   1/1     Running     0          130m
rook-ceph-mgr-a-75bd86d795-bjfm4                        1/1     Running     0          6d7h
rook-ceph-mon-a-777f4f9646-vrx9h                        1/1     Running     2          6d3h
rook-ceph-mon-b-d6977c76d-rhqr8                         1/1     Running     0          6d3h
rook-ceph-mon-c-5767c7c4c-nvl97                         1/1     Running     0          6d3h
rook-ceph-operator-6cd478f99-nk8jj                      1/1     Running     0          6d5h
rook-ceph-osd-0-6868c5d98b-8gzxk                        1/1     Running     0          6d7h
rook-ceph-osd-1-67485b97bc-4kw2h                        1/1     Running     0          6d7h
rook-ceph-osd-2-65d5884f4c-ctbtm                        1/1     Running     0          6d7h
rook-ceph-osd-prepare-k8s-node1-b86r2                   0/1     Completed   0          6d5h
rook-ceph-osd-prepare-k8s-node2-999vd                   0/1     Completed   0          6d5h
rook-ceph-osd-prepare-k8s-node3-6qhjg                   0/1     Completed   0          6d5h
rook-ceph-tools-6b4889fdfd-7mbnn                        1/1     Running     0          103m

----------------------------------------------------------------------------------------------------------------------------

# ceph -s
  cluster:
    id:     e71f1609-fba4-4851-b9aa-f00e07160172
    health: HEALTH_WARN
            2 daemons have recently crashed

  services:
    mon: 3 daemons, quorum a,b,c (age 31h)
    mgr: a(active, since 6d)
    mds: myfs:3 {0=myfs-b=up:active,1=myfs-d=up:active,2=myfs-f=up:active} 3 up:standby-replay
    osd: 3 osds: 3 up (since 6d), 3 in (since 6d)

  data:
    pools:   4 pools, 97 pgs
    objects: 93 objects, 15 MiB
    usage:   3.1 GiB used, 1.5 TiB / 1.5 TiB avail
    pgs:     97 active+clean

  io:
    client:   2.9 KiB/s rd, 6 op/s rd, 0 op/s wr

----------------------------------------------------------------------------------------------------------------------------

# kubectl get pvc -n rook-ceph
NAME          STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
ceph-test-1   Bound     pvc-98e46d1b-d7fb-42b4-a6ab-cb6078e7f2b8   2Gi        RWO            rook-ceph-block   31h
cephfs-test   Pending                                                                        rook-cephfs       129m

----------------------------------------------------------------------------------------------------------------------------

# kubectl describe -n rook-ceph pvc cephfs-test
Name:          cephfs-test
Namespace:     rook-ceph
StorageClass:  rook-cephfs
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   kubesphere.io/creator: admin
               volume.beta.kubernetes.io/storage-provisioner: rook-ceph.cephfs.csi.ceph.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason                Age                     From                                                                                                              Message
  ----     ------                ----                    ----                                                                                                              -------
  Warning  ProvisioningFailed    8m38s (x11 over 127m)   rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-64c8898766-ntwlg_fb0796d7-86a7-4d1a-98f8-6225b9eded7a  failed to provision volume with StorageClass "rook-cephfs": rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Normal   ExternalProvisioning  4m35s (x502 over 129m)  persistentvolume-controller                                                                                       waiting for a volume to be created, either by external provisioner "rook-ceph.cephfs.csi.ceph.com" or manually created by system administrator
  Normal   Provisioning          3m38s (x29 over 129m)   rook-ceph.cephfs.csi.ceph.com_csi-cephfsplugin-provisioner-64c8898766-ntwlg_fb0796d7-86a7-4d1a-98f8-6225b9eded7a  External provisioner is provisioning volume for claim "rook-ceph/cephfs-test"
```
log info
```
### rook-ceph-mgr log
debug 2021-02-04T08:17:55.358+0000 ffff8027c700 0 [volumes ERROR volumes.module] Failed _cmd_fs_subvolumegroup_create(format:json, group_name:csi, prefix:fs subvolumegroup create, vol_name:myfs) < "":

Traceback (most recent call last):

File "/usr/share/ceph/mgr/volumes/fs/operations/volume.py", line 165, in get_fs_handle

conn.connect()

File "/usr/share/ceph/mgr/volumes/fs/operations/volume.py", line 88, in connect

self.fs.mount(filesystem_name=self.fs_name.encode('utf-8'))

File "cephfs.pyx", line 739, in cephfs.LibCephFS.mount

cephfs.Error: error calling ceph_mount: Connection timed out [Errno 110]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/share/ceph/mgr/volumes/module.py", line 34, in wrap

return f(self, inbuf, cmd)

File "/usr/share/ceph/mgr/volumes/module.py", line 452, in _cmd_fs_subvolumegroup_create

uid=cmd.get('uid', None), gid=cmd.get('gid', None))

File "/usr/share/ceph/mgr/volumes/fs/volume.py", line 480, in create_subvolume_group

with open_volume(self, volname) as fs_handle:

File "/lib64/python3.6/contextlib.py", line 81, in __enter__

return next(self.gen)

File "/usr/share/ceph/mgr/volumes/fs/operations/volume.py", line 316, in open_volume

fs_handle = vc.connection_pool.get_fs_handle(volname)

File "/usr/share/ceph/mgr/volumes/fs/operations/volume.py", line 171, in get_fs_handle

raise VolumeException(-e.args[0], e.args[1])

TypeError: bad operand type for unary -: 'str'

debug 2021-02-04T08:17:55.358+0000 ffff8027c700 -1 mgr handle_command module 'volumes' command handler threw exception: bad operand type for unary -: 'str'

debug 2021-02-04T08:17:55.358+0000 ffff8027c700 -1 mgr.server reply reply (22) Invalid argument Traceback (most recent call last):

File "/usr/share/ceph/mgr/volumes/fs/operations/volume.py", line 165, in get_fs_handle

conn.connect()

File "/usr/share/ceph/mgr/volumes/fs/operations/volume.py", line 88, in connect

self.fs.mount(filesystem_name=self.fs_name.encode('utf-8'))

File "cephfs.pyx", line 739, in cephfs.LibCephFS.mount

cephfs.Error: error calling ceph_mount: Connection timed out [Errno 110]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/share/ceph/mgr/mgr_module.py", line 1177, in _handle_command

return self.handle_command(inbuf, cmd)

File "/usr/share/ceph/mgr/volumes/module.py", line 426, in handle_command

return handler(inbuf, cmd)

File "/usr/share/ceph/mgr/volumes/module.py", line 34, in wrap

return f(self, inbuf, cmd)

File "/usr/share/ceph/mgr/volumes/module.py", line 452, in _cmd_fs_subvolumegroup_create

uid=cmd.get('uid', None), gid=cmd.get('gid', None))

File "/usr/share/ceph/mgr/volumes/fs/volume.py", line 480, in create_subvolume_group

with open_volume(self, volname) as fs_handle:

File "/lib64/python3.6/contextlib.py", line 81, in __enter__

return next(self.gen)

File "/usr/share/ceph/mgr/volumes/fs/operations/volume.py", line 316, in open_volume

fs_handle = vc.connection_pool.get_fs_handle(volname)

File "/usr/share/ceph/mgr/volumes/fs/operations/volume.py", line 171, in get_fs_handle

raise VolumeException(-e.args[0], e.args[1])

TypeError: bad operand type for unary -: 'str'

debug 2021-02-04T08:17:55.578+0000 ffff8027c700 -1 client.0 error registering admin socket command: (17) File exists

debug 2021-02-04T08:17:55.578+0000 ffff8027c700 -1 client.0 error registering admin socket command: (17) File exists

debug 2021-02-04T08:17:55.578+0000 ffff8027c700 -1 client.0 error registering admin socket command: (17) File exists

debug 2021-02-04T08:17:55.578+0000 ffff8027c700 -1 client.0 error registering admin socket command: (17) File exists

debug 2021-02-04T08:17:55.578+0000 ffff8027c700 -1 client.0 error registering admin socket command: (17) File exists

10.244.1.1 - - [04/Feb/2021:08:17:55] "GET / HTTP/1.1" 200 176 "" "kube-probe/1.18"

debug 2021-02-04T08:17:57.228+0000 ffff81aac700 0 log_channel(cluster) log [DBG] : pgmap v272162: 97 pgs: 97 active+clean; 15 MiB data, 58 MiB used, 1.5 TiB / 1.5 TiB avail; 3.3 KiB/s rd, 0 B/s wr, 6 op/s

debug 2021-02-04T08:17:59.238+0000 ffff81aac700 0 log_channel(cluster) log [DBG] : pgmap v272163: 97 pgs: 97 active+clean; 15 MiB data, 58 MiB used, 1.5 TiB / 1.5 TiB avail; 2.5 KiB/s rd, 0 B/s wr, 5 op/s

debug 2021-02-04T08:18:01.238+0000 ffff81aac700 0 log_channel(cluster) log [DBG] : pgmap v272164: 97 pgs: 97 active+clean; 15 MiB data, 58 MiB used, 1.5 TiB / 1.5 TiB avail; 2.9 KiB/s rd, 0 B/s wr, 6 op/s

debug 2021-02-04T08:18:03.238+0000 ffff81aac700 0 log_channel(cluster) log [DBG] : pgmap v272165: 97 pgs: 97 active+clean; 15 MiB data, 58 MiB used, 1.5 TiB / 1.5 TiB avail; 3.3 KiB/s rd, 0 B/s wr, 6 op/s

debug 2021-02-04T08:18:05.238+0000 ffff81aac700 0 log_channel(cluster) log [DBG] : pgmap v272166: 97 pgs: 97 active+clean; 15 MiB data, 58 MiB used, 1.5 TiB / 1.5 TiB avail; 2.9 KiB/s rd, 0 B/s wr, 6 op/s

----------------------------------------------------------------------------------------------------------------------------

### csi-provisioner log

E0204 08:58:56.239002 1 controllerserver.go:149] ID: 9517 Req-ID: pvc-f5e9774c-8823-4781-8707-f545acfa1260 an operation with the given Volume ID pvc-f5e9774c-8823-4781-8707-f545acfa1260 already exists

E0204 08:58:56.239047 1 utils.go:136] ID: 9517 Req-ID: pvc-f5e9774c-8823-4781-8707-f545acfa1260 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-f5e9774c-8823-4781-8707-f545acfa1260 already exists

E0204 09:01:56.271502 1 volume.go:148] ID: 9508 Req-ID: pvc-f5e9774c-8823-4781-8707-f545acfa1260 failed to create subvolume group csi, for the vol csi-vol-2a317d04-66c6-11eb-8ac4-7ad5a47a3120: rados: ret=-22, Invalid argument: "Traceback (most recent call last):\n File \"/usr/share/ceph/mgr/volumes/fs/operations/volume.py\", line 165, in get_fs_handle\n conn.connect()\n File \"/usr/share/ceph/mgr/volumes/fs/operations/volume.py\", line 88, in connect\n self.fs.mount(filesystem_name=self.fs_name.encode('utf-8'))\n File \"cephfs.pyx\", line 739, in cephfs.LibCephFS.mount\ncephfs.Error: error calling ceph_mount: Connection timed out [Errno 110]\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File \"/usr/share/ceph/mgr/mgr_module.py\", line 1177, in _handle_command\n return self.handle_command(inbuf, cmd)\n File \"/usr/share/ceph/mgr/volumes/module.py\", line 426, in handle_command\n return handler(inbuf, cmd)\n File \"/usr/share/ceph/mgr/volumes/module.py\", line 34, in wrap\n return f(self, inbuf, cmd)\n File \"/usr/share/ceph/mgr/volumes/module.py\", line 452, in _cmd_fs_subvolumegroup_create\n uid=cmd.get('uid', None), gid=cmd.get('gid', None))\n File \"/usr/share/ceph/mgr/volumes/fs/volume.py\", line 480, in create_subvolume_group\n with open_volume(self, volname) as fs_handle:\n File \"/lib64/python3.6/contextlib.py\", line 81, in __enter__\n return next(self.gen)\n File \"/usr/share/ceph/mgr/volumes/fs/operations/volume.py\", line 316, in open_volume\n fs_handle = vc.connection_pool.get_fs_handle(volname)\n File \"/usr/share/ceph/mgr/volumes/fs/operations/volume.py\", line 171, in get_fs_handle\n raise VolumeException(-e.args[0], e.args[1])\nTypeError: bad operand type for unary -: 'str'\n"

E0204 09:01:56.271564 1 controllerserver.go:90] ID: 9508 Req-ID: pvc-f5e9774c-8823-4781-8707-f545acfa1260 failed to create volume pvc-f5e9774c-8823-4781-8707-f545acfa1260: rados: ret=-22, Invalid argument: "Traceback (most recent call last):\n File \"/usr/share/ceph/mgr/volumes/fs/operations/volume.py\", line 165, in get_fs_handle\n conn.connect()\n File \"/usr/share/ceph/mgr/volumes/fs/operations/volume.py\", line 88, in connect\n self.fs.mount(filesystem_name=self.fs_name.encode('utf-8'))\n File \"cephfs.pyx\", line 739, in cephfs.LibCephFS.mount\ncephfs.Error: error calling ceph_mount: Connection timed out [Errno 110]\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File \"/usr/share/ceph/mgr/mgr_module.py\", line 1177, in _handle_command\n return self.handle_command(inbuf, cmd)\n File \"/usr/share/ceph/mgr/volumes/module.py\", line 426, in handle_command\n return handler(inbuf, cmd)\n File \"/usr/share/ceph/mgr/volumes/module.py\", line 34, in wrap\n return f(self, inbuf, cmd)\n File \"/usr/share/ceph/mgr/volumes/module.py\", line 452, in _cmd_fs_subvolumegroup_create\n uid=cmd.get('uid', None), gid=cmd.get('gid', None))\n File \"/usr/share/ceph/mgr/volumes/fs/volume.py\", line 480, in create_subvolume_group\n with open_volume(self, volname) as fs_handle:\n File \"/lib64/python3.6/contextlib.py\", line 81, in __enter__\n return next(self.gen)\n File \"/usr/share/ceph/mgr/volumes/fs/operations/volume.py\", line 316, in open_volume\n fs_handle = vc.connection_pool.get_fs_handle(volname)\n File \"/usr/share/ceph/mgr/volumes/fs/operations/volume.py\", line 171, in get_fs_handle\n raise VolumeException(-e.args[0], e.args[1])\nTypeError: bad operand type for unary -: 'str'\n"

E0204 09:01:56.283091 1 utils.go:136] ID: 9508 Req-ID: pvc-f5e9774c-8823-4781-8707-f545acfa1260 GRPC error: rpc error: code = Internal desc = rados: ret=-22, Invalid argument: "Traceback (most recent call last):\n File \"/usr/share/ceph/mgr/volumes/fs/operations/volume.py\", line 165, in get_fs_handle\n conn.connect()\n File \"/usr/share/ceph/mgr/volumes/fs/operations/volume.py\", line 88, in connect\n self.fs.mount(filesystem_name=self.fs_name.encode('utf-8'))\n File \"cephfs.pyx\", line 739, in cephfs.LibCephFS.mount\ncephfs.Error: error calling ceph_mount: Connection timed out [Errno 110]\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File \"/usr/share/ceph/mgr/mgr_module.py\", line 1177, in _handle_command\n return self.handle_command(inbuf, cmd)\n File \"/usr/share/ceph/mgr/volumes/module.py\", line 426, in handle_command\n return handler(inbuf, cmd)\n File \"/usr/share/ceph/mgr/volumes/module.py\", line 34, in wrap\n return f(self, inbuf, cmd)\n File \"/usr/share/ceph/mgr/volumes/module.py\", line 452, in _cmd_fs_subvolumegroup_create\n uid=cmd.get('uid', None), gid=cmd.get('gid', None))\n File \"/usr/share/ceph/mgr/volumes/fs/volume.py\", line 480, in create_subvolume_group\n with open_volume(self, volname) as fs_handle:\n File \"/lib64/python3.6/contextlib.py\", line 81, in __enter__\n return next(self.gen)\n File \"/usr/share/ceph/mgr/volumes/fs/operations/volume.py\", line 316, in open_volume\n fs_handle = vc.connection_pool.get_fs_handle(volname)\n File \"/usr/share/ceph/mgr/volumes/fs/operations/volume.py\", line 171, in get_fs_handle\n raise VolumeException(-e.args[0], e.args[1])\nTypeError: bad operand type for unary -: 'str'\n"

----------------------------------------------------------------------------------------------------------------------------
### csi-cephfsplugin log

W0204 09:03:24.776373 1 controller.go:943] Retrying syncing claim "54cadc93-f0b9-44dd-a8ad-b02d187cf5a0", failure 29

E0204 09:03:24.776411 1 controller.go:966] error syncing claim "54cadc93-f0b9-44dd-a8ad-b02d187cf5a0": failed to provision volume with StorageClass "rook-cephfs": rpc error: code = DeadlineExceeded desc = context deadline exceeded

I0204 09:03:24.776446 1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"rook-ceph", Name:"cephfs-test", UID:"54cadc93-f0b9-44dd-a8ad-b02d187cf5a0", APIVersion:"v1", ResourceVersion:"11508873", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "rook-cephfs": rpc error: code = DeadlineExceeded desc = context deadline exceeded

I0204 09:03:56.239443 1 controller.go:1317] provision "rook-ceph/ceph-rwx" class "rook-cephfs": started

I0204 09:03:56.239600 1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"rook-ceph", Name:"ceph-rwx", UID:"f5e9774c-8823-4781-8707-f545acfa1260", APIVersion:"v1", ResourceVersion:"10859187", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "rook-ceph/ceph-rwx"
```
 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release): kubernetes 1.18.8 on Centos 7
* Kernel (e.g. `uname -a`): 4.18.0-80.7.2.el7.aarch64 #1 SMP Thu Sep 12 16:13:20 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
* Cloud provider or hardware configuration: HUAWEI Cloud
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.5.0-alpha.0.342.gc82ae69
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 15.2.8 (bdf3eebcd22d7d0b3dd4d5501bee5bac354d5b55) octopus (stable)
* Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/arm64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): 
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):HEALTH_WARN 2 daemons have recently crashed

**Comment by yyt6200** [comment]
@travisn Excuse me ,can you help me ?

**Comment by travisn** [comment]
@yyt6200 We are adding a CSI troubleshooting guide to the docs in #7157. Check if the filesystem pool exists, and the csi provisioner logs for errors in that doc. Does that help?
