### ISSUE TITLE
'prometheus' service not found, is the exporter enabled'.

### ISSUE THREAD

**Issue by subhamkrai** [rook/rook#7636]
Canary test failing with
```
Traceback (most recent call last):
  File "/etc/ceph/create-external-cluster-resources.py", line 801, in <module>
    raise err
  File "/etc/ceph/create-external-cluster-resources.py", line 798, in <module>
    rjObj.main()
  File "/etc/ceph/create-external-cluster-resources.py", line 779, in main
    generated_output = self.gen_json_out()
  File "/etc/ceph/create-external-cluster-resources.py", line 613, in gen_json_out
    self._gen_output_map()
  File "/etc/ceph/create-external-cluster-resources.py", line 598, in _gen_output_map
    self.out_map['MONITORING_ENDPOINT_PORT'] = self.get_active_and_standby_mgrs()
  File "/etc/ceph/create-external-cluster-resources.py", line 353, in get_active_and_standby_mgrs
    "'prometheus' service not found, is the exporter enabled?'.\n")
__main__.ExecutionFailureException: 'prometheus' service not found, is the exporter enabled?'.

command terminated with exit code 1
Error: Process completed with exit code 1.
```

example run: https://github.com/rook/rook/runs/2352543882?check_suite_focus=true

**Comment by leseb** [comment]
I wonder if this was intermittent, ran the CI again to confirm.
