### ISSUE TITLE
Upgrade test failing in release-1.5 branch

### ISSUE THREAD

**Issue by travisn** [rook/rook#7654]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The upgrade test suite is failing fairly consistently in the release-1.5 branch. The test is failing when first installing v1.4.7 and doesn't even get to the steps where the upgrade is actually tested.

A manual upgrade from v1.4.7 to v1.5.10 is successful, and no issues observed. This appears to only be a test bug.

Some failures are when just first waiting for mons to start. The test log shows:
```
[2021-04-15T22:23:04.597Z] 2021-04-15 22:23:04.252570 I | testutil: waiting for 1 pods (found 0) with label app=rook-ceph-mon in namespace upgrade-ns
[2021-04-15T22:23:09.863Z] 2021-04-15 22:23:09.256275 I | testutil: waiting for 1 pods (found 0) with label app=rook-ceph-mon in namespace upgrade-ns
...
```

and the operator log shows that the ceph version cannot be queried:
```
2021-04-15 15:58:23.361870 E | ceph-cluster-controller: failed to reconcile. failed to reconcile cluster "upgrade-ns": failed to configure local ceph cluster: failed the ceph version check: ceph version job returned failure with retcode 1.
  stdout: 
  stderr: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site.py", line 62, in <module>
    import os
  File "/usr/lib64/python2.7/os.py", line 49, in <module>
    import posixpath as path
  File "/usr/lib64/python2.7/posixpath.py", line 17, in <module>
    import warnings
ImportError: No module named warnings
```

In other failures, the OSDs frequently fail:
```
[2021-04-15T16:01:16.134Z] 2021-04-15 16:01:15.386087 I | testutil: waiting for 1 pods (found 0) with label app=rook-ceph-osd in namespace upgrade-ns
[2021-04-15T16:01:21.411Z] 2021-04-15 16:01:20.389447 I | testutil: waiting for 1 pods (found 0) with label app=rook-ceph-osd in namespace upgrade-ns
```

and the operator log shows that the disks are failing:
```
2021-04-15 15:59:53.787074 E | ceph-cluster-controller: failed to reconcile. failed to reconcile cluster "upgrade-ns": failed to configure local ceph cluster: 
failed to create cluster: failed to start ceph osds: 1 failures encountered while running osds in namespace upgrade-ns: orchestration for node test-prefix-this-is-a-very-long-hostname-ip-172-31-35-206 failed: &{OSDs:[] Status:failed PvcBackedOSD:false 
Message:failed to get available devices: failed to get device "nvme2n1" info: failed to determine if the device was available. failed to determine if the device "/dev/nvme2n1" is available. failed to execute ceph-volume inventory on disk "/dev/nvme2n1". exec: "ceph-volume": executable file not found in $PATH}
```

**Expected behavior:**
The upgrade test must pass for consistency.

**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
The upgrade tests are no longer failing in release-1.5 branch since [build 265](https://jenkins.rook.io/blue/organizations/jenkins/rook%2Frook/detail/release-1.5/265/pipeline/55/) starting 12 days ago. There does not appear to be a related fix, but must have been an environmental issue with jenkins.
