### ISSUE TITLE
ci: I/O errors in runners?!

### ISSUE THREAD

**Issue by leseb** [rook/rook#7728]
Seen in https://github.com/rook/rook/pull/7716/checks?check_run_id=2409905847

```
2021-04-22 12:16:10.139662 E | op-osd: failed to provision OSD(s) on node fv-az232-150. &{OSDs:[] Status:failed PvcBackedOSD:false Message:failed to configure devices: failed to initialize raw based osd: failed to run ceph-volume raw command. Running command: /usr/bin/ceph-authtool
--gen-print-key
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new 32c14f6e-9786-4fd0-827a-80648dfc8f54
Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-1
Running command: /usr/bin/chown -R ceph:ceph /dev/sda2
Running command: /usr/bin/ln -s /dev/sda2 /var/lib/ceph/osd/ceph-1/block
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/osd/ceph-1/activate.monmap
 stderr: got monmap epoch 1
Running command: /usr/bin/ceph-authtool /var/lib/ceph/osd/ceph-1/keyring --create-keyring --name osd.1 --add-key AQAIaYFg2RkKAxAATpJBMUXN7HJaNGsiRf6WRA==
 stdout: creating /var/lib/ceph/osd/ceph-1/keyring
 stdout: added entity osd.1 auth(key=AQAIaYFg2RkKAxAATpJBMUXN7HJaNGsiRf6WRA==)
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-1/keyring
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-1/
Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid 32c14f6e-9786-4fd0-827a-80648dfc8f54 --setuser ceph --setgroup ceph
 stderr: 2021-04-22T12:16:08.701+0000 7f0131b5a080 -1 bluestore(/var/lib/ceph/osd/ceph-1/) _read_fsid unparsable uuid
 stderr: 2021-04-22T12:16:08.713+0000 7f0131b5a080 -1 bluefs _replay 0x0: stop: uuid 00000000-0000-0000-0000-000000000000 != super.uuid fea3ed38-ef30-46b5-9a8f-a9941b51419b, block dump:
 stderr: 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 stderr: *
 stderr: 00000ff0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 stderr: 00001000
 stderr: 2021-04-22T12:16:09.257+0000 7f0131b5a080 -1 bluestore(/var/lib/ceph/osd/ceph-1/) _open_db erroring opening db:
 stderr: 2021-04-22T12:16:09.785+0000 7f0131b5a080 -1 OSD::mkfs: ObjectStore::mkfs failed with error (5) Input/output error
 stderr: 2021-04-22T12:16:09.785+0000 7f0131b5a080 -1  ** ERROR: error creating empty object store in /var/lib/ceph/osd/ceph-1/: (5) Input/output error
--> Was unable to complete a new OSD, will rollback changes
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.1 --yes-i-really-mean-it
 stderr: purged osd.1
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 169, in main
    self.safe_prepare(self.args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 91, in safe_prepare
    self.prepare()
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 134, in prepare
    tmpfs,
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 68, in prepare_bluestore
    db=db
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/prepare.py", line 480, in osd_mkfs_bluestore
    raise RuntimeError('Command failed with exit code %s: %s' % (returncode, ' '.join(command)))
RuntimeError: Command failed with exit code 250: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid 32c14f6e-9786-4fd0-827a-80648dfc8f54 --setuser ceph
 --setgroup ceph: exit status 1}
```

Runner is still alive so I'm looking into this.

**Comment by leseb** [comment]
```
[root@5e62d235d0f8 /]# ceph-bluestore-tool fsck --path 1 --log-level=30
2021-04-22T12:49:32.236+0000 7f6f7899f3c0 -1 bluestore(1) _open_db erroring opening db:
fsck failed: (5) Input/output error
```

**Comment by leseb** [comment]
@liewegas any idea?
