### ISSUE TITLE
Creating NFS Exports in dashboard don't work after upgrading to ceph 16.2.0

### ISSUE THREAD

**Issue by marklester** [rook/rook#7779]
when I tried to create an export I get a 500 error in the dashboard
logs in mgr
repeating

```
mgr debug 2021-04-29T06:21:00.223+0000 7f0714b72700  0 [rook WARNING root] CephNFS {'apiVersion': 'ceph.rook.io/v1', 'items': [{'apiVersion': 'ceph.rook.io/v1', 'kind': 'Cep ││ hNFS', 'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"ceph.rook.io/v1","kind":"CephNFS","metadata":{"annotations":{},"name" ││ :"ceph-nfs","namespace":"rook-ceph"},"spec":{"rados":{"namespace":"nfs-ns","pool":"cephfs-data0"},"server":{"active":2,"annotations":null,"logLevel":"NIV_INFO","placement":n ││ ull,"resources":null}}}\n'}, 'creationTimestamp': 
'2021-04-29T05:37:27Z', 'finalizers': ['cephnfs.ceph.rook.io'], 'generation': 3, 'labels': {'ceph_version': '16.2.1-0-pacif ││ ic'}, 'managedFields': [{'apiVersion': 'ceph.rook.io/v1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:kubectl.kubernetes.io/last-appl ││ ied-configuration': {}}}, 'f:spec': {'.': {}, 'f:rados': {'.': {}, 'f:namespace': {}, 'f:pool': {}}, 'f:server': {'.': {}, 'f:active': {}, 'f:logLevel': {}}}}, 'manager': 'k ││ ubectl-client-side-apply', 'operation': 'Update', 'time': '2021-04-29T05:37:27Z'}, {'apiVersion': 'ceph.rook.io/v1', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f ││ :finalizers': {}, 'f:labels': {'.': {}, 'f:ceph_version': {}}}, 'f:spec': {'f:server': {'f:placement': {}, 'f:resources': {}}}, 'f:status': {'.': {}, 'f:phase': {}}}, 'manag ││ er': 'rook', 'operation': 'Update', 'time': 
'2021-04-29T05:44:20Z'}], 'name': 'ceph-nfs', 'namespace': 'rook-ceph', 'resourceVersion': '86688375', 'uid': '0eb3a34d-ed43-4bf4 ││ -ae16-5de9c623eaaf'}, 'spec': {'rados': {'namespace': 'nfs-ns', 'pool': 'cephfs-data0'}, 'server': {'active': 2, 'logLevel': 'NIV_INFO', 'placement': {}, 'resources': {}}},  ││ 'status': {'phase': 'Ready'}}], 'kind': 'CephNFSList', 'metadata': {'continue': '', 'resourceVersion': '86694448'}}                                                           ││ 
mgr debug 2021-04-29T06:21:00.239+0000 7f0714b72700  0 [dashboard WARNING ganesha] Error when getting NFS service from the Orchestrator. 'ServiceSpec' object has no attribut ││ e 'pool'
```

and when I click the create button with dashboard debug on

```
 Internal Server Error                                                                      ││ mgr Traceback (most recent call last):                                                                                                                                        ││ mgr   File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 46, in dashboard_exception_handler                                                                     ││ mgr     return handler(*args, **kwargs)                                                                                                                                       ││ mgr   File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__                                                                                   ││ mgr     return self.callable(*self.args, **self.kwargs)                                                                                                                       ││ mgr   File "/usr/share/ceph/mgr/dashboard/controllers/__init__.py", line 694, in inner                                                                                        ││ mgr     ret = func(*args, **kwargs)                                                                                                                                           ││ mgr   File "/usr/share/ceph/mgr/dashboard/controllers/nfsganesha.py", line 265, in fsals                                                                                      ││ mgr     return Ganesha.fsals_available()                                                                                                                                      ││ mgr   File "/usr/share/ceph/mgr/dashboard/services/ganesha.py", line 154, in fsals_available                                                                                  ││ mgr     if RgwClient.admin_instance().is_service_online() and \                                                                                                               ││ mgr   File "/usr/share/ceph/mgr/dashboard/services/rgw_client.py", line 301, in admin_instance                                                                                ││ mgr     return RgwClient.instance(daemon_name=daemon_name)                                                                                                                    ││ mgr   File "/usr/share/ceph/mgr/dashboard/services/rgw_client.py", line 241, in instance                                                                                      ││ mgr     RgwClient._daemons = _get_daemons()                                                                                                                                   ││ mgr   File "/usr/share/ceph/mgr/dashboard/services/rgw_client.py", line 53, in _get_daemons                                                                                   ││ mgr     raise NoRgwDaemonsException                                                                                                                                           ││ mgr dashboard.services.rgw_client.NoRgwDaemonsException: No RGW service is running.                                                                                           ││ mgr debug 2021-04-29T06:23:10.147+0000 7f071336f700  0 [dashboard ERROR request] [192.168.0.12:6829] [GET] [500] [0.002s] [admin] [2.1K] /ui-api/nfs-ganesha/fsals            ││ mgr debug 2021-04-29T06:23:10.147+0000 7f071336f700  0 [dashboard ERROR request] [b'{"status": "500 Internal Server Error", "detail": "The server encountered an unexpected c ││ mgr debug 2021-04-29T06:23:10.163+0000 7f071336f700  0 [dashboard ERROR frontend.error] (https://ceph/#/nfs/create): Http failure response for https://ceph/ui-api/nfs-ganesh ││ mgr  None         
```

**Comment by marklester** [comment]
ok so I think I figure this out. on ubuntu 20.04.2 nfs looks to default to 4.2 which has issues. I can mount the nfs service if I set the version to 4.1.
`mount -v -t nfs -o nfsvers=4.1,proto=tcp ceph-nfs:/cephfs /mnt/ceph`

since you can't set mount options on nfs volumes. I got around this by setting this version as the default for all the nodes in the cluster. To do this you need to create a file cat /etc/nfsmount.conf
and in it you need to add
```ini
[ NFSMount_Global_Options ]
Defaultvers=4.1
```
that will make it so that when nfs mounts are mounted in pods it will default to version 4.1 instead of 4.2
