### ISSUE TITLE
ceph: failed to initialize OSD

### ISSUE THREAD

**Issue by satoru-takeuchi** [rook/rook#8023]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

OSD prepare pod sometimes fails when creating new OSD in PVC-based cluster.
It's due to the random failure of `ceph-volume raw prepare`.

I submitted an issue about this problem in Ceph issue tracker because I suspect it's a Ceph's problem.

https://tracker.ceph.com/issues/51034

For more details, please refer to the above-mentioned issue.

**Expected behavior:**

Suceed to initialize OSD

**How to reproduce it (minimal and precise):**

Create OSD on PVC continuously.

The reproduction probability is about 10%

** Workaround**:

Specify `bluefs_buffered_io=false` in `rook-config-override` cm.

**File(s) to submit**:

[ceph.zip](https://github.com/rook/rook/files/6575825/ceph.zip)

- Ceph related files.
  - ceph.conf
  - ceph-volume.log
  - osd-mkfs-1622521334.log: a failure log of ceph-osd --mkfs
- Rook specific files.
  - rook-ceph-osd-prepare-set1-data-5.yaml: Problemetic OSD's deployment
  - osd-prepare-set1-data-5.pod.log: the log of OSD preparing pod
  - osd-prepare-event.log: prepare pod's kubernetes event log
  - cephcluster yaml: CephCluster cluster resource

**Environment**:
* OS: flatcar
* Kernel: 5.10.38-flatcar
* Rook version (use `rook version` inside of a Rook Pod): v1.6.3
* Storage backend version (e.g. for ceph do `ceph -v`): ceph 16.2.4
* Kubernetes version (use `kubectl version`): v1.20.7

**Additional information**:

- This problem didn't happen in Ceph 15.2.8.
- I didn't confirm whether this problem happen on host-based cluster.

**Comment by leseb** [comment]
Nice report!

**Comment by leseb** [comment]
@satoru-takeuchi I saw a random failure in one run, see the ceph-volume logs:


```
2021-06-10 08:44:32.378358 E | op-osd: failed to provision OSD(s) on node fv-az234-793. &{OSDs:[] Status:failed PvcBackedOSD:false Message:failed to configure devices: failed to initialize raw based osd: failed to run ceph-volume raw command. Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new 70264ca4-fb20-4771-a3a2-9ab192881fe0
Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-1
Running command: /usr/bin/chown -R ceph:ceph /dev/sda2
Running command: /usr/bin/ln -s /dev/sda2 /var/lib/ceph/osd/ceph-1/block
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/osd/ceph-1/activate.monmap
 stderr: got monmap epoch 1
Running command: /usr/bin/ceph-authtool /var/lib/ceph/osd/ceph-1/keyring --create-keyring --name osd.1 --add-key AQDt0MFgJrfrFRAAB23ZjuE4JeAYW499aEW3GA==
 stdout: creating /var/lib/ceph/osd/ceph-1/keyring
added entity osd.1 auth(key=AQDt0MFgJrfrFRAAB23ZjuE4JeAYW499aEW3GA==)
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-1/keyring
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-1/
Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid 70264ca4-fb20-4771-a3a2-9ab192881fe0 --setuser ceph --setgroup ceph
 stderr: 2021-06-10T08:44:30.681+0000 7f1403da1080 -1 bluestore(/var/lib/ceph/osd/ceph-1/) _read_fsid unparsable uuid
 stderr: 2021-06-10T08:44:30.717+0000 7f1403da1080 -1 bluefs _replay 0x0: stop: uuid 00000000-0000-0000-0000-000000000000 != super.uuid 84142dfd-bf75-40b5-b439-c51918bcd607, block dump:
 stderr: 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 stderr: *
 stderr: 00000ff0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 stderr: 00001000
 stderr: 2021-06-10T08:44:31.229+0000 7f1403da1080 -1 bluestore(/var/lib/ceph/osd/ceph-1/) _open_db erroring opening db:
 stderr: 2021-06-10T08:44:31.761+0000 7f1403da1080 -1 OSD::mkfs: ObjectStore::mkfs failed with error (5) Input/output error
 stderr: 2021-06-10T08:44:31.761+0000 7f1403da1080 -1 [0;31m ** ERROR: error creating empty object store in /var/lib/ceph/osd/ceph-1/: (5) Input/output error[0m
--> Was unable to complete a new OSD, will rollback changes
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.1 --yes-i-really-mean-it
 stderr: purged osd.1
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 169, in main
    self.safe_prepare(self.args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 91, in safe_prepare
    self.prepare()
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 134, in prepare
    tmpfs,
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 68, in prepare_bluestore
    db=db
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/prepare.py", line 480, in osd_mkfs_bluestore
    raise RuntimeError('Command failed with exit code %s: %s' % (returncode, ' '.join(command)))
RuntimeError: Command failed with exit code 250: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid 70264ca4-fb20-4771-a3a2-9ab192881fe0 --setuser ceph --setgroup ceph: exit status 1}
2021-06-10 08:44:32.419679 E | ceph-cluster-controller: failed to reconcile. failed to reconcile cluster "my-cluster": failed to configure local ceph cluster: failed to create cluster: failed to start ceph osds: 1 failures encountered while running osds on nodes in namespace "rook-ceph". 
failed to provision OSD(s) on node fv-az234-793. &{OSDs:[] Status:failed PvcBackedOSD:false Message:failed to configure devices: failed to initialize raw based osd: failed to run ceph-volume raw command. Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new 70264ca4-fb20-4771-a3a2-9ab192881fe0
Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-1
Running command: /usr/bin/chown -R ceph:ceph /dev/sda2
Running command: /usr/bin/ln -s /dev/sda2 /var/lib/ceph/osd/ceph-1/block
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/osd/ceph-1/activate.monmap
 stderr: got monmap epoch 1
Running command: /usr/bin/ceph-authtool /var/lib/ceph/osd/ceph-1/keyring --create-keyring --name osd.1 --add-key AQDt0MFgJrfrFRAAB23ZjuE4JeAYW499aEW3GA==
 stdout: creating /var/lib/ceph/osd/ceph-1/keyring
added entity osd.1 auth(key=AQDt0MFgJrfrFRAAB23ZjuE4JeAYW499aEW3GA==)
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-1/keyring
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-1/
Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid 70264ca4-fb20-4771-a3a2-9ab192881fe0 --setuser ceph --setgroup ceph
 stderr: 2021-06-10T08:44:30.681+0000 7f1403da1080 -1 bluestore(/var/lib/ceph/osd/ceph-1/) _read_fsid unparsable uuid
 stderr: 2021-06-10T08:44:30.717+0000 7f1403da1080 -1 bluefs _replay 0x0: stop: uuid 00000000-0000-0000-0000-000000000000 != super.uuid 84142dfd-bf75-40b5-b439-c51918bcd607, block dump:
 stderr: 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 stderr: *
 stderr: 00000ff0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 stderr: 00001000
 stderr: 2021-06-10T08:44:31.229+0000 7f1403da1080 -1 bluestore(/var/lib/ceph/osd/ceph-1/) _open_db erroring opening db:
 stderr: 2021-06-10T08:44:31.761+0000 7f1403da1080 -1 OSD::mkfs: ObjectStore::mkfs failed with error (5) Input/output error
 stderr: 2021-06-10T08:44:31.761+0000 7f1403da1080 -1 [0;31m ** ERROR: error creating empty object store in /var/lib/ceph/osd/ceph-1/: (5) Input/output error[0m
--> Was unable to complete a new OSD, will rollback changes
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.1 --yes-i-really-mean-it
 stderr: purged osd.1
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 169, in main
    self.safe_prepare(self.args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 91, in safe_prepare
    self.prepare()
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 134, in prepare
    tmpfs,
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 68, in prepare_bluestore
    db=db
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/prepare.py", line 480, in osd_mkfs_bluestore
    raise RuntimeError('Command failed with exit code %s: %s' % (returncode, ' '.join(command)))
RuntimeError: Command failed with exit code 250: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid 70264ca4-fb20-4771-a3a2-9ab192881fe0 --setuser ceph --setgroup ceph: exit status 1}
2021-06-10 08:44:32.419732 I | op-k8sutil: Reporting Event rook-ceph:my-cluster Warning:ReconcileFailed:failed to reconcile cluster "my-cluster": failed to configure local ceph cluster: failed to create cluster: failed to start ceph osds: 1 failures encountered while running osds on nodes in namespace "rook-ceph". 
failed to provision OSD(s) on node fv-az234-793. &{OSDs:[] Status:failed PvcBackedOSD:false Message:failed to configure devices: failed to initialize raw based osd: failed to run ceph-volume raw command. Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new 70264ca4-fb20-4771-a3a2-9ab192881fe0
Running command: /usr/bin/ceph-authtool --gen-print-key
Running command: /usr/bin/mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-1
Running command: /usr/bin/chown -R ceph:ceph /dev/sda2
Running command: /usr/bin/ln -s /dev/sda2 /var/lib/ceph/osd/ceph-1/block
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/osd/ceph-1/activate.monmap
 stderr: got monmap epoch 1
Running command: /usr/bin/ceph-authtool /var/lib/ceph/osd/ceph-1/keyring --create-keyring --name osd.1 --add-key AQDt0MFgJrfrFRAAB23ZjuE4JeAYW499aEW3GA==
 stdout: creating /var/lib/ceph/osd/ceph-1/keyring
added entity osd.1 auth(key=AQDt0MFgJrfrFRAAB23ZjuE4JeAYW499aEW3GA==)
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-1/keyring
Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-1/
Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid 70264ca4-fb20-4771-a3a2-9ab192881fe0 --setuser ceph --setgroup ceph
 stderr: 2021-06-10T08:44:30.681+0000 7f1403da1080 -1 bluestore(/var/lib/ceph/osd/ceph-1/) _read_fsid unparsable uuid
 stderr: 2021-06-10T08:44:30.717+0000 7f1403da1080 -1 bluefs _replay 0x0: stop: uuid 00000000-0000-0000-0000-000000000000 != super.uuid 84142dfd-bf75-40b5-b439-c51918bcd607, block dump:
 stderr: 00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 stderr: *
 stderr: 00000ff0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 stderr: 00001000
 stderr: 2021-06-10T08:44:31.229+0000 7f1403da1080 -1 bluestore(/var/lib/ceph/osd/ceph-1/) _open_db erroring opening db:
 stderr: 2021-06-10T08:44:31.761+0000 7f1403da1080 -1 OSD::mkfs: ObjectStore::mkfs failed with error (5) Input/output error
 stderr: 2021-06-10T08:44:31.761+0000 7f1403da1080 -1 [0;31m ** ERROR: error creating empty object store in /var/lib/ceph/osd/ceph-1/: (5) Input/output error[0m
--> Was unable to complete a new OSD, will rollback changes
Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.1 --yes-i-really-mean-it
 stderr: purged osd.1
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 169, in main
    self.safe_prepare(self.args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 91, in safe_prepare
    self.prepare()
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 134, in prepare
    tmpfs,
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/prepare.py", line 68, in prepare_bluestore
    db=db
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/prepare.py", line 480, in osd_mkfs_bluestore
    raise RuntimeError('Command failed with exit code %s: %s' % (returncode, ' '.join(command)))
RuntimeError: Command failed with exit code 250: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 1 --monmap /var/lib/ceph/osd/ceph-1/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-1/ --osd-uuid 70264ca4-fb20-4771-a3a2-9ab192881fe0 --setuser ceph --setgroup ceph: exit status 1}
```

I reported an issue earlier https://github.com/rook/rook/issues/7728
Is it related?

**Comment by satoru-takeuchi** [comment]
@leseb I'll answer next week because today is paid holiday.

**Comment by satoru-takeuchi** [comment]
@leseb 

> I saw a random failure in one run, see the ceph-volume logs:

Your osd initialization failed a bit faster than mine[1]. However, if it's a kind of cache-sync-problem as I guessed, it might cause your problem.

I have some questions.

Q1. What version is your Ceph cluster? My problem happens in v16.2.x but not in v15.2.x
Q2. Could you try whether my mitigation, setting `bluefs_buffered_io=false` work?
Q3. Does Ceph team recognize this issue? I'm glad if they helm me because I've investigated this issue but haven't made any progress yet.

[1] My log on failure.
```
[2021-05-31 04:31:31,038][ceph_volume.process][INFO  ] Running command: /usr/bin/chown -R ceph:ceph /dev/dm-11
[2021-05-31 04:31:31,041][ceph_volume.process][INFO  ] Running command: /usr/bin/ln -s /dev/mapper/vg1-86317ef4--34ee--4119--9eb3--f8925d9f6e1d /var/lib/ceph/osd/ceph-5/block
[2021-05-31 04:31:31,043][ceph_volume.process][INFO  ] Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring mon getmap -o /var/lib/ceph/osd/ceph-5/activate.monmap
[2021-05-31 04:31:31,447][ceph_volume.process][INFO  ] stderr got monmap epoch 3
[2021-05-31 04:31:31,462][ceph_volume.process][INFO  ] Running command: /usr/bin/ceph-authtool /var/lib/ceph/osd/ceph-5/keyring --create-keyring --name osd.5 --add-key AQCiZrRgcNL6IxAAKnTgtW5nENbKwgFhTEtstg==
[2021-05-31 04:31:31,482][ceph_volume.process][INFO  ] stdout creating /var/lib/ceph/osd/ceph-5/keyring
added entity osd.5 auth(key=AQCiZrRgcNL6IxAAKnTgtW5nENbKwgFhTEtstg==)
[2021-05-31 04:31:31,483][ceph_volume.process][INFO  ] Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-5/keyring
[2021-05-31 04:31:31,487][ceph_volume.process][INFO  ] Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-5/
[2021-05-31 04:31:31,491][ceph_volume.process][INFO  ] Running command: /usr/bin/ceph-osd --cluster ceph --osd-objectstore bluestore --mkfs -i 5 --monmap /var/lib/ceph/osd/ceph-5/activate.monmap --keyfile - --osd-data /var/lib/ceph/osd/ceph-5/ --osd-uuid 339db773-cf9f-408e-ba1d-40044d788c4a --setuser ceph --setgroup ceph
[2021-05-31 04:31:32,587][ceph_volume.process][INFO  ] stderr 2021-05-31T04:31:31.533+0000 7f309bfb6f00 -1 bluestore(/var/lib/ceph/osd/ceph-5/) _read_fsid unparsable uuid
[2021-05-31 04:31:32,588][ceph_volume.process][INFO  ] stderr 2021-05-31T04:31:32.058+0000 7f309bfb6f00 -1 rocksdb: verify_sharding extra columns in rocksdb. rocksdb columns = [default,m-0] target columns = []
[2021-05-31 04:31:32,588][ceph_volume.process][INFO  ] stderr 2021-05-31T04:31:32.058+0000 7f309bfb6f00 -1 bluestore(/var/lib/ceph/osd/ceph-5/) _open_db erroring opening db:
[2021-05-31 04:31:32,588][ceph_volume.process][INFO  ] stderr 2021-05-31T04:31:32.573+0000 7f309bfb6f00 -1 OSD::mkfs: ObjectStore::mkfs failed with error (5) Input/output error
[2021-05-31 04:31:32,588][ceph_volume.process][INFO  ] stderr 2021-05-31T04:31:32.574+0000 7f309bfb6f00 -1 [0;31m ** ERROR: error creating empty object store in /var/lib/ceph/osd/ceph-5/: (5) Input/output error[0m
[2021-05-31 04:31:32,588][ceph_volume.devices.raw.prepare][ERROR ] raw prepare was unable to complete
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ceph_volume/devices/raw/prepare.py", line 91, in safe_prepare
    self.prepare()
  File "/usr/lib/python3/dist-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3/dist-packages/ceph_volume/devices/raw/prepare.py", line 127, in prepare
    prepare_bluestore(
  File "/usr/lib/python3/dist-packages/ceph_volume/devices/raw/prepare.py", line 64, in prepare_bluestore
    prepare_utils.osd_mkfs_bluestore(
  File "/usr/lib/python3/dist-packages/ceph_volume/util/prepare.py", line 480, in osd_mkfs_bluestore
    raise RuntimeError('Command failed with exit code %s: %s' % (returncode, ' '.join(command)))
 ```

**Comment by martin31821** [comment]
Seeing the same bug on a debian machine. 
Seems to occur more likely when trying to provision more OSDs at once.

**Comment by satoru-takeuchi** [comment]
@martin31821 Is your Ceph version v16.2? And what is the csi driver for OSD?

**Comment by martin31821** [comment]
@satoru-takeuchi I'm on 16.2.4. I'm not having a PVC backed OSD, it's raw devices with bluestore. 
I also don't have rbd or CephFS here deployed, this setup is only serving RGW.

**Comment by satoru-takeuchi** [comment]
@martin31821 Interesting.

I'll report your case in Ceph's issue. Please tell me one more question.

> Edit: Provisioning four OSDs on four devices failed, three devices worked

Did you try many times in both cases(three decices and four devices)?

**Comment by martin31821** [comment]
@satoru-takeuchi I tried four or five times with different device sets of four Devices (WD Red Pro if that matters), and one time with three devices which worked directly and then a single device afterwards which did work too.

**Comment by satoru-takeuchi** [comment]
@leseb 

> I have some questions.
> 
> Q1. What version is your Ceph cluster? My problem happens in v16.2.x but not in v15.2.x
> Q2. Could you try whether my mitigation, setting bluefs_buffered_io=false work?
> Q3. Does Ceph team recognize this issue? I'm glad if they help me because I've investigated this issue but haven't made any progress yet.

Could you answer these questions?

**Comment by leseb** [comment]
> @leseb
> 
> > I have some questions.
> > Q1. What version is your Ceph cluster? My problem happens in v16.2.x but not in v15.2.x

I saw this in the CI, which runs v16.2.

> > Q2. Could you try whether my mitigation, setting bluefs_buffered_io=false work?

I can try?

> > Q3. Does Ceph team recognize this issue? I'm glad if they help me because I've investigated this issue but haven't made any progress yet.

I'll ask again the ceph team for more inputs.

> 
> Could you answer these questions?

**Comment by satoru-takeuchi** [comment]
This problem was fixed in v16.2.6.

**Comment by paul-bormans** [comment]
Notice we have also seen this issue (in fact running rook 1.7.7 we actually never seen all raw devices being picked up by ceph, usually 50% is used).

Also 16.2.7 still has this issue; i retested and seen this issue again happening on all hosts.

We did run a test with the bluefs_buffered_io = false override and i can confirm that i did not get any crashes during osd prepare and i get all osd's i expect.

Maybe what is specific on our setup is that we have 3 disks per host; it looks like a concurrency issue to me; some "state" doesn't seem properly protected for exclusive access.

I'll see if i can reopen the ticket at the ceph repo.

Paul

**Comment by df-bingo** [comment]
Also 16.2.7 still has this issue; i retested and seen this issue again happening on all hosts.

**Comment by ftab** [comment]
Getting this error on a fresh test cluster

The weird thing is this is using the same version of rook (1.9.1), ceph (v17.2.0-20220420), almost the same cluster yml, and the same storageclass (deploy/examples/csi/rbd/storageclass.yml) as my production cluster which has been running for a while (but wasn't stood up directly on 1.9.1 / v17.2.0-20220420, it was upgraded to that from an older version). I added memory limits to the cluster.yml compared to the one I used in my production cluster setup. Everything else is the same.

Here's the diff between 1.9.1's cluster.yaml and my file:
```diff
24c24
<     image: quay.io/ceph/ceph:v16.2.7
---
>     image: quay.io/ceph/ceph:v17.2.0-20220420
57c57
<     count: 2
---
>     #count: 2
195,202c195,230
< # The requests and limits set here, allow the mgr pod to use half of one CPU core and 1 gigabyte of memory
< #    mgr:
< #      limits:
< #        cpu: "500m"
< #        memory: "1024Mi"
< #      requests:
< #        cpu: "500m"
< #        memory: "1024Mi"
---
>     mgr:
>       limits:
>         #cpu: "500m"
>         memory: "512Mi"
>       requests:
>         #cpu: "500m"
>         memory: "512Mi"
>     mon:
>       limits:
>         #cpu: "500m"
>         memory: "1024Mi"
>       requests:
>         #cpu: "500m"
>         memory: "1024Mi"
>     osd:
>       limits:
>         #cpu: "500m"
>         memory: "2048Mi"
>       requests:
>         #cpu: "500m"
>         memory: "2048Mi"
>     prepareosd:
>       limits:
>         memory: "50Mi"
>       requests:
>         memory: "50Mi"
>     crashcollector:
>       limits:
>         memory: "60Mi"
>       requests:
>         memory: "60Mi"
>     mgr-sidecar:
>       limits:
>         memory: "100Mi"
>       requests:
>         memory: "40Mi"
230c258
<       # databaseSizeMB: "1024" # uncomment if the disks are smaller than 100 GB
---
>       databaseSizeMB: "1024" # uncomment if the disks are smaller than 100 GB
```

I created three new Debian 11.3 VMs from the netinst image with just standard system utilities and SSH server, and partitioned without swap, then set up the same kubespray inventory settings as my production cluster, deployed with kubespray 2.19.0. This is the kubespray inventory: 

[inventory.zip](https://github.com/rook/rook/files/9186462/inventory.zip)

My intent was to set up the same versions on my test cluster as in my production cluster so that I can apply upgrades to the test cluster first so that I know what to expect and how to not screw up production. (Yeah, I did that in the wrong order, should've had the test cluster up first...oof)

Will I need to upgrade the ceph version to get this to work?

**Comment by xuanhr** [comment]
****

> edit: ok, nevermind that, I removed the memory limits, and it's working ok for now (I guess I'll see what happens when I deploy other stuff to the cluster)
> 
> ~Getting this error on a fresh test cluster~
> 
> The weird thing is this is using the same version of rook (1.9.1), ceph (v17.2.0-20220420), almost the same cluster yml, and the same storageclass (deploy/examples/csi/rbd/storageclass.yml) as my production cluster which has been running for a while (but wasn't stood up directly on 1.9.1 / v17.2.0-20220420, it was upgraded to that from an older version). I added memory limits to the cluster.yml compared to the one I used in my production cluster setup. Everything else is the same.
> 
> Here's the diff between 1.9.1's cluster.yaml and my file:
> 
> ```diff
> 24c24
> <     image: quay.io/ceph/ceph:v16.2.7
> ---
> >     image: quay.io/ceph/ceph:v17.2.0-20220420
> 57c57
> <     count: 2
> ---
> >     #count: 2
> 195,202c195,230
> < # The requests and limits set here, allow the mgr pod to use half of one CPU core and 1 gigabyte of memory
> < #    mgr:
> < #      limits:
> < #        cpu: "500m"
> < #        memory: "1024Mi"
> < #      requests:
> < #        cpu: "500m"
> < #        memory: "1024Mi"
> ---
> >     mgr:
> >       limits:
> >         #cpu: "500m"
> >         memory: "512Mi"
> >       requests:
> >         #cpu: "500m"
> >         memory: "512Mi"
> >     mon:
> >       limits:
> >         #cpu: "500m"
> >         memory: "1024Mi"
> >       requests:
> >         #cpu: "500m"
> >         memory: "1024Mi"
> >     osd:
> >       limits:
> >         #cpu: "500m"
> >         memory: "2048Mi"
> >       requests:
> >         #cpu: "500m"
> >         memory: "2048Mi"
> >     prepareosd:
> >       limits:
> >         memory: "50Mi"
> >       requests:
> >         memory: "50Mi"
> >     crashcollector:
> >       limits:
> >         memory: "60Mi"
> >       requests:
> >         memory: "60Mi"
> >     mgr-sidecar:
> >       limits:
> >         memory: "100Mi"
> >       requests:
> >         memory: "40Mi"
> 230c258
> <       # databaseSizeMB: "1024" # uncomment if the disks are smaller than 100 GB
> ---
> >       databaseSizeMB: "1024" # uncomment if the disks are smaller than 100 GB
> ```
> 
> I created three new Debian 11.3 VMs from the netinst image with just standard system utilities and SSH server, and partitioned without swap, then set up the same kubespray inventory settings as my production cluster, deployed with kubespray 2.19.0. This is the kubespray inventory:
> 
> [inventory.zip](https://github.com/rook/rook/files/9186462/inventory.zip)
> 
> My intent was to set up the same versions on my test cluster as in my production cluster so that I can apply upgrades to the test cluster first so that I know what to expect and how to not screw up production. (Yeah, I did that in the wrong order, should've had the test cluster up first...oof)
> 
> Will I need to upgrade the ceph version to get this to work?
> 
> edit: ok, nevermind that, I removed the memory limits, and it's working ok for now (I guess I'll see what happens when I deploy other stuff to the cluster)

same as me
