### ISSUE TITLE
Add docs about how to migrate a ceph cluster with disk encryption to a new kubernets cluster

### ISSUE THREAD

**Issue by neumantm** [rook/rook#8057]
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
The following should be added to [the disaster recovery documentation under adopting an existing rook ceph cluster into a new kuberntes cluster](https://github.com/rook/rook/blob/master/Documentation/ceph-disaster-recovery.md#adopt-an-existing-rook-ceph-cluster-into-a-new-kubernetes-cluster):
How to do such a migration/what to do different when `encryptedDevice: "true"` is set in the `storage.config` section of the Cluster spec.
**What is use case behind this feature:**
Anyone who wants to migrate their encrypted CephCluster can do that.
When following the existing guide, I got the following error in the OSDs logs at step 19:
```
+ ceph-volume lvm activate --no-systemd --bluestore 2 4e6efffe-6b79-4d0b-9eb7-9e8c63f1fbaa
Running command: /usr/bin/ceph --cluster ceph --name client.osd-lockbox.4e6efffe-6b79-4d0b-9eb7-9e8c63f1fbaa --keyring /var/lib/ceph/osd/ceph-2/lockbox.keyring config-key get dm-crypt/osd/4e6efffe-6b79-4d0b-9eb7-9e8c63f1fbaa/luks
 stderr: Error ENOENT: error obtaining 'dm-crypt/osd/4e6efffe-6b79-4d0b-9eb7-9e8c63f1fbaa/luks': (2) No such file or directory
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/main.py", line 42, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 370, in main
    self.activate(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 294, in activate
    activate_bluestore(lvs, args.no_systemd)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 173, in activate_bluestore
    dmcrypt_secret = encryption_utils.get_dmcrypt_key(osd_id, osd_fsid)
  File "/usr/lib/python3.6/site-packages/ceph_volume/util/encryption.py", line 139, in get_dmcrypt_key
    raise RuntimeError('Unable to retrieve dmcrypt secret')
RuntimeError: Unable to retrieve dmcrypt secret
```
**Environment**:

The error occurred with rook v1.6.4

I need to add that our Ceph Cluster was in a non-functioning state (after accidentally deleting all rook CRDs, which destroyed our  and trying some other things to restore) when I followed the guide.
Therefore, someone probably should first confirm, that it was not caused by that.
However, I don't really see how the new cluster would have the dmcrypt secrets when following the guide.

**Comment by neumantm** [comment]
Thanks for the answer. Yes I think you are right. It's just it would be helpful to document how to transfer these keys from the old K/V store to the new K/V store.
We had serious problems with our old cluster, so we probably had no chance to recover the keys from it.
Due to time running out we opted to create a fresh cluster and restore the data from backups.
Our new cluster is based on PVCs, so I think it is not of much use for me to run the command now.
