### ISSUE TITLE
NFS Ganesha Daemon not responding in Ceph Dashboard

### ISSUE THREAD

**Issue by linkvt** [rook/rook#8179]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When opening the NFS tab in the Ceph dashboard I can't configure the NFS Mounts anymore on one cluster, they just don't load. I'm not sure how the internal communication works, but I guess there is an issue with ganesha as an API request times out, see below.

The backend was correctly configured:
```
[root@rook-ceph-tools-7d79b476d4-fghr2 /]# ceph dashboard get-ganesha-clusters-rados-pool-namespace
REDACTED-data0/nfs-ns
```

**Expected behavior:**
Existing NFS Mounts should load in the dashboard so that I can configure them, I also can't add new mounts.

**How to reproduce it (minimal and precise):**

Not sure how to reproduce, what happened is that I had the CephNFS CR deployed, was able to setup a mount and tested some configurations but a bit unsuccessful (likely due to a user error on my side). I can't guarantee that something was configured via ceph CLI during these tests, but every check I ran showed an equal state compared to my working DEV cluster so I guess this was not the case.
When this mount didn't work I removed the CR and added it again later. The mount is now still setup by rook, but can't be configured anymore.

Shown errors:
1. Request to `/api/nfs-ganesha/daemon` from dashboard returns 504
![image](https://user-images.githubusercontent.com/3075401/122958199-ef5d2400-d382-11eb-991f-390287eb7f21.png)

2. While opening the NFS tab of the dashboard the `mgr` logs these errors multiple times:
```
mgr debug 2021-06-22T15:42:37.012+0000 7f5f75a5b700  0 [dashboard ERROR exception[] Internal Server Error
mgr Traceback (most recent call last):
mgr   File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 46, in dashboard_exception_handler
mgr     return handler(*args, **kwargs)
mgr   File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
mgr     return self.callable(*self.args, **self.kwargs)
mgr   File "/usr/share/ceph/mgr/dashboard/controllers/home.py", line 135, in __call__
mgr     return serve_file(full_path)
mgr   File "/usr/lib/python3.6/site-packages/cherrypy/lib/static.py", line 77, in serve_file
mgr     cptools.validate_since()
mgr   File "/usr/lib/python3.6/site-packages/cherrypy/lib/cptools.py", line 116, in validate_since
mgr     raise cherrypy.HTTPRedirect([], 304)
mgr cherrypy._cperror.HTTPRedirect: ([], 304)
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04.2
* Kernel (e.g. `uname -a`): 5.4.0-65-generic
* Cloud provider or hardware configuration: on premises
* Rook version (use `rook version` inside of a Rook Pod): 1.6.5
* Storage backend version (e.g. for ceph do `ceph -v`): `ceph -v` in tools says `16.2.2`, but the following images are used `ceph/ceph:v16.2.4-20210514` in the OSDs
* Kubernetes version (use `kubectl version`): 1.19.9
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Kubespray
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): `HEALTH_OK`

**Further possibly useful logs**
```
# ceph orch status

Error ENOENT: No orchestrator configured (try `ceph orch set backend`)
```

```
# ceph mgr module ls | head -n 13
{
    "always_on_modules": [
        "balancer",
        "crash",
        "devicehealth",
        "orchestrator",
        "pg_autoscaler",
        "progress",
        "rbd_support",
        "status",
        "telemetry",
        "volumes"
    ],
```

Existing NFS objects in rados
```
# rados -p REDACTED-data0 -N nfs-ns get export-1 -
EXPORT {
    export_id = 1;
    path = "/data";
    pseudo = "/REDACTED";
    tag = "data";
    access_type = "RW";
    squash = "no_root_squash";
    protocols = 3, 4;
    transports = "TCP", "UDP";
    FSAL {
        name = "CEPH";
        user_id = "admin";
        filesystem = "REDACTED";
        secret_access_key = "AQAzwbBREDACTEDRwZNKw==";
    }

    CLIENT {
        clients = REDACTED/8;
        access_type = "RW";
        squash = "no_root_squash";
    }

}
```

**Comment by travisn** [comment]
@varshar16 thoughts on this one?

**Comment by varshar16** [comment]
@linkvt please share the entire mgr log and nfs pods status

**Comment by linkvt** [comment]
@varshar16 sure, I deleted mgr and nfs pods, opened the dashboard, logged in and switched to the NFS tab.

[mgr.log](https://github.com/rook/rook/files/6701327/mgr.log)
[nfs-a.log](https://github.com/rook/rook/files/6701330/nfs-a.log)
[nfs-b.log](https://github.com/rook/rook/files/6701329/nfs-b.log)
[nfs-c.log](https://github.com/rook/rook/files/6701328/nfs-c.log)

**Comment by varshar16** [comment]
From the log, I see the cephfs export is successfully created. The error is more specific to dashboard. @alfonsomthd please look into it.
