### ISSUE TITLE
Can't create OSD when block is RAW, metadata is LVM

### ISSUE THREAD

**Issue by kondas** [rook/rook#8255]
**Is this a bug report or feature request?**
* Bug Report

**Environment**:
* OS (e.g. from /etc/os-release):  Debian GNU/Linux 10 (buster)
* Kernel (e.g. `uname -a`): Linux 4.19.0-17-amd64 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux
* Cloud provider or hardware configuration: Baremetal 
* Rook version (use `rook version` inside of a Rook Pod):  v1.6.7
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.7
* Kubernetes version (use `kubectl version`): 1.21.2

**Deviation from expected behavior:**
OSD doesn't get created when  OSD device is raw, metadata is LVM LV

**How to reproduce it (minimal and precise):**
I am trying to create an OSD, using a HDD as block and a partition on an NVME drive as block.db, but I have no success so far. 
I can see in ceph-volume docs that it can use raw device or LVM LV for metadata in batch mode so i'm trying to utilize the partition on the NVME drive as an LV, but the HDD as a raw device.

Cluster config:

```  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    #deviceFilter: "sda"
    config:
      metadataDevice: "/dev/nvme/ceph-md"
    nodes:
    - name: "k8s-1"
      devices: # specific devices to use for storage can be specified for each node
      - name: "sda"
```

OSD Prepare logs:
```
2021-07-04 20:41:45.907213 I | cephosd: using /dev/nvme/ceph-md as metadataDevice for device /dev/sda and let ceph-volume lvm batch decide how to create volumes
2021-07-04 20:41:45.907395 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --osds-per-device 1 --crush-device-class hdd /dev/sda --db-devices /dev/nvme/ceph-md --report
2021-07-04 20:41:47.391828 D | exec: --> passed data devices: 1 physical, 0 LVM
2021-07-04 20:41:47.391870 D | exec: --> relative data size: 1.0
2021-07-04 20:41:47.391881 D | exec: --> passed block_db devices: 0 physical, 1 LVM
2021-07-04 20:41:47.394979 D | exec: Traceback (most recent call last):
2021-07-04 20:41:47.395002 D | exec:   File "/usr/sbin/ceph-volume", line 11, in <module>
2021-07-04 20:41:47.395012 D | exec:     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
2021-07-04 20:41:47.395020 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
2021-07-04 20:41:47.395061 D | exec:     self.main(self.argv)
2021-07-04 20:41:47.395071 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
2021-07-04 20:41:47.395079 D | exec:     return f(*a, **kw)
2021-07-04 20:41:47.395088 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
2021-07-04 20:41:47.395096 D | exec:     terminal.dispatch(self.mapper, subcommand_args)
2021-07-04 20:41:47.395104 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2021-07-04 20:41:47.395134 D | exec:     instance.main()
2021-07-04 20:41:47.395217 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/main.py", line 42, in main
2021-07-04 20:41:47.395274 D | exec:     terminal.dispatch(self.mapper, self.argv)
2021-07-04 20:41:47.395364 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2021-07-04 20:41:47.395429 D | exec:     instance.main()
2021-07-04 20:41:47.395479 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
2021-07-04 20:41:47.395579 D | exec:     return func(*a, **kw)
2021-07-04 20:41:47.395695 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 402, in main
2021-07-04 20:41:47.395743 D | exec:     plan = self.get_plan(self.args)
2021-07-04 20:41:47.395808 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 440, in get_plan
2021-07-04 20:41:47.395869 D | exec:     args.wal_devices)
2021-07-04 20:41:47.395953 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 472, in get_deployment_layout
2021-07-04 20:41:47.395994 D | exec:     fast_type)
2021-07-04 20:41:47.396060 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 514, in fast_allocations
2021-07-04 20:41:47.396267 D | exec:     if (requested_osds - len(lvm_devs)) % len(phys_devs):
2021-07-04 20:41:47.396289 D | exec: ZeroDivisionError: integer division or modulo by zero
failed to configure devices: failed to initialize lvm based osd: failed ceph-volume report: exit status 1
```

**Comment by kondas** [comment]
If using device mapper path, privisioning results in different error.
``` 
   config:
      metadataDevice: "/dev/mapper/nvme-ceph--md"
```

```2021-07-04 20:47:02.778631 I | cephosd: using /dev/mapper/nvme-ceph--md as metadataDevice for device /dev/sda and let ceph-volume lvm batch decide how to create volumes
2021-07-04 20:47:02.778640 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm batch --prepare --bluestore --yes --osds-per-device 1 --crush-device-class hdd /dev/sda --db-devices /dev/mapper/nvme-ceph--md --report
2021-07-04 20:47:03.278109 D | exec: --> passed data devices: 1 physical, 0 LVM
2021-07-04 20:47:03.278125 D | exec: --> relative data size: 1.0
2021-07-04 20:47:03.278128 D | exec: --> passed block_db devices: 0 physical, 1 LVM
2021-07-04 20:47:03.278951 D | exec: Traceback (most recent call last):
2021-07-04 20:47:03.278957 D | exec:   File "/usr/sbin/ceph-volume", line 11, in <module>
2021-07-04 20:47:03.278959 D | exec:     load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
2021-07-04 20:47:03.278961 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
2021-07-04 20:47:03.278963 D | exec:     self.main(self.argv)
2021-07-04 20:47:03.278965 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
2021-07-04 20:47:03.278967 D | exec:     return f(*a, **kw)
2021-07-04 20:47:03.278971 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
2021-07-04 20:47:03.278982 D | exec:     terminal.dispatch(self.mapper, subcommand_args)
2021-07-04 20:47:03.278984 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2021-07-04 20:47:03.278986 D | exec:     instance.main()
2021-07-04 20:47:03.278988 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/main.py", line 42, in main
2021-07-04 20:47:03.278990 D | exec:     terminal.dispatch(self.mapper, self.argv)
2021-07-04 20:47:03.278992 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
2021-07-04 20:47:03.279007 D | exec:     instance.main()
2021-07-04 20:47:03.279008 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
2021-07-04 20:47:03.279011 D | exec:     return func(*a, **kw)
2021-07-04 20:47:03.279014 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 402, in main
2021-07-04 20:47:03.279015 D | exec:     plan = self.get_plan(self.args)
2021-07-04 20:47:03.279019 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 440, in get_plan
2021-07-04 20:47:03.279023 D | exec:     args.wal_devices)
2021-07-04 20:47:03.279025 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 472, in get_deployment_layout
2021-07-04 20:47:03.279027 D | exec:     fast_type)
2021-07-04 20:47:03.279029 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 509, in fast_allocations
2021-07-04 20:47:03.279031 D | exec:     ret.extend(get_lvm_fast_allocs(lvm_devs))
2021-07-04 20:47:03.279032 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 146, in get_lvm_fast_allocs
2021-07-04 20:47:03.279034 D | exec:     disk.Size(b=int(d.lvs[0].lv_size)), 1) for d in lvs if not
2021-07-04 20:47:03.279036 D | exec:   File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/batch.py", line 147, in <listcomp>
2021-07-04 20:47:03.279038 D | exec:     d.used_by_ceph]
2021-07-04 20:47:03.279040 D | exec: IndexError: list index out of range
failed to configure devices: failed to initialize lvm based osd: failed ceph-volume report: exit status 1

**Comment by leseb** [comment]
It looks like a `ceph-volume` limitation, please consider opening a bug here https://tracker.ceph.com/projects/ceph-volume instead to whether this is a supported scenario.
Thanks!
