### ISSUE TITLE
LV-backed PVC OSD pods CrashLoopBackOff when upgrading from v1.5.5 to v1.6.7

### ISSUE THREAD

**Issue by paxnil** [rook/rook#8264]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
When I update operator image to v1.6.7, all OSD pods could not start.

**Expected behavior:**
OSD pods all started.

**How to reproduce it (minimal and precise):**

I noticed that updated osd deployment removed host path `/dev`.
```spec:
  template:
    spec:
      containers:
      - name: osd
        volumeMounts:
        - mountPath: /dev
          name: devices
      volumes:
      - hostPath:
          path: /dev
        name: devi
```
Now I have to add it back manually to recover service.

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15.2.13
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: false
  dashboard:
    enabled: true
    ssl: false
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  monitoring:
    enabled: false  # requires Prometheus to be pre-installed
    rulesNamespace: rook-ceph
  network:
    hostNetwork: false
# rbdMirroring:
#   workers: 0
  storage:
    usageAllNodes: false
    useAllDevices: false
    config:
      osdsPerDevice: "1"
    storageClassDeviceSets:
    - name: lvm
      count: 3
      portable: false
      tuneSlowDeviceClass: false
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 1Ti
          selector:
            matchLabels:
              pv.devx.local/type: "rook-ceph"
          storageClassName: local-storage
          volumeMode: Block
          accessModes:
          - ReadWriteOnce
```
* PV
```apiVersion: v1
kind: PersistentVolume
metadata:
  name: rook0
  labels:
    pv.devx.local/type: "rook-ceph"
spec:
  capacity:
    storage: 1Ti
  volumeMode: Block
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /dev/devx/rook0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - devx
---
...
```

* Crashing pod(s) logs, if necessary
```
[2021-07-05 11:18:40,573][ceph_volume.main][INFO  ] Running command: ceph-volume  lvm activate --no-systemd -- 0 0a82f1da-94c9-455d-b4d7-4b0bdc574a88
[2021-07-05 11:18:40,574][ceph_volume.process][INFO  ] Running command: /usr/sbin/lvs --noheadings --readonly --separator=";" -a --units=b --nosuffix -S tags={ceph.osd_id=0,ceph.osd_fsid=0a82f1da-94c9-455d-b4d7-4b0bdc574a88} -o lv_tags,lv_path,lv_name,vg_name,lv_uuid,lv_size
[2021-07-05 11:18:40,698][ceph_volume.process][INFO  ] stdout ceph.block_device=/dev/devx/rook0,ceph.block_uuid=p3DRs2-ErWO-mkiB-MYG9-9op9-aJG2-lOAKPW,ceph.cephx_lockbox_secret=,ceph.cluster_fsid=bc113d7c-a441-4d4d-989a-2f116ced37f4,ceph.cluster_name=ceph,ceph.crush_device_class=None,ceph.encrypted=0,ceph.osd_fsid=0a82f1da-94c9-455d-b4d7-4b0bdc574a88,ceph.osd_id=0,ceph.type=block,ceph.vdo=0";"/dev/devx/rook0";"rook0";"devx";"p3DRs2-ErWO-mkiB-MYG9-9op9-aJG2-lOAKPW";"1099511627776
[2021-07-05 11:18:40,698][ceph_volume.process][INFO  ] stderr Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will manage logical volume symlinks in device directory.
[2021-07-05 11:18:40,698][ceph_volume.process][INFO  ] stderr Udev is running and DM_DISABLE_UDEV environment variable is set. Bypassing udev, LVM will obtain device list by scanning device directory.
[2021-07-05 11:18:40,702][ceph_volume.process][INFO  ] Running command: /usr/bin/mount -t tmpfs tmpfs /var/lib/ceph/osd/ceph-0
[2021-07-05 11:18:40,707][ceph_volume.util.system][INFO  ] CEPH_VOLUME_SKIP_RESTORECON environ is set, will not call restorecon
[2021-07-05 11:18:40,708][ceph_volume.devices.lvm.activate][DEBUG ] Found block device (rook0) with encryption: False
[2021-07-05 11:18:40,708][ceph_volume.devices.lvm.activate][DEBUG ] Found block device (rook0) with encryption: False
[2021-07-05 11:18:40,708][ceph_volume.process][INFO  ] Running command: /usr/bin/chown -R ceph:ceph /var/lib/ceph/osd/ceph-0
[2021-07-05 11:18:40,712][ceph_volume.process][INFO  ] Running command: /usr/bin/ceph-bluestore-tool --cluster=ceph prime-osd-dir --dev /dev/devx/rook0 --path /var/lib/ceph/osd/ceph-0 --no-mon-config
[2021-07-05 11:18:40,741][ceph_volume.process][INFO  ] stderr failed to read label for /dev/devx/rook0: (2) No such file or directory
2021-07-05T11:18:40.737+0000 7fd32e9fa240 -1 bluestore(/dev/devx/rook0) _read_bdev_label failed to open /dev/devx/rook0: (2) No such file or directory
[2021-07-05 11:18:40,743][ceph_volume][ERROR ] exception caught by decorator
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/main.py", line 42, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 370, in main
    self.activate(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 294, in activate
    activate_bluestore(lvs, args.no_systemd)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 194, in activate_bluestore
    process.run(prime_command)
  File "/usr/lib/python3.6/site-packages/ceph_volume/process.py", line 153, in run
    raise RuntimeError(msg)
RuntimeError: command returned non-zero exit status: 1
```

**Environment**:
* OS (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
* Kernel (e.g. `uname -a`): Linux devx 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
* Cloud provider or hardware configuration: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
* Rook version (use `rook version` inside of a Rook Pod): v1.6.7
* Storage backend version (e.g. for ceph do `ceph -v`): 15.2.13
* Kubernetes version (use `kubectl version`): 1.21.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Offical build
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by satoru-takeuchi** [comment]
@paxnil Sorry for the late reply.

> [2021-07-05 11:18:40,741][ceph_volume.process][INFO  ] stderr failed to read label for /dev/devx/rook0: (2) No such file or directory
> 2021-07-05T11:18:40.737+0000 7fd32e9fa240 -1 bluestore(/dev/devx/rook0) _read_bdev_label failed to open /dev/devx/rook0: (2) No such file or directory

It's odd. This log shows that "/dev/devx/rook0" didn't exist.

I have some questions and requests.

## Q1

> I noticed that updated osd deployment removed host path /dev.
```
  template:
    spec:
      containers:
      - name: osd
        volumeMounts:
        - mountPath: /dev
          name: devices
      volumes:
      - hostPath:
          path: /dev
        name: devi
 ```

Do you mean that above-mentioned

```
- hostPath:
    path: /dev
  name: devi
```

was missing? In addition, the `name` field was "devi"? Or it was "devices"?

## Q2

I guess you have at least three PVs because your `cluster.yaml` declares three OSDs should exist. If its correct, could you provide all three PV's manifests?

In addition, Could you give me the result of the following commands?

- `xxd -l 128 /dev/devx/rook0`
- `lsblk`
- `lvdisplay`

**Comment by travisn** [comment]
It looks like previous to 1.6, `/dev` was always mounted for [lvm mode](https://github.com/rook/rook/blob/release-1.5/pkg/operator/ceph/cluster/osd/spec.go#L315-L320), but since 1.6 it is only mounted for the [non-pvc mode](https://github.com/rook/rook/blob/release-1.6/pkg/operator/ceph/cluster/osd/spec.go#L342-L347). Seems like we need to add the mount for the lvm mode on PVC. @satoru-takeuchi Want to look at that?

**Comment by satoru-takeuchi** [comment]
@travisn OK, I overlooked this change. I'll send a PR.

**Comment by paxnil** [comment]
@satoru-takeuchi 

# Q1
`volumeMounts` and `volume` are both missing.
The `name` field was `devices`.

# Q2

```
# xxd -l 128 /dev/devx/rook0
00000000: 626c 7565 7374 6f72 6520 626c 6f63 6b20  bluestore block
00000010: 6465 7669 6365 0a30 6138 3266 3164 612d  device.0a82f1da-
00000020: 3934 6339 2d34 3535 642d 6234 6437 2d34  94c9-455d-b4d7-4
00000030: 6230 6264 6335 3734 6138 380a 0201 a701  b0bdc574a88.....
00000040: 0000 0a82 f1da 94c9 455d b4d7 4b0b dc57  ........E]..K..W
00000050: 4a88 0000 0000 0001 0000 66eb a75e b9aa  J.........f..^..
00000060: 771f 0400 0000 6d61 696e 0d00 0000 0a00  w.....main......
00000070: 0000 6266 6d5f 626c 6f63 6b73 0800 0000  ..bfm_blocks....
```

```
# lsblk
NAME                MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
loop0                 7:0    0    1T  0 loop
loop1                 7:1    0    1T  0 loop
loop2                 7:2    0    1T  0 loop
sda                   8:0    0  3.3T  0 disk
├─sda1                8:1    0  243M  0 part  /boot/efi
├─sda2                8:2    0  977M  0 part  /boot
└─sda3                8:3    0  3.3T  0 part
  ├─devx-root       253:0    0 59.6G  0 lvm   /
  ├─devx-var        253:1    0 59.6G  0 lvm   /var
  ├─devx-rook0      253:2    0    1T  0 lvm
  ├─devx-docker     253:3    0  512G  0 lvm
  └─devx-containerd 253:4    0  500G  0 lvm   /var/lib/containerd
sdb                   8:16   0  9.1T  0 disk
└─vault1            253:5    0  9.1T  0 mpath
  ├─vault-rook1     253:7    0    1T  0 lvm
  └─vault-empdata   253:8    0    5T  0 lvm   /mnt/vault2
sdc                   8:32   0  7.3T  0 disk
└─vault2            253:6    0  7.3T  0 mpath
  └─vault-rook2     253:9    0    1T  0 lvm
sdd                   8:48   0  9.1T  0 disk
└─vault1            253:5    0  9.1T  0 mpath
  ├─vault-rook1     253:7    0    1T  0 lvm
  └─vault-empdata   253:8    0    5T  0 lvm   /mnt/vault2
sde                   8:64   0  7.3T  0 disk
└─vault2            253:6    0  7.3T  0 mpath
  └─vault-rook2     253:9    0    1T  0 lvm
sr0                  11:0    1 1024M  0 rom
rbd0                252:0    0  100M  0 disk
```

```
# lvdisplay
  --- Logical volume ---
  LV Path                /dev/vault/rook1
  LV Name                rook1
  VG Name                vault
  LV UUID                8DclWZ-fVfQ-aFCo-gU4x-9kmq-bQnu-fZ6taV
  LV Write Access        read/write
  LV Creation host, time devx, 2019-11-29 11:17:10 +0800
  LV Status              available
  # open                 25
  LV Size                1.00 TiB
  Current LE             262144
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           253:7

  --- Logical volume ---
  LV Path                /dev/vault/rook2
  LV Name                rook2
  VG Name                vault
  LV UUID                CnoxVX-sFzu-Nynm-X0So-Hi1g-IBj1-M9olvN
  LV Write Access        read/write
  LV Creation host, time devx, 2019-11-29 16:09:11 +0800
  LV Status              available
  # open                 25
  LV Size                1.00 TiB
  Current LE             262144
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           253:9

  --- Logical volume ---
  LV Path                /dev/devx/rook0
  LV Name                rook0
  VG Name                devx
  LV UUID                p3DRs2-ErWO-mkiB-MYG9-9op9-aJG2-lOAKPW
  LV Write Access        read/write
  LV Creation host, time devx, 2018-01-09 14:18:51 +0800
  LV Status              available
  # open                 25
  LV Size                1.00 TiB
  Current LE             262144
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     256
  Block device           253:2
```

**Comment by satoru-takeuchi** [comment]
Thank you!

**Comment by satoru-takeuchi** [comment]
@paxnil Your problem will be fixed in the next stable release.
