### ISSUE TITLE
Certificate error cause ceph dashboard module fail

### ISSUE THREAD

**Issue by jmolmo** [rook/rook#8414]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

**Expected behavior:**
Ceph Dashboard module must run 

**How to reproduce it (minimal and precise):**
Create a ceph cluster with dashboard enabled ( in cluster.yaml)
`# kubectl create -f cluster.yaml`

Access the ceph  toolbox, and check status:

```
# ceph -s 
  cluster:
    id:     67fc116a-3ae8-4c1d-ba48-c89139a06ff6
    health: HEALTH_ERR
            Module 'dashboard' has failed: [('x509 certificate routines', 'X509_check_private_key', 'key values mismatch')]
            1 mgr modules have recently crashed
            OSD count 0 < osd_pool_default_size 3
 
  services:
    mon: 3 daemons, quorum a,b,c (age 22m)
    mgr: a(active, since 21m)
    osd: 0 osds: 0 up, 0 in
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs: 
```
**Manager log**:

```
debug 2021-07-28T15:23:28.831+0000 7fec3d05a700 -1 log_channel(cluster) log [ERR] : Unhandled exception from module 'dashboard' while running on mgr.a: [('x509 certificate routines', 'X509_check_private_key', 'key values mismatch')]
debug 2021-07-28T15:23:28.831+0000 7fec3d05a700 -1 dashboard.serve:
debug 2021-07-28T15:23:28.831+0000 7fec3d05a700 -1 Traceback (most recent call last):
  File "/usr/share/ceph/mgr/dashboard/module.py", line 322, in serve
    uri = self.await_configuration()
  File "/usr/share/ceph/mgr/dashboard/module.py", line 211, in await_configuration
    uri = self._configure()
  File "/usr/share/ceph/mgr/dashboard/module.py", line 173, in _configure
    verify_tls_files(cert_fname, pkey_fname)
  File "/usr/share/ceph/mgr/mgr_util.py", line 592, in verify_tls_files
    context.use_privatekey_file(pkey_fname, crypto.FILETYPE_PEM)
  File "/usr/lib/python3.6/site-packages/OpenSSL/SSL.py", line 990, in use_privatekey_file
    self._raise_passphrase_exception()
  File "/usr/lib/python3.6/site-packages/OpenSSL/SSL.py", line 967, in _raise_passphrase_exception
    _raise_current_error()
  File "/usr/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('x509 certificate routines', 'X509_check_private_key', 'key values mismatch')]
debug 2021-07-28T15:23:28.834+0000 7fec32745700  0 [restful INFO root] server_addr: :: server_port: 8003
debug 2021-07-28T15:23:28.835+0000 7fec32745700  0 [restful WARNING root] server not running: no certificate configured
debug 2021-07-28T15:23:28.848+0000 7fec58238700  1 mgr load Constructed class from module: volumes
CherryPy Checker:
The Application mounted at '' has an empty config.
[28/Jul/2021:15:23:28] ENGINE Serving on http://10.244.2.9:9283
[28/Jul/2021:15:23:28] ENGINE Bus STARTED
debug 2021-07-28T15:23:28.932+0000 7fec39853700  0 [prometheus INFO cherrypy.error] [28/Jul/2021:15:23:28] ENGINE Serving on http://10.244.2.9:9283
debug 2021-07-28T15:23:28.932+0000 7fec39853700  0 [prometheus INFO cherrypy.error] [28/Jul/2021:15:23:28] ENGINE Bus STARTED
debug 2021-07-28T15:23:28.932+0000 7fec39853700  0 [prometheus INFO root] Engine started.
```

**Environment**:
* OS (e.g. from /etc/os-release): CentOS Linux release 7.8.2003 (Core)
* Kernel (e.g. `uname -a`): Linux k8s-master-00.rook 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Cloud provider or hardware configuration: VMs in my laptop
* Rook version (use `rook version` inside of a Rook Pod): rook: v1.7.0-alpha.0.19.ga2fa57e // go: go1.16.3
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.5 (0883bdea7337b95e4b611c768c0279868462204a) pacific (stable)
* Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): plain k8s cluster

**Comment by avanthakkar** [comment]
Seems like a mismatch in private_key and dashboard is fetching it from [localized_store](https://github.com/ceph/ceph/blob/434b325c40e329d8a0e5593e1c036e508ec1fa10/src/pybind/mgr/dashboard/module.py#L164)..so i don't think that should be issue...maybe the key provided in key file is incorrect?
