### ISSUE TITLE
update CephNFS RADOS spec to use .nfs pool

### ISSUE THREAD

**Issue by josephsawaya** [rook/rook#8450]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**

CephNFS allows for customisation of RADOS pool and namespace. If the RADOS pool and namespace are incorrect, nfs exports cannot be managed.

**Expected behavior:**

CephNFS always creates an NFS daemon with a RADOS pool of '.nfs' and a RADOS namespace equal to the cluster ID of that NFS daemon.

**How to reproduce it (minimal and precise):**

Create a cluster with a toolbox pod, create a CephFS following [this](https://rook.io/docs/rook/v1.6/ceph-filesystem.html),  create a CephNFS with any RADOS pool name other than '.nfs' following [this](https://rook.io/docs/rook/v1.7/ceph-nfs-crd.html), go into the toolbox and run these commands:
```
$ ceph mgr module enable rook
$ ceph orch set backend rook
$ ceph nfs export create cephfs myfs my-nfs /a
```
**File(s) to submit**:

resulting error in toolbox:
```
Error EINVAL: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 1565, in _handle_command
    return CLICommand.COMMANDS[cmd['prefix']].call(self, cmd, inbuf)
  File "/usr/share/ceph/mgr/mgr_module.py", line 414, in call
    return self.func(mgr, **kwargs)
  File "/usr/share/ceph/mgr/nfs/module.py", line 42, in _cmd_nfs_export_create_cephfs
    squash=squash, addr=client_addr)
  File "/usr/share/ceph/mgr/nfs/export.py", line 36, in cluster_check
    return func(export, *args, **kwargs)
  File "/usr/share/ceph/mgr/nfs/export.py", line 333, in create_export
    if kwargs['cluster_id'] not in self.exports:
  File "/usr/share/ceph/mgr/nfs/export.py", line 156, in exports
    self._read_raw_config(cluster_id)
  File "/usr/share/ceph/mgr/nfs/export.py", line 237, in _read_raw_config
    with self.mgr.rados.open_ioctx(self.rados_pool) as ioctx:
  File "rados.pyx", line 981, in rados.Rados.open_ioctx
rados.ObjectNotFound: [errno 2] RADOS object not found (error opening pool '.nfs')
```

**Environment**:
* OS (e.g. from /etc/os-release): Buildroot (using minkube)
* Kernel (e.g. `uname -a`): `Linux minikube 4.19.182 #1 SMP Wed May 5 21:20:39 UTC 2021 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: Two nodes running in minikube, one has two 5GB virtual devices attached
* Rook version (use `rook version` inside of a Rook Pod):  v1.7.0-alpha.0.46.ge5a261f
* Storage backend version (e.g. for ceph do `ceph -v`): ceph version 16.2.5
* Kubernetes version (use `kubectl version`): v1.19.2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): Minikube?
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)): HEALTH_OK

**Comment by leseb** [comment]
Are you saying we should stop allowing pool name customization and hardcode?

**Comment by josephsawaya** [comment]
> Are you saying we should stop allowing pool name customization and hardcode?

Since it looks like it's hardcoded in the Ceph NFS module, I think it should be hardcoded in Rook

**Comment by leseb** [comment]
> > Are you saying we should stop allowing pool name customization and hardcode?
> 
> Since it looks like it's hardcoded in the Ceph NFS module, I think it should be hardcoded in Rook

Is it new in Pacific?

**Comment by josephsawaya** [comment]
> > > Are you saying we should stop allowing pool name customization and hardcode?
> > 
> > 
> > Since it looks like it's hardcoded in the Ceph NFS module, I think it should be hardcoded in Rook
> 
> Is it new in Pacific?

I'm not exactly sure what you mean, but it doesn't look like the changes have been backported to Pacific the changes are only on the Ceph master branch for now

**Comment by josephsawaya** [comment]
> > > > > Are you saying we should stop allowing pool name customization and hardcode?
> > > > 
> > > > 
> > > > Since it looks like it's hardcoded in the Ceph NFS module, I think it should be hardcoded in Rook
> > > 
> > > 
> > > Is it new in Pacific?
> > 
> > 
> > I'm not exactly sure what you mean, but it doesn't look like the changes have been backported to Pacific the changes are only on the Ceph master branch for now
> 
> Hum ok. Can you point to the PR that hardcoded this? Do you have more rationale on why that change was made? (the hardcode). Thanks

Here is the [PR](https://github.com/ceph/ceph/pull/42073). The PR description has a short explanation but it seems that the change was made to simplify using the nfs module.
