### ISSUE TITLE
OSD disk not coming UP after node reboot

### ISSUE THREAD

**Issue by kannanvr** [rook/rook#8536]
* Bug Report
One of the OSD is not come up after the Node restart
activate container of OSD is failing with the below error

```
kubectl logs -f rook-ceph-osd-0-7dcd88cdb-svkrp -n rook-ceph -c activate
+ OSD_ID=0
+ OSD_UUID=221d3675-110a-4763-80aa-70aebe7d3856
+ OSD_STORE_FLAG=--bluestore
+ OSD_DATA_DIR=/var/lib/ceph/osd/ceph-0
+ CV_MODE=lvm
+ DEVICE=/dev/ceph-47cc0223-57fa-4e4d-9b92-d6ea5cf60d9e/osd-block-221d3675-110a-4763-80aa-70aebe7d3856
+ ceph -n client.admin auth get-or-create osd.0 mon 'allow profile osd' mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring
[osd.0]
        key = AQCKywlhK4E7FhAAn5wITn4IljbDUV4da0cMVQ==
+ [[ lvm == \l\v\m ]]
++ mktemp -d
+ TMP_DIR=/tmp/tmp.oyxVLq3qkw
+ ceph-volume lvm activate --no-systemd --bluestore 0 221d3675-110a-4763-80aa-70aebe7d3856
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 40, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/main.py", line 42, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 370, in main
    self.activate(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/activate.py", line 275, in activate
    (osd_id, osd_fsid))
RuntimeError: could not find osd.0 with osd_fsid 221d3675-110a-4763-80aa-70aebe7d3856
```

**Expected behavior:**
OSD pod should come up

**How to reproduce it (minimal and precise):**

1. Bring up the rook ceph with version - 1.6.8
2. restarting the node
3. OSD did not come up

**Environment**:
* OS (e.g. from /etc/os-release): centos 7
* Kernel (e.g. `uname -a`): 4.18.0-240.22.1.el8_3.x86_64
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod): 1.8.8
* Storage backend version (e.g. for ceph do `ceph -v`): 16.2.2
* Kubernetes version (use `kubectl version`): 1.20
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): OnPrem
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):
```
HEALTH_WARN mon e is low on available space; Degraded data redundancy: 2/17349 objects degraded (0.012%), 1 pg degraded, 2 pgs undersized; 1 daemons have recently crashed
```

**Comment by travisn** [comment]
- You're running Rook v1.6.8? (you mentioned v1.6.8 above)
- Do you have [lvm installed on the hosts](https://rook.github.io/docs/rook/v1.7/ceph-prerequisites.html#lvm-package)? 
- In the toolbox does `ceph auth ls` show each OSD that isn’t starting?
