### ISSUE TITLE
Daily tests are failing to create OSDs against Ceph Master image

### ISSUE THREAD

**Issue by travisn** [rook/rook#9154]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The CephSmokeSuiteMaster and ObjectSuiteMaster tests are failing in the daily CI that runs against the latest ceph-master images, unable to start OSDs.

The osd prepare jobs complete successfully, then the CI logs show the following for the activate init container on the OSD daemon pod. 
```
+ find_device
+ python3 -c '
import sys, json
for _, info in json.load(sys.stdin).items():
	if info['\''osd_id'\''] == 0:
		print(info['\''device'\''], end='\'''\'')
		print('\''found device: '\'' + info['\''device'\''], file=sys.stderr) # log the disk we found to stderr
		sys.exit(0)  # don'\''t keep processing once the disk is found
sys.exit('\''no disk found with OSD ID 0'\'')
'
found device: /dev/sda1
+ [[ -z /dev/sda1 ]]
+ ceph-volume raw activate --device /dev/sda1 --no-systemd --no-tmpfs
 stderr: lsblk: : not a block device
 stderr: lsblk: d: not a block device
 stderr: lsblk: e: not a block device
 stderr: lsblk: v: not a block device
 stderr: lsblk: : not a block device
 stderr: lsblk: s: not a block device
 stderr: lsblk: d: not a block device
 stderr: lsblk: a: not a block device
 stderr: lsblk: 1: not a block device
Traceback (most recent call last):
  File "/usr/sbin/ceph-volume", line 11, in <module>
    load_entry_point('ceph-volume==1.0.0', 'console_scripts', 'ceph-volume')()
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 41, in __init__
    self.main(self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 153, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/activate.py", line 157, in main
    block_db=self.args.block_db)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/activate.py", line 92, in activate
    raise RuntimeError('did not find any matching OSD to activate')
RuntimeError: did not find any matching OSD to activate
/dev/sda1
```

See the full logs [here](https://github.com/travisn/rook/actions/runs/1446774724).  These failures have been consistent since 5 days ago. 

**Expected behavior:**
CI tests should pass against ceph master.

**How to reproduce it (minimal and precise):**

See the results from the [daily CI jobs](https://github.com/travisn/rook/actions/workflows/daily-nightly-jobs.yml).

**Comment by leseb** [comment]
@guits is looking into this.

**Comment by guits** [comment]
https://github.com/ceph/ceph/commit/1ce1b3b8ea8ef6b99abe8c14d69d83a47cbaf762#diff-e50fa2eed7ba730165a99ad1a30857e69990f162e997eb2fd982734abb270e64L100 broke this

**Comment by guits** [comment]
see https://github.com/ceph/ceph/pull/43927
