### ISSUE TITLE
Observed a panic: "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by ClaudiuLSH** [rook/rook#9242]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Upgrade to v1.7.7 fails with operator crash.

**How to reproduce it (minimal and precise):**

Upgrade from 1.6.8 to 1.7.7. So far this happens only on one cluster, I was able to upgrade 2 older clusters without issues.

**File(s) to submit**:

* Operator's logs, if necessary
```
2021-11-24 15:41:12.025339 I | op-flags: failed to set flag "logtostderr". no such flag -logtostderr
2021-11-24 15:41:12.025545 I | rookcmd: starting Rook v1.7.8 with arguments '/usr/local/bin/rook ceph operator'
2021-11-24 15:41:12.025554 I | rookcmd: flag values: --csi-cephfs-plugin-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin.yaml, --csi-cephfs-provisioner-dep-template-path=/etc/ceph-csi/cephfs/csi-cephfsplugin-provisioner-dep.yaml, --csi-rbd-plugin-template-path=/etc/ceph-csi/rbd/csi-rbdplugin.yaml, --csi-rbd-provisioner-dep-template-path=/etc/ceph-csi/rbd/csi-rbdplugin-provisioner-dep.yaml, --enable-machine-disruption-budget=false, --help=false, --kubeconfig=, --log-level=INFO, --operator-image=, --service-account=
2021-11-24 15:41:12.025556 I | cephcmd: starting Rook-Ceph operator
2021-11-24 15:41:12.134346 I | cephcmd: base ceph version inside the rook operator image is "ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable)"
2021-11-24 15:41:12.140129 I | op-k8sutil: ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS="15" (default)
2021-11-24 15:41:12.142467 I | op-k8sutil: ROOK_ENABLE_DISCOVERY_DAEMON="false" (configmap)
2021-11-24 15:41:12.144968 I | operator: looking for secret "rook-ceph-admission-controller"
2021-11-24 15:41:12.147079 I | operator: secret "rook-ceph-admission-controller" not found. proceeding without the admission controller
2021-11-24 15:41:12.149824 I | op-k8sutil: ROOK_ENABLE_FLEX_DRIVER="false" (configmap)
2021-11-24 15:41:12.149835 I | operator: watching all namespaces for ceph cluster CRs
2021-11-24 15:41:12.149925 I | operator: setting up the controller-runtime manager
2021-11-24 15:41:12.151608 I | ceph-cluster-controller: ConfigMap "rook-ceph-operator-config" changes detected. Updating configurations
2021-11-24 15:41:12.155482 I | op-k8sutil: ROOK_LOG_LEVEL="INFO" (env var)
I1124 15:41:13.200565       7 request.go:668] Waited for 1.04669907s due to client-side throttling, not priority and fairness, request: GET:https://10.43.0.1:443/apis/batch/v1beta1?timeout=32s
2021-11-24 15:41:15.156015 I | ceph-cluster-controller: successfully started
2021-11-24 15:41:15.156087 I | ceph-cluster-controller: enabling hotplug orchestration
2021-11-24 15:41:15.156106 I | ceph-crashcollector-controller: successfully started
2021-11-24 15:41:15.156170 I | ceph-block-pool-controller: successfully started
2021-11-24 15:41:15.156228 I | ceph-object-store-user-controller: successfully started
2021-11-24 15:41:15.156321 I | ceph-object-realm-controller: successfully started
2021-11-24 15:41:15.156389 I | ceph-object-zonegroup-controller: successfully started
2021-11-24 15:41:15.156438 I | ceph-object-zone-controller: successfully started
2021-11-24 15:41:15.156560 I | ceph-object-controller: successfully started
2021-11-24 15:41:15.156643 I | ceph-file-controller: successfully started
2021-11-24 15:41:15.156707 I | ceph-nfs-controller: successfully started
2021-11-24 15:41:15.156769 I | ceph-rbd-mirror-controller: successfully started
2021-11-24 15:41:15.156832 I | ceph-client-controller: successfully started
2021-11-24 15:41:15.156883 I | ceph-filesystem-mirror-controller: successfully started
2021-11-24 15:41:15.160633 I | operator: starting the controller-runtime manager
2021-11-24 15:41:15.262503 I | clusterdisruption-controller: create event from ceph cluster CR
2021-11-24 15:41:15.870024 I | ceph-cluster-controller: reconciling ceph cluster in namespace "rook-ceph"
2021-11-24 15:41:15.873364 I | clusterdisruption-controller: deleted all legacy blocking PDBs for osds
2021-11-24 15:41:15.873394 I | op-k8sutil: ROOK_ENABLE_FLEX_DRIVER="false" (configmap)
2021-11-24 15:41:15.875145 I | op-mon: parsing mon endpoints: b=10.43.118.220:6789,d=10.43.167.186:6789,c=10.43.87.166:6789
2021-11-24 15:41:15.875558 I | op-mon: parsing mon endpoints: b=10.43.118.220:6789,d=10.43.167.186:6789,c=10.43.87.166:6789
2021-11-24 15:41:15.875950 I | op-mon: parsing mon endpoints: b=10.43.118.220:6789,d=10.43.167.186:6789,c=10.43.87.166:6789
2021-11-24 15:41:15.879401 I | clusterdisruption-controller: deleted all legacy node drain canary pods
2021-11-24 15:41:15.887914 I | ceph-csi: successfully created csi config map "rook-ceph-csi-config"
2021-11-24 15:41:15.958057 I | ceph-object-controller: skipping reconcile since operator is still initializing
2021-11-24 15:41:15.958089 I | op-k8sutil: Reporting Event rook-ceph:object-storage Normal:ReconcileSucceeded:successfully configured CephObjectStore "rook-ceph/object-storage"
2021-11-24 15:41:15.958182 I | ceph-block-pool-controller: skipping reconcile since operator is still initializing
2021-11-24 15:41:15.960249 I | clusterdisruption-controller: Ceph "rook-ceph" cluster not ready, cannot check Ceph status yet.
2021-11-24 15:41:15.960607 I | ceph-file-controller: skipping reconcile since operator is still initializing
2021-11-24 15:41:16.041507 I | clusterdisruption-controller: Ceph "rook-ceph" cluster not ready, cannot check Ceph status yet.
2021-11-24 15:41:16.073179 I | op-k8sutil: ROOK_CSI_ENABLE_RBD="true" (configmap)
2021-11-24 15:41:16.273592 I | op-mon: parsing mon endpoints: b=10.43.118.220:6789,d=10.43.167.186:6789,c=10.43.87.166:6789
2021-11-24 15:41:16.285408 I | ceph-cluster-controller: enabling ceph mon monitoring goroutine for cluster "rook-ceph"
2021-11-24 15:41:16.285430 I | op-osd: ceph osd status in namespace "rook-ceph" check interval "1m0s"
2021-11-24 15:41:16.285435 I | ceph-cluster-controller: enabling ceph osd monitoring goroutine for cluster "rook-ceph"
2021-11-24 15:41:16.285440 I | ceph-cluster-controller: ceph status check interval is 1m0s
2021-11-24 15:41:16.285443 I | ceph-cluster-controller: enabling ceph status monitoring goroutine for cluster "rook-ceph"
2021-11-24 15:41:16.366029 I | ceph-cluster-controller: skipping ceph status since operator is still initializing
2021-11-24 15:41:16.473487 I | op-k8sutil: ROOK_CSI_ENABLE_CEPHFS="true" (configmap)
2021-11-24 15:41:16.673985 I | op-k8sutil: ROOK_OBC_WATCH_OPERATOR_NAMESPACE="true" (configmap)
2021-11-24 15:41:16.674002 I | op-bucket-prov: ceph bucket provisioner launched watching for provisioner "rook-ceph.ceph.rook.io/bucket"
I1124 15:41:16.674872       7 manager.go:118] objectbucket.io/provisioner-manager "msg"="starting provisioner"  "name"="rook-ceph.ceph.rook.io/bucket"
I1124 15:41:16.775699       7 controller.go:218]  "msg"="reconciling claim" "key"="test-mysql-operator/mysql-backup" 
I1124 15:41:16.775725       7 helpers.go:107]  "msg"="getting claim for key" "key"="test-mysql-operator/mysql-backup" 
I1124 15:41:16.779740       7 helpers.go:213]  "msg"="getting ObjectBucketClaim's StorageClass" "key"="test-mysql-operator/mysql-backup" 
I1124 15:41:16.782928       7 helpers.go:218]  "msg"="got StorageClass" "key"="test-mysql-operator/mysql-backup" "name"="rook-ceph-bucket"
I1124 15:41:16.782962       7 helpers.go:90]  "msg"="checking OBC for OB name, this indicates provisioning is complete" "key"="test-mysql-operator/mysql-backup" "mysql-backup"=null
I1124 15:41:16.782978       7 helpers.go:92]  "msg"="provisioning already completed" "key"="test-mysql-operator/mysql-backup" "ObjectBucket"="obc-test-mysql-operator-mysql-backup"
I1124 15:41:16.782992       7 controller.go:254]  "msg"="updating OBC" "key"="test-mysql-operator/mysql-backup" 
I1124 15:41:16.783009       7 resourcehandlers.go:148]  "msg"="seeing if OB for OBC exists" "key"="test-mysql-operator/mysql-backup" "checking for OB name"="obc-test-mysql-operator-mysql-backup"
I1124 15:41:16.786261       7 resourcehandlers.go:159]  "msg"="found OB belonging to this OBC" "key"="test-mysql-operator/mysql-backup" "OB"="obc-test-mysql-operator-mysql-backup"
I1124 15:41:16.786280       7 controller.go:682]  "msg"="Additional config changed, hence updating OB" "key"="test-mysql-operator/mysql-backup" 
2021-11-24 15:41:16.786289 I | op-bucket-prov: getting storage class "rook-ceph-bucket"
E1124 15:41:16.827294       7 controller.go:689]  "msg"="updating from Provisioner failed" "error"="skipping reconcile since operator is still initializing" "key"="test-mysql-operator/mysql-backup" 
E1124 15:41:16.827322       7 controller.go:205] error syncing 'test-mysql-operator/mysql-backup': skipping reconcile since operator is still initializing, requeuing
I1124 15:41:16.827336       7 controller.go:218]  "msg"="reconciling claim" "key"="velero/ceph-bucket" 
I1124 15:41:16.827351       7 helpers.go:107]  "msg"="getting claim for key" "key"="velero/ceph-bucket" 
I1124 15:41:16.830357       7 helpers.go:213]  "msg"="getting ObjectBucketClaim's StorageClass" "key"="velero/ceph-bucket" 
I1124 15:41:16.832589       7 helpers.go:218]  "msg"="got StorageClass" "key"="velero/ceph-bucket" "name"="rook-ceph-bucket"
I1124 15:41:16.832602       7 helpers.go:90]  "msg"="checking OBC for OB name, this indicates provisioning is complete" "key"="velero/ceph-bucket" "ceph-bucket"=null
I1124 15:41:16.832610       7 helpers.go:92]  "msg"="provisioning already completed" "key"="velero/ceph-bucket" "ObjectBucket"="obc-velero-ceph-bucket"
I1124 15:41:16.832618       7 controller.go:254]  "msg"="updating OBC" "key"="velero/ceph-bucket" 
I1124 15:41:16.832633       7 resourcehandlers.go:148]  "msg"="seeing if OB for OBC exists" "key"="velero/ceph-bucket" "checking for OB name"="obc-velero-ceph-bucket"
I1124 15:41:16.834448       7 controller.go:682]  "msg"="Additional config changed, hence updating OB" "key"="velero/ceph-bucket" 
E1124 15:41:16.834499       7 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1226 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1f23680, 0x337cef0)
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1f23680, 0x337cef0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner.(*obcController).handleUpdateClaim(0xc0012cf680, 0xc003d1de00, 0x12, 0xc000fff500, 0xc001081200, 0x0, 0x0)
	/home/rook/go/pkg/mod/github.com/kube-object-storage/lib-bucket-provisioner@v0.0.0-20210818162813-3eee31c01875/pkg/provisioner/controller.go:685 +0x25c
github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner.(*obcController).syncHandler(0xc0012cf680, 0xc003d1de00, 0x12, 0xc0035b6360, 0xc0038cbd90)
	/home/rook/go/pkg/mod/github.com/kube-object-storage/lib-bucket-provisioner@v0.0.0-20210818162813-3eee31c01875/pkg/provisioner/controller.go:255 +0x4a5
github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner.(*obcController).processNextItemInQueue.func1(0xc0012cf680, 0x1e4ce60, 0xc003528670, 0x0, 0x0)
	/home/rook/go/pkg/mod/github.com/kube-object-storage/lib-bucket-provisioner@v0.0.0-20210818162813-3eee31c01875/pkg/provisioner/controller.go:193 +0xe7
github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner.(*obcController).processNextItemInQueue(0xc0012cf680, 0x203001)
	/home/rook/go/pkg/mod/github.com/kube-object-storage/lib-bucket-provisioner@v0.0.0-20210818162813-3eee31c01875/pkg/provisioner/controller.go:202 +0x49
github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner.(*obcController).runWorker(...)
	/home/rook/go/pkg/mod/github.com/kube-object-storage/lib-bucket-provisioner@v0.0.0-20210818162813-3eee31c01875/pkg/provisioner/controller.go:157
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000e9dfd0)
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000e9dfd0, 0x2546b20, 0xc003358060, 0xc000e93201, 0xc0011182a0)
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000e9dfd0, 0x3b9aca00, 0x0, 0x22e1101, 0xc0011182a0)
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000e9dfd0, 0x3b9aca00, 0xc0011182a0)
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:90 +0x4d
created by github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner.(*obcController).Start
	/home/rook/go/pkg/mod/github.com/kube-object-storage/lib-bucket-provisioner@v0.0.0-20210818162813-3eee31c01875/pkg/provisioner/controller.go:133 +0x15b
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x138 pc=0x1afeffc]

goroutine 1226 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1f23680, 0x337cef0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner.(*obcController).handleUpdateClaim(0xc0012cf680, 0xc003d1de00, 0x12, 0xc000fff500, 0xc001081200, 0x0, 0x0)
	/home/rook/go/pkg/mod/github.com/kube-object-storage/lib-bucket-provisioner@v0.0.0-20210818162813-3eee31c01875/pkg/provisioner/controller.go:685 +0x25c
github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner.(*obcController).syncHandler(0xc0012cf680, 0xc003d1de00, 0x12, 0xc0035b6360, 0xc0038cbd90)
	/home/rook/go/pkg/mod/github.com/kube-object-storage/lib-bucket-provisioner@v0.0.0-20210818162813-3eee31c01875/pkg/provisioner/controller.go:255 +0x4a5
github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner.(*obcController).processNextItemInQueue.func1(0xc0012cf680, 0x1e4ce60, 0xc003528670, 0x0, 0x0)
	/home/rook/go/pkg/mod/github.com/kube-object-storage/lib-bucket-provisioner@v0.0.0-20210818162813-3eee31c01875/pkg/provisioner/controller.go:193 +0xe7
github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner.(*obcController).processNextItemInQueue(0xc0012cf680, 0x203001)
	/home/rook/go/pkg/mod/github.com/kube-object-storage/lib-bucket-provisioner@v0.0.0-20210818162813-3eee31c01875/pkg/provisioner/controller.go:202 +0x49
github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner.(*obcController).runWorker(...)
	/home/rook/go/pkg/mod/github.com/kube-object-storage/lib-bucket-provisioner@v0.0.0-20210818162813-3eee31c01875/pkg/provisioner/controller.go:157
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000e9dfd0)
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000e9dfd0, 0x2546b20, 0xc003358060, 0xc000e93201, 0xc0011182a0)
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000e9dfd0, 0x3b9aca00, 0x0, 0x22e1101, 0xc0011182a0)
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000e9dfd0, 0x3b9aca00, 0xc0011182a0)
	/home/rook/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:90 +0x4d
created by github.com/kube-object-storage/lib-bucket-provisioner/pkg/provisioner.(*obcController).Start
	/home/rook/go/pkg/mod/github.com/kube-object-storage/lib-bucket-provisioner@v0.0.0-20210818162813-3eee31c01875/pkg/provisioner/controller.go:133 +0x15b
```

**Environment**:
* OS (e.g. from /etc/os-release): Ubuntu 20.04
* Kernel (e.g. `uname -a`): `Linux k8s13-dev 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud provider or hardware configuration: bare metal server
* Rook version (use `rook version` inside of a Rook Pod): 
```
rook: v1.6.8
go: go1.16.3
```
This is current working version, new one fails to upgrade due to operator crash.
* Storage backend version (e.g. for ceph do `ceph -v`): 
```
[root@rook-ceph-tools-77f4f75cdd-6722t /]# ceph version
ceph version 16.2.5 (0883bdea7337b95e4b611c768c0279868462204a) pacific (stable)
[root@rook-ceph-tools-77f4f75cdd-6722t /]# ceph -v
ceph version 16.2.2 (e8f22dde28889481f4dda2beb8a07788204821d3) pacific (stable)
```
* Kubernetes version (use `kubectl version`): v1.20.9+rke2r2
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift): rke2
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)): HEALTH_OK

I suspect something related to S3 but I can't figure out what it is. Any way of debuging this?

**Comment by BlaineEXE** [comment]
Could you provide us with the `kubectl get -o yaml` of your OBC that is failing to help us debug.

**Comment by ClaudiuLSH** [comment]
Is this enough?
```
k get ObjectBucketClaim ceph-bucket -n velero -o yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"objectbucket.io/v1alpha1","kind":"ObjectBucketClaim","metadata":{"annotations":{},"name":"ceph-bucket","namespace":"velero"},"spec":{"generateBucketName":"velero","storageClassName":"rook-ceph-bucket"}}
  creationTimestamp: "2021-05-26T14:37:11Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2021-11-24T16:19:22Z"
  finalizers:
  - objectbucket.io/finalizer
  generation: 5
  labels:
    bucket-provisioner: rook-ceph.ceph.rook.io-bucket
  name: ceph-bucket
  namespace: velero
  resourceVersion: "161362480"
  uid: c44e3c6e-72bb-4b78-97cd-f9dbbb8eb8d7
spec:
  bucketName: velero-b17ac2a4-ecfd-4905-b561-aa4f189a42b6
  generateBucketName: velero
  objectBucketName: obc-velero-ceph-bucket
  storageClassName: rook-ceph-bucket
status:
  phase: Bound
```

The ObjectBucket was not created for this claim so I deleted it. Now the upgrade is progressing fine. Thanks, I did not notice the missing object so I guess it was stuck somehow or partially deleted.

**Comment by ClaudiuLSH** [comment]
Closing, the fix was easy enough, deleting hanged bucket.
