### ISSUE TITLE
Cleanup job fails to run c-v due to requiring privileged permissions

### ISSUE THREAD

**Issue by travisn** [rook/rook#9375]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
The node cleanup job is failing when the cluster is being destroyed. `ceph-volume` is failing with `SuperUserError: This command needs to be executed with sudo or as root`.

When setting the cleanup policy `yes-really-destroy-data` on the cluster CR, then deleting the CR, the cleanup job runs, but fails with the following log:
```
2021-12-09 19:26:33.050760 I | rookcmd: starting Rook v1.8.0-alpha.0.61.g2467daa40 with arguments '/usr/local/bin/rook ceph clean'
2021-12-09 19:26:33.050907 I | rookcmd: flag values: --cluster-fsid=3a5a863a-2c09-4300-87ea-a8522fc59fb2, --data-dir-host-path=/var/lib/rook, --help=false, --log-level=DEBUG, --mon-secret=*****, --namespace-dir=rook-ceph, --operator-image=, --sanitize-data-source=zero, --sanitize-iteration=1, --sanitize-method=quick, --service-account=
2021-12-09 19:26:33.050913 I | cephcmd: starting cluster clean up
2021-12-09 19:26:33.051162 E | cleanup: failed to clean up "/var/lib/rook/rook-ceph" directory. unlinkat /var/lib/rook/rook-ceph/3a5a863a-2c09-4300-87ea-a8522fc59fb2_0c9a8ffb-d6d7-47a3-9f57-68696eb89724/block: permission denied
2021-12-09 19:26:33.051247 E | cleanup: failed to clean up the mon directory "/var/lib/rook/mon-a" on the dataDirHostPath "/var/lib/rook". failed to read keyring "/var/lib/rook/mon-a/data/keyring" for the mon directory "/var/lib/rook/mon-a": open /var/lib/rook/mon-a/data/keyring: permission denied
2021-12-09 19:26:33.051264 E | cleanup: failed to clean up the mon directory "/var/lib/rook/mon-b" on the dataDirHostPath "/var/lib/rook". failed to read keyring "/var/lib/rook/mon-b/data/keyring" for the mon directory "/var/lib/rook/mon-b": open /var/lib/rook/mon-b/data/keyring: permission denied
2021-12-09 19:26:33.051303 E | cleanup: failed to clean up the mon directory "/var/lib/rook/mon-c" on the dataDirHostPath "/var/lib/rook". failed to read keyring "/var/lib/rook/mon-c/data/keyring" for the mon directory "/var/lib/rook/mon-c": open /var/lib/rook/mon-c/data/keyring: permission denied
2021-12-09 19:26:33.053574 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log lvm list  --format json
2021-12-09 19:26:33.342207 E | cephosd: . -->  SuperUserError: This command needs to be executed with sudo or as root
2021-12-09 19:26:33.342248 E | cephosd: [2021-12-09 19:26:33,316][ceph_volume.main][INFO  ] Running command: ceph-volume --log-path /tmp/ceph-log lvm list  --format json
[2021-12-09 19:26:33,316][ceph_volume.main][ERROR ] ignoring inability to load ceph.conf
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 144, in main
    conf.ceph = configuration.load(conf.path)
  File "/usr/lib/python3.6/site-packages/ceph_volume/configuration.py", line 51, in load
    raise exceptions.ConfigurationError(abspath=abspath)
ceph_volume.exceptions.ConfigurationError: Unable to load expected Ceph config at: /etc/ceph/ceph.conf
[2021-12-09 19:26:33,318][ceph_volume][ERROR ] exception caught by decorator
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/main.py", line 46, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/listing.py", line 223, in main
    self.list(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 15, in is_root
    raise exceptions.SuperUserError()
ceph_volume.exceptions.SuperUserError: This command needs to be executed with sudo or as root
2021-12-09 19:26:33.342275 E | cleanup: failed to list lvm osd(s). failed to retrieve ceph-volume lvm list results: failed ceph-volume call (see ceph-volume log above for more details): exit status 1
2021-12-09 19:26:33.342289 D | exec: Running command: stdbuf -oL ceph-volume --log-path /tmp/ceph-log raw list --format json
2021-12-09 19:26:33.636621 E | cephosd: . -->  SuperUserError: This command needs to be executed with sudo or as root
2021-12-09 19:26:33.636663 E | cephosd: [2021-12-09 19:26:33,316][ceph_volume.main][INFO  ] Running command: ceph-volume --log-path /tmp/ceph-log lvm list  --format json
[2021-12-09 19:26:33,316][ceph_volume.main][ERROR ] ignoring inability to load ceph.conf
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 144, in main
    conf.ceph = configuration.load(conf.path)
  File "/usr/lib/python3.6/site-packages/ceph_volume/configuration.py", line 51, in load
    raise exceptions.ConfigurationError(abspath=abspath)
ceph_volume.exceptions.ConfigurationError: Unable to load expected Ceph config at: /etc/ceph/ceph.conf
[2021-12-09 19:26:33,318][ceph_volume][ERROR ] exception caught by decorator
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/main.py", line 46, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/lvm/listing.py", line 223, in main
    self.list(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 15, in is_root
    raise exceptions.SuperUserError()
ceph_volume.exceptions.SuperUserError: This command needs to be executed with sudo or as root
[2021-12-09 19:26:33,613][ceph_volume.main][INFO  ] Running command: ceph-volume --log-path /tmp/ceph-log raw list --format json
[2021-12-09 19:26:33,613][ceph_volume.main][ERROR ] ignoring inability to load ceph.conf
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 144, in main
    conf.ceph = configuration.load(conf.path)
  File "/usr/lib/python3.6/site-packages/ceph_volume/configuration.py", line 51, in load
    raise exceptions.ConfigurationError(abspath=abspath)
ceph_volume.exceptions.ConfigurationError: Unable to load expected Ceph config at: /etc/ceph/ceph.conf
[2021-12-09 19:26:33,614][ceph_volume][ERROR ] exception caught by decorator
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python3.6/site-packages/ceph_volume/main.py", line 152, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/main.py", line 32, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python3.6/site-packages/ceph_volume/terminal.py", line 194, in dispatch
    instance.main()
  File "/usr/lib/python3.6/site-packages/ceph_volume/devices/raw/list.py", line 161, in main
    self.list(args)
  File "/usr/lib/python3.6/site-packages/ceph_volume/decorators.py", line 15, in is_root
    raise exceptions.SuperUserError()
ceph_volume.exceptions.SuperUserError: This command needs to be executed with sudo or as root
2021-12-09 19:26:33.636690 E | cleanup: failed to list raw osd(s). failed to retrieve ceph-volume raw list results: failed ceph-volume call (see ceph-volume log above for more details): exit status 1
```

**Expected behavior:**
The node cleanup job should succeed when the cluster is being destroyed.

**How to reproduce it (minimal and precise):**

- Run minikube
- Create a rook cluster
- Set the cleanup policy `yes-really-destroy-data` on the cluster CR,
- Delete the CR
- The cleanup job runs, but fails

**Comment by leseb** [comment]
Right, the operator runs as `rook` now and I'm waiting for this https://github.com/ceph/ceph/pull/44239 to be backported. I'm going to send a patch.
