### ISSUE TITLE
operator panic on v1.8.4

### ISSUE THREAD

**Issue by TomHellier** [rook/rook#9714]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Operator crashing

**Expected behavior:**
Operator doesn't crash

**How to reproduce it (minimal and precise):**

I've attempted to deploy a v1.8.4 version of rook to a fresh k8s cluster, 

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
```
[root@ip-redacted ~]# kubectl get po -n rook-ceph-system
NAME                                            READY   STATUS             RESTARTS   AGE
csi-cephfsplugin-cj8hh                          3/3     Running            0          9m43s
csi-cephfsplugin-db27h                          3/3     Running            0          9m43s
csi-cephfsplugin-p2b9d                          3/3     Running            0          9m43s
csi-cephfsplugin-provisioner-64d7d4f7c8-6jgn6   6/6     Running            0          9m43s
csi-cephfsplugin-provisioner-64d7d4f7c8-nvgz6   6/6     Running            0          9m43s
csi-cephfsplugin-qsjrs                          3/3     Running            0          9m43s
csi-cephfsplugin-sf597                          3/3     Running            0          9m43s
csi-cephfsplugin-w26nj                          3/3     Running            0          9m43s
csi-rbdplugin-8x8c6                             3/3     Running            0          9m43s
csi-rbdplugin-f8vjt                             3/3     Running            0          9m43s
csi-rbdplugin-lckwv                             3/3     Running            0          9m43s
csi-rbdplugin-lvvmj                             3/3     Running            0          9m43s
csi-rbdplugin-ph47j                             3/3     Running            0          9m43s
csi-rbdplugin-provisioner-545f7b4bcd-ctxk9      6/6     Running            0          9m43s
csi-rbdplugin-provisioner-545f7b4bcd-kjwh8      6/6     Running            0          9m43s
csi-rbdplugin-tvp4x                             3/3     Running            0          9m43s
rook-ceph-operator-77f5fbb56b-7h45l             0/1     CrashLoopBackOff   6          10m
[root@ip-redacted ~]# kubectl get po -n rook-ceph
NAME                               READY   STATUS    RESTARTS   AGE
rook-ceph-mon-a-74ccbcbc86-t4wqm   1/1     Running   0          9m35s
rook-ceph-toolbox-job-csbqt        0/1     Error     0          7m16s
rook-ceph-toolbox-job-ppttv        0/1     Error     0          10m
rook-ceph-toolbox-job-qhn8h        0/1     Error     0          9m16s
rook-ceph-toolbox-job-r6cbp        0/1     Error     0          9m26s
rook-ceph-toolbox-job-vlgrs        0/1     Error     0          8m36s
rook-ceph-tools-b55564d68-xsdjd    1/1     Running   0          10m
```
* Operator's logs, if necessary
```
2022-02-09 13:43:12.493060 I | op-mon: mon "b" endpoint is [v2:10.104.73.84:3300,v1:10.104.73.84:6789]
2022-02-09 13:43:12.517504 I | op-mon: mon "c" endpoint is [v2:10.110.135.46:3300,v1:10.110.135.46:6789]
2022-02-09 13:43:12.867507 I | op-mon: mon "a" endpoint is [v2:10.96.42.96:3300,v1:10.96.42.96:6789]
E0209 13:43:13.466383       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 877 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1da3d80, 0x30d9af0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1da3d80, 0x30d9af0)
        /opt/hostedtoolcache/go/1.16.13/x64/src/runtime/panic.go:965 +0x1b9
github.com/rook/rook/pkg/operator/ceph/cluster/mon.wereMonEndpointsUpdated(0xc000eb8b10, 0xc000da37d0, 0x17)
        /home/runner/work/rook/rook/pkg/operator/ceph/cluster/mon/predicate.go:99 +0x701
github.com/rook/rook/pkg/operator/ceph/cluster/mon.PredicateMonEndpointChanges.func4(0x23dcc38, 0xc0011db430, 0x23dcc38, 0xc000b87b80, 0x23dcc38)
        /home/runner/work/rook/rook/pkg/operator/ceph/cluster/mon/predicate.go:50 +0xb2
sigs.k8s.io/controller-runtime/pkg/predicate.Funcs.Update(...)
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/predicate/predicate.go:87
sigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnUpdate(0x23accb0, 0xc000360428, 0x23c7210, 0xc00012ca00, 0xc000126e60, 0x1, 0x1, 0x1ff5740, 0xc0011db430, 0x1ff5740, ...)
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/source/internal/eventsource.go:88 +0x134
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/shared_informer.go:775 +0x1c5
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0015a3760)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000ac1f60, 0x236e380, 0xc000ed2d80, 0x1d5b001, 0xc000fa6ba0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0015a3760, 0x3b9aca00, 0x0, 0x2130101, 0xc000fa6ba0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000bac180)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00047ad80, 0xc000a70230)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:71 +0x65
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x185ba81]

goroutine 877 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1da3d80, 0x30d9af0)
        /opt/hostedtoolcache/go/1.16.13/x64/src/runtime/panic.go:965 +0x1b9
github.com/rook/rook/pkg/operator/ceph/cluster/mon.wereMonEndpointsUpdated(0xc000eb8b10, 0xc000da37d0, 0x17)
        /home/runner/work/rook/rook/pkg/operator/ceph/cluster/mon/predicate.go:99 +0x701
github.com/rook/rook/pkg/operator/ceph/cluster/mon.PredicateMonEndpointChanges.func4(0x23dcc38, 0xc0011db430, 0x23dcc38, 0xc000b87b80, 0x23dcc38)
        /home/runner/work/rook/rook/pkg/operator/ceph/cluster/mon/predicate.go:50 +0xb2
sigs.k8s.io/controller-runtime/pkg/predicate.Funcs.Update(...)
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/predicate/predicate.go:87
sigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnUpdate(0x23accb0, 0xc000360428, 0x23c7210, 0xc00012ca00, 0xc000126e60, 0x1, 0x1, 0x1ff5740, 0xc0011db430, 0x1ff5740, ...)
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/source/internal/eventsource.go:88 +0x134
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/shared_informer.go:775 +0x1c5
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0015a3760)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000ac1f60, 0x236e380, 0xc000ed2d80, 0x1d5b001, 0xc000fa6ba0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0015a3760, 0x3b9aca00, 0x0, 0x2130101, 0xc000fa6ba0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000bac180)
        /home/runner/go/pkg/mod/k8s.io/client-go@v0.22.2/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00047ad80, 0xc000a70230)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.22.2/pkg/util/wait/wait.go:71 +0x65
```
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/latest/ceph-toolbox.html)):

**Comment by leseb** [comment]
I'm not sure how we missed it in the CI but here is the fix for this https://github.com/rook/rook/pull/9715

**Comment by toabi** [comment]
I upgraded an existing 1.8.2 to 1.8.4 and I'm seeing the same issue. Glad there's a fix or it and I only did it in dev-env :D
