### ISSUE TITLE
index out of range error when using skip_install_rook flag when running integration test

### ISSUE THREAD

**Issue by kokhang** [rook/rook#984]
Run int tests with `skip_install_rook` flag without creating rook.
I should expect an error saying "Rook not found" or something. But i get a panic with index out of range exception.

Also, i get the same if my rook-cluster is in a different namespace than the `defaultNamespace`.

```2017-09-13 22:31:02.183524 I | testutil: Running kubectl [create -f -]
Error from server (NotFound): error when creating "STDIN": namespaces "rook" not found
2017-09-13 22:31:02.385927 I | Exit Status: 1
--- FAIL: TestSmokeSuiteK8s (0.53s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 49 [running]:
testing.tRunner.func1(0xc4203c81a0)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x1fc0cc0, 0x29f89c0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/rook/rook/tests/framework/utils.(*K8sHelper).GetPodHostID(0xc420334960, 0x2148724, 0x8, 0x21439ea, 0x4, 0xc42001cf00, 0x56, 0x0, 0x0)
	/Users/steveleon/go/src/github.com/rook/rook/tests/framework/utils/k8s_helper.go:425 +0x7cc
github.com/rook/rook/tests/framework/clients.CreateRestAPIClient(0x1, 0xc420334960, 0x21439ea, 0x4, 0xc420334960)
	/Users/steveleon/go/src/github.com/rook/rook/tests/framework/clients/rest_client.go:50 +0x546
github.com/rook/rook/tests/framework/clients.CreateTestClient(0x1, 0xc420334960, 0x21439ea, 0x4, 0x0, 0x0, 0x0)
	/Users/steveleon/go/src/github.com/rook/rook/tests/framework/clients/test_client.go:52 +0x67
github.com/rook/rook/tests/smoke.(*SmokeSuite).SetupSuite(0xc4203c5110)
	/Users/steveleon/go/src/github.com/rook/rook/tests/smoke/smoke_test.go:52 +0x16a
github.com/rook/rook/vendor/github.com/stretchr/testify/suite.Run(0xc4203c81a0, 0x299c3e0, 0xc4203c5110)
	/Users/steveleon/go/src/github.com/rook/rook/vendor/github.com/stretchr/testify/suite/suite.go:63 +0x605
github.com/rook/rook/tests/smoke.TestSmokeSuiteK8s(0xc4203c81a0)
	/Users/steveleon/go/src/github.com/rook/rook/tests/smoke/smoke_test.go:31 +0x51
testing.tRunner(0xc4203c81a0, 0x21d6a38)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca
Steves-MacBook-Pro:rook steveleon$ _output/tests/darwin_amd64/smoke  -test.v test.timeout 1500s -testify.m TestBlockStorage_SmokeTest -test.v```

**Comment by travisn** [comment]
just install rook before running the tests with the skip_install_rook flag
